resources:
  - trickster-deployment.yaml
  - trickster-service.yaml

namespace: monitoring

commonLabels:
  app: trickster
  type: monitoring

configMapGenerator:
  - name: trickster-config
    files:
      - config/trickster.yaml

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: generated
