{{- range .Values.nodes }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "geth.fullname" $ }}-{{ .nodeName }}-service
  labels:
    app: {{ template "geth.name" $ }}-{{ .nodeName }}-service
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  selector:
    app: {{ template "geth.name" $ }}-{{ .nodeName }}
  type: NodePort
  ports:
    - name: node-jsonrpc
      protocol: TCP
      port: 8545
      targetPort: 8545
    - name: node-wsrpc
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: node-ipc-listen
      protocol: UDP
      port: 30301
      targetPort: 30301
    - name: node-ipc-discovery
      protocol: TCP
      port: 30303
      targetPort: 30303
---
{{- end }}
