= Keep Private Testnet Changelog

Summary of Keep private testnet releases in reverse chronological order.

== 2020-03-13

=== NEW FEATURES

- We're proud to annouce the Keep token dashboard!  Find at at `http://dashboard.test.keep.network`
  The token dashboard allows you to manage your KEEP grants, staking, authorizations, and
  operations.  We'll be shipping a separate guide over the coming weeks.  To use the dashboard all
  you need to do is load your issued keep-client Ethereum account into metamask.

== 2020-02-18

=== BUGFIXES

- keep-clients can now recover from an underlying Ethreum node connection loss

=== OTHERS

- Implemented slashing scheme per Yellowpaper
- Adjusted rewards and reimbursements
- Continued gas cost optimization
- Increase active time for commitment and points validation phases of GJKR
- Remove idle states and wait delays from state machines
- Validate if a peer is allowed to participate in threshold signature
- libp2p transport layer encryption
- Eliminate the possibility of accepting late retransmission
- libp2p buffers adjustments - improve message delivery rate
- Improve libp2p broadcast channel message delivery pipeline

== 2020-01-22

Happy New Year!!

=== BUGFIXES

- Group selection occasionally fails on Infura:  We now account for Infura's load balancing pattern.
- Group selection is not triggered again after a failure:  Resloved a condition where we would end up with zero groups on-chain.
- Undelegation failure: Resolved occasional function not found error in the staking dapp.

=== OTHERS

- Reentrancy protection: Retransmitter refinements and libp2p buffers adjustments to improve message delivery rates.
- Adjust gas price for Ropsten: Price adjust as compared to local environments.
- Signing group member as a relay entry timeout tattletale:  Added group signers as tattletales by default.  This should help reduce penalties and allow for additional beacon self-healing.

== 2019-12-13

=== BUGFIXES

- Relay submission: Ensure a valid relay request can only be submitted once.
- Timings: Corrected message unmarshallers being registered too late.
- Cost smoothing: Reduced relay entry verification gas cost peaks.
- DKG: Corrected failing DKG because of invalid detection of identical messages in network time cache.

=== OTHERS

- Simplified stake delegation: Operator's signature is no longer required.
- Migrated to Ropsten!

== 2019-10-31

=== OTHERS

- Block times optimization: Distributed group key generation and relay entry signing are two times
  faster now.
- Relay entry timeout: Improved validation to do not accept relay entries after the deadline.
- Improved validation: In the candidate group member ticket submission to reject duplicate tickets.
- Beacon pricing: Experimental implementation of the pricing mechanism for the beacon.

== 2019-10-15

=== BUGFIXES

- on-chain BLS verification spuriously failing: In some cases our off-chain calculations for BLS
  verification were not matching the on-chain counterpart.  This happened when calculated values were
  shorter than 32 bytes in length. The on-chain implementation was properly padding these cases, our
  off-chain implementation was not.  We've added padding to the off-chain piece so that we have a
  proper match in these cases.

== 2019-09-27

=== NEW FEATURES

- Configurable `AnnouncedAddresses`:  If you start a keep-client in a private network it's likely
that the IP address announced to the Keep Network is not accessible from the outside world.  Now in
your `keep-client-confg.toml` file you can override the default annouced address by providing known
list of IP addresses or DNS hostnames in section `[LibP2P]` with key `AnnoucedAddresses`.
`AnnouncedAddresses` has been added to configuration files included with deployment bundles. See the
quickstart guide on formatting for `AnnoucedAddresses` entries.  Leaving the configuration as-is
will result in setting the default announce address.

=== OTHERS

- Removed LibP2P NAT support:  We've opted for configurable announced addresses instead of leaning on
LibP2P built-ins whose success can vary widely depending on network conditions.

== 2019-09-09

=== BUGFIXES

- Incorrect group threshold when signing relay entry:  As part of a group there is an honest and
dishonest threshold for participants to produce a relay entry.  Our current group size is set to
5.  At a group size of 5 we need a minimum of 3 honest and max of 2 dishonest participants.  We
have been calculating the threshold at 4, resulting in more stringent than desired threshold
requirements.  Additionally, we corrected GJKR polynomial generation by setting the dishonest
threshold as the degree, instead of honest threshold.

== 2019-09-06

=== NEW FEATURES
- Allow for LibP2P NAT support:  This takes shape in the form of a new configuration option in your
`keep-client-confg.toml` file.  If enabled this feature will attempt to connect with
auto-discovered network firewall using UPnP, open a port, and configure the mapping internally.
To enable this feature set `NAT = true` under section `[LibP2P]` in your `keep-client-confg.toml`.

=== OTHERS
- Added enhanced logging around group statistics and network connection details.

== 2019-08-22

=== NEW FEATURES
- Timeout for a relay entry: If the group selected to produce a new random number does not deliver
relay entry on time, we terminate that group and another one is selected to do the work.

- Allow re-trigger genesis when the first group creation failed: We should be able to trigger
genesis once again if the first group creation failed. This is to avoid a situation that something
went wrong during the DKG and we are dead in the water with our contracts.

=== BUGFIXES
- Non-uniform distribution of group selection results: Fixed bug in group selection protocol; not
all groups registered on the chain had the same chance of being selected in the case when we were
marking some groups as expired. We fixed this problem and now all groups have the same chance of
being selected.

- Broadcast channel initialisation problems:  When running Keep nodes and sending a request for a
new relay entry, occasionally we received the error coming from the chain saying “Total number of
groups must be greater than zero”. This was caused by bug in DKG protocol in broadcast channel
initialisation and happened when we had a network glitch for a while.  This is addressed now.

- Incorrect seed for group selection and Pedersen commitment: The group selection protocol should
take the previous beacon value along with staker-specific values to create a ticket. The buggy
implementation passed the seed instead of the previous beacon value to group selection. This could
threat the trapdoor of Pedersen commitment we use in DKG.

=== OTHERS
- Upgrade to the newest OpenZeppelin version.

- Covered all known corner cases DKG protocol with integration tests for member inactivity and fixed
all minor issues found.

== 2019-07-16
- Extended the deployment bundle and `docker run` command to include persistence.  The addition of
persistence allows a restarted keep-client to recover group status/state.

- Added more robust logging (now with Timestamps!).

== 2019-07-10
- Updated Docker image restores `relay request` command to the keep-client.

- Updated config file for new contract references.

