resources:
  - ../../templates/keep-maintainer

namespace: default

# Regular testnet maintainer doesn't run bitcoinDifficulty module due to specifics
# of LightRelay running on testnet (SepoliaLightRelay). This setup is running
# the `bitcoinDifficulty` module of maintainer connected to Bitcoin mainnet.
nameSuffix: -staging

commonLabels:
  app: keep-maintainer-staging
  type: bitcoinDifficulty
  network: sepolia

images:
  - name: keep-maintainer
    newName: gcr.io/keep-test-f3e0/keep-client
    newTag: latest

configMapGenerator:
  - name: keep-maintainer-config
    behavior: merge
    literals:
      - network=testnet
      - electrum-api-url=wss://electrumx-server.tbtc.network:8443
    files:
      - .secret/keep-maintainer-keyfile

secretGenerator:
  - name: keep-maintainer-eth-account-password
    files:
      - .secret/keep-maintainer-password

patches:
  - target:
      kind: StatefulSet
      name: keep-maintainer
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --bitcoinDifficulty
      - op: replace
        path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/name
        value: eth-network-sepolia

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: generated
