export const ALLOWED_UPGRADE_DELAY = 1209600; // 2 weeks in sec. TODO: add as an option.param
export const REQUIRED_MIN_PRE_PARAMS = 500; // min requirement for pre params daily avg
export const QUERY_STEP = 600; // 10min in sec
export const REQUIRED_UPTIME_PERCENT = 96; // percent
export const IS_BEACON_AUTHORIZED = "isBeaconAuthorized";
export const BEACON_AUTHORIZATION = "beaconAuthorization";
export const IS_TBTC_AUTHORIZED = "isTbtcAuthorized";
export const TBTC_AUTHORIZATION = "tbtcAuthorization";
export const UP_TIME_PERCENT = "upTimePercent";
export const IS_UP_TIME_SATISFIED = "isUptimeSatisfied";
export const VERSION = "version";
export const AVG_PRE_PARAMS = "avgPreParams";
export const IS_PRE_PARAMS_SATISFIED = "isPreParamsSatisfied";
export const PRECISION = 1000;
export const QUERY_RESOLUTION = 60 // 1min sampling time for the metrics
export const HUNDRED = 100
export const IS_VERSION_SATISFIED = "isVersionSatisfied"
export const APR = 15 // percent
