---
apiVersion: v1
kind: Service
metadata:
  name: geth-goerli
  labels:
    app: geth
    type: goerli
spec:
  selector:
    app: geth
    type: goerli
  ports:
    - port: 8545
      targetPort: 8545
      name: tcp-8545
    - port: 8546
      targetPort: 8546
      name: tcp-8546
    - port: 30303
      targetPort: 30303
      name: tcp-30303
    - port: 30303
      targetPort: 30303
      name: udp-30303
      protocol: UDP
