---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: geth-goerli
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  replication-type: none
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geth-goerli
  labels:
    app: geth
    network: goerli
spec:
  replicas: 1
  serviceName: geth-goerli
  volumeClaimTemplates:
    - metadata:
        name: geth-goerli
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: geth-goerli
        resources:
          requests:
            storage: 100Gi
  selector:
    matchLabels:
      app: geth
      network: goerli
  template:
    metadata:
      labels:
        app: geth
        network: goerli
    spec:
      containers:
        - name: geth-goerli
          image: ethereum/client-go:latest
          ports:
            - containerPort: 8545
            - containerPort: 8546
            - containerPort: 30303
          volumeMounts:
            - name: geth-goerli
              mountPath: /root/.ethereum
          args: ["--http", "--http.addr=0.0.0.0", "--ws", "-ws.addr=0.0.0.0", "--goerli", "--syncmode=snap"]
---
apiVersion: v1
kind: Service
metadata:
  name: geth-goerli
  labels:
    app: geth
    network: goerli
spec:
  selector:
    app: geth
    network: goerli
  ports:
    - port: 8545
      targetPort: 8545
      name: tcp-8545
    - port: 8546
      targetPort: 8546
      name: tcp-8546
    - port: 30303
      targetPort: 30303
      name: tcp-30303
    - port: 30303
      targetPort: 30303
      name: udp-30303
      protocol: UDP
