= Group expiration

Desired qualities:

- larger pool of groups when demand is high
- pool doesn't grow _O(n)_ with output demand
- stakeless members are minimized
- the expiry cannot be manipulated
  - any function where stakers can impact which groups expire first is
    vulnerable to manipulation
- any group expires eventually
- groups churn reliably and the system doesn't get stuck in a state favoring any
particular staker(s)
- number of available groups never hits zero

Thus:

- the number of outputs within a certain time period determines how fast groups
expire -> to cater for DKG failures, calculate by number of groups instead? 
- small number of outputs -> long expiry
- large number of outputs -> short expiry

Represent the group expiration function by _Expire(GG, E) -> GG'_ where _GG_ is
the pool of currently active groups, _E_ is some value representing all other
inputs to the function, and _GG'_ is the new pool after removing expired groups.

== Expiry manipulation

If the actions of stakers can impact which groups expire first, it enables
manipulation.

==== Unstake manipulation

Consider a scenario where groups with unstaking members expire faster. Mallory
blitzpantses their stake _Stake~m~_ to allotments of _Stake~minimum~_ and is
represented in groups with an average fraction of
_Rep~m_average~ = Stake~m~ / Stake~total~_.

Then, Mallory proceeds to unstake all of their identities that are only present
in groups _G~i~_ where _Rep~m_i~ < Rep~m_average~_. Those groups will be removed
from the group pool faster, and replaced with groups where the expected fraction
of Mallory's nodes is _Rep~m_average~_.

==== Selection seed manipulation

Consider a scenario where Mallory can influence the value _E_ which determines
which groups expire with the function _Expire(GG, E)_.

Now Mallory can calculate what values of _E~m~_ within their control would yield
favorable outputs from _Expire(GG, E~m~)_.

=== Preventing manipulation

To avoid issues of this general nature, _Expire(GG, E)_ should use values of _E_
that cannot be manipulated. Some suitable values may be:

- The actual outputs of the random beacon (_V~i~_)
- Current blockheight (_T~j~_) when used in a linear fashion: if _G~i~_ would
expire with input _T~j~_, it should expire with all inputs _T~j+k~_ where _k > 0_
- Historical, statistical data about the beacon usage (_BeaconData_) when used to
eg. tune expiration sensitivity so that more groups remain in the pool if the
beacon is busy
- The state of the group pool (_GG_) is also suitable but is already accounted for
separately

Some values that are definitely unsuitable, unless mixed with good inputs in a
suitable way:

- Block hashes: miners can influence block hashes to select different groups for
expiry
- Details of requests: requesters can influence these inputs
- The state of the staker pool: stakers, especially blitzpantsing ones, can
manipulate these values
- Blockheight as a seed to a pseudorandom function: miner censorship can delay
processing of transactions to force the use of new seeds that produce a
different outcome for expiration
- Seeding a pseudorandom function with statistical data seems risky and is not
recommended

To summarize:

- Data under adversary control should not be used without effective sanitization
- Data the adversary can affect in very limited ways is usable as input to
functions that don't exhibit the avalanche effect
- Data that is out of anyone's effective control should be safe

==== Rationale

===== Why you shouldn't prf on the blockheight

What happens if we do the unsafe thing and avalanche the blockheight as a seed
for pseudorandom expiration?

If the size of the group pool is _n~GG~_, the delay window is _T~m~_, and the
average delay between group expirations is _T~e~_, Mallory has _T~m~_ attempts
to produce the most favorable/least unfavourable outcome. Since in a stable
group pool (and one where every DKG succeeds) each group has a _1 / n~GG~_
chance of expiring, Mallory's favourite group can only expire if all outcomes
would lead to its expiration, the probability of which is _1 / n~GG~^T~m~^_.

If we assume every expiration trigger event expires exactly one group (for
simplicity), and Mallory controls _m_ groups, the probability of that expiring
group being Mallory's is is normally _m / n~GG~_. If Mallory gets _T~m~_
expiration rerolls, this goes to _m^T~m~^ / n~GG~^T~m~^_. This means that
Mallory can stabilise a new equilibrium where Mallory's number of controlled
groups _m'_ is such that
_m'^T~m~^ / n~GG~^T~m~^ = m / n~GG~_

_m'^T~m~^ / n~GG~^(T~m~ - 1)^ = m_ +
_m'^T~m~^ = m * n~GG~^(T~m~ - 1)^_

_m' = nthRoot(T~m~, (m * n~GG~^(T~m~ - 1)^))_

or as an example, with _n~GG~ = 300 , T~m~ = 3, n~m~ = 10_, we get:

_m'^3^ = 10 * 300^2^ = 900,000_ +
_m' = 96.5_

Thus an enemy who normally could only control 3.3% of the groups in network can
stabilise a 32% control fraction. With _T~m~ = 4_ it goes to 43%, and _T~m~ = 5_
means 51% control.

===== Can we prf on statistics?

While manipulating blockheight requires only miner censorship, manipulating
beacon history and statistical data is much more involved and requires
requesting and paying for new outputs.

Superficially it would appear that the cost of manipulating group expiration in
such a way would exceed the benefits, but a thorough calculation would need to
address complex aspects of marginal pricing and external incentives.

There isn't really a good reason to feed statistics as input to pseudorandom
functions, and thus the effort is better spent elsewhere.

== Possible schemes

Due to the previous, we are left with essentially two classes of expiry
functions.

=== Limited Lifespan

Timed expiration takes the current blockheight _T~now~_ as input and outputs which
group(s) should expire.

The groups need to be in an unchanging order. If the groups' expiration order
can change (eg. by re-shuffling groups whenever a new one is added), it enables
manipulation by Mallory forcing a re-shuffle just before _G~j~_, where
_Rep~m_j~> Rep~m_average~_, would expire.

Timed expiration should not exhibit "evaporative cooling" either; a group should
not get lucky with a seed value that makes it enduringly less likely to expire
than others.

Because of the above requirements, it seems that expiration with blockheight as
input is effectively limited to ordering groups by
_ExpirySeed~j~ = T~j_creation~ + e~j~_
where _e~j~_ is a non-manipulateable value specific to _G~j~_, and expiring
groups where
_T~now~ > ExpirySeed~j~ + c_
where _c_ is a non-manipulateable value common to all groups.

There seems to be no particular advantage in _e~j~ != 0_ and thus the formula
can be simplified to
_T~now~ > T~j_creation~ + c_
where _c_ acts as the maximum age of a group. Let this form of timed expiration
be called _limited lifespan_. 

==== Limited lifespan manipulation

Timed expiration has a slight manipulation opportunity if a group is on the
verge of expiry and the transaction that would trigger group expiration can be
delayed by eg. miner censorship.

This is possible to mitigate by having such a transaction include a reference
blockheight that must be higher than the blockheight of the previous such
transaction but the same or lower than the current blockheight when the
transaction is mined. However, the impact is limited and specific mitigation
may not be necessary or useful when counterbalanced by the additional complexity
required.

===== Why it is unavoidable

If the trigger transaction happens at time _T_, group _G~i~_ will not expire. If
the transaction happens at _T' > T_, group _G~i~_ will expire. Mallory dislikes
group _G~i~_ and is able to delay the trigger transaction to block _T'_.

If the trigger transaction is a different transaction than the one that selects
the next signing group for output _V~j~_:

- If the transaction arrives at _T_, group _G~i~_ does not expire, and is
present in the pool from which the group to output _V~j~_ is selected
- If the transaction arrives at _T'_, group _G~i~_ expires, and is absent from
the pool for _V~j~_. Mallory's goal is achieved.

If the trigger transaction is the same one which selects group to produce output
_V~j~_, we get two different scenarios based on whether expiration is applied
before selection (so any groups that expire are removed from the pool for
_V~j~_), or after (so even expiring groups are eligible for _V~j~_ but will be
removed from the pool for any later outputs).

If expiration is applied before selection:

- At _T_, _G~i~_ doesn't expire, and is thus eligible for _V~j~_
- At _T'_, _G~i~_ has expired and is not eligible for _V~j~_. Mallory's goal is achieved.

If expiration is applied after selection:

- At _T_, _G~i~_ is eligible for _V~j~_, and is also not removed and thus stays in
the pool for _V~j+1~_ as well
- At _T'_, _G~i~_ is eligible for _V~j~_ despite being marked for expiration,
but it will not be in the pool for _V~j+1~_. Mallory's goal is achieved on the
next output.

===== Is it worth it?

If the size of the group pool is _n~GG~_, the delay window is _T~m~_, and the
average delay between group expirations is _T~e~_, Mallory has:

- _1 / n~GG~_ chance of denying _G~i~_ the signing position on a successful attack
- on any given trigger event there is an expected probability of _T~m~ / T~e~_
of there being a group whose expiry can be manipulated (if Mallory can delay a
transaction by 3 blocks, and a group expires on every 100th block on average, it
gives a 3% chance that a group expiration would occur within that window)
- a _R~m~ - R~i~_ return, where _R~m~_ is the average reward Mallory would get
if any group except _G~i~_, and _R~i~_ is the reward Mallory would (expect to)
get if _G~i~_ produces an output

(assuming we only need to consider one group at a time)

for a total return on the attack of _(R~m~ - R~i~) * T~m~ / T~e~ * n~GG~_.

To put some numbers on this, let's assume the active group pool _n~GG~ = 300_,
_T~m~ = 3, T~e~ = 100_ as above, and Mallory has an average of 5 members in a
group but only 1 in _G~i~_, we get:

_(5R~signer~ - 1) * 3 / 100 * 300 = 12R~signer~ / 30,000 = 0.0004 * R~signer~_
of expected value per trigger event of doing this attack, or
_0.0133 * R~signer~_ value per actual attack with a 0.03 chance of being able to
attack on any given trigger event.

=== Random Expiration

With random expiration, each group is assigned a pseudorandom expiration seed
value upon the expiration trigger transaction, and groups whose seed values fall
below a specific threshold are removed from the pool. Thus each group has an
equal chance of being removed.

== Expiration thresholds

Both timed and random expiration can be tuned to exhibit desirable
characteristics. The maximum age and expiration seed value threshold will be
referred to as simply "expiry threshold".

==== Absolute expiration

At each expiration trigger transaction, calculate the desired number of groups
_n_. If _|GG| > n_, expire _|GG| - n_ groups by setting the threshold accordingly.

==== Probabilistic expiration

Choose parameters for the functions that calculate the expiry threshold so that
the expected value of _|GG'|_ is _n_.

=== Group churn

It is desirable to have adequate turnover in beacon signing groups. Because a
group selection is triggered by every beacon output, new groups will be reliably
added to the pool if the DKG finishes most of the time. Assuming a group pool of
constant size and a DKG that never fails, each group would produce one output
before expiring, on average. If the DKG has a failure rate of _f_, a group would
be expected to sign _1 / (1 - f)_ outputs.

It seems desirable to decouple group expiration from DKG success to reduce the
effectiveness of manipulating the group pool by deliberately inducing DKG
failure. This has two implications:

1. DKG success should not be the group expiration trigger
2. The group expiration should be probabilistic, not absolute

=== Group pool size

TODO: check the math, does pool bias compound the variability in staker profits?
Taking a small sample of (small sample of large pool) vs. small sample of (large
sample of large pool); reconcile w/ churn and individual staker's perspective.

When the group pool is small, group lifespan is relatively short and the
probability of an active group being selected for any given output is relatively
high. Smaller pools are less representative of the pool of stakers, and may be
more susceptible to pool composition manipulation.

With a large pool, each group's (expected) lifespan is relatively long, while
each group's chance of being selected for any specific output is low. A large
pool is more representative of the stakers, but also more expensive to operate
due to on-chain processing costs.

=== Stakeless members

To unstake, a staker needs to wait _T~unstake~_ before the tokens are freed. An
unstaking holder will not be selected for new groups, but they will not be
removed from groups created earlier. Thus _G~i~_ is guaranteed not to have
members who have finished unstaking if _T~now~< T~i_creation~ + T~unstake~_.

With older groups there is a possibility that some members may have nothing at
stake and thus cannot be penalized for misbehavior. This can be prevented by
either extending the unstaking waiting period until the staker is no longer
a member of any active group, or by removing those members from the group and
possibly expiring the group if the number of remaining members falls below
_N - M~nofail~_.

With limited lifespan, these issues can be prevented entirely by setting a cap
on the maximum lifespan at _T~unstake~_ as long as at least 1 DKG can be relied
on to finish successfully within any period of _T~unstake~_.

==== Extended unstaking delay

===== Under random expiration

With random expiration, the probability of a group expiring within the unstaking
period _P~expire~(T~unstake~)_ determines the likelihood of this becoming a
severe issue. Call the probability that a group is still active when a member
finishes unstaking
_P~leftover~ = 1 - P~expire~(T~unstake~)_.

Because the age of a group doesn't impact the expiry probability under random
expiration, each unstake event has a _P~leftover~_ chance of leaving the member
in the group. After _2T~unstake~_ the probability is _P~leftover~^2^_, and so
on for
_1 - P~expire~(x * T~unstake~) = P~leftover~^x^_.
If _P~leftover~_ is low enough, for example _0.001_, this should be reasonably
uncommon. However, the non-deterministic unstaking period creates a severe tail
risk for stakers, which may have a larger-than-expected impact on the value of
the token.

===== Under limited lifespan

If group lifespans have a systemwide hard cap at _T~maxlife~_, blocking
unstaking until a staker's groups have expired means that the real unstaking
period _T'~unstake~_ is
_T~unstake~ <= T'~unstake~<= T~maxlife~_.

The actual value of _T'~unstake~_ for _S~i~_ can be estimated in advance with
some accuracy, using knowledge of the ages of the groups _S~i~_ is represented
in, and the formula for calculating group lifespans:
_c = F~maxlife~(GG, BeaconData)_.
This works even if no systemwide constants are used, although varying beacon
conditions will create some unpredictability.

==== Removing stakeless members

If _S~i~_ is represented as _P~i~_ in _G~j~_, but finishes unstaking while
_G~j~_ is still active, _P~i~_ could be removed from _G~j~_ so they will not be
able to collect rewards for contributing to future outputs. The probability of
this occurring for any given unstaking under random expiration is _P~leftover~_.

If _n_, the number of members remaining in _G~j~_ after DKG is closer to _N_
than _N - M~nofail~_, single members unstaking should not pose a significant
problem.

If a large number of members unstake, _n~remaining~ = n - n~unstaked~_ may fall
below _N - M~nofail~_ and residual security may be compromised. It may be
desirable to terminate a group if
_n~unstaked~ + n~dkg_inactive~ + n~dkg_disqualified~ > M~nofail~_.

If groups terminate when too many members unstake, it opens up a group pool
manipulation attack where _S~m~_ blitzpantses and then unstakes groups where
they control
_m >= M~nofail~ - (n~dkg_inactive~ + n~dkg_disqualified~)_
members.

This ties down _m * Stake~min~_ KEEP for _T~unstake~_ and has _P~leftover~_
probability of success. Assuming the blitzpantsing divides _S~m~_'s tokens in
such a way that any blitzpantsed staker identity is represented in at most one
group in _GG_ (expected number of representations per an identity with
_Stake~min~_ being
_Stake~min~ * N * |GG| / Stake~total~_),
the opportunity cost is as follows:

TODO: actually calculate this

== Terminating groups

In some situations a group may need to be terminated before it would expire
normally.

=== Member attrition

If enough members are removed from the group so that _n~remaining~ < H_,
termination is the only option to preserve beacon reliability.

Termination may be desirable if the group loses enough members to push it below
the threshold of _n~remaining~ < N - M~nofail~_, to preserve residual security.

===== Technical requirements

As qualified members of each group are tracked, no additional capabilities are
required to be able to terminate groups incapable of reaching quorum.

===== Punishment

In the case of termination due to member attrition, the remaining participants
should not be penalized, especially if member attrition below _N - M~nofail~_ is
used as the termination threshold.

If the punishment for each remaining member is _D~terminate_attrition~_ and the
lowest punishment for misbehavior that leads to _P~m~_ being removed from the
group is _D~dropout~_, punishing remaining members enables control bootstrapping
attacks if
_D~terminate_attrition~ * (N - M~terminate~) > D~dropout~ * (M~terminate~ - n~dkg_removed~)_ +
_= D~terminate_attrition~ > D~dropout~ * (M~terminate~ - n~dkg_removed~) / (N - M~terminate~)_ +
_= D~terminate_attrition~ / D~dropout~ > (M~terminate~ - n~dkg_removed~) / (N - M~terminate~)_ +
where +
_n~dkg_removed~ = n~dkg_inactive~ + n~dkg_disqualified~_ +
and _M~terminate~_ is the threshold at which number of removed members the group
is terminated, with probability equal to the adversary controlling
_M~terminate~ - n~dkg_removed~_
members in the group.

If punishing the subquorum group is desired, it will be safe if:

----
D_ta / D_d < (M_t - n_dr) / (N - M_t)
D_d / D_ta > (N - M_t) / (M_t - n_dr)
----

at _n~dkg_removed~ = M~nofail~_: +
_D~dropout~ / D~terminate_attrition~ > (N - M~terminate~) / (M~terminate~ - M~nofail~)_



If _M~terminate~ = M~nofail~ + 1 = (N - 1) / 4 + 1_, +
the above becomes +
*_D~dropout~ / D~terminate_attrition~ > (3N - 3) / 4_*

----
D_d / D_ta > (N - M_nf - 1) / (M_nf + 1 - M_nf)
D_d / D_ta > N - M_nf - 1
D_d / D_ta > N - (N - 1) / 4 - 1
D_d / D_ta > (4N - N + 1) / 4 - 4/4
D_d / D_ta > (3N - 3) / 4
----

Thus a safe punishment for a group falling under quorum would need to be
extremely small.

If _M~terminate~ = M + 1 = (N - 1) / 2 + 1_, +
we get the requirement +
*_D~dropout~ / D~terminate_attrition~ > 2 - 8 / (N + 3)_*

----
D_d / D_ta > (N - M - 1) / (M + 1 - M_nf)
D_d / D_ta > (N - (N - 1) / 2 - 1) / ((N - 1) / 2 - (N - 1) / 4 + 1)
D_d / D_ta > ((2N - N + 1) / 2 - 1) / ((N - 1) / 4 + 1)
D_d / D_ta > ((N + 1) / 2 - 1) / ((N - 1) / 4 + 1)
D_d / D_ta > (N/2 - 1/2) / (N/4 + 3/4)
D_d / D_ta > (2N - 2) / (N + 3)
D_d / D_ta > (2N + 6 - 8) / (N + 3)
D_d / D_ta > (2(N + 3) - 8) / (N + 3)
D_d / D_ta > 2 - 8 / (N + 3)
----

In this case, as long as the punishment for each remaining group member is less
than half of the smallest dropout punishment, the punishments can be given
without enabling arbitrary power bootstrapping attacks. Nonetheless, punishing a
disproportionately honest group of stakers for something caused by the actions
of the other members is not recommended.

Punishing the removed members in the case of failure to stay in quorum is
possible if removed members are flagged as disqualified for rewards while
remaining on the list of the original group members.

=== Compromised private key

If the group private key has been exposed or the group is proven to collude in
signing invalid values, the group should be terminated to preserve beacon
security.

===== Technical requirements

This can be achieved by tracking the values _Input~i~_ signed by the group to
generate outputs _V~i~_. Because each group signs on average
_1 + Prob~dkg_failure~ / Prob~dkg_success~_ inputs before expiring, this would
not lead to excessively expensive record-keeping.

If a valid signature on value _Input~m~_ is made using the public key of _G~j~_,
and _Input~m~_ is not present in the list of values _G~j~_ has signed in the
beacon operation, _G~j~_ should be terminated.

===== Punishment

Because signing such an invalid value requires at least _H_ members to misbehave
or have their individual private keys compromised, punishing the entire group
may seem safe and appropriate even if the specific guilty parties cannot be
identified.

However, control bootstrapping attacks are possible if +
_D~terminate_compromise~ * M > D~min_compromise~ * (H - n~dkg_dq_late~ - 1) + D~terminate_compromise~ - R~tattletale_compromise~_ +
where +
_D~min_compromise~= min(D~terminate_compromise~, D~dropout~)_, +
_n~dkg_dq_late~_ members are disqualified in phase 9 of the DKG, and +
_R~tattletale_compromise~_ is the reward for the actor presenting proof of the
violation.

Thus no amount of punishment is entirely safe if _n~dkg_dq_late~ > 1_.

The probability of success equals the probability of the adversary controlling
_m = H - n~dkg_dq_late~_ members in the group, with the minimum being
_m = M~nofail~ + 1_ with _n~dkg_dq_late~ = M~nofail~_.

The control bootstrap multiplier for this attack in the most favorable case is:
_(D~tc~ * M) / (D~mc~ * M~nf~ + D~tc~ - R~tc~)_.
Defining _R~tc~ = a * D~tc~_ where _a < m~mc~_ gets:
_(D~tc~ * M) / (D~mc~ * M~nf~ - (a - 1) * D~tc~)_
Define _r = D~tc~ / D~mc~_:

----
_(r * M) / (M~nf~ - (a - 1) * r)_
_(r * M) / (M/2 - (a - 1) * r)_
_2(r * M) / (M - (2a - 2) * r)_
_2r * M / (M - 2ar + 2r)_
----

simplifying to:

_2r + 4r^2^ * (a - 1) / (M - 2ar + 2r)_

Because _a_ should be larger than 1 to incentivize burning a compromised group
even if you have a node in it, and lower than _M/2_ to disincentivize actively
seeking to collude and loot other stakers, the _2r_ factor is the most relevant.
Consequently the required economic power for this attack is roughly
_50% * min(1, D~dropout~ / D~terminate_compromise~)_ of the honest participants'
power.
