= keep-core

https://circleci.com/gh/keep-network/keep-core[image:https://circleci.com/gh/keep-network/keep-core.svg?style=svg&circle-token=ec728f5ca814b6cb2db5ffeb7258151b752a207e[CircleCI Build Status]]
https://discord.gg/wYezN7v[image:https://img.shields.io/badge/chat-Discord-blueViolet.svg[Chat with us on Discord]]

The core code behind the Keep network, a privacy, interoperability, and
censorship-resistance toolkit for developers on Ethereum.

== Getting Started as a Developer

Start with the README in link:docs/development/[the developer docs directory].

== Directory structure

The directory structure used in the Keep repository is very similar to that used
in other Go projects:

```
keep-core/
  Dockerfile
  main.go, *.go
  docs/
  solidity/ <1>
  cmd/ <2>
  pkg/ <3>
    net/
      net.go, *.go <4>
      libp2p/
    chain/
      chain.go, *.go <4>
      ethereum/
        gen/
          gen.go <5>
    relay/
      relay.go, *.go
```
<1> While Keep only uses Solidity at the moment, the directory structure allows
    for other contract languages.
<2> Keep subcommands are implemented here, though they should be minimal and
    deal solely with user interaction. The meat of the commands should exist in
    a package fit for the appropriate purpose.
<3> All additional packages live in `pkg/`.
<4> The high-level interfaces for a package `mypackage` live in `mypackage.go`.
    `net` and `chain` are interface packages that expose a common interface
    to network and blockchain layers. Their subpackages provide particular
    implementations of these common interfaces. Only `cmd/` and the main
    package should interact with the implementations directly.
<5> When a package requires generated code, it should have a subpackage named
    `gen/`. This subpackage should contain a single file, `gen.go`, with a
    `// go:generate` annotation to trigger appropriate code generation. All code
    generation is done with a single invocation of `go generate` at build time.

== link:docs/[`docs/`]

Documentation related to the Keep network, Keep client, and Keep
contracts.

=== link:docs/development/[`docs/development/`]

Specifically developer documentation for the various parts of Keep.

== link:solidity/[`solidity/`]

The Solidity smart contracts behind the https://keep.network[Keep network].

They handle creating and managing keeps, bridging off-chain secret
storage and the public blockchain.

== link:pkg/[`pkg/`]

The Keep Go client.

It runs the Keep network’s random beacon and participates in related
computations.