apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: electrumx-v2
# Requires Google Compute Engine persistent disk CSI Driver to be enabled on the
# cluster, see: https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/gce-pd-csi-driver
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-ssd
  replication-type: none
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
