---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: electrumx
spec:
  replicas: 1
  serviceName: electrumx
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        # https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: electrumx
          image: lukechilds/electrumx:v1.16.0 # TODO: switch to our image
          imagePullPolicy: Always
          # Full list of env vars: https://electrumx.readthedocs.io/en/latest/environment.html
          env:
            - name: COIN
              value: BitcoinSegwit
            - name: NET
              value: mainnet
            - name: DAEMON_USER
              valueFrom:
                secretKeyRef:
                  name: bitcoind
                  key: rpc-user
            - name: DAEMON_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bitcoind
                  key: rpc-password
            - name: DAEMON_HOST
              valueFrom:
                configMapKeyRef:
                  name: electrumx
                  key: daemon-host
            - name: DAEMON_URL
              value: http://$(DAEMON_USER):$(DAEMON_TOKEN)@$(DAEMON_HOST)
            - name: DB_DIRECTORY
              value: /mnt/electrum/data
            - name: SSL_CERTFILE
              value: /mnt/electrum/cert/tls.crt
            - name: SSL_KEYFILE
              value: /mnt/electrum/cert/tls.key
            - name: SERVICES
              value: tcp://:50001,ssl://:50002,ws://:50003,wss://:50004,rpc://0.0.0.0:8000
            - name: COST_SOFT_LIMIT
              value: "0"
            - name: COST_HARD_LIMIT
              value: "0"
            - name: LOG_LEVEL
              value: debug
          ports:
            - name: tcp
              containerPort: 50001
            - name: ssl
              containerPort: 50002
            - name: ws
              containerPort: 50003
            - name: wss
              containerPort: 50004
            - name: rpc
              containerPort: 8000
          livenessProbe:
            tcpSocket:
              port: rpc
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: tcp
            initialDelaySeconds: 20
            periodSeconds: 30
          resources:
            requests:
              cpu: 500m
              memory: 8Gi
          volumeMounts:
            - name: electrumx-data
              mountPath: /mnt/electrum/data
            - name: tbtc-network-cloudflare-origin-cert
              mountPath: /mnt/electrum/cert
      volumes:
        - name: electrumx-data
          persistentVolumeClaim:
            claimName: electrumx
        - name: tbtc-network-cloudflare-origin-cert
          secret:
            secretName: tbtc-network-cloudflare-origin-cert
  volumeClaimTemplates:
    - metadata:
        name: electrumx-data
      spec:
        storageClassName: electrumx-v2
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 450Gi
