resources:
  - electrumx-service.yaml
  - electrumx-statefulset.yaml
  - electrumx-storageclass.yaml
  - electrumx-volumesnapshotclass.yaml

commonLabels:
  chain: bitcoin
  app: electrumx

configMapGenerator:
  - name: electrumx
    literals:
      - daemon-host=bitcoind:8332

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: generated
