---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: tbtc-v2-monitoring
  namespace: default
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 240
      backoffLimit: 0
      template:
        spec:
          volumes:
            - name: tbtc-v2-monitoring-data
              persistentVolumeClaim:
                claimName: tbtc-v2-monitoring-data
          restartPolicy: Never
          containers:
            - name: tbtc-v2-monitoring
              image: tbtc-v2-monitoring:latest
              imagePullPolicy: Always
              env:
                - name: ENVIRONMENT
                  valueFrom:
                    configMapKeyRef:
                      name: tbtc-v2-monitoring-config
                      key: environment
                - name: ETHEREUM_URL
                  valueFrom:
                    secretKeyRef:
                      name: tbtc-v2-monitoring-config
                      key: ethereum-url
                - name: ELECTRUM_URL
                  valueFrom:
                    secretKeyRef:
                      name: tbtc-v2-monitoring-config
                      key: electrum-url
                - name: LARGE_DEPOSIT_THRESHOLD_SAT
                  valueFrom:
                    configMapKeyRef:
                      name: tbtc-v2-monitoring-config
                      key: large-deposit-threshold-sat
                - name: DATA_DIR_PATH
                  value: /mnt/tbtc-v2-monitoring/data
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: tbtc-v2-monitoring-config
                      key: sentry-dsn
                - name: DISCORD_WEBHOOK_URL
                  valueFrom:
                    secretKeyRef:
                      name: tbtc-v2-monitoring-config
                      key: discord-webhook-url
              volumeMounts:
                - name: tbtc-v2-monitoring-data
                  mountPath: /mnt/tbtc-v2-monitoring/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tbtc-v2-monitoring-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi