:toc: macro

= Technical Status Report: 2020-11-11 Geth Hardfork Retrospective

toc::[]

This is a Keep-specific post-mortem on the impact of the geth hardfork that
occurred on 11 November 2020. A full post-mortem of the geth issue is
available
https://gist.github.com/karalabe/e1891c8a99fdc16c4e60d9713c35401f[on GitHub],
and an explanation of how the fork was triggered was posted to Twitter
https://twitter.com/jinglanW/status/1326651349912719360[by the Optimism
team].

[#timeline,%header]
.Incident timeline (Keep)
|===
| Time	    | Event
| 08:43 UTC |	Provider observes random beacon relay entry timeout on mainnet node
| 08:58 UTC |	Keep on-call engineer starts investigating the root cause of the relay entry timeout
| 09:05 UTC |	Fork is suggested due to no relay entry timeout observed on Etherscan
| 09:32 UTC |	Advised by team, provider begins redirecting a node from their existing Ethereum node provider to Infura to test fork hypothesis
| 09:52 UTC |	Provider reports node is seeing a signing process, but still not lining up with Etherscan
| 10:01 UTC |	On-call engineer notes Infura outage flagged on the Infura status page
| 10:09 UTC |	On-call engineer continues to observe inconsistencies on Etherscan
| 10:37 UTC |	On-call engineer observes a relay entry timeout reporting bot submitting timeouts
| 10:47 UTC |	On-call engineer notes 20 AWAITING_SIGNER_SETUP Bitcoin deposits and ~22 nodes disappeared from the main Keep network
| 10:51 UTC |	On-call engineer escalates to project lead + head of engineering
| 12:19 UTC |	Decision is made to disable tBTC dApp and Keep token dashboard
| 12:20 UTC |	Decision is made to disable the Keep random beacon operator contract, shutting down the Keep random beacon
| 12:38 UTC |	Keep random beacon operator contract is disabled at https://etherscan.io/tx/0x68da31c439fd057f044f510e83a09ec8968015e35a0fcf82c19eaca921b205f5
|===

== Impact

=== Random Beacon

The random beacon had 3 timeouts due to a failure to respond with a random
number in time. Before a fourth timeout triggered, the random beacon operator
contract was disabled by unilateral action from the team. This action
immediately disables the token slashing capabilities of the operator
contract, and is the “panic button” functionality described in the
https://docs.keep.network/random-beacon/#_the_registry_and_panic_button[random
beacon specification].

By default, each timeout slashes the current minimum stake of tokens for each
slot in the group that has failed to provide the random beacon entry. Each
group includes between 33 and 64 slots, usually 64, with each operator able
to take up multiple slots depending on the group member choice. 32 of those
slots have to fail to provide a signature share in order for a group to fail.
A sufficient portion of the network was offline or on a forked chain that
this happened to 3 groups in a row. The total slashing was 153,600 KEEP
tokens. 151,219.2 KEEP tokens were burned (~0.01% of the total, fixed
supply), while 2380.8 KEEP was awarded to the account that reported the relay
entry timeout as a reward.

Notably, the account that reported the relay entry timeout appeared to be a
bot attached to a smart contract that flash-loaned WETH and immediately
converted the KEEP to WETH on Uniswap for a total gain of ~1.71 ETH. Here are
the timeout transactions:

* https://etherscan.io/tx/0x2ff7912c387fc0261f04ceabdbe110694fbdc98462f87428552edb909e668c6a
* https://etherscan.io/tx/0x368467abdb10891d6f6d06ccf37852b8e5b0ac76ac87f998c497370e277a7633
* https://etherscan.io/tx/0xd59e74b7b201d8b544ec8b346fc1a55151cf15c6ac850bf4ffdb4a175de5db3c

A total of 63 unique operators were slashed in varying amounts, across several staking providers and individuals.

=== tBTC

The impact to tBTC was limited to 22 deposits that started setup before the
fork and never finished. This is the state of a deposit right after a user
requests the deposit be created, and right before the network provides a
Bitcoin address to fund. The deposits never received an address due to the
network fork. This has a small cost, as the depositors can reclaim their
opening fee (~0.15 ETH) from signer bonds in scenarios where the signers fail
to provide an address. In this case the total cost across all deposits to
operators was ~3.3 ETH, split across the various operators the deposits used.

Note that although tBTC uses the random beacon for additional randomness in
choosing operators, it is designed to operate even if the random beacon is
disabled, as occurred in this case.

Though the impact to tBTC was limited, chain splits like this one always open
an opportunity for loss of funds, whether users are moving ERC-20s, NFTs, or
ETH.

== Team Actions

The Keep team does not operate nodes on the Keep network. Some team members
who have KEEP grants choose to stake with certain providers (and several team
members’ stakes were slashed in the beacon timeouts), the company does not
directly operate or have visibility into nodes. This means the actions the
Keep team takes are biased towards responsiveness with on-chain action,
helping providers better react to issues, and helping coordinate
inter-provider actions where necessary. Here are our primary takeaways from
this incident:

* The team has already been working on a shared set of monitoring and alerting
  recommendations for all operators, professional or personal. We are in the
  final stages of reviewing these with larger node operators to verify that
  they would generally catch and escalate issues that we have seen in the past,
  including this one, with plenty of time to react.footnote:[These are
  currently available at
  https://docs.keep.network/monitoring-and-alerting.html.]
* The random beacon client does not clearly signal to an operator that a relay
  request is in danger of timing out. The team will be exploring adding WARN
  level logs as a relay request approaches timeout. In conjunction with the
  monitoring and alerting recommendations, the intent is to provide a clear
  escalation to operators with enough time to react to an approaching timeout.
* We are generally loath to use the ability to disable operator contracts, as
  it can have an extremely disruptive impact to users of the those contracts
  and is an irreversible action. Additionally, the capability to halt the
  beacon is something that we are intending on transferring to a multisig, DAO,
  or other decentralized mechanism in the future, which would make it much more
  difficult to trigger in this kind of scenario. Nonetheless, the team is
  studying whether it would have made sense to halt the random beacon earlier
  than the point at which it was halted, and setting guidelines for future
  action in a similar scenario.

Lastly, the team is working on strategies for staking providers and
individual stakers to coordinate with each other in cases where network
failures cross node and network boundaries. There is currently space for ad
hoc coordination, but the Keep team is often an intermediary; future network
growth will likely mean the number of operators will make it an untenable
strategy moving forward.
