global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
scrape_configs:
  - job_name: keep-discovered-nodes
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    relabel_configs:
      - source_labels: [__meta_chain_address]
        separator: ;
        regex: (.*)
        target_label: chain_address
        replacement: $1
        action: replace
      - source_labels: [__meta_network_id]
        separator: ;
        regex: (.*)
        target_label: network_id
        replacement: $1
        action: replace
    file_sd_configs:
      - files:
          - /etc/prometheus/sd/keep-sd.json
        refresh_interval: 5m
