:toc: macro

= Monitoring and Alerting for Keep Nodes

toc::[]

Operators on the Keep network are typically running two client executables,
generally on separate nodes. These clients each join a separate libp2p network,
one for the Keep random beacon and one for the Keep ECDSA system used to back,
amongst other things, tBTC.

Below are some important metrics and alerting guidelines that apply to both
clients.

== Important Metrics

Clients report information in two primary ways: a metrics endpoint accessible
via HTTP and the logs that are printed from the client. Logs have levels that
correspond to message severity.

As such, the most important metrics to track for all Keep nodes are:

* WARN log count over time
* ERROR log count over time
* CRITICAL log count over time
* Peer count over time (accessible at `/metrics` on the port configured in the
  `Metrics` block of the configuration file.)
* ETH balance of the operator account

The client can be configured to log ERROR-level logs when the ETH balance of the
operator account drops below a set level; look for `BalanceAlertThreshold` in
the sample configuration file for more.

For ECDSA clients, in addition to these metrics, it’s recommended that you
track the keeps that a given node is participating in. You can track these by
looking for log messages in the format:

```
member [%s] is starting signer generation for keep [%s]...  
```

These indicate keep opening, with the first `%s` being the operator address
and the second being the keep address. Keep closing or termination can be
spotted by looking for log messages in the format:

```
unsubscribing from events on keep terminated 
unsubscribing from events on keep closed 
```

These currently do not include the keep address, though they will be updated to do so.

== Alerting and Notification Thresholds

The guidelines below distinguish between **notifications**, which are
informational but not necessarily interruptive, and **alerts**, which should
trigger pages and lead to quick investigation. The guidelines also
distinguish between different likelihoods of fund loss. Recommended
thresholds are as follows:

* More than 5 WARN logs over 5 minutes should result in a **notification** for
  on-call personnel for closer monitoring. These are typically
  connectivity-related, and can be precursors to larger issues if remediation
  is not applied. Fund loss may or may not occur without intervention if
  warnings do not stop.
* More than 10 WARN logs over 15 minutes should result in **alerts** that will
  trigger pages for on-call personnel. As above, these can be precursors to
  larger issues without remediation. Fund loss is possible without
  intervention.
* ERROR and CRITICAL logs should result in escalated **alerts** that will
  trigger pages for on-call personnel. CRITICAL logs are generally associated
  with a node crash. Both are a high-signal indicator that the node is
  experiencing issues that have already led to on-chain problems or will soon
  do so. Fund loss is probable without intervention.
* Peer counts that drop by more than 5% in a 10-minute period should result in
  a **notification** for on-call personnel for closer monitoring. These may
  or may not be due to the node itself, but can be precursors to larger
  issues if not investigated. Fund loss may or may not occur without
  intervention if these counts do not recover.
* Peer counts that drop by more than 10% and remain dropped for a 20-minute
  period should result in **alerts** that will trigger pages for on-call
  personnel. These may or may not be due to the node itself, but can be
  precursors to larger issues if not investigated. If the issues don’t seem
  to be with the node but with one of its peers, it’s highly recommended to
  engage with the community Discord to try and find the relevant operator.
  Fund loss is possible without intervention if the problematic node is
  participating in a keep with the node you are operating.
* Operator ETH balance below 0.5 ETH should result in a **notification** for
  on-call personnel for closer monitoring. This is a high safety margin, but
  should result in close monitoring of balance and start the process for
  topping the operator account up.
* Operator ETH balance below 0.2 ETH should result in **alerts** that will
  trigger pages for on-call personnel. ETH balance below 0.2 ETH can quickly
  deplete in cases of high network activity, so replenishing it is high
  priority. Fund loss is possible without intervention if the node in
  question fails to participate in a critical operation (e.g. a redemption
  signature or a signer setup).