apiVersion: v1
kind: Service
metadata:
  name: atlantis-https
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"atlantis-https-port":"HTTPS"}'
spec:
  type: NodePort
  ports:
  - name: atlantis-https-port
    port: 8443
    targetPort: 8443
  selector:
    app: atlantis