---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eth-tx
  namespace: ropsten
spec:
  replicas: 1
  serviceName: eth-tx
  volumeClaimTemplates:
  - metadata:
      name: eth-tx
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: eth-tx
      resources:
        requests:
          storage: 100Gi
  selector:
    matchLabels:
      app: geth
      type: tx
  template:
    metadata:
      labels:
        app: geth
        type: tx
    spec:
      containers:
      - name: tx
        image: ethereum/client-go:v1.9.6
        ports:
          - containerPort: 8545
          - containerPort: 8546
          - containerPort: 30303
        volumeMounts:
          - name: eth-tx
            mountPath: /root/.ethereum
        args: ["--testnet", "--datadir=/root/.ethereum", "--syncmode=light", "--rpc", "--rpcapi=eth,web3,personal", "--rpcport=8545", "--rpcaddr=0.0.0.0", "--rpccorsdomain=\"\"", "--rpcvhosts=*", "--ws", "--wsport=8546", "--wsaddr=0.0.0.0", "--wsorigins=*", "--txpool.accountslots 128", "--txpool.accountqueue 512"]

