---
apiVersion: v1
kind: Service
metadata:
  name: eth-miner-node
  labels:
    app: geth
    type: miner
spec:
  ports:
  - port: 8545
    targetPort: 8545
    name: tcp-8545
  - port: 8546
    targetPort: 8546
    name: tcp-8546
  - port: 30303
    targetPort: 30303
    name: tcp-30303
  - port: 30303
    targetPort: 30303
    name: udp-30303
    protocol: UDP
  selector:
    app: geth
    type: miner
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eth-miner-node
spec:
  serviceName: eth-miner-node
  replicas: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  selector:
    matchLabels:
      app: geth
      type: miner
  template:
    metadata:
      labels:
        app: geth
        type: miner
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: miner
        image: gcr.io/keep-dev-fe24/geth-node
        ports:
        - containerPort: 8545
        - containerPort: 8546
        - containerPort: 30303
        volumeMounts:
        - name: eth-miner-node
          mountPath: /mnt/eth-data
        env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NETWORKID
          value: "9384767738"
        - name: WS_SERVER
          value: ws://eth-dashboard.default.svc.cluster.local:3000
        - name: WS_SECRET
          value: BANZAI!!!!
        - name: BOOTNODE_URL
          value: http://eth-dashboard.default.svc.cluster.local:3001
        - name: BOOTNODE_NETWORK
          value: network_1
        - name: ENABLE_MINER
          value: "1"
        - name: MINER_THREADS
          value: "1"
        - name: HOSTVOLUME
          value: /mnt/eth-data
        - name: ETH_IPC_PATH
          value: $(HOSTVOLUME)/geth.ipc
  volumeClaimTemplates:
    - metadata:
        name: eth-miner-node
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
