---
apiVersion: v1
kind: Service
metadata:
  name: keep-dapp-staking
  labels:
    app: keep-dapp
    type: staking
spec:
  ports:
  - port: 80
    targetPort: 80
    name: tcp-80
  selector:
    app: keep-dapp
    type: staking