---
apiVersion: v1
kind: Service
metadata:
  name: keep-client-peer-3
  labels:
    app: keep-client-peer-3
spec:
  ports:
  - port: 3925
    targetPort: 3925
    name: tcp-3925
  selector:
    app: keep-client-peer-3
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keep-client-peer-3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keep-client-peer-3
    spec:
      containers:
      - name: keep-client-peer-3
        image: gcr.io/keep-dev-fe24/keep-client-peer-3
        ports:
          - containerPort: 3925