package dkg2

import (
	"math/big"
	"testing"

	bn256 "github.com/ethereum/go-ethereum/crypto/bn256/cloudflare"
	relayChain "github.com/keep-network/keep-core/pkg/beacon/relay/chain"
	"github.com/keep-network/keep-core/pkg/beacon/relay/gjkr"
	chainLocal "github.com/keep-network/keep-core/pkg/chain/local"
	netLocal "github.com/keep-network/keep-core/pkg/net/local"
)

func TestExecuteDKGLocal(t *testing.T) {
	groupSize := 5
	threshold := 3

	requestID := big.NewInt(13)
	seed := big.NewInt(8)

	networkProvider := netLocal.Connect()
	chainHandle := chainLocal.Connect(groupSize, threshold, big.NewInt(200))

	blockCounter, err := chainHandle.BlockCounter()
	if err != nil {
		t.Fatal(err)
	}

	executeDKG := func(playerIndex int) error {
		broadcastChannel, err := networkProvider.ChannelFor("testing_channel")
		if err != nil {
			t.Fatalf("cannot generate broadcast channel [%v]", err)
		}

		_, err = ExecuteDKG(
			requestID,
			seed,
			playerIndex,
			groupSize,
			threshold,
			blockCounter,
			chainHandle.ThresholdRelay(),
			broadcastChannel,
		)

		return err
	}

	errors := make([]chan error, groupSize)
	for index := range errors {
		errors[index] = make(chan error)
		defer close(errors[index])

		go func(i int) {
			errors[i] <- executeDKG(i)
		}(index)
	}

	for index := range errors {
		err := <-errors[index]

		if err != nil {
			t.Errorf("unexpected error: [%v]",
				err,
			)
		}
	}

	isResultPublished, err := chainHandle.ThresholdRelay().IsDKGResultPublished(requestID)
	if err != nil {
		t.Error(err)
	}

	if !isResultPublished {
		t.Fatal("result is not published")
	}

	// TODO After Phase 14 implementation add more validations to check if results generated by all players are consistent

}

func TestConvertResult(t *testing.T) {
	groupSize := 5

	publicKey := new(bn256.G1).ScalarBaseMult(big.NewInt(2))
	var serializedPublicKey [32]byte
	copy(serializedPublicKey[:], publicKey.Marshal())

	var tests = map[string]struct {
		gjkrResult     *gjkr.Result
		expectedResult *relayChain.DKGResult
	}{
		"success: false, group public key: nil, DQ and IA: empty": {
			gjkrResult: &gjkr.Result{
				Success:        false,
				GroupPublicKey: nil,
				Disqualified:   []gjkr.MemberID{},
				Inactive:       []gjkr.MemberID{},
			},
			expectedResult: &relayChain.DKGResult{
				Success:        false,
				GroupPublicKey: [32]byte{},
				Disqualified:   []byte{0x00, 0x00, 0x00, 0x00, 0x00},
				Inactive:       []byte{0x00, 0x00, 0x00, 0x00, 0x00},
			},
		},
		"success: true, group public key: provided, DQ and IA: provided": {
			gjkrResult: &gjkr.Result{
				Success:        true,
				GroupPublicKey: publicKey,
				Disqualified:   []gjkr.MemberID{1, 3, 4},
				Inactive:       []gjkr.MemberID{5},
			},
			expectedResult: &relayChain.DKGResult{
				Success:        true,
				GroupPublicKey: serializedPublicKey,
				Disqualified:   []byte{0x01, 0x00, 0x01, 0x01, 0x00},
				Inactive:       []byte{0x00, 0x00, 0x00, 0x00, 0x01},
			},
		},
	}
	for _, test := range tests {
		convertedResult := convertResult(test.gjkrResult, groupSize)

		if !test.expectedResult.Equals(convertedResult) {
			t.Fatalf("\nexpected: %v\nactual:   %v\n", test.expectedResult, convertedResult)
		}
	}
}
