export const KEEP_TOKEN_CONTRACT_NAME = 'token'
export const TOKEN_STAKING_CONTRACT_NAME = 'stakingContract'
export const TOKEN_GRANT_CONTRACT_NAME = 'grantContract'
export const OPERATOR_CONTRACT_NAME = 'keepRandomBeaconOperatorContract'
export const OPERATOR_CONTRACT_NAME_EVENTS = 'eventKeepRandomBeaconOperatorContract'
