// Package gjkr contains code that implements Distributed Key Generation protocol
// described in [GJKR 99].
//
// See http://docs.keep.network/random-beacon/dkg.html
//
//     [GJKR 99]: Gennaro R., Jarecki S., Krawczyk H., Rabin T. (1999) Secure
//         Distributed Key Generation for Discrete-Log Based Cryptosystems. In:
//         Stern J. (eds) Advances in Cryptology — EUROCRYPT ’99. EUROCRYPT 1999.
//         Lecture Notes in Computer Science, vol 1592. Springer, Berlin, Heidelberg
//         http://groups.csail.mit.edu/cis/pubs/stasio/vss.ps.gz
package gjkr

import (
	crand "crypto/rand"
	"fmt"
	"math/big"

	bn256 "github.com/ethereum/go-ethereum/crypto/bn256/cloudflare"
	"github.com/keep-network/keep-core/pkg/beacon/relay/group"
	"github.com/keep-network/keep-core/pkg/net/ephemeral"
)

// GenerateEphemeralKeyPair takes the group member list and generates an
// ephemeral ECDH keypair for every other group member. Generated public
// ephemeral keys are broadcasted within the group.
//
// See Phase 1 of the protocol specification.
func (em *EphemeralKeyPairGeneratingMember) GenerateEphemeralKeyPair() (
	*EphemeralPublicKeyMessage,
	error,
) {
	ephemeralKeys := make(map[group.MemberIndex]*ephemeral.PublicKey)

	// Calculate ephemeral key pair for every other group member
	for _, member := range em.group.MemberIDs() {
		if member == em.ID {
			// don’t actually generate a key with ourselves
			continue
		}

		ephemeralKeyPair, err := ephemeral.GenerateKeyPair()
		if err != nil {
			return nil, err
		}

		// save the generated ephemeral key to our state
		em.ephemeralKeyPairs[member] = ephemeralKeyPair

		// store the public key to the map for the message
		ephemeralKeys[member] = ephemeralKeyPair.PublicKey
	}

	return &EphemeralPublicKeyMessage{
		senderID:            em.ID,
		ephemeralPublicKeys: ephemeralKeys,
	}, nil
}

// GenerateSymmetricKeys attempts to generate symmetric keys for all remote group
// members via ECDH. It generates this symmetric key for each remote group member
// by doing an ECDH between the ephemeral private key generated for a remote
// group member, and the public key for this member, generated and broadcasted by
// the remote group member.
//
// See Phase 2 of the protocol specification.
func (sm *SymmetricKeyGeneratingMember) GenerateSymmetricKeys(
	ephemeralPubKeyMessages []*EphemeralPublicKeyMessage,
) error {
	for _, ephemeralPubKeyMessage := range ephemeralPubKeyMessages {
		otherMember := ephemeralPubKeyMessage.senderID

		if !sm.isValidEphemeralPublicKeyMessage(ephemeralPubKeyMessage) {
			logger.Warningf(
				"[member:%v] member [%v] disqualified because of "+
					"sending invalid ephemeral public key message",
				sm.ID,
				otherMember,
			)
			sm.group.MarkMemberAsDisqualified(otherMember)
			continue
		}

		sm.evidenceLog.PutEphemeralMessage(ephemeralPubKeyMessage)

		// Find the ephemeral key pair generated by this group member for
		// the other group member.
		ephemeralKeyPair, ok := sm.ephemeralKeyPairs[otherMember]
		if !ok {
			return fmt.Errorf(
				"ephemeral key pair does not exist for member %v",
				otherMember,
			)
		}

		// Get the ephemeral private key generated by this group member for
		// the other group member.
		thisMemberEphemeralPrivateKey := ephemeralKeyPair.PrivateKey

		// Get the ephemeral public key broadcasted by the other group member,
		// which was intended for this group member.
		otherMemberEphemeralPublicKey := ephemeralPubKeyMessage.ephemeralPublicKeys[sm.ID]

		// Create symmetric key for the current group member and the other
		// group member by ECDH'ing the public and private key.
		symmetricKey := thisMemberEphemeralPrivateKey.Ecdh(
			otherMemberEphemeralPublicKey,
		)
		sm.symmetricKeys[otherMember] = symmetricKey
	}

	return nil
}

// isValidEphemeralPublicKeyMessage validates a given EphemeralPublicKeyMessage.
// Message is considered valid if it contains ephemeral public keys for
// all other group members.
func (sm *SymmetricKeyGeneratingMember) isValidEphemeralPublicKeyMessage(
	message *EphemeralPublicKeyMessage,
) bool {
	for _, memberID := range sm.group.MemberIDs() {
		if memberID == message.senderID {
			// Message contains ephemeral public keys only for other group members
			continue
		}

		if _, ok := message.ephemeralPublicKeys[memberID]; !ok {
			logger.Warningf(
				"[member:%v] ephemeral public key message from member [%v] "+
					"does not contain public key for member [%v]",
				sm.ID,
				message.senderID,
				memberID,
			)
			return false
		}
	}

	return true
}

// CalculateMembersSharesAndCommitments starts with generating coefficients for
// two polynomials. It then calculates shares for all group member and packs
// them into a broadcast message. Individual shares inside the message are
// encrypted with the symmetric key of the indended share receiver.
// Additionally, it calculates commitments to `a` coefficients of first
// polynomial using second's polynomial `b` coefficients.
//
// If there are no symmetric keys established with all other group members,
// function yields an error.
//
// See Phase 3 of the protocol specification.
func (cm *CommittingMember) CalculateMembersSharesAndCommitments() (
	*PeerSharesMessage,
	*MemberCommitmentsMessage,
	error,
) {
	polynomialDegree := cm.group.DishonestThreshold()
	coefficientsA, err := generatePolynomial(polynomialDegree)
	if err != nil {
		return nil, nil, fmt.Errorf(
			"could not generate shares polynomial [%v]",
			err,
		)
	}
	coefficientsB, err := generatePolynomial(polynomialDegree)
	if err != nil {
		return nil, nil, fmt.Errorf(
			"could not generate hiding polynomial [%v]",
			err,
		)
	}

	cm.secretCoefficients = coefficientsA

	// Calculate shares for other group members by evaluating polynomials
	// defined by coefficients `a_i` and `b_i`
	var sharesMessage = newPeerSharesMessage(cm.ID)
	for _, receiverID := range cm.group.MemberIDs() {
		// s_j = f_(j) mod q
		memberShareS := cm.evaluateMemberShare(receiverID, coefficientsA)
		// t_j = g_(j) mod q
		memberShareT := cm.evaluateMemberShare(receiverID, coefficientsB)

		// Check if calculated shares for the current member.
		// If so, store them without sharing in a message.
		if cm.ID == receiverID {
			cm.selfSecretShareS = memberShareS
			cm.selfSecretShareT = memberShareT
			continue
		}

		// If there is no symmetric key established with the receiver,
		// yield an error.
		symmetricKey, hasKey := cm.symmetricKeys[receiverID]
		if !hasKey {
			logger.Warningf("no symmetric key for receiver: [%v]", receiverID)
			continue
		}

		err := sharesMessage.addShares(
			receiverID,
			memberShareS,
			memberShareT,
			symmetricKey,
		)
		if err != nil {
			return nil, nil, fmt.Errorf(
				"could not add shares for receiver %v [%v]",
				receiverID,
				err,
			)
		}
	}

	commitments := make([]*bn256.G1, len(coefficientsA))
	for k := range commitments {
		commitments[k] = cm.calculateCommitment(coefficientsA[k], coefficientsB[k])
	}
	commitmentsMessage := &MemberCommitmentsMessage{
		senderID:    cm.ID,
		commitments: commitments,
	}

	return sharesMessage, commitmentsMessage, nil
}

// calculateCommitment generates a Pedersen commitment to a secret value
// `secret` with a blinding factor `t`.
func (cm *CommittingMember) calculateCommitment(
	secret *big.Int,
	t *big.Int,
) *bn256.G1 {
	gs := new(bn256.G1).ScalarBaseMult(secret)                 // G * secret
	ht := new(bn256.G1).ScalarMult(cm.protocolParameters.H, t) // H * t

	return new(bn256.G1).Add(gs, ht) // G * secret + H * t
}

// generatePolynomial generates a random polynomial over `Z_q` of a given degree.
// This function will generate a slice of `degree + 1` coefficients (+1 for
// a constant coefficient). Each value will be a random `big.Int` in range
// `(0, q)` where `q` is the cardinality of alt_bn128 elliptic curve.
func generatePolynomial(degree int) ([]*big.Int, error) {
	generateCoefficient := func() (c *big.Int, err error) {
		for {
			c, err = crand.Int(crand.Reader, bn256.Order)
			if c.Sign() > 0 || err != nil {
				return
			}
		}
	}

	coefficients := make([]*big.Int, degree+1)
	for i := range coefficients {
		coefficient, err := generateCoefficient()
		if err != nil {
			return nil, err
		}

		coefficients[i] = coefficient
	}

	return coefficients, nil
}

// evaluateMemberShare calculates a share for given memberID.
//
// It calculates `s_j = Σ a_k * j^k mod q`for k in [0..T], where:
// - `a_k` is k coefficient
// - `j` is memberID
// - `T` is dishonest threshold, so there are T+1 coefficients
// - `q` is the order of cyclic group formed over the alt_bn128 curve
func (cm *CommittingMember) evaluateMemberShare(
	memberID group.MemberIndex,
	coefficients []*big.Int,
) *big.Int {
	result := big.NewInt(0)
	for k, a := range coefficients {
		result = new(big.Int).Mod(
			new(big.Int).Add(
				result,
				new(big.Int).Mul(
					a,
					pow(memberID, k),
				),
			),
			bn256.Order,
		)
	}
	return result
}

// VerifyReceivedSharesAndCommitmentsMessages verifies shares and commitments
// received in messages from other group members. Returns accusation message
// with IDs of members for which the verification failed. All those members are
// disqualified by the current member in this function.
//
// Function returns error only if it is fatal to the protocol. Such situation
// should never happen.
//
// Member is disqualified if:
// - messages contain invalid number of shares or commitments
// - shares can not be decrypted
// - shares are not valid against commitments
//
// See Phase 4 of the protocol specification.
func (cvm *CommitmentsVerifyingMember) VerifyReceivedSharesAndCommitmentsMessages(
	sharesMessages []*PeerSharesMessage,
	commitmentsMessages []*MemberCommitmentsMessage,
) (*SecretSharesAccusationsMessage, error) {
	for _, sharesMessage := range sharesMessages {
		cvm.evidenceLog.PutPeerSharesMessage(sharesMessage)
	}

	accusedMembersKeys := make(map[group.MemberIndex]*ephemeral.PrivateKey)
	for _, commitmentsMessage := range commitmentsMessages {
		if !cvm.isValidMemberCommitmentsMessage(commitmentsMessage) {
			logger.Warningf(
				"[member:%v] member [%v] disqualified because of "+
					"sending invalid member commitments message",
				cvm.ID,
				commitmentsMessage.senderID,
			)
			cvm.group.MarkMemberAsDisqualified(commitmentsMessage.senderID)
			continue
		}

		// Find share message sent by the same member who sent commitment message
		sharesMessageFound := false
		for _, sharesMessage := range sharesMessages {
			if sharesMessage.senderID == commitmentsMessage.senderID {
				sharesMessageFound = true

				if !cvm.isValidPeerSharesMessage(sharesMessage) {
					logger.Warningf(
						"[member:%v] member [%v] disqualified because of "+
							"sending invalid peer shares message",
						cvm.ID,
						sharesMessage.senderID,
					)
					cvm.group.MarkMemberAsDisqualified(sharesMessage.senderID)
					break
				}

				// If there is no symmetric key established with the sender of
				// the message, error is returned.
				// This should never happen - member which did not establish
				// symmetric key with the current member is marked as inactive
				// in the second phase and we no longer accept messages from them.
				// If the symmetric key is not available, we consider it as a
				// fatal error. Such a situation should never happen.
				symmetricKey, hasKey := cvm.symmetricKeys[sharesMessage.senderID]
				if !hasKey {
					return nil, fmt.Errorf(
						"no symmetric key for sender %v",
						sharesMessage.senderID,
					)
				}

				// Decrypt shares using symmetric key established with sender.
				// Message validation performed earlier in this phase ensures
				// that shares for all group members (including the current one)
				// are in the message.
				// The only reason possible why shares could not be decrypted
				// here is because they are broken. If shares are broken,
				// sender is disqualified and an accusation against the sender
				// is published.
				shareS, shareT, err := sharesMessage.decryptShares(
					cvm.ID,
					symmetricKey,
				)
				if err != nil {
					logger.Warningf(
						"[member:%v] member [%v] disqualified because "+
							"could not decrypt shares received from them",
						cvm.ID,
						sharesMessage.senderID,
					)
					cvm.group.MarkMemberAsDisqualified(sharesMessage.senderID)
					accusedMembersKeys[sharesMessage.senderID] =
						cvm.ephemeralKeyPairs[sharesMessage.senderID].PrivateKey
					break
				}

				if !cvm.areSharesValidAgainstCommitments(
					shareS,                         // s_ji
					shareT,                         // t_ji
					commitmentsMessage.commitments, // C_j
					cvm.ID,                         // i
				) {
					logger.Warningf(
						"[member:%v] shares from member [%v] invalid against "+
							"commitments; disqualifying and accusing the member",
						cvm.ID,
						commitmentsMessage.senderID,
					)
					cvm.group.MarkMemberAsDisqualified(commitmentsMessage.senderID)
					accusedMembersKeys[commitmentsMessage.senderID] =
						cvm.ephemeralKeyPairs[commitmentsMessage.senderID].PrivateKey
					break
				}
				cvm.receivedValidSharesS[commitmentsMessage.senderID] = shareS
				cvm.receivedValidSharesT[commitmentsMessage.senderID] = shareT
				cvm.receivedValidPeerCommitments[commitmentsMessage.senderID] =
					commitmentsMessage.commitments

				break
			}
		}
		if !sharesMessageFound {
			logger.Warningf("cannot find shares message from member: [%v]",
				commitmentsMessage.senderID,
			)
		}
	}

	return &SecretSharesAccusationsMessage{
		senderID:           cvm.ID,
		accusedMembersKeys: accusedMembersKeys,
	}, nil
}

// isValidMemberCommitmentsMessage validates a given MemberCommitmentsMessage.
// Message is considered valid if it contains an expected number of commitments.
func (cvm *CommitmentsVerifyingMember) isValidMemberCommitmentsMessage(
	message *MemberCommitmentsMessage,
) bool {
	// A commitment is generated for each coefficient of the polynomial.
	// The polynomial is of degree equal to the dishonest threshold, thus we
	// have dishonest threshold + 1 coefficients in the polynomial including a
	// constant coefficient. It implicates the same count of commitments.
	expectedCommitmentsCount := cvm.group.DishonestThreshold() + 1
	if len(message.commitments) != expectedCommitmentsCount {
		logger.Warningf(
			"[member:%v] member [%v] sent a message with a wrong number "+
				"of commitments: [%v] instead of expected [%v]",
			cvm.ID,
			message.senderID,
			len(message.commitments),
			expectedCommitmentsCount,
		)
		return false
	}

	return true
}

// isValidPeerSharesMessage validates a given PeerSharesMessage.
// Message is considered valid if it contains shares for all other group members.
func (cvm *CommitmentsVerifyingMember) isValidPeerSharesMessage(
	message *PeerSharesMessage,
) bool {
	for _, memberID := range cvm.group.OperatingMemberIDs() {
		if memberID == message.senderID {
			// Message contains shares only for other group members.
			continue
		}

		if _, ok := message.shares[memberID]; !ok {
			logger.Warningf(
				"[member:%v] peer shares message from member [%v] does not "+
					"contain shares for member [%v]",
				cvm.ID,
				message.senderID,
				memberID,
			)
			return false
		}
	}

	return true
}

// areSharesValidAgainstCommitments verifies if commitments are valid for passed
// shares.
//
// The `j` member generated a polynomial with `k` coefficients before. Then they
// calculated a commitments to the polynomial's coefficients `C_j` and individual
// shares `s_ji` and `t_ji` with a polynomial for a member `i`. In this function
// the verifier checks if the shares are valid against the commitments.
//
// The verifier checks whether [GJKR 99] 1.(b) holds:
// `(g ^ s_ji) * (h ^ t_ji) mod p == Π (C_j[k] ^ (i^k)) mod p` for `k` in `[0..T]`
//
// What, using elliptic curve, is the same as:
// `G * s_ji + H * t_ji == Σ (C_j[k] * (i^k))` for `k` in `[0..T]`
func (cm *CommittingMember) areSharesValidAgainstCommitments(
	shareS, shareT *big.Int, // s_ji, t_ji
	commitments []*bn256.G1, // C_j
	memberID group.MemberIndex, // i
) bool {
	if len(commitments) == 0 {
		return false
	}

	var sum *bn256.G1                // Σ (C_j[k] * (i^k)) for k in [0..T]
	for k, ck := range commitments { // k, C_j[k]
		ci := new(bn256.G1).ScalarMult(ck, pow(memberID, k)) // C_j[k] * (i^k)
		if sum == nil {
			sum = ci
		} else {
			sum = new(bn256.G1).Add(sum, ci)
		}
	}

	commitment := cm.calculateCommitment(shareS, shareT) // G * s_ji + H * t_ji

	return commitment.String() == sum.String()
}

// ResolveSecretSharesAccusationsMessages resolves complaints received in
// secret shares accusations messages. The member calls this function to judge
// which party of the dispute is misbehaving.
//
// Function should not receive accusation message sent by the current member.
// Members accused by the current member are disqualified in the previous phase,
// at the same time when an accusation against them is published.
//
// If the current member is accused, it marks the accuser as disqualified
// without checking self shares. Each member consider itself as an honest
// participant.
//
// This function needs to decrypt shares sent previously by the accused member
// to the accuser in an encrypted form. To do that it needs to recover a symmetric
// key used for data encryption. It takes private key revealed by the accuser
// and public key broadcasted by the accused and performs Elliptic Curve Diffie-
// Hellman operation on them.
//
// Function returns error only if it is fatal to the protocol. Such situation
// should never happen.
//
// Accuser is disqualified if:
// - accused the current member
// - the revealed private key does not match the public key previously broadcast
//   by the accuser
// - accused inactive or already disqualified member and as a result, we do not
//   have enough information to resolve that accusation
// - shares of the accused member are valid against commitments
//
// Accused member is disqualified if:
// - shares of the accused member can not be decrypted
// - shares of the accused member are not valid against commitments
//
// See Phase 5 of the protocol specification.
func (sjm *SharesJustifyingMember) ResolveSecretSharesAccusationsMessages(
	messages []*SecretSharesAccusationsMessage,
) error {
	for _, message := range messages {
		accuserID := message.senderID
		for accusedID, revealedAccuserPrivateKey := range message.accusedMembersKeys {
			if sjm.ID == accusedID {
				// The member does not resolve the dispute as an accused.
				// Mark the accuser as disqualified immediately,
				// as each member consider itself as a honest participant.
				sjm.group.MarkMemberAsDisqualified(accuserID)
				continue
			}

			accuserPublicKey := findPublicKey(
				sjm.evidenceLog,
				accuserID,
				accusedID,
			)
			if accuserPublicKey == nil {
				// Ephemeral public key of the accuser, generated for the sake
				// of communication with the accused member should be present
				// in the evidence log. The key is not there only if it was not
				// sent by the accuser in the first phase of the protocol and
				// such behaviour results in marking that member as disqualified
				// in the second phase. As a result, we no longer accept
				// messages from that member and it is not possible we will
				// receive an accusation from an inactive member in this phase.
				// If the public key could not be found we consider this a
				// fatal error. Such a situation should never happen.
				return fmt.Errorf(
					"could not find public key sent by [%v] to [%v]",
					accuserID,
					accusedID,
				)
			}

			if !accuserPublicKey.IsKeyMatching(revealedAccuserPrivateKey) {
				logger.Warningf(
					"[member:%v] member [%v] disqualified because of "+
						"revealing private key not matching the public key",
					sjm.ID,
					accuserID,
				)
				sjm.group.MarkMemberAsDisqualified(accuserID)
				continue
			}

			// Recover symmetric key based on ephemeral public key message sent
			// by the accused member. If the message is not present in the
			// evidence log, it means the accused member did not sent us
			// their public key in the first phase of the protocol and we
			// marked the accused member as inactive in the second phase of the
			// protocol. Assuming everyone in the group has the same view on
			// who is inactive, it means the accuser sent and accusation against
			// inactive member, knowing we can not resolve that accusation.
			// As a result, we should mark the accuser as disqualified.
			//
			// If the message is present in the evidence log but it does not
			// contain a public key generated for the accuser, it means we have
			// already marked the accused party as disqualified when performing
			// a validation of a message with public keys in the first phase of
			// the protocol. Assuming everyone in the group has the same view on
			// who is disqualified after the second phase of the protocol, it
			// means the accuser sent an accusation against a disqualified
			// member, knowing we can not resolve that accusation.
			// As a result, we should mark the accuser as disqualified.
			accusedPublicKey := findPublicKey(
				sjm.evidenceLog,
				accusedID,
				accuserID,
			)
			if accusedPublicKey == nil {
				logger.Warningf(
					"[member:%v] member [%v] disqualified because could not "+
						"recover symmetric key; accused member [%v] is already "+
						"marked as inactive or disqualified ",
					sjm.ID,
					accuserID,
					accusedID,
				)
				sjm.group.MarkMemberAsDisqualified(accuserID)
				continue
			}
			symmetricKey := revealedAccuserPrivateKey.Ecdh(accusedPublicKey)

			// Get from evidence log peer shares message sent by the accused
			// member. If the message is not present, this means the accused
			// member has been already marked as inactive in phase 4.
			// Assuming that each other member consider the accused member as
			// inactive, the accuser should be disqualified because of
			// accusing an inactive member knowing we can not resolve this
			// accusation.
			accusedSharesMessage := sjm.evidenceLog.peerSharesMessage(accusedID)
			if accusedSharesMessage == nil {
				logger.Warningf(
					"[member:%v] member [%v] disqualified because could not "+
						"get peer shares message from evidence log; "+
						"accused member [%v] is already marked as inactive",
					sjm.ID,
					accuserID,
					accusedID,
				)
				sjm.group.MarkMemberAsDisqualified(accuserID)
				continue
			}

			// Message validation performed in the fourth phase ensures
			// that shares for all group members (including the accused one)
			// are in the message.
			// The only reason possible why shares could not be decrypted
			// here is because they are broken. If shares are broken,
			// the accused member is disqualified.
			shareS, shareT, err := accusedSharesMessage.decryptShares(
				accuserID,
				symmetricKey,
			)
			if err != nil {
				logger.Warningf(
					"[member:%v] member [%v] disqualified because of sending "+
						"to member [%v] shares that could not be decrypted",
					sjm.ID,
					accusedID,
					accuserID,
				)
				sjm.group.MarkMemberAsDisqualified(accusedID)
				continue
			}

			if sjm.areSharesValidAgainstCommitments(
				shareS, shareT, // s_mj, t_mj
				sjm.receivedValidPeerCommitments[accusedID], // C_m
				accuserID, // j
			) {
				logger.Warningf(
					"[member:%v] member [%v] disqualified because of "+
						"false accusation against member [%v] ",
					sjm.ID,
					accuserID,
					accusedID,
				)
				sjm.group.MarkMemberAsDisqualified(accuserID)
			} else {
				logger.Warningf(
					"[member:%v] member [%v] disqualified because of "+
						"confirmed misbehaviour against member [%v] ",
					sjm.ID,
					accusedID,
					accuserID,
				)
				sjm.group.MarkMemberAsDisqualified(accusedID)
			}
		}
	}
	return nil
}

// Inspects evidence log looking for ephemeral public key message sent in phase
// 1 of the protocol by the sender with the given ID and retrieves from that
// message public key generated by that sender for the given receiver ID.
//
// The function fails if ephemeral public key message for the given sender ID
// could not be found or if the public key for the given received ID was not
// present in that message.
//
// There are two assumptions made here:
// 1. If the given sender did not deliver ephemeral public key message in phase
//    1, it should be marked as inactive, hence, this function should never be
//    called for that sender ID,
// 2. If the given sender delivered ephemeral public key message in phase 1
//    but that message did not contain a public key for all group members
//    including the one passed as receiver to this function, sender should be
//    disqualified in phase 2, and this function should never be called for that
//    sender ID.
func findPublicKey(
	evidenceLog evidenceLog,
	senderID, receiverID group.MemberIndex,
) *ephemeral.PublicKey {
	ephemeralPublicKeyMessage := evidenceLog.ephemeralPublicKeyMessage(senderID)
	if ephemeralPublicKeyMessage == nil {
		logger.Warningf(
			"no ephemeral public key message for sender %v",
			senderID,
		)
		return nil
	}

	senderPublicKey, ok := ephemeralPublicKeyMessage.ephemeralPublicKeys[receiverID]
	if !ok {
		logger.Warningf(
			"no ephemeral public key generated for receiver %v",
			receiverID,
		)
		return nil
	}

	return senderPublicKey
}

// Recover ephemeral symmetric key used to encrypt communication between sender
// and receiver assuming that receiver revealed its private ephemeral key.
//
// Finds ephemeral public key sent by sender to the receiver. Performs ECDH
// operation between sender's public key and receiver's private key to recover
// the ephemeral symmetric key.
//
// Deprecated: Body of this function should be used directly in order to
// explain intentions more expressively in the client code.
// TODO Remove when all usages will be replaced.
func recoverSymmetricKey(
	evidenceLog evidenceLog,
	senderID, receiverID group.MemberIndex,
	receiverPrivateKey *ephemeral.PrivateKey,
) (ephemeral.SymmetricKey, error) {
	senderPublicKey := findPublicKey(evidenceLog, senderID, receiverID)
	if senderPublicKey == nil {
		return nil, fmt.Errorf(
			"could not find public key sent by [%v] to [%v]",
			senderID,
			receiverID,
		)
	}

	return receiverPrivateKey.Ecdh(senderPublicKey), nil
}

// Recovers from the evidence log share S and share T sent by sender to the
// receiver.
//
// First it finds in the evidence log the Peer Shares Message sent by the sender
// to the receiver. Then it decrypts the decrypted shares with provided symmetric
// key.
//
// Deprecated: Should be replaced. `peerSharesMessage` should be obtained and
// `decryptShares` method from `PeerSharesMessage` should be used to decrypt shares.
// TODO Remove when all usages will be replaced.
func recoverShares(
	evidenceLog evidenceLog,
	senderID, receiverID group.MemberIndex,
	symmetricKey ephemeral.SymmetricKey,
) (*big.Int, *big.Int, error) {
	peerSharesMessage := evidenceLog.peerSharesMessage(senderID)
	if peerSharesMessage == nil {
		return nil, nil, fmt.Errorf(
			"no peer shares message for sender %v",
			senderID,
		)
	}

	shareS, err := peerSharesMessage.decryptShareS(receiverID, symmetricKey) // s_mj
	if err != nil {
		return nil, nil, fmt.Errorf("cannot decrypt share S [%v]", err)
	}
	shareT, err := peerSharesMessage.decryptShareT(receiverID, symmetricKey) // t_mj
	if err != nil {
		return nil, nil, fmt.Errorf("cannot decrypt share T [%v]", err)
	}

	return shareS, shareT, nil
}

// CombineMemberShares sums up all `s` shares intended for this member.
// Combines secret shares calculated by current member `i` for itself `s_ii`
// with shares calculated by peer members `j` for this member `s_ji`.
//
// `x_i = Σ s_ji mod q` for `j` in a group of players who passed secret shares
// accusations stage. `q` is the order of cyclic group formed over the alt_bn128
// curve.
//
// See Phase 6 of the protocol specification.
func (qm *QualifiedMember) CombineMemberShares() {
	combinedSharesS := qm.selfSecretShareS // s_ii
	for _, s := range qm.receivedValidSharesS {
		combinedSharesS = new(big.Int).Mod(
			new(big.Int).Add(combinedSharesS, s),
			bn256.Order,
		)
	}

	qm.groupPrivateKeyShare = combinedSharesS
}

// CalculatePublicKeySharePoints calculates public values for member's
// coefficients.
//
// It calculates:
// `A_k = g^a_k` for `k` in `[0..T]`.
//
// What, using elliptic curve, is the same as:
// `A_k = G * a_k` for `k` in `[0..T]`.
// where `G` is curve's generator.
//
// See Phase 7 of the protocol specification.
func (sm *SharingMember) CalculatePublicKeySharePoints() *MemberPublicKeySharePointsMessage {
	sm.publicKeySharePoints = make([]*bn256.G2, len(sm.secretCoefficients))
	for i, a := range sm.secretCoefficients {
		sm.publicKeySharePoints[i] = new(bn256.G2).ScalarBaseMult(a)
	}

	return &MemberPublicKeySharePointsMessage{
		senderID:             sm.ID,
		publicKeySharePoints: sm.publicKeySharePoints,
	}
}

// VerifyPublicKeySharePoints validates public key share points received in
// messages from peer group members.
// It returns accusation message with ID of members for which the verification
// failed.
//
// See Phase 8 of the protocol specification.
func (sm *SharingMember) VerifyPublicKeySharePoints(
	messages []*MemberPublicKeySharePointsMessage,
) (*PointsAccusationsMessage, error) {
	accusedMembersKeys := make(map[group.MemberIndex]*ephemeral.PrivateKey)
	// `product = Π (A_j[k] ^ (i^k)) mod p` for k in [0..T],
	// where: j is sender's ID, i is current member ID, T is dishonest threshold.
	for _, message := range messages {
		if !sm.isValidMemberPublicKeySharePointsMessage(message) {
			logger.Warningf(
				"[member:%v] member [%v] disqualified because of "+
					"sending invalid member public key share points message",
				sm.ID,
				message.senderID,
			)
			sm.group.MarkMemberAsDisqualified(message.senderID)
			continue
		}

		if !sm.isShareValidAgainstPublicKeySharePoints(
			sm.ID,
			sm.receivedValidSharesS[message.senderID],
			message.publicKeySharePoints,
		) {
			logger.Warningf(
				"[member:%v] member [%v] disqualified because of "+
					"invalid public key share points",
				sm.ID,
				message.senderID,
			)
			sm.group.MarkMemberAsDisqualified(message.senderID)
			accusedMembersKeys[message.senderID] = sm.ephemeralKeyPairs[message.senderID].PrivateKey
			continue
		}
		sm.receivedValidPeerPublicKeySharePoints[message.senderID] = message.publicKeySharePoints
	}

	return &PointsAccusationsMessage{
		senderID:           sm.ID,
		accusedMembersKeys: accusedMembersKeys,
	}, nil
}

// isValidMemberPublicKeySharePointsMessage validates a given
// MemberPublicKeySharePointsMessage. Message is considered valid if it
// contains an expected number of public key share points.
func (sm *SharingMember) isValidMemberPublicKeySharePointsMessage(
	message *MemberPublicKeySharePointsMessage,
) bool {
	// A public key share point is generated for each coefficient of the
	// polynomial. The polynomial is of degree equal to the dishonest threshold,
	// thus we have dishonest threshold + 1 coefficients in the polynomial
	// including a constant coefficient. It implicates the same count of
	// public key share points.
	expectedPointsCount := sm.group.DishonestThreshold() + 1
	if len(message.publicKeySharePoints) != expectedPointsCount {
		logger.Warningf(
			"[member:%v] member [%v] sent a message with a wrong number "+
				"of public key share points: [%v] instead of expected [%v]",
			sm.ID,
			message.senderID,
			len(message.publicKeySharePoints),
			expectedPointsCount,
		)
		return false
	}

	return true
}

// isShareValidAgainstPublicKeySharePoints verifies if public key share points
// are valid for passed share S.
//
// The `j` member calculated public key share points for their polynomial
// coefficients and share `s_ji` with a polynomial for a member `i`. In this
// function the verifier checks if the public key share points are valid against
// the share S.
//
// The verifier checks whether [GJKR 99] 4.(b) holds:
// `g^s_ji mod p == Π (A_j[k] ^ (i^k)) mod p` for `k` in `[0..T]`
//
// What, using elliptic curve, is the same as:
// G * s_ji == Σ ( A_j[k] * (i^k) ) for `k` in `[0..T]`
func (sm *SharingMember) isShareValidAgainstPublicKeySharePoints(
	senderID group.MemberIndex,
	shareS *big.Int,
	publicKeySharePoints []*bn256.G2,
) bool {
	if len(publicKeySharePoints) == 0 {
		return false
	}

	var sum *bn256.G2 // Σ ( A_j[k] * (i^k) ) for `k` in `[0..T]`
	for k, a := range publicKeySharePoints {
		aj := new(bn256.G2).ScalarMult(a, pow(senderID, k)) // A_j[k] * (i^k)
		if sum == nil {
			sum = aj
		} else {
			sum = new(bn256.G2).Add(sum, aj)
		}
	}

	gs := new(bn256.G2).ScalarBaseMult(shareS) // G * s_ji

	return gs.String() == sum.String()
}

// ResolvePublicKeySharePointsAccusationsMessages resolves complaints received
// in points accusations messages. The member calls this function to judge
// which party of the dispute is misbehaving.
//
// Function should not receive accusation message sent by the current member.
// Members accused by the current member are disqualified in the previous phase,
// at the same time when an accusation against them is published.
//
// If the current member is accused, it marks the accuser as disqualified
// without checking self shares. Each member consider itself as an honest
// participant.
//
// This function needs to decrypt shares sent previously by the accused member
// to the accuser in an encrypted form. To do that it needs to recover a symmetric
// key used for data encryption. It takes private key revealed by the accuser
// and public key broadcasted by the accused and performs Elliptic Curve Diffie-
// Hellman operation between them.
//
// Function returns error only if it is fatal to the protocol. Such situation
// should never happen.
//
// Accuser is disqualified if:
// - accused the current member
// - the revealed private key does not match the public key previously broadcast
//   by the accuser
// - accused inactive or already disqualified member and as a result, we do not
//   have enough information to resolve that accusation
// - shares of the accused member are valid against public key share points
// - shares of the accused member can not be decrypted and the accuser didn't
//   complain about this fact in phase 4 (protocol violation)
//
// Accused member is disqualified if:
// - shares of the accused member can not be decrypted
// - shares of the accused member are not valid against public key share points
//
// See Phase 9 of the protocol specification.
func (pjm *PointsJustifyingMember) ResolvePublicKeySharePointsAccusationsMessages(
	messages []*PointsAccusationsMessage,
) error {
	for _, message := range messages {
		accuserID := message.senderID
		for accusedID, revealedAccuserPrivateKey := range message.accusedMembersKeys {
			if pjm.ID == accusedID {
				// The member does not resolve the dispute as an accused.
				// Mark the accuser as disqualified immediately,
				// as each member consider itself as a honest participant.
				pjm.group.MarkMemberAsDisqualified(accuserID)
				continue
			}

			evidenceLog := pjm.evidenceLog

			accuserPublicKey := findPublicKey(
				evidenceLog,
				accuserID,
				accusedID,
			)
			if accuserPublicKey == nil {
				// Ephemeral public key of the accuser, generated for the sake
				// of communication with the accused member should be present
				// in the evidence log. The key is not there only if it was not
				// sent by the accuser in the first phase of the protocol and
				// such behaviour results in marking that member as disqualified
				// in the second phase. As a result, we no longer accept
				// messages from that member and it is not possible we will
				// receive an accusation from an inactive member in this phase.
				// If the public key could not be found we consider this a
				// fatal error. Such a situation should never happen.
				return fmt.Errorf(
					"could not find public key sent by [%v] to [%v]",
					accuserID,
					accusedID,
				)
			}

			if !accuserPublicKey.IsKeyMatching(revealedAccuserPrivateKey) {
				logger.Warningf(
					"[member:%v] member [%v] disqualified because of "+
						"revealing private key not matching the public key",
					pjm.ID,
					accuserID,
				)
				pjm.group.MarkMemberAsDisqualified(accuserID)
				continue
			}

			// Recover symmetric key based on ephemeral public key message sent
			// by the accused member. If the message is not present in the
			// evidence log, it means the accused member did not sent us
			// their public key in the first phase of the protocol and we
			// marked the accused member as inactive in the second phase of the
			// protocol. Assuming everyone in the group has the same view on
			// who is inactive, it means the accuser sent and accusation against
			// inactive member, knowing we can not resolve that accusation.
			// As a result, we should mark the accuser as disqualified.
			//
			// If the message is present in the evidence log but it does not
			// contain a public key generated for the accuser, it means we have
			// already marked the accused party as disqualified when performing
			// a validation of a message with public keys in the first phase of
			// the protocol. Assuming everyone in the group has the same view on
			// who is disqualified after the second phase of the protocol, it
			// means the accuser sent an accusation against a disqualified
			// member, knowing we can not resolve that accusation.
			// As a result, we should mark the accuser as disqualified.
			accusedPublicKey := findPublicKey(
				evidenceLog,
				accusedID,
				accuserID,
			)
			if accusedPublicKey == nil {
				logger.Warningf(
					"[member:%v] member [%v] disqualified because could not "+
						"recover symmetric key; accused member [%v] is already "+
						"marked as inactive or disqualified ",
					pjm.ID,
					accuserID,
					accusedID,
				)
				pjm.group.MarkMemberAsDisqualified(accuserID)
				continue
			}
			recoveredSymmetricKey := revealedAccuserPrivateKey.Ecdh(accusedPublicKey)

			// Get from evidence log peer shares message sent by the accused
			// member. If the message is not present, this means the accused
			// member has been already marked as inactive in phase 4.
			// Assuming that each other member consider the accused member as
			// inactive, the accuser should be disqualified because of
			// accusing an inactive member knowing we can not resolve this
			// accusation.
			accusedSharesMessage := evidenceLog.peerSharesMessage(accusedID)
			if accusedSharesMessage == nil {
				logger.Warningf(
					"[member:%v] member [%v] disqualified because could not "+
						"get peer shares message from evidence log; "+
						"accused member [%v] is already marked as inactive",
					pjm.ID,
					accuserID,
					accusedID,
				)
				pjm.group.MarkMemberAsDisqualified(accuserID)
				continue
			}

			// Message validation performed in the fourth phase ensures
			// that shares for all group members (including the accused one)
			// are in the message.
			// The only reason possible why shares could not be decrypted
			// here is because they are broken. If shares are broken,
			// the accused member is disqualified.
			// Accuser should be also marked as disqualified because they didn't
			// complain earlier about invalid shares so they violated the protocol.
			shareS, _, err := accusedSharesMessage.decryptShares(
				accuserID,
				recoveredSymmetricKey,
			)
			if err != nil {
				logger.Warningf(
					"[member:%v] member [%v] disqualified because of sending "+
						"shares that could not be decrypted; "+
						"member [%v] disqualified because did not complain "+
						"about invalid shares earlier",
					pjm.ID,
					accusedID,
					accuserID,
				)
				pjm.group.MarkMemberAsDisqualified(accuserID)
				pjm.group.MarkMemberAsDisqualified(accusedID)
				continue
			}

			if pjm.isShareValidAgainstPublicKeySharePoints(
				message.senderID,
				shareS,
				pjm.receivedValidPeerPublicKeySharePoints[accusedID],
			) {
				logger.Warningf(
					"[member:%v] member [%v] disqualified because of "+
						"false accusation against member [%v] ",
					pjm.ID,
					accuserID,
					accusedID,
				)
				pjm.group.MarkMemberAsDisqualified(accuserID)
			} else {
				logger.Warningf(
					"[member:%v] member [%v] disqualified because of "+
						"confirmed misbehaviour against member [%v] ",
					pjm.ID,
					accusedID,
					accuserID,
				)
				pjm.group.MarkMemberAsDisqualified(accusedID)
			}
		}
	}
	return nil
}

// RevealDisqualifiedMembersKeys reveals ephemeral private keys used to create
// an ephemeral symmetric key with disqualified members who share a group private
// key. The function filters members who sent valid share S in Phase 3 but were
// disqualified in Phase 9. It returns a message containing a map of ephemeral
// private key for each disqualified member sharing a group private key.
//
// See Phase 10 of the protocol specification.
func (rm *RevealingMember) RevealDisqualifiedMembersKeys() (
	*DisqualifiedEphemeralKeysMessage,
	error,
) {
	privateKeys := make(map[group.MemberIndex]*ephemeral.PrivateKey)

	for _, disqualifiedMemberID := range rm.disqualifiedSharingMembers() {
		ephemeralKeyPair, ok := rm.ephemeralKeyPairs[disqualifiedMemberID]
		if !ok {
			return nil, fmt.Errorf(
				"no ephemeral key pair for disqualified member %v",
				disqualifiedMemberID,
			)
		}
		privateKeys[disqualifiedMemberID] = ephemeralKeyPair.PrivateKey
	}

	return &DisqualifiedEphemeralKeysMessage{
		senderID:    rm.ID,
		privateKeys: privateKeys,
	}, nil
}

func (rm *RevealingMember) disqualifiedSharingMembers() []group.MemberIndex {
	disqualifiedMembersIDs := rm.group.DisqualifiedMemberIDs()

	// From disqualified members list filter those who provided valid shares in
	// Phase 3 and are sharing the group private key.
	disqualifiedSharingMembers := make([]group.MemberIndex, 0)
	for _, disqualifiedMemberID := range disqualifiedMembersIDs {
		if _, ok := rm.receivedValidSharesS[disqualifiedMemberID]; ok {
			disqualifiedSharingMembers = append(
				disqualifiedSharingMembers,
				disqualifiedMemberID,
			)
		}
	}
	return disqualifiedSharingMembers
}

// ReconstructDisqualifiedIndividualKeys reconstructs individual private key `z_m` and  public
// key `y_m` of disqualified members `m`. To do that, it first needs to recover
// shares calculated by disqualified members `m` in Phase 3 for other members `k`.
// The shares were encrypted before broadcast, so ephemeral symmetric key needs
// to be recovered. This requires messages containing ephemeral private key
// revealed by member `k` used in communication with disqualified member `m`.
//
// See Phase 11 of the protocol specification.
func (rm *ReconstructingMember) ReconstructDisqualifiedIndividualKeys(
	messages []*DisqualifiedEphemeralKeysMessage,
) error {
	revealedDisqualifiedShares, err := rm.revealDisqualifiedShares(messages)
	if err != nil {
		return fmt.Errorf("revealing disqualified shares failed [%v]", err)
	}
	rm.reconstructIndividualPrivateKeys(revealedDisqualifiedShares) // z_m
	rm.reconstructIndividualPublicKeys()                            // y_m
	return nil
}

// Reveal shares calculated by members disqualified in previous phases.
// First, perform shares recovery based on received DisqualifiedEphemeralKeysMessage.
// Then, add disqualified member shares generated for the current member.
// In result, a complete slice of shares is returned and reconstruction
// of individual private keys is possible.
func (rm *ReconstructingMember) revealDisqualifiedShares(
	messages []*DisqualifiedEphemeralKeysMessage,
) ([]*disqualifiedShares, error) {
	disqualifiedShares, err := rm.recoverDisqualifiedShares(messages)
	if err != nil {
		return nil, err
	}

	// Add disqualified member shares generated for the current member.
	for _, disqualifiedMemberID := range rm.group.DisqualifiedMemberIDs() {
		for _, shares := range disqualifiedShares {
			if shares.disqualifiedMemberID == disqualifiedMemberID {
				if currentMemberShare, ok := rm.receivedValidSharesS[disqualifiedMemberID]; ok {
					shares.peerSharesS[rm.ID] = currentMemberShare
				}
				break
			}
		}
	}

	return disqualifiedShares, nil
}

// Recover shares `s_mk` calculated by members `m` disqualified in Phase 9.
// The shares were evaluated in Phase 3 by `m` for other members `k` and
// broadcasted in an encrypted fashion, hence reconstructing member has to
// recover a symmetric key to decode the shares messages. It returns a slice
// containing shares `s_mk` recovered for each member `m` whose ephemeral key
// was revealed in provided DisqualifiedMembersKeysMessage.
func (rm *ReconstructingMember) recoverDisqualifiedShares(
	messages []*DisqualifiedEphemeralKeysMessage,
) ([]*disqualifiedShares, error) {
	revealedDisqualifiedShares := make([]*disqualifiedShares, 0)

	// For disqualified member `m` add shares `s_mk` the member calculated for
	// other members `k` who revealed the ephemeral key.
	addShare := func(
		disqualifiedMemberID, revealingMemberID group.MemberIndex, // m, k
		shareS *big.Int, // s_mk
	) {
		// If a `disqualifiedShares` entry already exists in the slice for given
		// disqualified member add the share.
		for _, disqualifiedShares := range revealedDisqualifiedShares {
			if disqualifiedShares.disqualifiedMemberID == disqualifiedMemberID {
				disqualifiedShares.peerSharesS[revealingMemberID] = shareS
				return
			}
		}

		// When a `disqualifiedShares` entry doesn't exist yet in the slice for given
		// disqualified member initialize it with the share.
		newDisqualifiedShares := &disqualifiedShares{
			disqualifiedMemberID: disqualifiedMemberID,
			peerSharesS:          make(map[group.MemberIndex]*big.Int),
		}
		newDisqualifiedShares.peerSharesS[revealingMemberID] = shareS

		revealedDisqualifiedShares = append(
			revealedDisqualifiedShares,
			newDisqualifiedShares,
		)
	}

	for _, message := range messages {
		revealingMemberID := message.senderID
		for disqualifiedMemberID, revealedPrivateKey := range message.privateKeys {
			if rm.ID == disqualifiedMemberID {
				// Mark the revealing member as disqualified immediately,
				// as each member consider itself as a honest participant.
				// Continue as there is no sense to recover own shares.
				rm.group.MarkMemberAsDisqualified(revealingMemberID)
				continue
			}

			// After phase 9, all group members should have the same view on
			// who is disqualified. Revealing key of non-disqualified members
			// is forbidden and leads to disqualifying the revealing member.
			if rm.group.IsOperating(disqualifiedMemberID) {
				logger.Warningf(
					"[member:%v] member [%v] disqualified because "+
						"revealing key of non-disqualified member",
					rm.ID,
					revealingMemberID,
				)
				rm.group.MarkMemberAsDisqualified(revealingMemberID)
				continue
			}

			publicKey := rm.evidenceLog.ephemeralPublicKeyMessage(revealingMemberID).
				ephemeralPublicKeys[disqualifiedMemberID]
			if !publicKey.IsKeyMatching(revealedPrivateKey) {
				logger.Warningf(
					"[member:%v] member [%v] disqualified because of "+
						"revealing private key not matching the public key",
					rm.ID,
					revealingMemberID,
				)
				rm.group.MarkMemberAsDisqualified(revealingMemberID)
				continue
			}

			// TODO Replace as in phase 5.
			recoveredSymmetricKey, err := recoverSymmetricKey(
				rm.evidenceLog,
				disqualifiedMemberID, // m
				revealingMemberID,    // k
				revealedPrivateKey,
			)
			if err != nil {
				logger.Errorf("cannot recover symmetric key: [%v]", err)
				// TODO Disqualify the revealing member
				continue
			}

			// TODO Replace as in phase 5
			shareS, _, err := recoverShares(
				rm.evidenceLog,
				disqualifiedMemberID,  // m
				revealingMemberID,     // k
				recoveredSymmetricKey, // s_mk
			)
			if err != nil {
				logger.Errorf("cannot decrypt share S: [%v]", err)
				// TODO Disqualify the revealing member
				continue
			}

			addShare(disqualifiedMemberID, revealingMemberID, shareS)
		}
	}
	return revealedDisqualifiedShares, nil
}

// disqualifiedShares contains shares `s_mk` calculated by the disqualified
// member `m` for peer members `k`. The shares were revealed due to disqualification
// of the member `m` from the protocol execution.
type disqualifiedShares struct {
	disqualifiedMemberID group.MemberIndex              // m
	peerSharesS          map[group.MemberIndex]*big.Int // <k, s_mk>
}

// reconstructIndividualPrivateKeys reconstructs disqualified members' individual
// private keys `z_m` from provided revealed shares calculated by disqualified
// members for peer members.
//
// Function need to be executed for qualified members that presented valid shares
// and commitments and were approved for Phase 6 but were disqualified on public
// key shares validation stage (Phase 9).
//
// It stores a map of reconstructed individual private keys for each disqualified
// member in a current member's reconstructedIndividualPrivateKeys field:
// <disqualifiedMemberID, privateKeyShare>
func (rm *ReconstructingMember) reconstructIndividualPrivateKeys(
	revealedDisqualifiedShares []*disqualifiedShares,
) {
	rm.reconstructedIndividualPrivateKeys = make(map[group.MemberIndex]*big.Int, len(revealedDisqualifiedShares))

	for _, ds := range revealedDisqualifiedShares { // for each disqualified member
		// Reconstruct individual private key `z_m = Σ (s_mk * a_mk) mod q` where:
		// - `z_m` is disqualified member's individual private key
		// - `s_mk` is a share calculated by disqualified member `m` for peer member `k`
		// - `a_mk` is lagrange coefficient for peer member k (see below)
		individualPrivateKey := big.NewInt(0)
		// Get IDs of all peer members from disqualified shares.
		var peerIDs []group.MemberIndex
		for k := range ds.peerSharesS {
			peerIDs = append(peerIDs, k)
		}
		// For each peerID `k` and peerShareS `s_mk` calculate `s_mk * a_mk`
		for peerID, peerShareS := range ds.peerSharesS {
			// a_mk
			lagrangeCoefficient := rm.calculateLagrangeCoefficient(peerID, peerIDs)

			// Σ (s_mk * a_mk) mod q
			individualPrivateKey = new(big.Int).Mod(
				new(big.Int).Add(
					individualPrivateKey,
					// s_mk * a_mk
					new(big.Int).Mul(peerShareS, lagrangeCoefficient),
				),
				bn256.Order,
			)
		}
		// <m, z_m>
		rm.reconstructedIndividualPrivateKeys[ds.disqualifiedMemberID] =
			individualPrivateKey
	}
}

// Calculates Lagrange coefficient `a_mk` for member `k` in a group of members.
//
// `a_mk = Π (l / (l - k)) mod q` where:
// - `a_mk` is a lagrange coefficient for the member `k`,
// - `l` are IDs of members who provided shares,
// - `q` is an order of alt_bn128 elliptic curve
// and `l != k`.
func (rm *ReconstructingMember) calculateLagrangeCoefficient(memberID group.MemberIndex, groupMembersIDs []group.MemberIndex) *big.Int {
	lagrangeCoefficient := big.NewInt(1)
	// For each otherID `l` in groupMembersIDs:
	for _, otherID := range groupMembersIDs {
		if otherID != memberID { // l != k
			// l / (l - k)
			quotient := new(big.Int).Mod(
				new(big.Int).Mul(
					big.NewInt(int64(otherID)),
					new(big.Int).ModInverse(
						new(big.Int).Sub(
							otherID.Int(),
							memberID.Int(),
						),
						bn256.Order,
					),
				),
				bn256.Order,
			)

			// Π (l / (l - k)) mod q
			lagrangeCoefficient = new(big.Int).Mod(
				new(big.Int).Mul(
					lagrangeCoefficient, quotient,
				),
				bn256.Order,
			)
		}
	}
	return lagrangeCoefficient // a_mk
}

// reconstructIndividualPublicKeys calculates and stores individual public keys
// `y_m` from reconstructed individual private keys `z_m`.
//
// Public key is calculated as `g^privateKey mod p` what, using elliptic curve,
// is the same as `G * privateKey`.
//
// See Phase 11 of the protocol specification.
func (rm *ReconstructingMember) reconstructIndividualPublicKeys() {
	rm.reconstructedIndividualPublicKeys = make(
		map[group.MemberIndex]*bn256.G2,
		len(rm.reconstructedIndividualPrivateKeys),
	)
	for memberID, individualPrivateKey := range rm.reconstructedIndividualPrivateKeys {
		// y_m = G * z_m
		individualPublicKey := new(bn256.G2).ScalarBaseMult(individualPrivateKey)
		rm.reconstructedIndividualPublicKeys[memberID] = individualPublicKey
	}
}

func pow(id group.MemberIndex, y int) *big.Int {
	return new(big.Int).Exp(id.Int(), big.NewInt(int64(y)), nil)
}

// CombineGroupPublicKey calculates a group public key by combining individual
// public keys. Group public key is calculated as a product of individual public
// keys of all group members including member themself.
//
// `Y = Π y_j mod p` for `j`, where `y_j` is individual public key of each
// qualified group member. With elliptic curve, it is: `Y = Σ y_j`.
//
// This function combines individual public keys of all Qualified Members who were
// approved for Phase 6. Three categories of individual public keys are considered:
// 1. Current member's individual public key.
// 2. Peer members' individual public keys - for members who passed a public key
//    share points validation in Phase 8 and accusations resolution in Phase 9 and
//    are still active group members.
// 3. Disqualified members' individual public keys - for members who were disqualified
//    in Phase 9 and theirs individual private and public keys were reconstructed
//    in Phase 11.
//
// See Phase 12 of the protocol specification.
func (rm *CombiningMember) CombineGroupPublicKey() {
	// Current member's individual public key `A_i0`.
	groupPublicKey := rm.individualPublicKey()

	// Add received peer group members' individual public keys `A_j0`.
	for _, peerPublicKey := range rm.receivedValidPeerIndividualPublicKeys() {
		groupPublicKey = new(bn256.G2).Add(groupPublicKey, peerPublicKey)
	}

	// Add reconstructed disqualified members' individual public keys `G * z_m`.
	for _, peerPublicKey := range rm.reconstructedIndividualPublicKeys {
		groupPublicKey = new(bn256.G2).Add(groupPublicKey, peerPublicKey)

	}

	rm.groupPublicKey = groupPublicKey
}
