    * Feature Name: Network Security
    * Status: draft
    * Start Date: 2018-08-11
    * Authors: Raghav Gulati
    * RFC PR: #275
    * Keep Issues: #9, #87, #88

:icons: font
:numbered:
toc::[]

== Background

Keep is a decentralized network that is anchored to one or more host chains via
on-chain smart contracts, allowing interactions both on- and off-chain depending
on the use case. To ensure the safety, security, and integrity of the network,
the network needs to implement authorization, encryption, and authentication. The
decentralized nature of the network brings about the unique challenge where
off-the-shelf protocols such as TLS aren't suitable. Specifically, these
protocols can't be used as-is due to their requirement of trusted central
authorities and intermediaries.

This document (as requested in <<FD>>) specifies desired behaviors,
surveys current available protocols, and describes a protocol to secure the
network layer of Keep.

A successful protocol involves verifying identities (to prevent Sybil attacks),
ensuring message integrity (to avoid malicious tampering), and encrypting
messages (to ensure that only intended recipients receive a message).


=== Terminology

peer:: A member of a network that can initiate, accept, and handle secure
connections.
network:: A set of peers who are connected to each other, not necessarily p2p.
handshake:: An initial negotiation between peers to establish secret key
material.
chain:: A decentralized, consensus driven store with identities and economic
incentives.
stake:: The amount of value required to be a participant in the network. This
amount is held on the host chain and associated with an identity.
bootstrap node:: A trusted peer in a network that handles requests for joining
the network from peers outside of it. This involves verifying an on-chain stake
among many other responsibilities.


=== Goal

We aim to authenticate peers, control access to a network where Keep’s protocols
execute, and provide verifiable, private channels between communicating peers.


==== Capabilities

The protocol must provide the following capabilities:


===== Authentication

The goal of authentication is to provide the communicating parties with some
assurance that they know each others' identities.

An authenticated peer is a known identity in the network such that all messages
from the authenticated peer, _M~i~_, can be provably linked to the authenticated
peer.

Given an authenticated peer and an unauthenticated peer, the unauthenticated peer
must provide the authenticated peer proof of attestation over a staked key on
chain. If an authenticated peer's stake falls below the minimum stake amount or
they it is proven that they are malicious, then an authenticated peer becomes
unauthenticated.


===== Authorization

The goal of authorization is to ensure that capabilities within the system are
restricted to authenticated identities.

The only capabilities a peer has before establishing a secure, authenticated
connection is sending an initialization message, referred to as the
AuthenticationMessage, to a peer that can process this message and authenticate
the peer. Authenticated peers can participate in the network and form secure
channels with other authenticated members.


==== Required Properties

In addition to these capabilities, the following security properties should hold:


===== Secure

<<AAKE>> introduces us to the definition of a secure protocol. We summarize it as:

1. If two peers, _P~1~_ and _P~2~_, share a secret key, it is computationally
infeasible for anyone not _P~1~_ and _P~2~_, to recover the secret key.

2.  The record of messages shared between _P~1~_ and _P~2~_ to establish the
authentication of identity must be identical and logically linked. This prevents
replay attacks (re-use of previous messages) and interleaving attacks (injecting
a message used in previous runs).

Furthermore, <<TLS>> states that for a protocol to be secure it must contain the
capabilities listed above as well as provide confidentiality and integrity. Then,
the __Secure__ property is a superset of the capabilities and properties listed in
this section.


===== Confidentiality

A message sent from a peer that is authenticated is only intelligible to the
communicating peers <<CNF>>.

===== Integrity

Data sent over the channel after establishment cannot be modified by
adversaries without detection.


===== Attributability

A message from a given peer is known to be from that peer.

==== Optional Properties

Lastly, the desired protocol may have the following optional properties:

---


=== Scenarios

The protocol should be flexible enough to satisfy the following (but not limited to)
scenarios:


==== Joining

An unauthenticated peer wants to become an authenticated peer in the Keep
Network. This peer must be, first and foremost, successfully staked (otherwise
dishonest participants can't be punished). Furthermore, the peer must prove their
stake to the members of the network.

The capabilities, authentication and authorization, cover the requirements
of this example. Specifically, authentication allows a peer to validate the
identity of the unknown peer. Next, authorization enables the following:

1. The restriction of the unknown, untrusted peer to only send the initial
request to be authenticated.
2. The capability of an authenticated peer to respond to on-chain events or to
network-specific events.
3. The disconnection from the network for members who fall below the minimum
stake.


==== Point-to-Point

A peer wishes to send a point-to-point message such that only the intended
recipient can inspect and verify the contents of the message.

This example presumes that the identity is verified and accepted in the network,
which means that authentication and authorization are satisfied.
Confidentiality is needed to ensure that the communicating peers can communicate
in secret. Integrity to ensure that the message hasn't been tampered with in
transit over the wire. Attributability to ensure that if either peer sends a
message which contains a payload that would result in punishment, the correct
peer will be punished.


==== Message Gossip

Originally specified in <<0RTT>>, formalized here.

A packed message _M_ that contains many sub-messages _S~all~_, each signed and
encrypted for a specific peer _P~i~_. This message _M_ can be circulated
throughout a network such that all intended recipients _P~all~_ will eventually
receive the message _M_ BUT will be only be able to unpack the contents of a
sub-message _S~i~_ intended for them (_P~i~_ can read _S~i~_ in _M_).

This example will require all of confidentiality, integrity, and attributability.

Confidentiality ensures that each sub-message _S~i~_ is signed and encrypted for
the use of a specific peer _P~i~_.

Integrity ensures that no other peer _P~1~_ can successfully tamper with another
peer's _P~2~_ message _S~2~_(as many peers will be exposed to the same message _M_,
but only have access to a specific sub-message _S~i~_).

Attributability ensures that if a peer acts in bad faith, they are easily
identifiable by any other authenticated peer in the network.


=== Potential Implementations

Given the above, we are primarily concerned with authentication and key exchange.
The literature overwhelmingly recommends a solution which provides authentication
and key-exchange considered jointly. Per <<AAKE>>:

> A protocol providing authentication without key exchange is susceptible to an
> enemy who waits until the authentication is complete and then takes over one
> end of the communications line. Such an attack is not precluded by a key
> exchange that is independent of authentication. Key exchange should be linked
> to authentication so that a party has assurances that an exchanged key (which
> might be used to facilitate privacy or integrity and thus keep authenticity
> alive) is in fact shared with the authenticated party, and not an impostor. For
> these reasons, it is essential to keep key exchange in mind in the design and
> analysis of authentication protocols.

There are a few implementations we can explore given the above constraints:


==== Elliptic-Curve-Diffie-Hellman

===== Overview

Diffie-Hellman satisfies some of the properties above, but due
to [reasons], it does not assume the presence of signature keys and hence
is susceptible to man-in-the-middle attacks. As a building block, we can
take this into account and layer on-top signing keys. This introduces
complexity to the protocol.

===== Limitations

- Does not deal with DoS attacks where _P~1~_ accepts _P~2~_'s identity, and then
sends a final message to P2 letting them know


==== Station-to-Station (STS)

===== Overview

* The base spec concerns with exponentiation, but also applies equally well to
additive groups (elliptic curve over finite fields).

* Authenticated key agreement with key confirmation: two-way explicit key
confirmation.

* Begins with Diffie-Helman key establishment, followed by an exchange of
authentication signatures, specifically of exponentials (of which at least one is
created for this specific run.

* Requires (given honest peers _P~1~_, _P~2~_, and adversary _A_)

** Encryption on signatures.
*** If we remove this requirement, _A_ can man-in-the-middle a handshake between
*** _P~1~_ and _P~2~_ (where _P~2~_ starts the handshake). Therefore, the
*** protocol fails to maintain a shared secret key between _P~1~_ and _P~2~_.
*** Instead, a secret key exists between _P~1~_ and _P~2~_ BUT _P~1~_ has
*** acknowledged _A_'s identity, not _P~2~_'s.

** _P~1~_ and _P~2~_ both sign _P~1~_, _P~2~_ exponentials.
*** Specific (though, not general) attacks exists for the case where an honest
*** peer only signs their exponential, or where they only sign the other peer's
*** exponential.

** Authentication must be coupled with Diffie-Hellman key-exchange.
*** Otherwise the protocol is susceptible to a man-in-the-middle attack <<AAKE>>.

** Must include Diffie-Hellman parameters in certificates.
*** _A_ has the freedom to modify the DH parameters, allowing _A_ to calculate
*** the exchanged key.

The following is a slightly modified summary from <<AAKE>>:

> There are two other desirable properties of the STS protocol. The first is that
> public key techniques are used to make key management simpler and more secure
> than is possible using conventional cryptography. If parties generate their own
> secret keys, these keys need never be disclosed (to anyone, including any
> supposedly trusted party), even during initialization. The second is that there
> is no need for communicating parties to contact a central facility on a per-
> call basis. If certificates are used for distributing public keys, once a party
> has its own certificate and the trusted authority’s public key, it can exchange
> keys with, and authenticate other parties without consulting a central facility.
> The protocol appears to strike an elegant and difficult balance, being simple
> and secure without utilizing unnecessary or redundant elements.

===== Analysis



==== Noise Protocol

===== Overview

===== Limitations


==== TLS

===== Overview

===== Limitations

==== Custom

===== Overview

===== Limitations


== Open Questions

* Do we need to expect that other higher-level protocols will be
layered on top?

* Do we require forward secrecy - how will we get that?

* What does a non-bootstrap node do with an authentication message?

* Is a requirement for communicating participants that they be online?

[bibliography]
== References

- [[[TLS]]] E Rescorla, Mozilla, August 2018
The Transport Layer Security (TLS) Protocol Version 1.3
https://www.rfc-editor.org/rfc/rfc8446.txt

- [[[AAKE]]] Diffie W. (1992)
Authentication and Authenticated Key Exchanges
In: Designs, Codes and Cryptography, 2, 107-125 (1992), Kluwer Academic Publishers
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.216.6107&rep=rep1&type=pdf

- [[[FD]]] Discussions on writing this document (2018)
In: Thesis Flowdock
https://www.flowdock.com/app/cardforcoin/tech/messages/152290
https://www.flowdock.com/app/cardforcoin/tech/messages/153124
https://www.flowdock.com/app/cardforcoin/tech/messages/153592

- [[[0RTT]]] Point-to-Point vs a single message with 0-RTT (2018)
In: Thesis Flowdock
https://www.flowdock.com/app/cardforcoin/tech/messages/154946

- [[[CNF]]] Desired properties of confidentiality in Keep's network (2018)
In: Thesis Flowdock
https://www.flowdock.com/app/cardforcoin/tech/messages/156769
