    * Feature Name: Network Security
    * Status: draft
    * Start Date: 2018-08-11
    * Authors: Raghav Gulati
    * RFC PR: #275
    * Keep Issues: #9, #87, #88

:icons: font
:numbered:
toc::[]


== Background

Keep is a decentralized network that is anchored to one or more host chains via
on-chain smart contracts, allowing interactions both on- and off-chain depending
on the use case. To ensure the safety, security, and integrity of the network,
the network needs to implement authorization, encryption, and authentication. The
decentralized nature of the network brings about the unique challenge where
off-the-shelf protocols (such as TLS) aren't suitable. Specifically, these
protocols can't be used as-is due to their requirement of trusted central
authorities and intermediaries. That being said, with some modifications,
we can make these options more secure and work for our use case.

This document specifies the desired behaviors and properties of a protocol that
will secure the network layer of Keep.

A successful protocol involves verifying identities (to prevent Sybil attacks),
ensuring message integrity (to avoid malicious tampering), and allows for the
encrypting of messages (to ensure that only intended recipients receive a
message). Furthermore, the protocol should be versioned for easy upgrades.

=== Terminology

peer:: A member of a network that can initiate, accept, and handle secure
       connections.
network:: A set of peers who are connected to each other, not necessarily p2p.
chain:: A decentralized, consensus driven store with identities and economic
        incentives.
stake:: The amount of value a given participant has locked up for participation
        in the network. This value is held on the host chain, and always
        associated with an identity.
minimum stake:: The minimum amount of value that is required to be a participant.
bootstrap peer:: A trusted, authenticated peer that handles requests for joining
          the network from unauthenticated peers. This involves verifying an
          on-chain stake among many other responsibilities.

=== Goal

We aim to authenticate peers, control access to a network where Keep’s protocols
execute, and provide verifiable private channels between communicating peers.

==== Capabilities

The protocol must provide the following capabilities:

===== Authentication

The goal of authentication is to provide the communicating parties with some
assurance that they know each others' identities.

An authenticated peer is a known identity in the network such that all messages
from the authenticated peer, _M~i~_, can be provably linked to the authenticated
peer.

Given an authenticated peer and an unauthenticated peer, the unauthenticated peer
must provide the authenticated peer proof of attestation over a staked key on
chain. If an authenticated peer's stake falls below the minimum stake amount for
any reason, then an authenticated peer becomes unauthenticated.

===== Authorization

The goal of authorization is to ensure that capabilities within the system are
restricted to authenticated identities.

The only capabilities a peer has before establishing a secure, authenticated
connection is sending an initialization message, to an authenticated peer that
can process this message (bootstrap peers) and authenticate the unauthenticated
peer. Authenticated peers can participate in the network and form secure channels
with other authenticated peers. In short:

* unauthenticated peer => can only send NetworkJoinRequest to bootstrap peers
* authenticated peer => can send and accept all kinds of messages


==== Required Properties

In addition to these capabilities, the following security properties should hold:

===== Secure

<<AAKE>> introduces us to the definition of a secure protocol. We summarize it as:

1. If two peers, _P~1~_ and _P~2~_, share a secret key, it is computationally
infeasible for anyone other than _P~1~_ and _P~2~_, to recover the secret key.

2.  The record of messages shared between _P~1~_ and _P~2~_ to establish the
authentication of identity must be:

 * identical, within a given session, regardless of perspective
 * logically linked, from one message to the next

This prevents replay attacks (re-use of previous messages) and interleaving
attacks (injecting a message used in previous runs).

===== Integrity

Data sent over the network after authentication cannot be modified by adversaries
without detection.

===== Attributability

A message from a given peer is known to be from that peer.


=== Scenarios

The protocol should be able to satisfy some known scenarios, described below,
though this should not be considered a comprehensive list.

==== Joining the network

An unauthenticated peer wants to become an authenticated peer in the Keep
Network. This peer must be, first and foremost, successfully staked (otherwise
dishonest participants can't be punished). Furthermore, the peer must prove their
stake to the members of the network.

The capabilities, authentication and authorization, cover the requirements
of this example. Specifically, authentication allows a peer to validate the
identity of the unknown peer. Next, authorization enables the following:

1. The restriction of the unknown, untrusted peer to only send the initial
request to be authenticated.
2. The capability of an authenticated peer to respond to on-chain events or to
network-specific events.
3. The disconnection from the network for members who fall below the minimum
stake.

==== Point-to-Point communications

A peer wishes to send a point-to-point message such that only the intended
recipient can inspect and verify the contents of the message.

This example presumes that the identity is verified and accepted in the network,
which means that authentication and authorization are satisfied.
Confidentiality is needed to ensure that the communicating peers can communicate
in secret. Integrity to ensure that the message hasn't been tampered with in
transit over the wire. Attributability to ensure that if either peer sends a
message which contains a payload that would result in punishment, the correct
peer will be punished.

==== Message Gossip

A packed message _M_ that contains many sub-messages _S~all~_, each signed and
encrypted for a specific peer _P~i~_. This message _M_ can be circulated
throughout a network such that all intended recipients _P~all~_ will eventually
receive the message _M_ BUT will be only be able to unpack the contents of a
sub-message _S~i~_ intended for them (_P~i~_ can read _S~i~_ in _M_).

This example will require all of confidentiality, integrity, and attributability.

Confidentiality ensures that each sub-message _S~i~_ is signed and encrypted for
the use of a specific peer _P~i~_.

Integrity ensures that no other peer _P~1~_ can successfully tamper with another
peer's _P~2~_ message _S~2~_(as many peers will be exposed to the same message _M_,
but only have access to a specific sub-message _S~i~_).

Attributability ensures that if a peer acts in bad faith, they are easily
identifiable by any other authenticated peer in the network.


== Summary

Given the above, we are primarily concerned with authentication and key exchange.
The literature overwhelmingly recommends a solution which provides authentication
and key-exchange considered jointly. Per <<AAKE>>:

> A protocol providing authentication without key exchange is susceptible to an
> enemy who waits until the authentication is complete and then takes over one
> end of the communications line. Such an attack is not precluded by a key
> exchange that is independent of authentication. Key exchange should be linked
> to authentication so that a party has assurances that an exchanged key (which
> might be used to facilitate privacy or integrity and thus keep authenticity
> alive) is in fact shared with the authenticated party, and not an impostor. For
> these reasons, it is essential to keep key exchange in mind in the design and
> analysis of authentication protocols.

== Open Questions

* Do we need to expect that other higher-level protocols will be
layered on top?

* Do we require forward secrecy - how will we get that?

* What does a non-bootstrap peer do with an authentication message?

* Is a requirement for communicating participants that they be online?

* Should all communications between Keep nodes be encrypted in order to provide
confidentiality for all transcripts between nodes?

[bibliography]
== References

- [[[TLS]]] E Rescorla, Mozilla, August 2018
The Transport Layer Security (TLS) Protocol Version 1.3
https://www.rfc-editor.org/rfc/rfc8446.txt

- [[[AAKE]]] Diffie W. (1992)
Authentication and Authenticated Key Exchanges
In: Designs, Codes and Cryptography, 2, 107-125 (1992), Kluwer Academic Publishers
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.216.6107&rep=rep1&type=pdf

== Related Links

- Discussions on writing this document.
https://www.flowdock.com/app/cardforcoin/tech/messages/152290
https://www.flowdock.com/app/cardforcoin/tech/messages/153124
https://www.flowdock.com/app/cardforcoin/tech/messages/153592

- t-ECDSA performance with some thoughts on network performance optimizations.
https://www.flowdock.com/app/cardforcoin/tech/messages/154946

- Desired properties of confidentiality in Keep's network.
https://www.flowdock.com/app/cardforcoin/tech/messages/156769
