:toc: macro
:icons: font

= Keep ECDSA v2

The Keep Network offers threshold ECDSA protocol to generate a ECDSA wallets
without any single signer having access to the corresponding private key. This
functionality is used by TBTC v2 to manage Bitcoin wallets used by TBTC Bridge.

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

toc::[]

== Overview

Keep ECDSA allows creating threshold ECDSA wallets where where `n` parties share
the power to issue digital signatures under a single public key. A threshold `t`
is specified such that any subset of `t + 1` players can jointly sign, but any
smaller subset cannot.

`WalletRegistry` smart contract is an on-chain registry of ECDSA wallets
controlled by off-chain network of nodes. The distributed key generation
protocol used by the off-chain network of nodes should have three properties:

- The signing group as a whole should have an ECDSA public key, which will be
  shared on the host chain (Ethereum) and will correspond to the Bitcoin wallet
  owned by that signing group.
- Each member of the signing group should have a threshold ECDSA secret key
  share, which can be used to create a threshold ECDSA signature share for any
  transactions involving the signing group’s wallet.
- Each member of the signing group should be able to combine a threshold number
  of signature shares from itself and other members of the group to produce a
  signed version of a given transaction to be performed on behalf of the signing
  group.


== Build

The contracts use https://hardhat.org/[*Hardhat*] development
environment. To build and deploy contracts, please follow the instructions
presented below.

=== Prerequisites

Please make sure you have the following prerequisites installed on your machine:

- https://nodejs.org[Node.js] >=14
- https://yarnpkg.com[Yarn] >=1.22

=== Build contracts

To build the smart contracts, install node packages first:

```sh
yarn install
```

Once packages are installed, you can build the smart contracts using:

```sh
yarn build
```

Compiled contracts will land in the `build/` directory.

==== TypeScript Typings

Typings are generated for the contracts in `typechain/` directory.

=== Test contracts

There are multiple test scenarios living in the `test` directory.
You can run them by doing:

```sh
yarn test
```

=== Deploy contracts

To deploy contract execute:

```
yarn deploy --network <NETWORK>
```

After the Bridge contract from tbtc-v2 is deployed it has to be set as the
Wallet Owner in the `WalletRegistry`:

```
npx hardhat --network <NETWORK> initialize-wallet-owner --wallet-owner-address <BRIDGE_ADDRESS>
```
