---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoind-data-bitcoind-1
  namespace: bitcoin
  labels:
    app: bitcoind
    chain: bitcoin
    network: mainnet
spec:
  storageClassName: bitcoind
  dataSource:
    name: bitcoind-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 650Gi
