resources:
  - ../../../templates/bitcoin/bitcoind

namespace: bitcoin

commonLabels:
  network: mainnet

configMapGenerator:
  - name: bitcoind
    behavior: merge
    literals:
      - chain=main

secretGenerator:
  - name: bitcoind
    behavior: merge
    envs:
      - .env.secret

patches:
  - target:
      kind: StatefulSet
      name: bitcoind
    patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: bitcoind
      spec:
        replicas: 2
