== Intro

Here we provide a mechanism to prepare deployment bundles for external parties
particpating in our private testnet.  New bundles need to be generated after each
contract migration or keep-client build for the `keep-test` environment.  Bundles
are managed via scripts provided in the `/scripts` dir and should require little
context to operate.

== General Steps

Scripts should be run from `keep-core/private-testnet/scripts`

* Run a new circle build from `keep-test-deployment` branch
* Update `changelog.adoc` with relevant info since the last release
* Update `keep-client-quickstart.adoc` with any changes
* Run `prepare-participant-bundles.sh`
* Run `fetch-contract-data.js`
* Run `stake-accounts.js`

== Directory Structure

This touches on directory format and reasons for this format.  It's not exhaustive,
but should cover the bits that must be honored.

=== Top level

On `keep-core/private-testnet` we store files that are generally applicable to
external participants.  This should look like:

Files the bundling script expects to be on this level:

* `keep-client-snapshot.tar`
* `eth-account-password.txt`
* `changelog.adoc`

=== Participants

Participant directories should all live in `keep-core/private-testnet/partcipants`.
Each particpant must get their own directory.  The bundling script and quickstart
guide both operate under the assumption that each participant directory is
structured in the format highlighted below:

Files/Directories the bundling script expects to be on this level:

* `config/eth-account-keyfile`
* `config/keep-client-config.toml`
* `persistence/`


== Scripts

There are 3 scripts that make up preparing deployment bundles:

`fetch-contract-data.js`::
Grabs the latest contract data for `KeepToken` and `TokenStaking`. These are used in the `stake-accounts.js` script
`stake-accounts.js`::
Stakes each ETH account that is assigned to a participant.
`prepare-participant-bundles.js`::
Creates a `.tar.gz` bundle to be distributed to each participant.  The file is stored on the top level of the particpant directory.

=== Dependencies

Package dependencies are listed in `keep-core/private-testnet/scripts/package.json`.
You can install these by running `npm i` from the scripts dir.

