# Values from Kube ConfigMap and set via InitContainer run, do not update manually.

[ethereum]
  URL = ""
  URLRPC = ""

  [ethereum.account]
    Address = ""
    KeyFile = ""

  [ethereum.ContractAddresses]
    # Hex-encoded address of KeepRandomBeaconOperator contract
    KeepRandomBeaconOperator = ""

    # Hex-encoded address of TokenStaking contract
    TokenStaking = ""

    # Hex-encoded address of KeepRandomBeaconService contract. Only needed
    KeepRandomBeaconService = ""

[LibP2P]
  Peers = []
  Port = ""
  AnnouncedAddresses = []

[Storage]
  DataDir = ""

[ClientInfo]
  Port = ""
