:toc: macro

== Go Guidelines

toc::[]

Go code generally adheres to the best practices of the Go community. All Go code
is formatted using `goimports` to ensure both adherence with `gofmt`'s output,
as well as unified organization of imports. 

=== Max line length

Go code is wrapped at 80 charactersper line as a general rule, though some
lines may be left longer at the discretion of the developers for clarity. No
line should exceed 120 characters in length. When wrapping function calls,
each parameter should be on its own line.

=== `go vet`/`go lint`

We vet and lint our code at commit-time. All code should pass both `go vet` and
`go lint` in their default configurations.

=== Deviations

Two major deviations from typical Go practices that are worth calling out:

 - We do *not* prefix commit messages with the packages touched by the commit.
   The commit includes diffs, diffs include paths, paths imply packages. We
   consider this unnecessary and noisy.

 - We *discourage* single-letter variable names and related extra-shortness.
   Short variable names produce diffs that are more difficult to analyze
   quickly, and generally result in lower clarity for less experienced
   developers. We consider this an antipattern, and the additional typed
   characters to be comparatively very cheap. We make a few exceptions:

    External packages::
      We use the package name irrespective of our own practices, unless it
      introduces ambiguity.
    The `err` variable::
      We use `err` as is common in Go.
    Iteration indices::
      `i`, `j`, etc are well-understood and not domain-specific.
    Method receivers::
      Since Go does not have a standard `this`, we do use the first letter of
      each word as the variable name of a method receiver (e.g., for a type
      `MyCoolType`, the method receiver would be named `mct`).
    Name clashes::
      If a variable name would clash with the name of a type, e.g. a variable
      of type `magic` whose name would naturally be `magic`, the last vowel
      may be dropped to achieve a unique name.
