:toc: macro

= T developer documentation

toc::[]

== Quick installation
To quickly install and start a client use the following scripts.

=== Pre-requirements
For development purposes, it is convenient to set up a local Ethereum client with a group of connected peers. A note-taken walkthrough <<local-t-network.adoc,[set up local T network]>>  covers the entire process
including setting up a local Ethereum client, deploying T contracts and
configuring T peers. +

Additionaly, to start a client we need to provide config options either by creating a config file or passing the required parameters. For simple installation using a config file please refer to a <<sample_config_file,sample configuration>> file that is placed under `/configs/` dir.

=== Starting a client

Run from the project root:

* `./scripts/install.sh`
* `./scripts/initialize.sh`
* `./scrtips/start.sh`

=== Installation scripts explained

The `+install.sh+` needs to be run only once and it will:

* install yarn dependencies across the projects
* unlock ethereum accounts 
* build `threshold-network/solidity-contracts`, `random-beacon`, `ecdsa` and `tbtc-v2` contracts
* deploy `threshold-network/solidity-contracts`, `random-beacon`, `ecdsa` and `tbtc-v2` contracts 
* build a client

For more info please refer to `./scripts/install.sh --help`

```
Usage: ENV_VAR(S) ./scripts/install.sh --network <network> --tbtc-path <tbtc-path> --threshold-network-path <threshold-network-path> --skip-deployment --skip-client-build

Environment variables:

        KEEP_ETHEREUM_PASSWORD: The password to unlock local Ethereum accounts to set up delegations. Required only for 'local' network. Default value is 'password'

Command line arguments:

        --network: Ethereum network for keep-core client(s). Available networks and settings are specified in the 'hardhat.config.ts'
        --tbtc-path: 'Local' tbtc project's path. 'tbtc' is cloned to a temporary directory upon installation if the path is not provided
        --threshold-network-path: 'Local' threshold network project's path. 'threshold-network/solidity-contracts' is cloned to a temporary directory upon installation if the path is not provided
        --skip-deployment: This option skips all the contracts deployment. Default is false
        --skip-client-build: Should execute contracts part only. Client installation will not be executed
```

The `./scripts/initialize.sh --stake-owner <address>` needs to be run for each 
client. Default setup assumes that the staking provider, operator, beneficiary,
and the authorizer all have the same addresses as the stake owner. Only the
`stake-owner` has to be unique for the default setup. The default stake amount is
`1,000,000 T` tokens. The default authorization amount is the minimum authorization
amount +
Ex. if you need to initialize a network with 3 clients using the default setup,
then this script needs to be run 3 times with a different `--stake-owner` address
like so: +
- `initialize.sh --stake-owner <address1>` +
- `initialize.sh --stake-owner <address2>` +
- `initialize.sh --stake-owner <address3>`

The `+initialize.sh+` script will:

* mint & approve `T` tokens
* stake `T` tokens
* increase authorization for `RandomBeacon` and `WalletRegistry` applications
* register operator for `RandomBeacon` and `WalletRegistry` applications

For more info please refer to `./scripts/initialize.sh --help`

```
Usage: ./scripts/initialize.sh --network <network> --stake-owner <stake owner address> --staking-provider <staking provider address> --operator <operator address> --beneficiary <beneficiary address> --authorizer <authorizer address> --stake-amount <stake amount> --authorization-amount <authorization amount>

Mandatory line arguments:

        --stake-owner: Stake owner address

Optional line arguments:

        --network: Ethereum network for keep-core client. Available networks and settings are specified in the 'hardhat.config.ts'
        --staking-provider: Staking provider address
        --operator: Operator address
        --beneficiary: Staking beneficiary address
        --authorizer: Staking authorizer address
        --stake-amount: Stake amount
        --authorization-amount: Authorization amount
```

Afer executing `install.sh` and `initialize.sh` now you can run `./scripts/start.sh`
to start a client. It will prompt you to chose from the available config files that
should match the one chosen for `./scripts/initialize.sh`. Please refer to
`./scripts/start.sh --help` for more info

```
./scripts/start.sh --help

Usage: ENV_VAR(S) ./scripts/start.sh --config-dir-path <path-to-configuration-files>

Environment variables:

        KEEP_ETHEREUM_PASSWORD: Ethereum account password. Required only for 'local' network. Default value is 'password'

Command line arguments:

        --config-dir-path: Path to a client configuration files
```

=== Configuration

==== Application

The client expects configuration options to be specified in a config file or passed
as parameters. If you specify an option by using a parameter on the command line,
it overrides the value from the configuration file.

Application configuration can be stored in a file and passed to the application
run command with the `--config` flag. Example:
[source,bash]
----
./keep-client --config /path/to/your/config.toml start
----

Configuration files in formats TOML, YAML and JSON are supported.

==== Operator's Ethereum Key File

Ethereum Key File is expected to be encrypted with a password. The password has
to be provided in prompt after the client starts or configured as environment
variable `KEEP_ETHEREUM_PASSWORD`.

==== Command-line Options

[source,bash,role=small]
----
include::cmd-help[]
----

==== Sample Config File [[sample_config_file]]

[source,toml,role=small]
----
include::../../configs/config.toml.SAMPLE[]
----

=== Network

Default port mappings.

[%header,cols=2*]
|===
|Egress
|Port

|Keep Network
| TCP: `3919`
|===

[%header,cols=2*]
|===
|Ingress
|Port

|Keep Network
|`3919`
|===

If you set a different `port` in your configuration, or configure `peers` with
non-default ports configured, firewall rules will need to be adjusted accordingly.

== Development Guidelines

There are two primary languages in the T code right now:

Go::
  Go code largely adheres to community practices where they have been decided.
  Divergences and additional tidbits are listed in the link:go-guidelines.adoc[Go
  Guidelines] document.

Solidity::
  Solidity code generally adheres to the
  https://solidity.readthedocs.io/en/latest/style-guide.html[Solidity style guide].
  Contracts and their functions are documented using
  https://docs.soliditylang.org/en/develop/natspec-format.html[the
  Ethereum Natural Specification Format] (NatSpec).

== Working with Solidity contracts

The fastest and easiest way to have a local Ethereum testent is to use
https://hardhat.org/[Hardhat].


Navigate to one of the projects `solidity/ecdsa` or `solidity/random-beacon`.
You can deploy contracts executing `yarn deploy` or run tests against the local
Hardhat's network `yarn test`.
