:toc: macro

= T developer documentation

toc::[]

== <<local-t-network.adoc,Setting up local T network>>

For development purposes, it is convenient to set up a local Ethereum client with
a group of connected peers. A note-taken walkthrough covers the entire process
including setting up a local Ethereum client, deploying T contracts and
configuring T peers.

== Quick installation

To quickly install and start a client use the following scripts.

=== Install scripts

The `+install.sh+` script will:

* install yarn dependencies
* unlock accounts
* build contracts
* deploy contracts
* build client

The `+initialize.sh+` script will:

* mint & approve `T` tokens
* stake `T` tokens
* increase authorization for `RandomBeacon`
* register operator

Please refer to the scripts `help` for available command arguments and environment
variables. `./install.sh --help` or `./initialize.sh --help`. Accounts unlocking
and staking can be run outside of these scripts as standalone hardhat tasks.

To deploy and initialize contracts:

* run `./scripts/install.sh`. You need to run it only once.

* run `./scripts/initialize.sh --stake-owner <address>` for the default setup for
each client. Default setup assumes that the staking provider, operator, beneficiary,
and the authorizer all have the same addresses as the stake owner. Only the
`stake-owner` has to be unique for the default setup. The default stake amount is
`1,000,000 T` tokens. The default authorization amount is the minimum authorization
amount +
Ex. if you need to initialize a network with 3 clients with the default setup,
then run this script 3 times with a different `<address>`.


=== Starting a client

TBD

==== Configuration

===== Application

The client expects configuration options to be specified in a config file or passed
as parameters. If you specify an option by using a parameter on the command line,
it overrides the value from the configuration file.

Application configuration can be stored in a file and passed to the application
run command with the `--config` flag. Example:
[source,bash]
----
./keep-client --config /path/to/your/config.toml start
----

====== Operator's Ethereum Key File

Ethereum Key File is expected to be encrypted with a password. The password has
to be provided in prompt after the client starts or configured as environment
variable `KEEP_ETHEREUM_PASSWORD`.

====== Command-line Options

[source,bash,role=small]
----
include::cmd-help[]
----

====== Sample Config File

[source,toml,role=small]
----
include::../../configs/config.toml.SAMPLE[]
----

===== Network

Default port mappings.

[%header,cols=2*]
|===
|Egress
|Port

|Keep Network
| TCP: `3919`
|===

[%header,cols=2*]
|===
|Ingress
|Port

|Keep Network
|`3919`
|===

If you set a different `port` in your configuration, or configure `peers` with
non-default ports configured, firewall rules will need to be adjusted accordingly.

== Development Guidelines

There are two primary languages in the T code right now:

Go::
  Go code largely adheres to community practices where they have been decided.
  Divergences and additional tidbits are listed in the link:go-guidelines.adoc[Go
  Guidelines] document.

Solidity::
  Solidity code generally adheres to the
  https://solidity.readthedocs.io/en/latest/style-guide.html[Solidity style guide].
  Contracts and their functions are documented using
  https://docs.soliditylang.org/en/develop/natspec-format.html[the
  Ethereum Natural Specification Format] (NatSpec).

== Working with Solidity contracts

The fastest and easiest way to have a local Ethereum testent is to use
https://hardhat.org/[Hardhat].


Navigate to one of the projects `solidity/ecdsa` or `solidity/random-beacon`.
You can deploy contracts executing `yarn deploy` or run tests against the local
Hardhat's network `yarn test`.
