:toc: macro

= Keep developer documentation

toc::[]

== <<local-keep-network.adoc,Setting up local Keep network>>

For development purposes, it is convenient to set up a local Ethereum client with
a group of connected peers. A note-taken walkthrough covers the entire process
including setting up a local Ethereum client, deploying Keep contracts and
configuring Keep peers.

== Quick installation

To quickly install and start a client use the following scripts.

=== Install script

The `+install.sh+` script will:

* install yarn dependencies
* unlock accounts
* build contracts
* deploy contracts
* setup staking contract
* build client

Please refer to the script's help for available command arguments and environment variables. `./install.sh --help`

To start the installation execute:

....
./scripts/install.sh
....

=== Starting a client

TBD

== Development Guidelines

There are two primary languages in the Keep code right now:

Go::
  Go code largely adheres to community practices where they have been decided.
  Divergences and additional tidbits are listed in the link:go-guidelines.adoc[Go
  Guidelines] document.

Solidity::
  Solidity code generally adheres to the
  https://solidity.readthedocs.io/en/latest/style-guide.html[Solidity style guide].
  Contracts and their functions are documented using
  https://docs.soliditylang.org/en/develop/natspec-format.html[the
  Ethereum Natural Specification Format] (NatSpec).

== Working with Solidity contracts

The fastest and easiest way to have local Ethereum testent is to use Hardhat.
https://hardhat.org/


Navigate to one of the projects `solidity/ecdsa` or `solidity/random-beacon`.
You can deploy contracts executing `yarn deploy` or run tests against the local
Hardhat's network `yarn test`.
