:toc: macro
:ext-relative: .adoc

= Skaffold Managed Local Dev Environment

toc::[]

== Overview
We use Skaffold to manage the local development environment. Skaffold
takes care of booting up a sane local Kubernetes environment that includes:

- a local Ethereum test network (_n_ nodes)
- a local Keep client (_n_ nodes)
- when started in `dev` mode Skaffold will automatically build new Keep
binaries on file changes.

The _n_ we set here is the number of replicas of each type of node. We will
initially set that in the yaml files and later parameterize that so we
can define it on the command line.

=== Goals
1. Simplify coding, debugging and testing Keep code
by standardizing the local development environment
2. Keeping local development congruent with the Kubernetes environment
in the cloud.

=== Design ===

```
+--------------------------------------------------+
|                Kubernetes Cluster                |
|                                                  |
| +---------------------------------------------+  |
| |                  Ethereum                   |  |
| |                   Testnet                   |  |
| |                                             |  |
| |                                             |  |
| |                                             |  |
| |                                             |  |
| | +---------+    +---------+    +---------+   |  |
| | |  Geth   |    |  Geth   |    |  Geth   |   |  |
| | | Mining  |    |   TX    |    |Dashboard|   |  |
| | |  Node   |<-->|  Node   |<-->|  Node   |   |  |
| | |         |    |         |    |         |   |  |
| | +---------+    +---------+    +---------+   |  |
| +---------------------^-----------------------+  |
|                       |                          |
|                       |                          |
|                       |                          |
|        +--------------+--------------+           |
|        |              |              |           |
|        |              |              |           |
|        |              |              |           |
|        |              |              |           |
|    +-------+      +-------+      +------+        |
|    |       |      |       |      |      |        |
|    | Keep  |      | Keep  |      | Keep |        |
|    |   1   |<---->|   2   |<---->|  3   |        |
|    |       |      |       |      |      |        |
|    +-------+      +-------+      +------+        |
|        ^                             ^           |
|        |                             |           |
|        +-----------------------------+           |
|                                                  |
|                  +--------+                      |
|                  |        |                      |
|                  | Pumba  |                      |
|                  |        |                      |
|                  +--------+                      |
+--------------------------------------------------+
```

== Setup
We assume you have Homebrew installed. Many of the tools needed for a complete
development environment can be installed via Homebrew. In some cases Homebrew
won't install the latest version. We will mention the minimum version needed
for each tool. Please check the version you install.

=== Mojave Fixes
Make sure the Xcode developer tools are installed:

```
xcode-select --install
```
Expected output: 
```
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

On Mojave you will need to install the missing header files:

```
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
```

=== Docker for Mac
Install Docker for Mac via Homebrew or download the installer from https://docs.docker.com/docker-for-mac/install/[Docker website].
```
brew cask install docker
```
Make sure you run at least version `18.09.0-ce-beta1` or higher.
```
$ docker --version
Docker version 18.09.2, build 6247962
```

=== Kubernetes

Activate Kubernetes in the Docker preferences: _Docker_ -> _Preferences_ -> 
_Kubernetes_ -> _Enable Kubernetes_.
Make sure you are running at least version `v1.10.3` or higher.
```
$ kubectl version --short
Client Version: v1.10.11
Server Version: v1.10.11
```

==== Kubernetes-CLI
Docker for Mac comes with an older version of `kubectl`. You'll want
to upgrade that. Make sure you are using version `v1.12.0` or higher.
```
$ kubectl version --short
Client Version: v1.10.11    <-- this is kubectl version
Server Version: v1.10.11
```
If _Client version_ is less than required upgrade it:
```
mv /usr/local/bin/kubectl /usr/local/bin/kubectl-Docker-for-Mac
brew install kubernetes-cli
kubectl version --short
```


=== Skaffold
Install Skaffold via Homebrew:

```
brew install skaffold
```

Or by downloading a release binary:

```
curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-darwin-amd64
chmod +x skaffold
mv skaffold /usr/local/bin
```

Whatever you choose make sure you're using version `v0.17.0` or
higher.
```
$ skaffold version
v0.24.0
```

=== Google Cloud SDK

Install Google Cloud SDK via Homebrew:
```
brew cask install google-cloud-sdk
```
Or by following an https://cloud.google.com/sdk/docs/quickstart-macos[instruction].

Initialize gcloud by running `gcloud init`. Login with your `@thesis.co` e-mail
and configure:

_Pick cloud project to use_ : `keep-dev-fe24`

_Do you want to configure a default Compute Region and Zone?_: `n`

Execute script to configure access to the Google Container Registry:
```
./infrasctructure/scripts/create-google-container-registry-secret.sh -c docker-for-desktop
```

== Local Development
=== Ethereum Testnet Components

```

 ╔═════════════════════════════════════════════════════════════════════════════════════════════════╗
 ║                                                                                                 ║
 ║                                     ┏━━━━━━━━━━━━━━━━━━━━━┓                                     ║
 ║                                     ┃ ┌─────────────────┐ ┃                                     ║
 ║                                     ┃ │                 │ ┃                                     ║
 ║                     register        ┃ │    Boot Node    │ ┃           register                  ║
 ║               ┌───────node──────────╋▶│    Registrar    │◀╋─────────────node─────┐              ║
 ║               │                     ┃ │                 │ ┃                      │              ║
 ║               │                     ┃ └─────────────────┘ ┃                      │              ║
 ║               │                     ┃                     ┃                      │              ║
 ║               │                     ┃                     ┃                      │              ║
 ║               │                     ┃                     ┃                      │              ║
 ║               │                     ┃                     ┃                      │              ║
 ║               │                     ┃                     ┃                      │              ║
 ║               │                     ┃                     ┃                      │              ║
 ║               │                     ┃                     ┃                      │              ║
 ║               │                     ┃ ┌─────────────────┐ ┃                      │              ║
 ║               │                     ┃ │                 │ ┃                      │              ║
 ║               │                     ┃ │  Eth-Netstats   │ ┃                      │              ║
 ║               │               ┌─────╋▶│    Dashboard    │◀╋─────┐                │              ║
 ║    ┏━━━━━━━━━━╋━━━━━━━━━━┓    │     ┃ │                 │ ┃     │     ┏━━━━━━━━━━╋━━━━━━━━━━┓   ║
 ║    ┃          │          ┃    │     ┃ └─────────────────┘ ┃     │     ┃          │          ┃   ║
 ║    ┃ ┌─────────────────┐ ┃    │     ┃                     ┃     │     ┃ ┌─────────────────┐ ┃   ║
 ║    ┃ │                 │ ┃    │     ┃    Dashboard Pod    ┃     │     ┃ │                 │ ┃   ║
 ║    ┃ │    Boot Node    │ ┃    │     ┗━━━━━━━━━━━━━━━━━━━━━┛     │     ┃ │    Boot Node    │ ┃   ║
 ║    ┃ │    Reporter     │ ┃    │                                 │     ┃ │    Reporter     │ ┃   ║
 ║    ┃ │                 │ ┃    │                                 │     ┃ │                 │ ┃   ║
 ║    ┃ └─────────────────┘ ┃    │                                 │     ┃ └─────────────────┘ ┃   ║
 ║    ┃                     ┃    │                              report   ┃                     ┃   ║
 ║    ┃ ┌─────────────────┐ ┃ report                             node    ┃ ┌─────────────────┐ ┃   ║
 ║    ┃ │                 │ ┃  node                             stats    ┃ │                 │ ┃   ║
 ║    ┃ │    EthStats     │ ┃ stats                                │     ┃ │    EthStats     │ ┃   ║
 ║    ┃ │       Api       │─╋────┘                                 └─────╋─│       Api       │ ┃   ║
 ║    ┃ │                 │ ┃                                            ┃ │                 │ ┃   ║
 ║    ┃ └────────▲────────┘ ┃                                            ┃ └────────▲────────┘ ┃   ║
 ║    ┃          │          ┃                                            ┃          │          ┃   ║
 ║    ┃          │          ┃                                            ┃          │          ┃   ║
 ║    ┃          │          ┃                                            ┃          │          ┃   ║
 ║    ┃ ┌────────┴────────┐ ┃                                            ┃ ┌────────┴────────┐ ┃   ║
 ║    ┃ │                 │ ┃                                            ┃ │                 │ ┃   ║
 ║    ┃ │      geth       │ ┃                 P2P                        ┃ │      geth       │ ┃   ║
 ║    ┃ │                 │◀┃─ ─ ─ ─ ─ ─ ─ ─ block ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ╋▶│                 │ ┃   ║
 ║    ┃ │                 │ ┃               updates                      ┃ │                 │ ┃   ║
 ║    ┃ └─────────────────┘ ┃                                            ┃ └─────────────────┘ ┃   ║
 ║    ┃                     ┃                                            ┃                     ┃   ║
 ║    ┃      Miner Pod      ┃                                            ┃       TX Pod        ┃   ║
 ║    ┗━━━━━━━━━━━━━━━━━━━━━┛                                            ┗━━━━━━━━━━━━━━━━━━━━━┛   ║
 ║                                           Kubernetes                                            ║
 ╚═════════════════════════════════════════════════════════════════════════════════════════════════╝
```

When we boot the testnet via Kubernetes it brings up a minimum of three pods.
The `dashboard` pod presents a view of the Ethereum testnet with live nodes,
block propagation times and other relevant stats. The `miner` pod mines new
Ethereum blocks. The `tx` pod processes requests from clients via the geth API.

Both `miner` and `tx` pods run a `bootNodeReporter` daemon that reports to the
`bootNodeRegistrar` daemon that runs on the `dashboard` pod. Any new booting
`miner` or `tx` pod will query the registrar on the `dashboard` pod for known
addresses of `geth` peers. We don't use auto-discovery on our testnet.

Both `miner` and `tx` pods run a `EthStatsApi` daemon that queries the local
`geth` daemon for vital stats and reports those to the `EthNetstats` dashboard
where they are displayed.

All `miner` and `tx` pods also communicate with each other via P2P protocol
and inform each other about new blocks.


=== Boot the Ethereum Kubernetes Testnet
If you want to just boot the Ethereum testnet cluster, you can do that without
using Skaffold by running the start script:

```
./infrastructure/scripts/up
```

To shutdown the testnet cluster:

```
./infrastructure/scripts/down
```

==== Important Note
The current setup supports Kubernetes PersistentVolume for chain data. To
simplify setup we are only allowing one mining node and one tx node. They
write to distinct subdirectories underneath `/tmp/k8-volumes` assuming that
your Docker Desktop is configured to share `/tmp` with containers which is
the default. The benefit of writing to PersistentVolumes in the test cluster
is that you can retain chain data like deployed contracts between restarts and
don't have to go through the full setup routing again.

If you need to restart the chain from a clean slate you will have to manually
delete the `/tmp/k8-volumes` directory and all subdirectories.

If you don't care about preserving chain data and need to run more miner or
tx nodes just comment out the definition of the `HOSTVOLUME` environment
variable in the coresponding `yaml` file for miner and/or tx node. The pod
will then fallback to ephemeral storage inside the container at boot time.

=== Develop Keep
To start developing run the following command:

```
skaffold dev
```

This will build the Docker container for the Keep client and deploy it inside
a Kubernetes pod. Any log output will be printed on the console where you
started Skaffold.

Any time you save a changed file related to the Keep client a new build is
kicked off and the resulting container deployed.

To destroy the Skaffold environment just press Ctrl-C.


== Appendix
=== Docker Network Fuzzing
Pumba enables the `netem` tool for Docker containers so you can
simulate wide area network failures like packet delay and packet loss.

https://github.com/alexei-led/pumba][https://github.com/alexei-led/pumba

```
brew install pumba
```

Fetch the pumba container
```
docker run gaiaadm/pumba
```

Fetch the iproute2 image
```
docker run gaiadocker/iproute2
```

Start the first shell in a docker container
```
docker run -it busybox bash
```

Open a new shell window and start the second shell in a docker container.
```
docker run -it busybox bash
```

On the shell inside the first container get its IP address.
```
ifconfig eth0|grep 'inet addr'
  inet addr:172.17.0.2  Bcast:172.17.255.255  Mask:255.255.0.0
```

On the shell inside the second container get its container id.
```
hostname
  fbb3b55b17ec
```

Now ping the first container.
```
ping 172.17.0.2
```

Open a third shell on your Docker host. The hostname of our second container was
`fbb3b55b17ec`. We need to fetch its name.
```
docker ps|grep fbb3b55b17ec
  fbb3b55b17ec        busybox             "sh"                13 minutes ago
  Up 13 minutes                           fervent_hermann
```

Disturb the network of the container named `fervent_hermann`.
```
pumba netem --duration 20s --tc-image gaiadocker/iproute2 \
 delay --time 3000 jitter 50 --distribution normal\
 fervent_hermann
```
You should observe the ping times jumping up to 3000ms for the duration of 20s
then fall back to normal.

Randomly kill a matching container who's name starts with the matching string
```
pumba --random --interval 3s kill re2:^fervent_hermann
```
There's only one exact match to the regular expression in this case and container
two is killed immediately. If there were a set of containers named `fervent_xxx`
then it would kill one of them at random every 3s until you abort `pumba` with
Ctrl-C.

=== Authenticate Docker to access Google Container Registry

If you need to access GCR directly from Docker execute following command:
```
gcloud auth configure-docker
```
