= Skaffold Managed Local Dev Environment

== Overview
We use Skaffold to manage the local development environment. Skaffold
takes care of booting up a sane local Kubernetes environment that includes:
- a local Ethereum test network (n nodes)
- a local Keep client (n nodes)
- Pumba chaos creator to disturbe the network or mess with container
  state
- a standardized way to attach the Go Delve debugger to a Keep node in
  the cluster.

When started in `dev` mode Skaffold will automatically build new Keep
binaries on file changes.

=== Goals
1. Simplify coding, debugging and testing Keep code
by standardizing the local development environment
2. Keeping local development congruent with the Kubernetes environment
in the cloud.

=== Design ===

....
+-------------------------------------------------------------------+
|                        Kubernetes Cluster                         |
|                                                                   |
| +----------------------------------------------------------+      |
| |                         Ethereum                         |      |
| |                         Testnet                          |      |
| |                                                          |      |
| |                                                          |      |
| |                                                          |      |
| |                                                          |      |
| | +---------+    +---------+    +---------+    +---------+ |      |
| | |         |    |         |    |         |    |         | |      |
| | |  Geth   |    |  Geth   |    |  Geth   |    |  Geth   | |      |
| | |  Node   |<-->|  Node   |<-->|  Node   |<-->|  Node   | |      |
| | |         |    |         |    |         |    |         | |      |
| | +----^----+    +---------+    +---------+    +----^----+ |      |
| +------+--------------+-------+------+------+-------+------+      |
|        |              |       |   ^  |      |    ^  |             |
|        |              |       |   |  |      |    |  |             |
|        |          +-------+   +--++-----+   +----+  |             |
|        |          |       |      |      |           |             |
|        |          | Keep  |      | Keep |           |             |
|        |      +-->|   2   |<---->|  3   |<--+       |             |
|        |      |   |       |      |      |   |       |             |
|        |      |   +-------+      +------+   |       |             |
|    +-------+  |       ^              ^      |   +-------+         |
|    |       |  |       |              |      |   |       |         |
|    | Keep  |  |       |              |      |   | Keep  |         |
|    |   1   |<-+       |              |      +-->|   4   |         |
|    |       |          |              |          |       |         |
|    +-------+          |              |          +-------+         |
|        ^              |              |              ^             |
|        |              |              |              |             |
|        +--------------+--------------+--------------+             |
|                                                                   |
|                         +--------+                                |
|                         |        |                                |
|                         | Pumba  |                                |
|                         |        |                                |
|                         +--------+                                |
+-------------------------------------------------------------------+
....

== Setup
We assume you have Homebrew installed. Many of the tools needed for a complete
development environment can be installed via Homebrew. In some cases Homebrew
won't install the latest version. We will mention the minimum version needed
for each tool. Please check the version you install.

=== Mojave Fixes
Make sure the Xcode developer tools are installed:

....
xcode-select --install
....

On Mojave you will need to install the missing header files:

....
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
....

=== Docker for Mac
Install Docker for Mac via Homebrew. Make sure you run at least
version `18.09.0-ce-beta1` or higher.

....
brew cask install docker
....

Or download the installer from here:
https://docs.docker.com/docker-for-mac/install/

After the installation activate Kubernetes in the Docker preferences
and make sure you are running at least version `v1.10.3` or higher.

=== Kubernetes-CLI
Docker for Mac comes with an older version of `kubectl`. You'll want
to upgrade that. Make sure you are using version `v1.12.0` or higher.

....
kubectl version
mv /usr/local/bin/kubectl /usr/local/bin/kubectl-Docker-for-Mac
brew install kubernetes-cli
kubectl version
....


=== Skaffold
Install Skaffold via Homebrew:

....
brew install skaffold
....

Or by downloading a release binary:

....
curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-darwin-amd64
chmod +x skaffold
mv skaffold /usr/local/bin
....

Whatever you choose make sure you're using version `v0.17.0` or
higher.

== Development

=== Develop
=== Attach a Debugger
=== Pumba Network Fuzzing
