= Skaffold Managed Local Dev Environment

== Overview
We use Skaffold to manage the local development environment. Skaffold
takes care of booting up a sane local Kubernetes environment that includes:
- a local Ethereum test network (n nodes)
- a local Keep client (n nodes)
- Pumba chaos creator to disturbe the network or mess with container
  state
- a standardized way to attach the Go Delve debugger to a Keep node in
  the cluster.

When started in `dev` mode Skaffold will automatically build new Keep
binaries on file changes.

=== Goals
1. Simplify coding, debugging and testing Keep code
by standardizing the local development environment
2. Keeping local development congruent with the Kubernetes environment
in the cloud.

=== Design ===

....
+-------------------------------------------------------------------+
|                        Kubernetes Cluster                         |
|                                                                   |
| +----------------------------------------------------------+      |
| |                         Ethereum                         |      |
| |                         Testnet                          |      |
| |                                                          |      |
| |                                                          |      |
| |                                                          |      |
| |                                                          |      |
| | +---------+    +---------+    +---------+    +---------+ |      |
| | |         |    |         |    |         |    |         | |      |
| | |  Geth   |    |  Geth   |    |  Geth   |    |  Geth   | |      |
| | |  Node   |<-->|  Node   |<-->|  Node   |<-->|  Node   | |      |
| | |         |    |         |    |         |    |         | |      |
| | +----^----+    +---------+    +---------+    +----^----+ |      |
| +------+--------------+-------+------+------+-------+------+      |
|        |              |       |   ^  |      |    ^  |             |
|        |              |       |   |  |      |    |  |             |
|        |          +-------+   +--++-----+   +----+  |             |
|        |          |       |      |      |           |             |
|        |          | Keep  |      | Keep |           |             |
|        |      +-->|   2   |<---->|  3   |<--+       |             |
|        |      |   |       |      |      |   |       |             |
|        |      |   +-------+      +------+   |       |             |
|    +-------+  |       ^              ^      |   +-------+         |
|    |       |  |       |              |      |   |       |         |
|    | Keep  |  |       |              |      |   | Keep  |         |
|    |   1   |<-+       |              |      +-->|   4   |         |
|    |       |          |              |          |       |         |
|    +-------+          |              |          +-------+         |
|        ^              |              |              ^             |
|        |              |              |              |             |
|        +--------------+--------------+--------------+             |
|                                                                   |
|                         +--------+                                |
|                         |        |                                |
|                         | Pumba  |                                |
|                         |        |                                |
|                         +--------+                                |
+-------------------------------------------------------------------+
....

== Setup
=== Mojave Fixes
Install the missing header files:

....
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
----

=== Docker for Mac
Install Docker for Mac via Homebrew:
....
brew cask install docker
....
Or download the installer from here:
https://docs.docker.com/docker-for-mac/install/

=== Kubernetes-CLI
Docker for Mac comes with an older version of `kubectl`. You'll want
to upgrade that.
....
kubectl version
mv /usr/local/bin/kubectl /usr/local/bin/kubectl-Docker-for-Mac
brew install kubernetes-cli
kubectl version
....
Make sure you are using version `v1.12.0` or higher.

=== Skaffold
Install Skaffold via Homebrew:
....
brew install skaffold
....
Or by downloading a release binary:
....
curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-darwin-amd64
chmod +x skaffold
mv skaffold /usr/local/bin
....
Whatever you choose make sure you're using version `v0.17.0` or
higher.

== Development

=== Develop
=== Attach a Debugger
=== Pumba Network Fuzzing 



