apiVersion: batch/v1
kind: Job
metadata:
  name: keystore-configmap-job
spec:
  template:
    metadata:
      name: batch-configmap-job
    spec:
      containers:
      - name: batch-configmap-job
        image: gcr.io/google_containers/busybox
        volumeMounts:
        - name: keystore-configmap-volume
          mountPath: /keystore
        command: ["cat", "$(KEEP_ETHEREUM_KEYFILE)"]
        env:
          - name: KEEP_ETHEREUM_ACCOUNT
            value: "8b99e241b3a65030661cf8788de8e5ca45c48f2b"
          - name: KEEP_ETHEREUM_KEYFILE
            value: "/keystore/8b99e241b3a65030661cf8788de8e5ca45c48f2b"
      volumes:
        - name: keystore-configmap-volume
          configMap:
            name: 8b99e241b3a65030661cf8788de8e5ca45c48f2b
            items:
              - key: 8b99e241b3a65030661cf8788de8e5ca45c48f2b
                path: 8b99e241b3a65030661cf8788de8e5ca45c48f2b
      restartPolicy: Never
  backoffLimit: 4
