---
apiVersion: v1
kind: Service
metadata:
  name: miner-node
  labels:
    app: geth
    type: miner
spec:
  ports:
  - port: 8545
    targetPort: 8545
    name: tcp-8545
  - port: 8546
    targetPort: 8546
    name: tcp-8546
  - port: 30303
    targetPort: 30303
    name: tcp-30303
  - port: 30303
    targetPort: 30303
    name: udp-30303
    protocol: UDP
  selector:
    app: geth
    type: miner
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: miner-node
spec:
  replicas: 1  # must be 1 to utilize local persistent volume (see docs)
  template:
    metadata:
      labels:
        app: geth
        type: miner
    spec:
      containers:
      - name: miner
        image: lispmeister/geth-node
        volumeMounts:
          - mountPath: "/hostvolume"
            name: hostvolume
        ports:
        - containerPort: 8545
        - containerPort: 8546
        - containerPort: 30303
        env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NETWORKID
          value: "9384767738"
        - name: WS_SERVER
          value: ws://dashboard:3000
        - name: WS_SECRET
          value: BANZAI!!!!
        - name: BOOTNODE_URL
          value: http://dashboard:3001
        - name: BOOTNODE_NETWORK
          value: network_1
        - name: BOOTNODE_PUBLIC_IP
          value: dashboard
        - name: ENABLE_MINER
          value: "1"
        - name: MINER_THREADS
          value: "1"
        - name: HOSTVOLUME
          value: "/hostvolume"
        - name: ETH_IPC_PATH
          value: "/root/.geth/geth.ipc"
      volumes:
      - name: hostvolume
        hostPath:
          path: /tmp/k8-volumes/miner
          type: DirectoryOrCreate
