== Details+Rationale

=== Message delivery

==== Broadcast channel

Every group member in phase _p_ can safely assume
every non-inactive group member has seen
all messages broadcast within _T~p~_ after the beginning of phase _p_.

All messages broadcast by _P~i~_ are assumed to be signed with _X~i~_.

A message is malformed if it cannot be parsed and validated
as the message required in a particular phase of the protocol.

The implementation details of the broadcast channel
are currently out of scope for this document.

===== Assumptions and implications

The broadcast channel is assumed to give all participants
the same view of the world,
and deliver all messages from non-inactive participants
within a time that is less than the applicable time limit for each phase.

If these assumptions don't hold, certain attacks become possible.
For example, if a message from _P~i~_
reaches honest participant _P~j~_ but not _P~k~_,
their sets of inactive participants _IA~Pj~_ and _IA~Pk~_ will differ.
This will make them vote for different results,
which will prevent quorum from being reached on _full verification_,
while on _escalating votes_ a coordinating adversary
could make its preferred incorrect result win the vote.
To protect against the latter,
_escalating votes_ assumes a null result when any single result is opposed
by _f~max~ + 1_ participants as it means that the honest votes are split.

=== Result format

The result of the DKG protocol can be either a success or a failure.

Success means the DKG protocol finished with at most _M~fail~_ participants
misbehaving or dropping offline during the execution of the protocol,
and the group of the remaining honest participants _G_
should be added to the signing groups for the threshold relay.

Failure means that the group creation could not finish, due to either
the number of (inactive + disqualified) participants exceeding _M~fail~_,
or the presented results being disputed
in a way where the correct outcome cannot be ascertained.

[source, haskell]
----
data Result = NoFaultFailure
            | FailureDQ { disqualified :: Array Bool }
            | PerfectSuccess { pubkey :: BeaconPubkey }
            | SuccessIA { pubkey :: BeaconPubkey
                        , inactive :: Array Bool }
            | SuccessDQ { pubkey :: BeaconPubkey
                        , disqualified :: Array Bool }
            | MixedSuccess { pubkey :: BeaconPubkey
                           , inactive :: Array Bool
                           , disqualified :: Array Bool }
----

For a reasonably compact representation,
we can use the first byte of the result to encode not only success/failure,
but also whether there were inactive or disqualified participants.

The inactive and disqualified participants are listed
in one-indexed bit arrays where the __i__th bit being set means
_P~i~_ is in the corresponding set.

WARNING: One-indexing is a risk factor for off-by-one errors in the code.
Using zero-indexed arrays with the first bit unset
would instead move the risk into the length calculations.

If the __i__th bit is set in both `inactive` and `disqualified`,
the result message can either be deemed invalid
or have disqualification take precedence.

The maximum length of a result message is _1 + |BeaconPubkey| + n/4_ bytes.

(For an unreasonably compact representation we could use ternary in trees
to represent only the indexes of participants who were in _IA_ or _DQ_.
In theory this would save space almost every time,
as the longest message (_MixedSuccess_) may only contain
1/4 of participants in either of them.
A less ridiculous ternary encoding would be squeezing 5 trits into 1 byte
between 0-242, using 8 bytes where binary encoding would use 10.
These trytes could be further compressed by prefixing them with bytes
encoding which trytes of the entire array contain any nonzero values,
saving a small amount of space in most cases.
In practice there is no way it would be worth it,
especially given the reputation of ternary in this industry.)

=== Dispute resolution

Given that the protocol is performed off-chain,
participants may submit incorrect results
in an attempt to gain advantage.
By relying on the honest majority assumption,
this can be mitigated by having participants vote on results.

Voting on results means that only votes need to be counted on-chain;
validating everything else can be offloaded onto the honest majority.
This has significant cost advantages as _O(n^2^)_ blockchain operations,
including _O(n)_ transactions and up to _O(n^2^)_ elliptic curve operations,
can be replaced with simply _O(n)_ transactions of mostly constant size,
or a single transaction with _O(n)_ elliptic curve operations.

There are two main ways this voting can be performed:
either by members signing valid results, which are then verified on-chain,
or by designated members being eligible to submit a result
which may be challenged by others if they consider it incorrect.

==== Full verification

The _full verification_ technique of voting is simple.
The designated eligible submitter _P~sub~_ publishes the correct result
which is then checked by the contract to contain at least _M~max~ + 1_
valid signatures from unique members of _P_.

This technique requires fewer transactions and is less complex to implement,
but bears a constant cost as _O(n)_ signatures must be validated on-chain
upon every group creation.
Assuming for the sake of example _N = 201_ and _M~max~ = 100_,
and that `ecrecover = 3000 gas` dominates the transaction fees,
the cost of full verification would be constant on the order of 325,000 gas.

This also sets a hard limit on the group size of _N < gasLimit / 3000_,
but in practice this would only happen with impractically large groups
(currently more than 2,000 participants).

It is easy to see why _full verification_ would be correct:
if _M~max~_ is the largest number of malicious participants,
requiring _M~max~ + 1_ signatures means that any result accepted by the system
must have at least one honest participant supporting it.

==== Escalating votes

As an alternative to the above,
_escalating votes_ is a protocol where a result is submitted,
and accepted if it is not challenged within a specified time limit.
If multiple results are presented,
the participants will proceed to submit votes on the results
iff their preferred result is not in the lead,
or their vote would break a tie.
After a certain time limit has elapsed since the last vote,
a confirmation request transaction may be presented by anybody,
and the result with the highest number of supporting votes is accepted.

The security of this scheme is less obvious,
but follows from the honest majority assumption:
since at least _M~max~ + 1_ honest players are online at the voting stage,
for any amount of adversary votes _0 < v~m~<= M~max~_
there will be _v~m~ + 1_ honest participants
who will outvote the malicious players
(proof by induction).

This scheme is only suitable for situations where _N >= 2 * M~max~ + 1_,
due to the reliance on the honest majority assumption.
If the majority of participants is dishonest,
the plurality result may be incorrect.

In the worst-case scenario escalating votes will cost
_(M~max~ + 2) * 21000_ gas to the honest participants,
or around 2.15 million gas.
However, the practical cost of using escalating votes would be variable
and would be expected to be significantly lower most of the time.

Given that a rational adversary who cannot break the honest majority assumption
will expect to inevitably lose the escalating vote,
and the cost of the voting is symmetrical
(submitting one vote costs approximately 21,000 gas,
so the malicious players will pay _v~m~ * 21000_ gas
while honest players will pay _(v~m~ + 2) * 21000_ gas in total;
this means the honest players will always pay exactly
42,000 gas more than the malicious players regardless of the value of _v~m~_),
one would expect the escalating votes to usually go unchallenged.

In the example scenario, escalating votes is cheaper than full verification
if the average number of votes supporting the highest-voted incorrect result
is less than 13 out of 200 participants,
or alternatively if the worst-case scenario occurs at most 1/8 the time.

=== Misbehavior penalties

Attributable misbehavior:

* sending malformed messages
** malicious only
* presenting inconsistent shares
** malicious only
* voting for incorrect outcome
** can be done by honest participant
if the broadcast channel assumption fails

Inactivity:

* inactivity in the beginning
* inactivity during the execution
* inactivity at result stage
** not signing correct result if using FV
** with EV it gets super complex and don't want to think about it
