= Random Beacon Pricing

Possibilities:

. bid for stake
. bid for seed

== Bid For Seed

Customers publish bids, including:

- bid amount
- expiration time
- seed commitment

When the total of bids in the pool reaches or exceeds _Price~current~_
a number of highest bids are selected so that the sum of the selected
bids' values is at least _Price~current~_ -> _Bids~used~_.

The number of bids in _Bids~used~_ determines the _Timeout~seedReveal~_
by some function `timeoutByBidN`. With a smaller number of bidders, the timeout
will be reached sooner and thus the output will be generated faster; this
incentivizes placing high bids to improve the reliability.

One implication of this is that the top bidder can manipulate the output by
withholding the reveal of their seed to re-roll an unfavorable output
(if they collude with the selected group to determine the output in advance).
With solo bidding (bidding more than the current price) reaching timeout means
no output is generated, and this convenient vulnerability is blocked.
This would incentivize users with extremely high trust requirements to be solo
bidders.

The total value of the bids in _Bids~used~_ is multiplied by
_BID_STAKE_MULTIPLIER_ to determine the total stakes;
this is then divided by the number of members in a beacon signing group
to calculate each member's individual stake.
Thus bidding above the minimum price increases the group members' profits
but also penalties in the case of a failure.

The function `getCurrentOutputPrice` does most of the heavy lifting here.
While defining a precise function would require more work and is out of scope,
some features can be determined:

- The price of generating an output should always be higher than the gas cost
- With greater demand (more outputs generated recently) the price should rise,
with low demand (few outputs generated) it should fall
- If a certain total amount of bids exceeding the gas cost is placed,
the beacon should generate an output eventually as a long period of inactivity
pushes the price below the bid sum
