:toc: macro

= T-ECDSA Protocol

toc::[]

== Setup Phase

=== Commitment Master Public Key
[.lead]
_Commitment Master Publick Key_ is a value needed for commitment generation.
It is generated individually for each signer. This setup needs to be performed 
before each of two phases: key generation and signing.

Each signer generates _Commitment Master Public Key Share_ and broadcasts it to other signers.
After receiving all shares signers combine them to get _Commitment Master Public Key_.

A _Commitment Master Public Key Share_ is a point in an abstract cyclic group _G2_ of link:https://github.com/ethereum/go-ethereum/tree/master/crypto/bn256/cloudflare[256-bit Barreto-Naehrig]
curve.

* *Output*: 
** _Commitment Master Public Key_

== Key Generation Phase

[.lead]
In this phase signers jointly generate _DSA Key_ which will be used in the Signing
phase.

Each signer generates _Secret Key Share_ and _Public Key Share_ which form
_ECDSA Key Share_. +
Since _Secret Key Share_ must always be kept private, signer encrypts it with 
Paillier and broadcasts the encrypted _Secret Key Share_ along with _Public Key Share_
to other signers. +
After receiving all shares, signers combine them to get _ECDSA Key_, consisting of
_Encrypted Secret Key_ and _Public Key_.

* *Input*:
** _Commitment Master Public Key_

* *Output*: 
** _ECDSA Key_ {_Encrypted Secret Key_, _Public Key_}


== Signing Phase

[.lead]
In this phase signers jointly generate a _Signature_ for a _Message Hash_.

Signers communicate with each other in 6 rounds, exchanging information
to produce a T-ECDSA _Signature_ in a {_R_, _S_} format over a _Message Hash_ 
which is expected to be exactly 32 bytes.

Before starting this phase a fresh _Commitment Master Public Key_ should be generated.

This phase requires also _ECDSA Key_ which is a result of Key Generation Phase.

* *Input*:
** _Commitment Master Public Key_
** _ECDSA Key_
** _Message Hash_

* *Output*: 
** _Signature_ {_R_, _S_}
