:toc: macro

= T-ECDSA Protocol

toc::[]

== Setup Phase

=== Master Public Key
*Output*: _Master Public Key_

[.lead]
_Master Publick Key_ is a value needed for commitment generation.
It is generated individually for each signer. This setup needs to be done before each 
of two phases: key generation and signing.

. Each signer generates _Master Public Key Share_ and broadcasts it to other signers
 in _Master Public Key Share Message_.
+
.Master Public Key Share Message
[halign=center,options="header"]
|=== 
^|name ^|type ^|description

^|`signerID` 
^|`string`
^|Signer's ID

^|`masterPublicKeyShare` 
^|`[]byte`
^|Master Public Key Share
|=== 

. Each signer combines all _Master Public Key Shares_ to get _Master Public Key_.

== Key Generation Phase

*Input*: _Master Public Key_ +
*Output*: _DSA Key_

[.lead]
In this phase signers jointly generate _DSA Key_ which will be used in the Signing
phase.

=== Round #1

. Each signer generates _DSA Key Share_ which consists of _Secret Key Share_ and
_Public Key Share_.
+
_Secret Key Share_ value must be kept secret and never shared.
+
_Public Key Share_ value cannot be exposed until all signers in the group commit
to their values.

. Each signer calculates a commitment to the _Public Key Share_ value and 
broadcasts this commitment in  _Public Key Share Commitment Message_.

.Public Key Share Commitment Message
[halign=center,options="header"]
|=== 
^|name ^|type ^|description

^|`signerID` 
^|`string`
^|Signer's ID

^|`publicKeyShareCommitment` 
^|`commitment.MultiTrapdoorCommitment`
^|Commitment to _Public Key Share_
|=== 

=== Round #2
After commitments from all signers are gathered the next round starts.

. Signers reveal their _DSA Key Shares_ and broadcast _Key Share Reveal Message_. 
+
Since _Secret Key Share_ should always be kept secret it is first encrypted with
Paillier and this encrypted value is broadcasted along with Zero Knowledge Proof 
Π~i~ to confirm that _Secret Key Share_ value is in [-q^3^, q^3^] range.
+
_Public Key Share_ is broadcasted with a decommitment key used in a previous round
in commitment to _Public Key Share_ value.
+
.Key Share Reveal Message
[halign=center,options="header"]
|=== 
^|name ^|type ^|description

^|`signerID` 
^|`string`
^|Signer's ID

^|`secretKeyShare` 
^|`paillier.Cypher`
^|Encrypted _Secret Key Share_

^|`publicKeyShare` 
^|`curve.Point`
^|_Public Key Share_

^|`publicKeyShareDecommitmentKey` 
^|`commitment.DecommitmentKey`
^|Decommitment key for _Public Key Share_

^|`secretKeyProof` 
^|`zkp.DsaPaillierKeyRangeProof`
^|ZKP Π~i~ -- _Secret Key Share_ is in range [-q^3^, q^3^]
|=== 

. Each signer validates received _Key Share Reveal Messages_ and combines shares 
to get encrypted _Secret Key_ and _Public Key_ which together forms _DSA Key_.

== Signing Phase

*Input*: _Master Public Key_, _Message Hash_, _DSA Key_ +
*Output*: _Signature_

[.lead]
In this phase signers jointly generate signature for a message hash.

=== Round #1
Each signer:

. Generates encrypted _Secret Key Factor Share_ and _Secret Key Multiple Share_. These
values are kept secret for now. +

. Calculates a commitment to both values and broadcasts the commitment in _Sign Round 1 Message_.

.Sign Round 1 Message
[halign=center,options="header"]
|=== 
^|name ^|type ^|description

^|`signerID` 
^|`string`
^|Signer's ID

^|`secretKeyFactorShareCommitment` 
^|`commitment.MultiTrapdoorCommitment`
^|Commitment to _Secret Key Factor Share_ and _Secret Key Multiple Share_
|=== 

=== Round #2

Each signer:

. Calculates a Zero Knowledge Proof Π~1,i~.

. Broadcasts _Sign Round 2 Message_ containing _Secret Key Factor Share_, 
_Secret Key Multiple Share_ and decommitment key for the commitment from Round #1.

.Sign Round 2 Message
[halign=center,options="header"]
|=== 
^|name ^|type ^|description

^|`signerID` 
^|`string`
^|Signer's ID

^|`secretKeyFactorShare` 
^|`paillier.Cypher`
^|_Secret Key Factor Share_

^|`secretKeyMultipleShare` 
^|`paillier.Cypher`
^|_Secret Key Multiple Share_

^|`secretKeyFactorShareDecommitmentKey` 
^|`commitment.DecommitmentKey`
^|Decommitment key for a commitment to _Secret Key Factor Share_ and _Secret Key Multiple Share_

^|`secretKeyFactorProof` 
^|`zkp.DsaPaillierSecretKeyFactorRangeProof`
^|ZKP Π~1,i~
|=== 

. Validates received _Sign Round 1 Messages_ and _Sign Round 2 Messages_. +
Combines shares to get _Secret Key Factor_ and _Secret Key Multiple_.

=== Round #3
