---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trickster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trickster
      type: monitoring
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
      containers:
        - name: trickster
          image: trickstercache/trickster:2
          ports:
            - name: trickster
              containerPort: 8480
            - name: metrics
              containerPort: 8481
          readinessProbe:
            httpGet:
              path: "/trickster/health/default"
              port: metrics
          livenessProbe:
            httpGet:
              path: "/trickster/ping"
              port: trickster
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: trickster-config
              mountPath: /etc/trickster
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: trickster-config
          configMap:
            name: trickster-config
            items:
              - key: trickster.yaml
                path: trickster.yaml
