= Token distribution

Token distribution at existing projects
can be empirically observed to follow a power law:

From the Ethereum rich list at etherscan.io:

* 7,000 accounts have at least 1/100,000 of the total supply each
* 1,000 accounts have at least 1/10,000
* 150 accounts have at least 1/1,000
* 5 accounts have at least 1/100

From btc.com rich list:

* 100 accounts with 10,000+ (1/1,750)
* 2,000 accounts with 1,000+ (1/17,500)
* 15,000 accounts with 100+ (1/175,000)
* 150,000 accounts with 10+ (1/1,750,000)

The number of accounts holding at least _(total / X)_ tokens
tends to be roughly _(X / 10)_.
We can use this to generate a rough estimate of token distribution:

1B tokens in total

* 1 account with at least 10% = 100M
* 10 accounts with between 1% and 10% = 10M ~ 100M
* 100 with 0.1% to 1% -> 1M ~ 10M
* 1,000 with 0.01% to 0.1% -> 100k ~ 1M
* 10,000 with 0.001% to 0.01% -> 10k ~ 100k

== Minimum stake

Non-trivial stake requirements in other projects
(approximate fraction of total):

* Ethereum (Casper docs): 1,000 ETH deposit (1/100,000)
* Ethereum (speculation of eventual minimum): 32 ETH (1/3,000,000)
* Dash: 1,000 Dash (1/8,500)
* Cardano: 10,000 ADA (1/4,500,000)
* Tezos (masternode): 10,000 XTZ (1/80,000)
* Decred: ~110 (1/80,000)

Initial suggestion: 10,000 KEEP or 1/100,000 of the total supply

== Sample distribution

If we disregard tokens held in accounts with less than the minimum stake,
this provides us:

* 1 _megawhale_ with 200M (20%, 20,000 * minimum stake);
realistically this means Keep Org's tokens.
To preserve integrity these tokens would need to be inert
and not used for staking.
* 10 _whales_ with an average of 20M each (2%, 2,000 * minimum stake)
* 100 _large stakers_ with avg. 2M each (0.2%, 200 * minimum stake)
* 1,000 _medium stakers_ with avg. 200k (0.02%, 20 * minimum stake)
* 10,000 _small stakers_ with avg. 20k (0.002%, 2 * minimum stake)

The megawhale could be used as a sample adversary
with a 20% adversary power on its own.
If the megawhale colludes with the whales,
we have a cartel of 11 actors controlling 40% of the tokens.

The above approximation would hold even when accounting for tokens
not held by accounts large enough to stake;
in this case we'd simply ignore the small accounts
and calculate the ratios from stakeable tokens.
If e.g. 33% of tokens are held by small accounts,
the minimum stake would correspondingly be ~6,700 KEEP
at 0.001% of stakeable/staked tokens.
