---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: keep-network-relay-request-submitter
  labels:
    app: keep-network
    type: relay-requester
spec:
  schedule: '*/5 * * * *'
  jobTemplate:
    metadata:
      labels:
        app: keep-network
        type: relay-requester
    spec:
      activeDeadlineSeconds: 600
      template:
        spec:
          containers:
          - name: keep-network-relay-request-submitter
            image: gcr.io/keep-test-f3e0/keep-client
            ports:
              - containerPort: 3919
            env:
              - name: KEEP_ETHEREUM_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: eth-account-passphrase
                    key: eth-account-passphrase
            volumeMounts:
              - name: keep-network-relay-request-submitter
                mountPath: /mnt/keep-client/config
            command: ["keep-client", "-config", "/mnt/keep-client/config/keep-client-config.toml", "relay", "request"]
          volumes:
          - name: keep-network-relay-request-submitter
            persistentVolumeClaim:
              claimName: keep-network-relay-request-submitter
          restartPolicy: OnFailure
          initContainers:
          - name: initcontainer-provision-keep-client
            image: gcr.io/keep-test-f3e0/keep-client-initcontainer
            env:
              - name: KEEP_CLIENT_TYPE
                value: relay-requester
              - name: KEEP_CLIENT_ETH_ACCOUNT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: eth-account-passphrase
                    key: eth-account-passphrase
              - name: KEEP_CLIENT_ETH_KEYFILE
                value: /mnt/keep-client/config/eth_account_keyfile
              - name: KEEP_DATA_DIR
                value: /tmp
            volumeMounts:
              - name: keep-network-relay-request-submitter
                mountPath: /mnt/keep-client/config
            command: ["node", "/tmp/provision-keep-client.js"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keep-network-relay-request-submitter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi