:toc: macro
:toclevels: 4

= Contract structure

ifndef::yellowpaper[toc::[]]

== Overview

Token contract::

KEEP is an ERC20 token defined by the _token contract_.
The token contract is hard-coded in the operator and staking contracts,
but the design of the overall system makes it possible
to later migrate to a new version of the token contract
without disrupting customer experience.

Staking contract::

Owners of KEEP tokens can use a _staking contract_
to _stake_ them and use them as collateral for _operators_
who perform useful work in the Keep Network.
Staked tokens are transferred to the staking contract
and _delegated_ to an operator address.
The staking contract makes the tokens available to _operator contracts_
that have been _authorized_ to punish the operator in case of misbehavior,
while protecting them from unauthorized operator contracts.

Operator contracts::

Operators interact with _operator contracts_
to perform useful work for customers.
Operator contracts handle operations
that are critical for the proper incentives of individual operators.
They reward operators for correct behavior,
and are authorized to punish misbehavior.

Service contracts::

_Service contracts_ provide higher-level services to the public
using work performed by one or more operator contracts.
Service contracts do not interact directly with operators
nor do they need to be aware of the KEEP tokens or the staking contract.
Operator contracts can be upgraded without disrupting customer experience
by deploying a new version and adding it to the service contract.

Registry::

The addresses of contracts approved by Keep Org are kept in the _registry_.
Token contracts, staking contracts, operator contracts and service contracts
are all tracked separately in the registry.
The addresses and statuses of various contracts
can be queried from the registry.

== Operator contracts

Operator contracts coordinate the work performed by network operators,
and provide services to other "customer" contracts.
Operator contracts handle all operations
that may have an impact on staked tokens.
Conversely, operators performing work for the network
only need to interact with operator contracts.

The customer contract is treated as untrusted
and the operator contract must maintain correctness
and the safety of the operators' stakes
regardless of the customer contract's input.
Each operator contract is an independent "microservice",
keeping its own state on security-critical data.

When a customer contract requests an operator contract to perform a service,
it must pay the operator contract for the service provided.
The payment is distributed to contributing operators
according to the operator contract's own rules.
An operator contract can either provide services
to any contract that makes a valid request and pays the correct fee,
or it can be owned by a specific contract and only serve its owner.
In the random beacon
the service contract is the only "customer" of the operator contracts,
and operator contracts only provide services to the random beacon.
Future operator contracts may provide services directly to the public.

If one or more participant operators misbehave
or fail to perform promised work,
the operator contract tells the staking contract to punish the guilty parties
and optionally reward a tattletale that proved the misbehavior.
To punish misbehaving operators,
an operator contract must be authorized by the operator's authorizer.
Once an operator contract has been authorized by some address,
it can never be deauthorized by that address.

== Service contracts

Service contracts use the basic functionality
performed by operator contracts,
to provide useful services to the public.
In contrast to operator contracts,
service contracts don't interact directly with operators
and a failure in a service contract cannot risk operators' stakes.

Service contracts receive requests for their services from customers,
and provide the requested services.
Elements that are critical for operators' security and incentives
are delegated to an operator contract,
while other parts of the work are performed in the service contract.
The service contract keeps shared state which is not security-critical.

Service contracts can use
multiple different versions of operator contracts
to perform the operator contract functions.
To permit system upgrades,
the list of used operator contracts can be updated with proper authorization.
