= Stake delegation - notes

Based on RFC 3

Network throughput only depends on atomic stakes vs multioperation, ie whether
you lock the stake (which means every operation locks MINIMUM_STAKE as holders
will simply divide their stakes over the largest possible number of addresses if
the full stake is locked) or permit "fractional reserve staking" where the same
MINIMUM_STAKE may back up multiple different operations at the cost of being
able to pull off an "exit scam" style misbehaviour where someone who is going to
get their stake slashed away entirely misbehaves on all their other operations
as well.

Since the average level of stake leveraging this way is going to be the same for
both honest and malicious participants, the effect of this on network integrity
is ultimately probabilistically constrained and anomalously high leverages (eg.
someone with 2 * MINIMUM_STAKE participating in 20 operations when typically
someone with MINIMUM_STAKE participates in 3) would be correspondingly rare.

Thus the real outcome is:

With atomic staking, the network throughput is hard-capped at TOTAL_SUPPLY /
MINIMUM_STAKE operations simultaneously. This necessitates adjusting
MINIMUM_STAKE downwards if there is significant growth in the network usage.
However, if the value of the tokens scales linearly with usage, the amounts at
stake remain constant in external money.

The need to adjust MINIMUM_STAKE down over time also means that barriers to
entry to staking should remain constant, and ownership of tokens would be free
to get distributed more widely.

With unrestricted multioperation the network throughput is not limited by the
supply/stake ratio, and increased demand just means the same stakes get used for
multiple different operations if MINIMUM_STAKE remains constant. If the value of
the tokens increases with network usage, this means that the price of "random"
misbehaviour also increases, and acts as a serious incentive to ensure
reliability on a more mature network, but when failures happen there is less
incentive to not misbehave further. However, the total amount of misbehaviour
one can afford with a constant external money amount is limited to a small
multiplier of the amount under atomic staking.

If MINIMUM_STAKE stays constant, it increases the barriers to entry to staking
and encourages concentration of tokens in fewer, richer hands. However, if
multioperation is combined with downwards adjustment in minimum stake (and
penalties, which both of these imply should be defined as fractions of the
minimum stake), its behaviour ends up being a hybrid of unadjusted
multioperation and fully adjusted atomic staking (or, if the minimum stake is
completely adjusted for network demand, similar to that with atomic staking
except with a small chance of stakes being leveraged), but all forms of
unrestricted multioperation offer unlimited throughput.

'''

Because all forms of atomic staking are isomorphic due to the incentive
structure created by positive expected value from network participation, it
seems that these proposals actually break down into the following:

- atomic staking vs. multioperation
- dynamic vs. constant MINIMUM_STAKE
- instant undelegation with penalties vs. delayed undelegation with stake
locking

'''

If the above are condensed into letters denoting particular combinations:

A : M +
D : C +
P : L

I think anything from xxP is not very viable because of the
problems with instant undelegation, and thus xxL is the design space I'd
recommend. ACL has inherently limited throughput and is not a long-term viable
option. This leaves ADL, MDL and MCL .

MCL is the simplest to implement because it avoids the need to adjust the
minimum stake (This scheme is not present in this RFC; options 1 and 3
correspond to AxL of which ADL is a viable option, while 2 is MxP and 4 is AxP,
not recommended because of instant undelegating). MDL is more complex but also
more flexible if changes in the token staking patterns are desired. ADL is
slightly more intuitive in its characteristics in resistance to misbehaviour,
but it's also inflexible in how the minimum stake has to be adjusted to keep up
with demand, and it may present problems with accommodating possible future
services with especially high per-member stake requirements.

'''

There is also the option of keeping MINIMUM_STAKE constant but adjusting
penalties to match increase in demand and effective leveraging of multioperated
stakes. This would also enable particularly high-assurance services as the
maximum money at stake effectively grows with network demand.

'''

N~max_stakers~::
Tokens~total~ / Stake~min~
+
The maximum count of stakers if all tokens were distributed in exact integer
multiples of _Stake~min~_

N~stakers~::
sum(map(Stake~i~ -> floor(Stake~i~/Stake~min~), Stakers))
+
The actual number of virtual stakers available in the network

c::
N~stakers~ / N~max_stakers~
+
The staking efficiency factor of the network; what fraction of the tokens is
"actually performing work"

Ops::
min(Ops~max~, Demand)
+
The amount of simultaneous operations being performed

o::
Ops / N~stakers~
+
The overcapacity factor; how many simultaneous operations the average virtual
staker is performing

Ops~max~::
o~max~ * N~stakers~ +
f~ops~ * Demand

The maximum amount of simultaneous operations the network can perform

o~max~::
The maximum overcapacity factor

Price::
f~price~ * Demand
+
Token price assuming it follows network demand linearly; argument for this:
+
Expected value from operating is _EV = R * o - OpCost = (R - f~op_cost~) * o_
+
Let _CapCost_ be cost of capital and ignore some constant factors.
+
Operating a node is profitable when _EV > Stake~min~ * Price * CapCost_.
+
_R * o > Stake~min~ * Price * CapCost_ +
_R * Ops / N~stakers~ > Stake~min~ * Price * CapCost_ +
_R * Demand / (Tokens~total~ / Stake~min~) > Stake~min~ * Price * CapCost_ +
_R * Demand / Tokens~total~ > Price * CapCost_ +
_(R / Tokens~total~) * Demand > Price * CapCost_
+
Thus equilibrium at _Price = Demand * R / (Tokens~total~ * CapCost)_
(and the ignored constant factors).

OpCost::
f~op_cost~ * o
+
The cost of operating a node (assuming cost follows network demand linearly)

Stake~actual~::
Stake~min~ * Price
+
The actual amount of money at stake with network operations

'''

Proposal 1:

- 1:1 owner address/operator address
- atomic stake
- delayed undelegation

o~max~ = 1
Ops~max~ = N~stakers~

Because of the 1:1 nature and atomicity, stakes will be blitzpantsed. Thus there
will be _N~stakers~_ capacity in the network. This requires
_N~stakers~ = Demand_ and further _c * (Tokens~total~ / Stake~min~) = Demand_
or _Stake~min~ = c * (Tokens~total~ / Demand)_

Name _c' = c * Tokens~total~_; now _Stake~min~ = c' / Demand_

'''

Proposal 2:

- 1:1 owner/operator
- multioperation
- instant/penalized undelegation

o~max~ = unlimited
Ops~max~ = unlimited

No specific incentive to blitzpants. No specific need to adjust _Stake~min~_.

_Stake~actual~ = Stake~min~ * f~price~ * Demand_;
with _p = Stake~min~ * f~price~_: _Stake~actual~ = p * Demand_

The risk of "free" misbehavior when _D~sum~ > Stake~min~_ is mostly illusory.
The maximum penalty _S~i~_ could earn is _D~max_i~ = o~i~ * Stake~min~_.
_D~max_i~ > Stake~min~_ when _o~i~ > 1_.

_Demand = Ops_ so
_Demand = o * N~stakers~_ +
_Demand = o * c * (Tokens~total~ / Stake~min~)_.

Let constant factor _f' = c * f~price~_.

Now, _Price = o * f' * N~max_stakers~_.

Also _Stake~actual~ = Stake~min~ * f' * o * Tokens~total~ / Stake~min~_
simplifying to _o * f' * Tokens~total~_.

Let _f'' = 1 / (f' * Tokens~total~)_.

The ratio _D~max_i~ / Stake~actual~ = o~i~ * Stake~min~ / (o * Stake~min~) * f''_.

We get _(o~i~ / o) * f''_.

Thus the overleveraging of stakes only actually happens, compared to a constant
value stake, when _o~i~ > o_ which is constrained by the random distribution of
_o~i~_ around _o_. This would be expected to follow roughly a poisson
distribution and thus the probability of _o~i~ / o_ being large is quite small
with large _o_.

Further add to this that the opportunity cost for _S~i~_ is _R * o~i~_.

'''

== Delegation

=== Option 5: Multioperated delegation

==== General requirements:
1. _owner_ can only have one operator.
2. _owner_ can stake any amount of tokens between _Stake~min~_ and their stake.
3. _operator_ can only be _operating_ on behalf of one _owner_.
4. If an _owner_ tries to delegate to more than one operator, the tx must
fail.
5. If an _owner_ tries to delegate a stake to an _operator_ who already has a
stake, the tx must fail.

==== Basic design

With this scheme, tokens are staked by signing and publishing a staking contract
("agreement" to distinguish it from on-chain smart contracts) which specifies
the various details of any individual staking arrangement. This creates a new
staker identity in respect to those tokens, which can then be used to
participate in the network.

To improve security, separate roles are created for each aspect of staking. The
addresses behind these roles can be the same or different, depending on the
specific arrangement. This lets token-holders utilize cold storage effectively,
or delegate different aspects to different parties.

owner::
The address actually holding the tokens

operator::
An address authorized to use the tokens as stakes for participating in the
network

beneficiary::
An address designated to receive any rewards from participation

overseer::
An address with the authority to audit and authorize contract upgrades

==== Roles

===== Owner

The owner is the ultimate holder of the tokens. Before staking, the owner has
full control over the tokens, and the tokens are returned to the owner after
staking has finished. The owner's participation is not required in the
day-to-day operations of the staker, so cold storage can be accommodated to the
maximum extent.

The owner address is used to initiate staking and create the staker, and to
finish staking and reclaim the staked tokens.

===== Operator

The operator handles the everyday operations of the staker without actually
owning the staked tokens. While this enables third-party delegation without eg.
making it possible for the operator to simply transfer away tokens, it should be
noted that a malicious operator can exploit stake slashing to steal or destroy
tokens and thus the entire staked amount is indeed at stake.

The operator address is used to provide network functionality by participating
in various protocols. A signature from the operator is also required to initiate
staking, and the operator can unilaterally finish staking and return the tokens
to the owner.

===== Beneficiary

The beneficiary collects rewards earned from staking and participating in the
network. The beneficiary doesn't sign or publish any protocol-relevant transactions,
but any currency or tokens earned by the staker will be transferred to the
beneficiary.

===== Overseer



==== Stake multioperation
The stake multioperation feature enables performing several operations on the
same stake at the same time. As the stake is not locked for any particular
operation then it is possible for the _operator_ to participate in more than one
parallel operation using the same stake.

==== Basic structure:

* _delegating contract_
  ** _tokens[owner] -> amount_ table
  ** _staking[owner] -> delegation_id_ table
  ** _operating[operator] -> delegation_id_ table
  ** _op_agreement[delegation_id] -> agreement_ table with:
    *** _amount_ of staked tokens
    *** (if atomic alternative is desired:)
      **** _free_tokens_ unallocated to any contract
      **** _locked_tokens[contract_address] -> amount_ table of allocated tokens
    *** _state_ of the staking agreement
    *** _since_ last change
    *** _owner_ of the tokens
    *** _operator_ performing actions
    *** _beneficiary_ receiving rewards
    *** _authorizer_ auditing upgrades
  ** `delegate` method for delegating
  ** `undelegate` method for initiating undelegation
  ** `reclaim` method for finishing undelegation and freeing tokens
  ** `penalize` method for slashing stakes and rewarding tattletales with tokens
  ** `reward` method for paying out currency rewards
  ** (if atomic alternative is desired: `lock` method for assigning tokens to
  contracts)

* _authorization contract_
  ** _authorized[authorizer] -> [contract_address]_ table
  ** _blocked[contract] -> bool_ table of contracts `panic` has been called on
  ** `authorize` method for adding a contract to the caller's authorization list
  ** `panic` method for aborting all operations on a specific contract and
  revoking authorizations

* _functionality contracts_ provide network functions, and may call methods of
the _delegating contract_ for rewards and punishments (if atomicity is desired,
these contracts can also call `lock` with the proper authorization)

==== Functionality

===== Delegating a stake:

1. The _owner_ chooses the _staked amount_, and the _operator_, _beneficiary_ and
_upgrade authorizer_ addresses and creates a _delegation order_ containing this
information

2. Both the _owner_ and _operator_ sign the _delegation order_

3. The _delegation order_ is published on-chain

4. The contract receives the _delegation order_ and verifies the following (if
any condition is unfulfilled, processing aborts):
  * `staking[owner] == nil`
  * `operating[operator] == nil`
  * `tokens[owner] >= staked_amount >= minimum_stake`

5. If all conditions are satisfied the contract processes the _delegation order_
and sets the following:

  * `staking_time := current_time`
  * `delegation_id := hash(owner, operator)`
  * `tokens[owner] -= staked_amount`
  * `staking[owner] := delegation_id`
  * `operating[operator] := delegation_id`
  *  {blank}
+
....
op_agreement[delegation_id] := {
  amount = staked_amount,
  state = Active,
  since = staking_time,
  owner = owner,
  operator = operator,
  beneficiary = beneficiary,
  authorizer = upgrade_authorizer
}
....

6. The _operator_ can now use this stake for operating

(A _n-to-n_ variant can be designed where owners and operators are not tied to a
single delegation, but an owner can delegate to unlimited operators, an operator
can operate for unlimited owners, and each _owner, operator_ pair can have
unlimited delegation agreements between each other.

This would be done by eliminating the `staking[owner]` and `operating[operator]`
tables, and by setting `delegation_id := hash(owner, operator, staking_time)`.
With this change, the only limit is that the owner and operator can only
establish a single delegation agreement in a single block.)

===== Undelegating a stake:

1. The _owner_ or _operator_ chooses to unstake, and creates a
_undelegation order_ containing the _delegation ID_

2. Either the _owner_ or _operator_ signs the _undelegation order_ and publishes
it on-chain

3. The contract receives the _undelegation order_ and verifies the following
(`d_agreement := op_agreements[delegation_id]`):

  * `d_agreement != nil`
  * The _undelegation order_ is signed by either `d_agreement.owner` or
  `d_agreement.operator`

4. If the conditions are satisfied, the contract processes the
_undelegation order_ and sets the following:

  * `unstaking_time := current_time`

  * `d_agreement.state := Unstaking`

  * `d_agreement.since := unstaking_time`

5. The _operator_ can not enter new operations until the undelegated stake is
reclaimed

===== Claiming undelegated stake

1. After _T~unstake~_ has passed since the _undelegation order_ has been
processed, the _owner_ or _operator_ creates, signs and publishes a
_stake reclaiming order_ containing the _delegation ID_

2. The contract receives the _stake reclaiming order_ and verifies the
following (`d_agreement := op_agreements[delegation_id]`):

  * `d_agreement != nil`
  * The _stake reclaiming order_ is signed by either `d_agreement.owner` or
  `d_agreement.operator`
  * `d_agreement.state == Unstaking`
  * `d_agreement.since + unstake_delay =< current_time`

3. The contract processes the _stake reclaiming order_ and sets the following:

  * `tokens_unlocked := d_agreement.amount - new_penalties` (`new_penalties`
  applies if eg. an operation is still underway and it has been decided to set
  penalties for reclaiming stakes in such a situation)
  * `staking[owner] := nil`
  * `operating[operator] := nil`
  * `op_agreements[delegation_id] := nil`
  * `tokens[owner] += tokens_unlocked`

4. The _operator_ is now free to start operating for a new _owner_

(In the _n-to-n_ variant the `staking[owner]` and `operating[operator]` tables
are absent)

===== Operating on a stake

1. When the _operator_ tries to join an operation (eg. present a ticket for beacon
group selection) they should create a _operation initialization order_ including
the _delegation ID_ and the _contract address_, signed by the _operator_.

2. The _operation initialization order_ is published along with any other data
required to join the operation, after which the following should be checked
(`d_agreement := op_agreements[delegation_id]`:

  * `d_agreement != nil`
  * `d_agreement.state == Active`
  * If there is a requirement that the operator be staked before _deadline_, then
`d_agreement.since =< deadline`
  * The request is signed by `d_agreement.operator`
  * `d_agreement.amount >= minimum_stake`
  * The current contract has been authorized by `d_agreement.authorizer`
  * The current contract has not been blocked with the panic button:
`blocked[contract_address] == nil`

3. If the checks pass, the operator may join the operations.

===== Rewards

1. If the operator is awarded a _reward_ of currency, the reward should be paid
to `d_agreement.beneficiary`

===== Penalties

1. If the operator is to be punished by stake slashing, the
_penalizing contract_ should call the _delegation contract_ with the _penalty_.
The _penalty_ should contain the following:

  * The _penalty amount_
  * The _delegation ID_ to be slashed
  * Optionally the _tattletale reward amount_ and the _tattletale delegation ID_

2. The _delegation contract_ should then check the following
(`d_agreement := op_agreements[delegation_id]`):

  * The _penalizing contract_ is authorized by `d_agreement.authorizer` and has
not been blocked with the panic button
  * `penalty_amount =< minimum_stake`

3. If the penalty is valid, the _delegation contract_ will then perform the
following:

  * `actual_penalty := min(penalty_amount, d_agreement.amount)`
  * If there is a tattletale reward:
    ** `actual_tattletale_reward := min(tattletale_reward_amount, actual_penalty)`
    ** `tattletale_beneficiary := op_agreements[tattletale_id].beneficiary`
    ** `tokens[tattletale_beneficiary] += actual_tattletale_reward`
  * `d_agreement.amount -= actual_penalty`
  * If `d_agreement.amount < minimum_stake`, then the operator is blocked from
joining any new operations and the tokens are automatically unstaked:
    ** `d_agreement.state := Unstaking`
    ** `d_agreement.since := current_time`

The _actual penalty_ is set to be at most the amount of tokens remaining in the
stake, and the _actual tattletale reward_ is set to be at most the
_actual penalty_ to ensure no new tokens can be created by exploiting
overstaking. However, this means that it becomes possible to deny the tattletale
a reward by processing other penalties (where the misbehaving party also
controls the tattletale, to reduce their losses) first so that there is no stake
remaining when the real tattletale's turn comes. The only way to avoid this is
by stake atomicity so each operation is backed by hard tokens.

===== Upgrading a contract

1. The _upgrade authorizer_ audits and authorizes the new contract

2.  The _upgrade authorization contract_ checks that the _contract address_ is
present on the canonical version list, and adds it to the authorizer's list of
authorized contracts: `upgrade_authorizer.contracts += contract_address`

The rationale for this is that the authorizations can be outsourced to a third
party, and thus it is useful to have the authorizations stored separately to
reduce costs compared to including them in each delegation agreement.

If the new contract is found compromised, the recourse is for the _owner_ or
_operator_ to unstake or for the _panic button_ to be used to halt all
operations on the compromised contract. Once authorized, a contract is
technically capable of completely burning or transferring any staked tokens, even
if unstaking has been ordered. If this were not the case it would be possible to
avoid legitimate penalties.

Stake atomicity could be used to reduce exposure to compromised contracts, by
limiting the amount subject to the contract. Stake atomicity can be combined
with contract-specific stakes while keeping global minimum stake constant, so
that network throughput can be improved by upgrading contracts to new versions
with lower stakes required to participate.
