= Incentives

When an operator misbehaves attributably, the corresponding stake should be
slashed. Punishments should be appropriate for the severity of the misbehavior
and its impact on the network, and can be between _0_ and _Stake~MIN~_.

== Rewards and punishments

All rewards and punishments are incurred by a specific virtual staker.

STATUS: proposal

Currency and token rewards are paid to the beneficiary address specified in the stake
delegation transaction.

Punishments are performed by removing the designated amount of tokens from the
stakes of the _owner_.

If the operator has enough free stake to cover a minor penalty, the virtual
staker may continue performing operations and the penalty is subtracted from the
free stake, possibly impacting the operator's eligibility for subsequent group
selections.

If the operator cannot pay a minor penalty from free stake, the virtual staker
is terminated to avoid a stake deficit. When a virtual staker is terminated it
is removed from any groups it is in, rendering it ineligible for further rewards
from participating in those groups, and locking the remaining stake
_Stake~remaining~ = Stake~MIN~ - D_ for _T~UNSTAKE~_, after which
_Stake~remaining~_ is added to the operator's free stake.

TODO: do we want to lock the stake like this if terminated?

Major penalties always include termination of the virtual staker, regardless of
the free stake available. A major penalty may be smaller in absolute amount than
a minor penalty (but probably not); the distinction reflects the nature of the
misbehavior.

=== Group selection

==== Rewards

Group selection has no intrinsic rewards. However, presenting a valid challenge
to an invalid ticket should be amply rewarded to preserve the integrity of the
interactive protocol.

R~TICKET_TATTLETALE~::

Token reward for operator that presents a valid challenge to an invalid ticket.
+
_R~TICKET_TATTLETALE~ < D~INVALID_TICKET~_
+
It may be desirable for _R~TICKET_TATTLETALE~_ to include both tokens and
currency. `CostlyCheck` is expected to be expensive to perform in the future,
and submitting a valid ticket challenge should always be profitable. If the
ticket tattletale reward consists of both tokens and currency:
+
_R~TICKET_TATTLETALE~ = R~TICKET_TATTLETALE_TOKENS~ + R~TICKET_TATTLETALE_CURRENCY~_ +
_R~TICKET_TATTLETALE_TOKENS~ < D~INVALID_TICKET~_ +
_R~TICKET_TATTLETALE_CURRENCY~ >= GasEstimate(CostlyCheck)_
+
However, group selection provides no source of such currency, and thus it would
need to be taken from a general pool. It may be prohibitively difficult to
protect such a pool from getting emptied by attackers.
+
If the tattletale reward consists of only tokens, it would be profitable if
_R~TICKET_TATTLETALE~ * TokenPrice > GasEstimate(CostlyCheck)_.

==== Punishments

D~INVALID_TICKET~::

Major
+
Penalty for any operator that presents an invalid ticket. The invalid ticket may
fail either `CheapCheck`, or `CostlyCheck` after being challenged.
+
The requirements on _R~TICKET_TATTLETALE~_ constrain the value of
_D~INVALID_TICKET~_:
+
_D~INVALID_TICKET~ > GasEstimate(CostlyCheck) / TokenPrice_
+
This is necessary to ensure that the incentives of challenging invalid tickets
are in place.

D~INVALID_CHALLENGE~::

Major
+
Penalty for operator that presents an invalid challenge, and the accused ticket
passes `CostlyCheck`. Because the gas costs of `CostlyCheck` are incurred by the
accuser, _D~INVALID_CHALLENGE~_ can be set relatively freely without significant
impact on the incentives of the group selection protocol. 

=== DKG

==== Rewards

R~DKG_SUBMITTER~::

The member submitting the finally accepted result is paid a submission reward.
The distributed key generation has no rewards for non-submitting members. The
prospect of future rewards from signing beacon outputs provides the incentive to
participate in the DKG.

==== Punishments

D~DKG_MISSED_SUBMISSION~::

Minor
+
The DKG expects the first member _P~1~_ of the candidate group _P_ to submit
the result. If the finally accepted result is submitted by _P~i~, i > 1_, each
_P~1~ .. P~i-1~_ are penalized by D~DKG_MISSED_SUBMISSION~.

D~DKG_DQ~::

Minor
+
As the DKG is performed off-chain, only a list of disqualified participants is
produced. Thus all actual misbehavior necessarily has the same penalty. A member
on the list of disqualified members will be penalized by D~DKG_DQ~.
+
*TODO: minor penalty?*
+
The penalty is minor despite reflecting potentially severe protocol violations
because the misbehavior was not proven on-chain. A colluding cartel that
controls the created group can forcibly disqualify even well-behaved members.

=== Signing 

When publishing beacon outputs on-chain, there are two possible outcomes for an
output:

- if the output fails the BLS signature check, punish the submitter
- if the output passes the check, reward submitter and other members

==== Variable stakes and rewards

To incentivize paying more for the beacon outputs, siging rewards and penalties
are adjusted by _RequestMultiplier~i~_ whose value depends on how much has been
paid for _V~i~_.

_RequestMultiplier~MAX~_ is the highest value _RequestMultiplier_ can take.

Penalties are limited by the value +
_Stake~REQUEST_BASE~ = Stake~MIN~ / RequestMultiplier~MAX~_ +
so that the highest penalty at the highest request value multiplier is equal to
the maximum penalty of _Stake~MIN~_.

==== Rewards

R~submitter~(T), R~group~(T)::

The submitter and group reward will vary over time, where _T_ is the time it
takes to publish the valid output on-chain (_T' > T_):
+
_R~submitter~(T) > R~group~(T)_
+
The submitter is always rewarded more than the other members. This is partially
to cover the gas fees of submitting the beacon output (expensive BLS
verification), and partially to incentivize submissions.
+
_R~submitter~(T) <= R~submitter~(T')_ +
_R~group~(T) >= R~group~(T')_
+
Over time, the submitter reward grows while the group reward declines. If the
group takes long enough to submit the output, the group reward can go negative.
+
_R~total~(T) = R~submitter~(T) + (N - 1) * R~group~(T)_ +
_R~total~(T) >= R~total~(T')_
+
The total reward for the entire group (submitter + other members) declines over
time.
+
When _T <= T' <= T~output_expected~_: +
_R~submitter~(T) = R~submitter~(T')_ +
_R~group~(T) = R~group~(T')_ +
_R~total~(T) = R~total~(T')_
+
The maximum possible reward is given out when the output is submitted within
_1 <= T <= T~output_expected~_ from the reveal of the value to be signed. Within
this window there is no difference in rewards between different submission
times.
+
When _T' > T > T~output_expected~_: +
_R~submitter~(T) < R~submitter~(T')_ +
_R~group~(T) > R~group~(T')_ +
_R~total~(T) > R~total~(T')_
+
If _T > T~output_expected~_, the total reward is lower, the submitter reward
grows every block, and the group reward declines every block.
+
The value of _T~output_expected~_ may be set by the output request, or it may be
a global constant. If _T~output_expected~ = 1_ there is no constant-reward
window.
+
_R~selfish~(T, m) = R~submitter~(T) + (m - 1) * R~group~(T)_ + 
_R~selfish~(T, M~nofail~) > R~selfish~(T', M~nofail~)_
+
Because of the selfish signing attack, the submitter reward should not grow
faster than a moderate multiple of the group reward declines, to avoid creating
an incentive to delay output publication.
+
A hard limit for this is when _m = M~nofail~_. This is because it takes _H_
honest participants to produce an output, and the minimum number of active
participants in a group is _H + M~nofail~_ if _M~nofail~_ members have been lost
in DKG. If an actor controls less than _M~nofail~_ members in a group, there
should be enough other members that the output can be completed without the
adversary's input. This cannot be guaranteed when _m > M~nofail~_, and thus
selfish signing should always be unprofitable in such a case.
+
_R~group~(T~late~) = D~late_output~(T~late~)_ when _T~late~ > T~MAX_OUTPUT_DELAY~_
+
If the group takes particularly long to submit the output, the group reward can
go negative. In this case instead of rewarding the group members in _$CURRENCY_,
their stakes are slashed.

==== Punishments

D~INVALID_SIGNATURE~::

Major
+
If an invalid signature is submitted, its submitter is to be penalized by
_D~INVALID_SIGNATURE~ * RequestMultiplier_.
+
_D~INVALID_SIGNATURE~ <= Stake~REQUEST_BASE~_
+
The invalid signature penalty is limited by the base stake.

D~late_output~(T)::

Minor
+
_R~group~(T~late~) = D~late_output~(T~late~)_ when _T~late~ > T~MAX_OUTPUT_DELAY~_
+
If the group takes particularly long to submit the output, the group reward can
go negative. In this case instead of rewarding the group members in _$CURRENCY_,
their stakes are slashed. Additionally, the unreliable group is terminated.
+
_D~late_output~(T) < D~late_output~(T')_
+
To ensure an incentive to submit a late output remains, the penalty should grow
over time.
+
_D~late_output~(T~OUTPUT_FAILURE~) = Stake~REQUEST_BASE~_
+
If the output is not submitted within _T~OUTPUT_FAILURE~_, every member in the
group is penalized by _Stake~REQUEST_BASE~ * RequestMultiplier_.

==== Anchored rewards

It may be desirable to let members prove that a late submission is not their
fault. A member wishing to anchor their reward would publish the beacon input
signed by their individual private key, which can be verified by providing the
corresponding individual public key and the merkle path to the merkle root of
all individual public keys.

If the signature share submitted at _T_ is valid, the member _P~j~_ would be
rewarded _R~group~(T) * RequestMultiplier_. _P~j~_ would effectively pay the
price of the BLS verification to gain immunity from late submission penalties.

If the signature share is invalid, _P~j~_ would be penalized
_D~INVALID_SIGNATURE~ * RequestMultiplier_.

If a reward has been anchored at _T_ and the full output is submitted at _T'_,
the submitter reward should be adjusted by the anchoring:

_R~submitter~(T') = (R~submitter~(T) * (1 / N)) + (R~submitter~(T') * (N - 1) / N)_

If multiple rewards have been anchored at _T~1~, T~2~..._ the submitter reward
should be correspondingly:

_R~submitter~(T') = (R~submitter~(T~1~) / N) + (R~submitter~(T~2~) / N) + (R~submitter~(T') * (N - 2) / N)_

If the submitter reward is not adjusted, it would be possible to extract more
than the amount available for the rewards.

Anchoring rewards requires publishing and storing the merkle root of individual
public keys from DKG.

==== Leftover rewards

Because the beacon operation rewards decline over time, the maximum total reward
may not be paid out. In this case there will be leftovers.

_R~max~ = R~total~(T~output_expected~)_ +
_R~leftover~(T) = R~max~ - R~total~(T)_

If _R~leftover~(T) > 0_, the surplus needs to be allocated somehow.

Leftover pool::

One possibility is to establish a _leftover pool_ and use the pool to subsidize
later outputs by an amount determined by the currency balance in the pool:

_Bid'~i~ = Bid~i~ + R~leftover_subsidy~(PoolBalance~i~, Bid~i~)_ +
_PoolBalance~i+1~ = PoolBalance~i~ - R~leftover_subsidy~(PoolBalance~i~, Bid~i~)_

Leftover refund::

Another possibility is to refund the leftovers to the requester. This could be
desirable as compensation for slowness of output, but if a large number of
customers contributed to the request payment it may be inconvenient to refund
them all proportionally.

=== General

Some rewards and punishments don't fit into a specific category.

==== Individual private key compromise

If a private key is exposed or used inappropriately, the consequences to the
network could be serious. If the owner of a compromised key is punished for the
failure to secure it adequately, it can improve the incentives and weed out
insecure participants.

D~KEY_COMPROMISED~::

Major punishment
+
If the individual private key of _P~i~_ is compromised or used to sign an
inappropriate value _v_, _P~i~_ should be given the major punishment of
_D~KEY_COMPROMISED~_.
+
Compromise of an individual private key can be proven by submitting a message
signed with the key, along with the corresponding public key and its merkle path
to the root of the individual public key merkle tree, published in DKG result.

R~KEY_COMPROMISE_TATTLETALE~::

Reward
+
An operator who submits proof of an individual private key compromise should be
rewarded by _R~KEY_COMPROMISE_TATTLETALE~_ tokens.
+
_R~KEY_COMPROMISE_TATTLETALE~ < D~KEY_COMPROMISED~_

==== Group private key compromise

If the private group key of any group is compromised, beacon security can be
violated for outputs assigned to that group. Detection and termination of such
groups should be incentivized.

D~GROUP_KEY_COMPROMISED~::

Minor punishment
+
If the group private key of _G~i~_ is used to sign an inappropriate value _v_,
every member in _G~i~_ can be punished by _D~GROUP_KEY_COMPROMISED~_. A group
whose key has been compromised must be terminated.
+
Because signing an invalid value requires contribution from at least _H_
members, the existence of such a signature proves that the honest majority
assumption has not held. However, because participants disqualified in DKG
phase 9 have their secret information exposed, it is possible for an adversary
controlling _M~nofail~ + 1_ members in the group to create such a signature if
_M~nofail~_ members were disqualified in phase 9. This should be a rare
occurrence but provides a slight control bootstrapping attack for a sufficiently
powerful adversary.

R~GROUP_KEY_COMPROMISE_TATTLETALE~::

Reward
+
An operator who submits proof of an individual private key compromise should be
rewarded by _R~GROUP_KEY_COMPROMISE_TATTLETALE~_ tokens.
+
_R~GROUP_KEY_COMPROMISE_TATTLETALE~ << M~nofail~ * D~GROUP_KEY_COMPROMISED~_
+
The magnitude of the group key compromise tattletale reward has a significant
impact on the viability of the control bootstrapping attack for deliberately
compromising the group key.

== Extra notes

=== Tattletale ratio

The operator can still transfer tokens by abusing the tattletale mechanisms.
However, the efficiency of this is limited by the
`tattletale_fraction = tattletale_reward / misbehavior_penalty`
ratio of the best available exploit.

This seems impossible to mitigate because if the operator is paid
`operator_reward = operator_fraction * expected_value_multiplier * total_stake`
and thus the opportunity cost of stealing
`tattletale_fraction * total_stake`
is negative only when
`operator_fraction * expected_value_multiplier > tattletale_fraction`.
However, in this case it becomes profitable to bribe a potential tattletale
simply with the earnings one will get in the future from the tokens that would
be slashed if the tattletale would do their job, and only the presence of a
sufficient number of non-coordinating potential tattletales keeps this from
being an easy way out.
