:toc: macro
:toclevels: 4
:yellowpaper:

= The Keep Random Beacon: An Implementation of a Threshold Relay

toc::[]

[abstract]
.Abstract
--
The Keep Network requires a trusted source of randomness for the process of
trustless group election. While the network requires that randomness to function
correctly, the source of randomness is itself broadly applicable. This trusted
source of randomness takes the form of a BLS Threshold Relay. We discuss
implementation of this random beacon, including assumptions and mitigations for
bad actors and poor network connectivity.
--

== Overview

The threshold relay described herein is a way of generating verifiable
randomness that is resistant to bad actors both in the relay network and on the
anchoring blockchain, assumed here to be Ethereum. The basic functioning of the
relay (further details are in the section on <<System Details>>) is:

* Some number of groups exist in the relay.
* An arbitrary seed value _v~s~_ counts as the first entry in the relay.footnote:[The
  importance, from a security perspective, of the seed value goes away almost
  immediately in a functioning network.]
* A request _r~i~_ is dispatched to the chain for a new entry.
* The previous entry _v~s~_ is used
to choose a group to produce the response to the request.
* _v~s~_ is signed by at least a subset of the chosen group members, and the
  resulting signature is the entry generated in response to the request. It is
  published to the anchoring blockchain as the entry _v~i~_.
* The new entry _v~i~_ may trigger the formation of a new group from the set of
  all members in the relay.
* A group expires after a certain amount of time.

The following sections will detail how this basic function is implemented in
practice, including notes on <<Prior Work>> that motivated this design,
the <<Incentive Structures>> used to economically incentivize good behavior by
network participants, <<Core Technologies>> used in the network, and finally the
<<System Details>> that outline the implementation itself. <<Upgrade Management>>
is also discussed.

== Prior Work

Dfinity has described their implementation of a random beacon backed by a
threshold relay in their consensus whitepaper
footnote:[https://dfinity.org/pdf-viewer/library/dfinity-consensus.pdf]. The
relay described in this paper is heavily based on the one devised by the Dfinity
team, with certain adjustments for implementation on an existing blockchain. The
key distinction between the Dfinity implementation and the Keep implementation
is that Keep has to contend with blockchains that do not implement the same
primitives as the in-house Dfinity chain targeted in their paper. Concerns such
as transaction costs and payment for beacon entries are therefore a core part of
the incentive system built around the Keep random beacon.

As described in the above paper, at the heart of the relay beacon is the
signature scheme described by Dan Boneh, Ben Lynn, and Hovav Shacham in
footnote:[D. Boneh, B. Lynn and H. Shacham, “Short signatures from the Weil
pairing”, Advances in Cryptology – ASIACRYPT 2001, Lecture Notes in Computer
Science, 2248 (2001), 514–532. Full version: Journal of Cryptology, 17 (2004),
297–319.], termed BLS. Three properties of the scheme are of particular use in
this case: BLS signatures can be used in _threshold_ mode, where _k_ of _n_
participants are sufficient to produce a combined signature; BLS threshold
signatures produce the same final signature irrespective of the participants;
and BLS signatures are typically shorter than those of many other threshold
signature schemes.

Finally, underpinning the process of generating new groups for BLS threshold
signatures in the system is a distributed key generation algorithm based on work
by Gennaro, Jarecki, Krawczyk, and Rabin footnote:[R. Gennaro, S. Jarecki, H.
Krawczyk, and T. Rabin. Advances in Cryptology — EUROCRYPT ’99: International
Conference on the Theory and Application of Cryptographic Techniques Prague,
Czech Republic, May 2–6, 1999 Proceedings, chapter Secure Distributed Key
Generation for Discrete-Log Based Cryptosystems, pages 295–310. Springer Berlin
Heidelberg, Berlin, Heidelberg, 1999 ;
http://groups.csail.mit.edu/cis/pubs/stasio/vss.ps.gz], as also described in the
Dfinity paper above. The Keep Random Beacon publishes group public keys to the
anchoring blockchain and does member selection on-chain, but key generation
occurs between nodes with only the final result vote occurring on-chain.

== Incentive Structure

The system generates verifiable random numbers using threshold signatures.
BLS threshold signatures are deterministic,
so a given signing group can only produce one valid signature
for any given input.
A party that knows the private key of a signing group
can calculate signatures in advance,
and generated entries can be influenced
by preventing the selected group from producing a signature
and thus forcing the beacon to select a different group.

To incentivize participants,
every member of a group that produces a valid entry is rewarded.
Participants that perform costly but necessary actions
are reimbursed for the costs and further rewarded.

Each participant is required to _stake_ a number of tokens
that are held as collateral against misbehavior.
Participants staking a greater number of tokens
have a correspondingly greater opportunity to earn rewards.
In the event that a group fails to produce a signature when requested
or its private key is provably abused,
each member of the group is punished by _slashing_ their stake;
taking away some or all of their staked tokens.

In some cases,
misbehavior is proven with the help of a third party _"tattletale"_
who notifies the beacon of the misbehavior,
and if necessary, provides the required proof.
If the misbehavior occurred as claimed,
the tattletale is rewarded with a fraction of the slashed tokens.

== System Details

The system has two high-level modes of operation, discussed in detail in their
individual sections:

* Group formation, consisting of group member selection and distributed key
  generation.
* Threshold signing, triggered by a beacon request and producing a new entry in
  the relay (which in turn also triggers the formation of a new group). signing
  also involves selecting the appropriate price for a new relay entry.

Additionally, the beacon makes money by charging for _beacon requests_. An early
draft of the pricing mechanism is described in its own section.

=== Group formation

include::group-selection/index.adoc[leveloffset=+3]

include::dkg/index.adoc[leveloffset=+3]

include::signing/index.adoc[leveloffset=+2]

include::pricing.adoc[leveloffset=+2]

include::staking/index.adoc[leveloffset=+2]

include::slashing.adoc[leveloffset=+2]

== Upgrade management

The system has been designed to facilitate upgrades
without exposing stakers to vulnerabilities
commonly found in upgradeable smart contracts.
For this purpose,
smart contracts in the system are divided into different categories
based on their purpose and functionality,
and strict security boundaries are maintained in the design.

Furthermore, the authority to take various actions in the system
has been divided into a number of roles
where each role has a specific purpose and domain.
The roles and their authorizations are designed
to limit the impact of single key compromise.
Severely harmful actions such as stealing participants' stakes
should require the compromise of multiple independent actors
wherever feasible.

include::contract-structure.adoc[leveloffset=+2]

include::authorizations.adoc[leveloffset=+2]

include::upgrades.adoc[leveloffset=+2]

include::glossary.adoc[]
