:toc: macro
:toclevels: 4

= Misbehavior and punishments

ifndef::yellowpaper[toc::[]]

To incentivize correct behavior in the Keep network,
misbehaving participants will be punished.
In some situations,
proving misbehavior requires cooperation from another participant,
a _tattletale_.
This coordination is incentivized by rewarding the _tattletale_
by granting them a fraction of the tokens
taken from the misbehaving participant.

== Authorization

_Operator contracts_ are authorized to impose penalties
by stakers' _authorizers_.
All stakers using the same _authorizer_
share the set of authorized operator contracts.
Once given, this authorization cannot be revoked by the authorizer.

When an operator wishes to join a signing group
the operator contract creating the group
must be authorized by the operator's authorizer.
Authorization is checked when an operator submits a ticket for validation.
The operator contract queries the staking contract
for the amount of stake available for it.
If the operator contract is not authorized
or the operator is otherwise ineligible for work selection,
the staking contract will return that the operator has no available stake,
leading to any submitted tickets being rejected.

== Penalties

When an operator's misbehavior is proven on-chain
the operator contract calls the staking contract to punish the operator,
specifying the type and magnitude of the punishment.
The staking contract checks
that the operator contract is authorized to punish the operator,
and if true, applies the penalty according to its own rules.

A penalty can be applied to one or more operators simultaneously.
Each affected operator is penalized in the same way by the same amount.
If the same address is listed multiple times
among the operators to be punished,
the punishment will be applied multiple times.

=== Pure slashing

When misbehavior is detected without third-party input,
a _pure slashing_ penalty is applied.
Pure slashing means that the staking contract
subtracts the applicable penalty from the operator's stake
and burns tokens equal to the penalty amount.
If the operator doesn't have enough stake for the punishment
(e.g. because it has been punished earlier),
the punishment is equal to the remaining stake.

=== Seizing

When a tattletale proves another operator's misbehavior,
a fraction of the penalty amount is _seized_ and transferred to the tattletale,
while the rest is burned.

If the full amount is transferred to the tattletale,
it can be exploited to transfer staked tokens
without the normal constraints.
To reduce the effectiveness of this "tattletale transfer",
the seized amount is limited to a maximum of 5% of the entire penalty.
The tattletale reward can be set to any value
between 0 and the maximum of 5% of the penalty.

To apply a seizing penalty,
the operator contract includes the tattletale operator's address in the call.
The staking contract subtracts the applicable penalty from the operator's stake
and transfers the reward to the tattletale's _beneficiary_ address.
The remainder is burned.

=== Penalty amounts

In later versions,
penalties for misbehavior can be adjusted
to match the severity of the misbehavior.
However, initially the penalty for misbehaving in the random beacon
will equal the minimum stake required to join a signing group.

== Interfaces

=== Staking contract: slashing

`slash(tokens amount, address[] misbehavers)`::

Slash each operator in the list `misbehavers`
by the specified amount
(or their remaining stake, whichever is lower).
+
For each `misbehaver` in `misbehavers`,
perform the following:
+
. Check that the caller is authorized to slash the operator:
`isAuthorized(msg.sender, misbehaver.authorizer) == true`.
. Determine the applicable punishment for the operator:
`thisPenalty = min(amount, misbehaver.stake)`.
. Subtract the punishment from the operator's stake
and add it to the total to be burned:
`misbehaver.stake -= thisPenalty; totalPenalty += thisPenalty`.
+
Finally, burn an amount of tokens equal to the slashed total:
`tokenContract.burn(totalPenalty)`.

`seize(tokens amount, float rewardMultiplier, address tattletale, address[] misbehavers)`::

Punish each operator in the list `misbehavers`
by the specified amount or their remaining stake.
Reward the `tattletale` by an amount between 0 and the maximum reward,
determined by the `rewardMultiplier` argument:
if `rewardMultiplier` is greater than `0` and at most `1`,
multiply the highest allowed tattletale reward by `rewardMultiplier`.
Otherwise reject the call for an invalid reward multiplier.
+
For each `misbehaver` in `misbehavers`,
calculate and apply the appropriate penalty
and track the total as in `slash()`.
+
Finally, determine the tattletale reward:
`reward = totalPenalty * 0.05 * rewardMultiplier`.
Transfer the reward to the tattletale's _Beneficiary_
and burn the rest of the penalty:
`tokenContract.burn(totalPenalty - reward)`.

=== Staking contract: authorizations

`authorize(address op_contract)`::

Authorize `op_contract`.
Operators using `msg.sender` as their authorizer
may now join operations on `op_contract`
and `op_contract` may slash their stakes.

`isAuthorized(address op_contract, address authorizer) -> bool`::

Check if the authorizer `authorizer` has authorized `op_contract`
to apply punishments on operators using `authorizer` as their authorizer.

`eligibleStake(address operator) -> uint`::

Return the number of staked tokens available for the calling contract.
Includes an authorization check `isAuthorized(msg.sender, operator.authorizer)`
and other checks on the operator's eligibility for work selection.

=== Token contract

`burn(amount sum)`::

Any address that holds tokens can call `burn(amount sum)`
to burn `sum` tokens, limited by tokens held by the address.

== Punishable misbehavior

=== Failure to sign an entry

If a signing group is tasked with producing a beacon entry,
but fails to submit a valid entry within the allotted deadline,
each member in the group is punished by _seizing_
and the group itself will be terminated.

The punishment is triggered by calling `reportRelayEntryTimeout()`
once the deadline has been reached.
The submitter of the trigger transaction will be treated as the _tattletale_,
but the tattletale reward will be limited
to `min(1, 20 / group_size)` of the maximum,
or effectively the minimum stake of a single member.
This is to prevent actors in a lynchpin position
from profitably stealing other stakers' funds.

=== Unauthorized use of group signing key

If the group signing key of a signing group has been leaked,
it can be proven by using the key to sign the address of the group
and calling `reportUnauthorizedSigning()`.

If the signature is valid for the public key of the signing group,
it proves that the key has been used without authorization.
Each member of the signing group is punished by _seizing_
and the group is terminated.
The submitter of the trigger transaction
receives the maximum tattletale reward.

////
=== Disqualification in DKG

If an operator misbehaves during DKG,
and is included among the disqualified operators
when a valid DKG result is submitted,
the misbehaving operator is punished by _seizing_
and removed from the created group.
The submitter of the DKG result
receives the maximum tattletale reward.

It should be noted that a dishonest majority could punish honest operators.
However, such behavior can be proven off-chain
by presenting a DKG transcript conflicting with the accepted result.
////
