:toc: macro

= Terms

ifndef::yellowpaper[toc::[]]

== Conventions

=== Basic conventions

[horizontal]
Term~context~::
Globally meaningful terms are capitalized, and usually include subscripts.
_Term_ specifies the broader type, such as _Stake_, and the subscript _context_
is used to specify the particular purpose and/or usage of this value.
+
Terms are formatted as _CamelCase~snake_case~_.

T~context~::
Shorthand symbol for commonly used terms. The meaning can be memorized or
looked up from the shorthand symbol table, as a specific letter always
corresponds to a specific term.

Term~GLOBAL_CONSTANT~::
Hardcoded global constants have their subscript in capitals following the
common programming convention.

C::
A particularly significant global constant can be expressed as a single capital
letter. Where this letter corresponds to a shorthand symbol, the constant _C_ is
of the same type as terms _C~context~_, and could alternatively be expressed as
_C~IMPORTANT_CONSTANT~_.

Function~context~(input)::
The value depends on _input_. _Function_ can be (and usually is) a term that is
normally used as a plain value: eg. _R~submitter~(T)_ means that the submitter
reward varies depending on time

variable~context~::
A local value that is only used briefly, or may even be altogether unknown to
uninvolved participants.

=== Shorthand symbols

Some meanings are used so often that it is useful to have single-letter terms
for them. Each shorthand symbol maps to a specific longhand term.

TODO: Shorthands and terms have been matched to ensure each term maps to its
initial wherever possible. The exception is _Penalty_ and _D_ (with
_disciplinary action_ as a mnemonic); alternatives or abolishing this shorthand
should be considered.

[horizontal]
V~i~::
Value~i~
+
The __i__-th output of the random beacon

N~ctx~::
Number~ctx~
+
A number of operators or group members

M~ctx~::
Malicious~ctx~
+
A number of malicious operators or group members

G~ctx~::
Group~ctx~
+
Some specific group

S~ctx~::
Staker~ctx~
+
Some specific staker

P~ctx~::
Participant~ctx~
+
A participant in some group

T~ctx~::
Time~ctx~
+
A block number used as an unambiguous measure of time

R~ctx~::
Reward~ctx~
+
A reward for correct operation; tokens or currency

D~ctx~::
Penalty~ctx~
+
A punishment for misbehavior (mnemonic: _disciplinary_ action); always tokens

=== Common long-form terms

Longhand terms should be self-explanatory wherever possible, and are explained
locally where they are used. The meanings of some term types that are used
regularly but don't have a specific shorthand are listed below.

[horizontal]
Stake~ctx~::
Some amount of tokens used for staking

Prob~ctx~::
The probability of some event

== Specific terms

=== Globally significant values

==== Global security parameters

[horizontal]
N::
H + M = 2M + 1 = 4M~nofail~ + 1
+
Number of participants in a group

H::
M + 1 = (N - 1)/2 + 1
+
Minimum number of honest participants in a group

M::
H - 1 = (N - 1)/2
+
Maximum number of malicious participants in a group beyond which security
guarantees don't hold

M~nofail~::
M/2 = (N - 1)/4
+
Maximum number of disqualified participants in a group beyond which DKG will
abort to preserve security

:leveloffset: +1

include::alt_bn128.adoc[]

:leveloffset: +1

include::group-selection/terms.adoc[]

include::dkg/terms.adoc[]

include::signing/terms.adoc[]

include::group-expiration/terms.adoc[]
