= Upgrade processes

== Operator contract upgrade

Operator contracts are immutable,
and are upgraded by deploying a new version in a separate contract.
The _Registry Keeper_ then approves the new contract on the _registry_,
and operators are able to authorize it.
Once authorized by a sufficient number of stakers,
the contract can be added into the used operator contracts
of a service contract.

Operator contracts can be upgraded without losing service contract state,
but critical state is held within the operator contract and cannot be migrated.

. Deploy the new operator contract
. Approve the operator contract on the registry
. Wait for stakers to authorize the operator contract
. Activate the operator contract on the relevant service contract/s

== Service contract upgrade

Because service contracts don't impact the security of staked tokens,
they can be upgraded in-place without migrating to a new address.

== New service contract

A new service contract is deployed on-chain and listed on the _registry_.

If the service contract doesn't rely on
an operator contract exclusive to itself,
it can be deployed after the operator contracts it uses are in place.

Otherwise the service contract must be deployed first,
inactive because it has no operator contracts it uses.
Once the address of the service contract is determined,
the operator contract is deployed,
approved on the registry,
and authorized by stakers.
The operator contract can now be activated on the service contract,
making it ready to provide services.

. Deploy the new service contract
. Deploy a new operator contract serving the new service contract
. Approve the operator contract on the registry
. Wait for stakers to authorize the operator contract
. Activate the operator contract on the service contract

== Staking contract upgrades

Staking contracts can be upgraded by deploying a new version,
and waiting for stakers to migrate
by withdrawing their stakes on the old contract
and staking them again on the new contract.
While stakers are migrating,
new operator contracts using the new staking contract should be deployed.
Once stakers have migrated and approved the new operator contracts,
the contracts can be activated on service contracts.

. Deploy the new staking contract
. Deploy new operator contracts recognizing the new staking contract
. Approve the operator contracts on the registry
. Wait for stakers to migrate to the new staking contract
. Wait for stakers to authorize the new operator contracts
. Activate the operator contracts on the service contracts

== Token upgrade

The upgrade process makes it possible to even hard-fork the token
without disrupting service contract user experience:

. Deploy the new token contract
. Deploy a migration contract
that lets holders convert old tokens to new tokens
. Deploy a new staking contract for the new tokens
. Deploy new operator contracts recognizing the new token and staking contract
. Approve the operator contracts on the registry
. Wait for stakers to convert their tokens,
stake on the new contract
and authorize the new operator contracts
. Activate the operator contracts on the service contracts
