bases:
  - ../../templates/tbtc-v2-monitoring

images:
  - name: tbtc-v2-monitoring
    newName: gcr.io/keep-test-f3e0/tbtc-v2-monitoring
    newTag: latest

configMapGenerator:
  - name: tbtc-v2-monitoring-config
    literals:
      - environment=testnet
      - large-deposit-threshold-sat=10000000 # 0.1 BTC for testing purposes

secretGenerator:
  - name: tbtc-v2-monitoring-config
    envs:
      - .env.secret

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: generated

