#@data/values-schema
---
clients:
  - id: 0
    #@schema/nullable
    networkPeers: ""
    #@schema/nullable
    publicAnnouncedAddress: ""
    #@schema/nullable
    staticIP: ""
    stakeAmount: 800_000
initContainers:
  - name: ""
    image: ""
