{
 "title": "Keep Nodes",
 "tags": [
  "tbtc",
  "keep"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Nodes Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (sum by(chain_address) (up{job=\"keep-discovered-nodes\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Bootstraps",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min by(chain_address) (connected_bootstrap_count{job=\"keep-discovered-nodes\"})",
     "legendFormat": "{{chain_address}}"
    }
   ]
  },
  {
   "title": "TBTC PreParams Count",
   "type": "timeseries",
   "gridPos": { "h": 28, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "min by(chain_address) (tbtc_pre_params_count{job=\"keep-discovered-nodes\"})",
     "legendFormat": "{{chain_address}}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 13, "x": 11, "y": 16 },
   "targets": [
    {
     "expr": "min by(chain_address) (connected_peers_count{job=\"keep-discovered-nodes\"})",
     "legendFormat": "{{chain_address}}"
    }
   ]
  },
  {
   "title": "Client Versions",
   "type": "table",
   "gridPos": { "h": 25, "w": 11, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "up{job=\"keep-discovered-nodes\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "client_info{job=\"keep-discovered-nodes\"}"
    }
   ]
  },
  {
   "title": "BTC Connectivity",
   "type": "timeseries",
   "description": "Provides information on whether the node is connected to the Bitcoin network",
   "gridPos": { "h": 20, "w": 13, "x": 11, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "min by(chain_address) (btc_connectivity{job=\"keep-discovered-nodes\"})",
     "legendFormat": "{{chain_address}}"
    }
   ]
  },
  {
   "title": "ETH Connectivity",
   "type": "timeseries",
   "description": "Provides information on whether the node is connected to the Ethereum network",
   "gridPos": { "h": 20, "w": 13, "x": 11, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "min by(chain_address) (eth_connectivity{job=\"keep-discovered-nodes\"})",
     "legendFormat": "{{chain_address}}"
    }
   ]
  },
  {
   "title": "Node Instances",
   "type": "state-timeline",
   "description": "A number of running instances for each operator address.",
   "gridPos": { "h": 20, "w": 11, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "count by(chain_address) (up{job=\"keep-discovered-nodes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime (experimental)",
   "type": "state-timeline",
   "gridPos": { "h": 25, "w": 13, "x": 11, "y": 76 },
   "targets": [
    {
     "expr": "min by(chain_address) (up{job=\"keep-discovered-nodes\"})",
     "legendFormat": "{{chain_address}}"
    }
   ]
  }
 ]
}