= Staking

The Keep network uses staking of tokens to enforce correct behavior.

== Basic description

Anyone with tokens can stake them,
setting them aside as collateral for network operations.
Staked tokens are delegated to an _operator_ address
who performs work for _operator contracts_.
_Operators_ can earn rewards from contributing to the network,
but if they misbehave their collateral can be taken away
(_stake slashing_) as punishment.

=== Stakers and roles

A token owner may wish to stake in a variety of different ways,
for security or efficiency reasons.
To support different ways of staking,
the network uses a single abstraction of a _staker_
comprised of multiple separate _roles_:

owner::
Provides the tokens for the staker

operator::
Handles the day-to-day participation in the network operations

beneficiary::
Collects any rewards earned by the staker

authorizer::
Authorizes contracts to protect against buggy or compromised upgrades

The different roles can all be performed by the same address;
they may be divided between different addresses controlled by the same person;
or they may be different parties entirely,
executing a sophisticated scheme of cold storage and third-party delegation.
As far as the network is concerned,
any of these arrangements simply forms a _staker_.

staker::
An abstraction representing the _owner_, _operator_, _beneficiary_ and _authorizer_
each performing their respective roles.

Stakers are identified by their operator address.

=== Initiating staking

Staking is initiated by the _owner_ choosing the amount of tokens to stake,
and the _operator_, _beneficiary_ and _authorizer_ addresses.
The owner then authorizes the _staking contract_ to claim a number of tokens,
and calls the staking contract to stake the tokens.
The _staking contract_ processes the call,
claims the tokens to itself,
and records the information.
The addresses of the roles cannot be changed after delegation.

=== Contract authorization

Before the staker can participate in the network,
the _authorizer_ must _authorize_ each _operator contract_
the staker wishes to use.
It is necessary to introduce new functionality and to upgrade old contracts,
but buggy or malicious _operator contracts_ could be used
to steal or destroy tokens by _slashing_ well-behaved stakers.
The requirement for _authorization_ ensures that the owner's tokens are safe
even if a contract upgrade is compromised,
as long as the _authorizer_ denies authorization to such contracts.

Once a contract has been authorized,
the authorization cannot be revoked.

=== Operation

The _operator_ provides _services_ in the network
by following the protocols of authorized _operator contracts_.

Any number of operations may be active at once
regardless of the _staked amount_.

==== Rewards

Stakers that provide services in the network
will be rewarded at certain points.
Rewards may be either tokens or the currency used to pay for network services.
Rewards earned by a staker will be sent to the staker's _beneficiary_ address.

=== Slashing

If a staker violates the protocol of an operation
in a way which can be proven on-chain,
they will be penalized by having their stakes _slashed_.

If a staker has joined multiple operations at once,
they may accrue more punishments than their stake can cover.
If a staker's remaining stake falls to zero,
the staker is terminated and may not continue any operations.
Any remaining penalties are nullified.

==== Tattletales

Some misbehavior cannot be caught by a contract alone
and requires the cooperation of a third party _tattletale_.
If a _tattletale_ presents proof of misbehavior by a staker,
a part of the penalty will be awarded to the tattletale
as a _tattletale reward_.

=== Unstaking

When staking, the tokens used as collateral are locked
until the staker announces their intention to stop staking,
and for a period of time afterwards.
The purpose of this _unstaking period_ is to give operations time to finish
before the collateral can be moved away.
No new operations can be started or joined within the _unstaking period_
but the staker is required to continue participating
in any unfinished operations.

== Details

=== Roles

The staker is an abstraction comprising of four different roles,
each with a clear scope of responsibility.
The initial design included only the roles of the owner, operator and beneficiary;
the authorizer was added to take full advantage of the upgrade security plan.

==== Owner

The owner makes the decision to stake,
provides the tokens for the staker,
and chooses the addresses for the other roles.
The owner can initiate unstaking and reclaim tokens,
but these can also be performed by the operator.

The role of the owner is designed to facilitate cold storage
by minimizing the interaction necessary for staking.
Initiating staking is the only operation
where the owner's keys are absolutely required.

==== Operator

The operator address is tasked with participation in network operations,
and represents the staker in most circumstances.

Rewards and punishments are based solely on the operator's actions,
and the operator can not only cause opportunity costs
but can also lose the entire stake and possibly steal a fraction of it
using only contracts functioning as intended.
If the operator is a different party from the owner,
a high level of trust is necessary.

In addition to participating in the network
via the authorized operator contracts,
the operator can also initiate undelegation.

==== Beneficiary

The beneficiary is an entirely passive role.
Rewards of tokens or currency are simply sent to the beneficiary address
by the staking contract.

The beneficiary role is separate from the owner and operator
to provide flexibility in how to receive and use rewards
without interfering with the owner's cold storage
or the possible contractual relationship between the owner and operator.

==== Authorizer

Because slashing stakes requires arbitrary access to stakers' accounts,
explicit authorization is required
for each operator contract before it may penalize stakers.

The upgrade security plan is designed
to limit the impact of upgrade key compromise
and to provide a graceful recovery route
while minimizing the impact to the rest of the network.
The explicit authorization requirement prevents a compromised contract
from stealing stakers' funds by exploiting the punishment interface.
Instead, compromise of both the authorizer and the contract is required.

As a further security measure,
the authorizer can only authorize pre-approved contracts
from a list maintained by the governance structure of the network.
This ensures that the authorizer cannot do damage
in the absence of further compromise,
except by withholding desired authorizations.

The authorizer role is separated from the owner and operator
to facilitate cold storage for the former
and to reduce the necessary privileges of the latter.

If the owner were required to authorize each new contract and upgrade,
it would present an unnecessary hindrance to effective cold storage schemes.
Due to the two-factor nature of the authorizer keys,
the same level of protection is not necessarily required.

On the other hand, separating the authorizer from the operator
reduces the latter's ability to profit from damaging the owner's interests.
While even the operator has the ability
to lose or steal the owner's tokens,
it is restricted by the opportunities provided by the authorized contracts.
Using the tattletale mechanism to transfer tokens is inefficient,
but a compromised contract would not be subject to the same restrictions
and could be used to transfer all of the staker's tokens to the attacker.

===== Third party delegation

The role of the authorizer can be delegated to a third party,
and it is expected that many would do so.

Most owners and operators are unlikely to scrutinize each contract,
or even to have the ability to do so effectively.
Providing a convenient way to express one's choice to trust a third party
would make centralization of such trust visible.

A downside of convenient delegation is that requiring individual authorizations
provides another source of friction and human judgment
between compromise of single points of failure and actual loss of staker funds.
An owner can avoid this fate
by not assigning a third party as the authorizer address.

=== Staking contract

The staking contract records two time (blockheight) fields for each operator:
the block the operator was created,
and the block undelegating began.

Operators can be:

- _non-existent_
- _not ready_ for work selection because they were created too recently
- _active_ and eligible for work selection
- _winding down_ and ineligible for work selection but finishing earlier work
- _finished_ undelegation so the owner can recover their tokens

Using the systemwide constant _undelegation period_,
the operator's _status_ can be determined
from the creation and undelegation blocks.

Operators are uniquely identified by their address
and operator addresses cannot be reused,
even after returning the tokens to the owner.

To reduce the impact of transaction reordering,
both delegating and undelegating take effect on the next block
after the block the transaction is processed in.

==== Parameters

===== Operator initialization period

E.g. 50,000 (roughly 6 days)

To avoid certain attacks on work selection,
recently created operators must wait for a specific period of time
before being eligible for work selection.
This waiting period must be greater than the highest permissible time
between the making of a beacon entry request
and the request being served.
In the ideal case, multiple entries would be requested and generated
within the initialization period.

If the initialization period is insufficiently long,
the pseudorandom work selection process can be subverted
by creating operators whose identifiers (addresses)
are calculated to yield advantageous outputs in the selection function.
This can let the adversary control the majority in the new signing group.

If the new group is in line to sign the next entry,
the adversary could choose the group's private key
so that the following entry also gets signed
by a group controlled by the same adversary.
With sufficient calculation capability,
this can be repeated _n_ times at the cost of roughly _O(k^n^)_ calculations
where _k_ equals the number of active groups
divided by the number of active adversary-controlled groups.
If another signing group is created within this time,
it can be similarly controlled.
This can eventually lead to the adversary controlling the entire network.

With the initialization period,
the adversary has to create the operators in advance
long before they become eligible for work selection.
Thus the adversary has to be able to predict each entry
generated during the initialization period.
With an unreasonably powerful adversary
that can arbitrarily frontrun 50% of all entries,
generating _n_ entries within the initialization period
provides _2^n^_ security against this attack.

===== Undelegation period

E.g. 200,000 ~ 800,000 (roughly 1 to 3 months)

The staking contract guarantees that an undelegated operator's stakes
will stay locked for a number of blocks after undelegation,
and thus available as collateral for any work the operator is engaged in.

==== Operator data

----
mapping(address => Operator) operators;

struct Operator {
  uint128 stakedAmount;
  uint64  createdAt;
  uint64  undelegatedAt;
  address owner;
  address beneficiary;
  address authorizer;
}
----

Each operator stores the addresses of its owner, beneficiary and authorizer,
the amount of tokens delegated to the operator,
the block it was created at,
and the block it was undelegated at if applicable.

==== Operator status

----
enum Status { NonExistent, NotReady, Active, WindingDown, Finished }

operatorStatus(address operator) -> Status
----

An operator's status determines what actions are available
for the operator and the owner the delegated tokens.

===== Non-existent

The operator doesn't exist.

`operators[operator] == nil`

===== Not ready

The operator has been created in the same block the query was performed in.
The operator is ineligible for work selection.

An operator is `NotReady`
if the current block is equal or less than
the creation block plus the initialization period.

`block.number =< operator.createdAt + initializationPeriod`

===== Active

The owner has delegated staked tokens to the operator,
and the operator is eligible for work selection.

An operator is `Active`
if the current block is greater than
the creation block plus initialization period,
and the undelegation block is either 0 or equal or greater than the current block.

`block.number > operator.createdAt + initializationPeriod && (block.number =< operator.undelegatedAt || operator.undelegatedAt == 0)`

===== Winding down

The operator has been undelegated and is not eligible for work selection,
and the operator is finishing any work they were selected for earlier.
The operator's backing tokens continue to be locked as collateral.

An operator is `WindingDown`
if the current block is greater than the undelegation block,
but at most the undelegation block plus the undelegation period.

`operator.undelegatedAt < block.number =< (operator.undelegatedAt + undelegationPeriod)` 

===== Finished

Undelegating the operator has finished.
The backing tokens are unlocked and can be returned to the owner.

An operator is `Finished` if the current block is greater than
the undelegation block plus the undelegation period.

`block.number > operator.undelegatedAt + undelegationPeriod`

==== Work selection eligibility

`eligibleStake(address operator, uint block) -> uint`

Operators are eligible for work selection
based on their status in the block the work selection started in.
In some situations an operator's status may have changed
after work selection started,
but before the operator contract queries it.
For these cases the staking contract must provide a way to determine
the operator's eligibility for work selection that started in an earlier block.

It is the responsibility of each operator contract
to query operator eligibility with the correct block number.
Failure to use the correct block leads to minor manipulation opportunities.
For example, querying an operator's eligibility
on the current block when they submit a ticket
means that an ineligible operator whose initialization period is almost over
could wait to submit their ticket
until they become eligible for work selection.

To make determining an operator's eligibility for work selection
simpler and cheaper,
the staking contract must provide the `eligibleStake()` function
which returns the number of KEEP tokens available for use as collateral.

When calling `eligibleStake()`,
the staking contract assumes `msg.sender` is an operator contract.
`eligibleStake()` does not return meaningful results
when called by an address that doesn't correspond to an operator contract.
If the `operator` is ineligible for work selection on `msg.sender`,
`eligibleStake()` returns `0`.
Otherwise `eligibleStake()` returns `operator.stakedAmount`.

----
operatorExists = operators[operator] != nil

senderAuthorized = authorized[operator.authorizer][msg.sender] == True

operatorReady = block > operator.createdAt + initializationPeriod

notUndelegated = block =< operator.undelegatedAt || operator.undelegatedAt == 0

if operatorExists && senderAuthorized && operatorReady && notUndelegated:
  return operator.stakedAmount
else:
  return 0
----

==== Actions

===== Staking

`stake(uint amount, address operator, address beneficiary, address authorizer)`

Staking tokens delegates them to the operator,
who can then use them as collateral for performing work.
Staking is performed by the owner of the tokens,
who must have authorized the staking contract
to transfer `amount` KEEP to itself
(e.g. via `approveAndCall()`).

`token.allowance(msg.sender, stakingContract) >= amount`

The nominated operator must not already exist.

`operators[operator] == nil`

The staking contract transfers `amount` KEEP from `msg.sender` to itself,
and creates a stake delegation relationship,
with the operator becoming `Active` in the next block.

----
operators[operator] = Operator {
  stakedAmount = amount;
  createdAt = block.number;
  undelegatedAt = 0;
  owner = msg.sender;
  beneficiary = beneficiary;
  authorizer = authorizer;
}
----

===== Cancelling staking

`cancelStake(address operator)`

The owner can cancel staking within the operator initialization period
without being subjected to the token lockup for the undelegation period.
This can be used to undo mistaken delegation to the wrong operator address.

`msg.sender == operator.owner`

`block.number =< operator.createdAt + initializationPeriod`

If staking is cancelled,
the staked tokens are immediately returned to the owner,
and the undelegation time is set to the present.

`operator.stakedAmount = 0`

`operator.undelegatedAt = block.number`

===== Undelegating

`undelegate(address operator)`

Undelegating sets the operator to `WindingDown` status
so that the backing tokens can later be recovered by the owner.
Undelegating can be performed by either the owner or the operator.

`msg.sender == (operator || operator.owner)`

Undelegating can only be performed on a currently active operator.

`operatorStatus(operator) == Active`

The staking contract sets the undelegation block of the operator
to equal the current block,
making the operator ineligible for any work selection in the future.
Work selection performed earlier in the same block shall proceed as normal.

`operator.undelegatedAt = block.number`

===== Recovering tokens

`recoverStake(address operator) -> uint`

Recovering staked tokens transfers them back to the owner.
Recovering tokens can only be performed by the owner,
when the operator is finished undelegating.

`msg.sender == operator.owner`

`operatorStatus(operator) == Finished`

The staking contract sets the staked amount of the operator to zero,
and transfers the previously delegated tokens (or however much was remaining)
back to the owner.

`operator.stakedAmount = 0`

The staking contract may additionally clean up
the owner, beneficiary and authorizer addresses for the gas refund.
However, the staking contract must not delete
the creation and undelegation times,
as this would enable reuse of the same operator address.
