= Staking

Notes and speculation

== Minimum stake

From the Ethereum rich list at etherscan.io:

7,000 accounts have at least 1/100,000 of the total supply each
1,000 accounts have at least 1/10,000
150 accounts have at least 1/1,000
5 accounts have at least 1/100

From btc.com rich list:

100 accounts with 10,000+ (1/1,750)
2,000 accounts with 1,000+ (1/17,500)
15,000 accounts with 100+ (1/175,000)
150,000 accounts with 10+ (1/1,750,000)

Non-trivial stake requirements in other projects:

Ethereum (Casper docs): 1,000 ETH deposit (1/100,000)
Ethereum (speculation of eventual minimum): 32 ETH (1/3,000,000)
Dash: 1,000 Dash (1/8,500)
Cardano: 10,000 ADA (1/4,500,000)
Tezos (masternode): 10,000 XTZ (1/80,000)
Decred: ~110 (1/80,000)

Initial suggestion: 10,000 KEEP or 1/100,000 of the total supply

.Market cap vs. minimum stake
|===
|Market cap |Minimum stake

|$10M |$100
|$100M |$1,000
|$1,000M |$10,000
|$10,000M |$100,000
|===
== Authorizations

Can't revoke authorizations:
naively implemented, this functionality would enable evading penalties. 
It could be made to work
by keeping track of when a staker actually is active in a contract,
but this would impose significant storage burdens.

== Token grants

* a specific amount of tokens
* for a specific address
* locked up for a specific time period
* vesting over time, unlocking parts of the grant
* may have a cliff, so tokens only start to unlock after a certain point
* may be revocable

Most of the issues with token grants concern conflicts of interest
between the _grant creator_ and the _grant recipient_,
and the _recipient's_ ability to subvert the goals of the _creator_.
If the creator and recipient are considered to be a single actor
as far as the rest of the network is concerned,
any such conflicts would simply manifest
as seemingly irrational behavior from the actor as whole.

However, given that the Keep org is the most significant grant creator
and all initial tokens would be given out as grants,
the practical effects of the grant mechanism are significant.

=== Grant features

Currently planned for 2 years or roughly 100 weeks

If minimum stake is set at 10,000 and stake-ahead at 2 weeks,
the minimum to begin staking right away would be 500,000
or 1/2,000 of the supply

=== Tattletale transfer

(T-transfer for convenience)

Misbehave deliberately in a way which entitles a tattletale to large rewards,
collect rewards on another account you control.

_transfer_efficiency = tattletale_reward / misbehavior_penalty_

When you know your grant would be revoked,
t-transfer may act as a way to secure a fraction
_grant * transfer_efficiency_ of the grant.

When you expect the future value of _grant_ to be less than
_transfer_efficiency * grant_ right now,
t-transfer may enable premature seizing of the value.

The practicality of t-transfer depends on the efficiency,
dictated by how contracts use slashed stakes.
If the seized collateral or a significant fraction
is transferred to an address the adversary can control,
t-transfer is highly viable.
If the seized collateral is distributed widely
in a way that is difficult to bias,
eg. in proportion to stakers' legitimate earnings from the contract,
the efficiency plummets.

biased distribution::
An algorithm for distributing slashed stakes is _biased_
if adversary _A_ with _adversary stake_ tokens
can give it some input _i_ that is not publicly available to all stakers,
and thus change the expected distribution so that _A_ receives more than
_(adversary stake / total staked) * slashed amount_.

unbiased distribution::
An algorithm for distributing slashed stakes has an _unbiased distribution_
when the expected amount of tokens received by any adversary
with _adversary stake_ tokens staked
is equal to _slashed amount * (adversary stake / total staked)_
regardless of the adversary's input.

[NOTE]
.T-transfer efficiency conjecture
====
The minimum t-transfer efficiency
for an adversary controlling _adversary_fraction_ of stakers
is conjectured equal to _adversary_fraction_.

This _unbiased distribution_ may be achieved in different ways:
by eg. simply transferring the tokens
to a random address weighted by stakes;
or by increasing all future rewards from the contract
by a small amount.

Any method that attempts to change this distribution
is subject to manipulation by the adversary "playing both sides".

For example, gifting the tokens to a random staker, non-weighted,
disproportionately rewards blitzpantsing.
The adversary, knowing in advance that they would be penalized,
can then prepare for this.
Similarly, the tattletale reward itself is such a bias,
subject to advance preparation on the basis of privileged information.

Such a biasing method is conjenctured to be possible
for every biased distribution of slashed tokens.
====

=== Slashing methods

==== Simple slashing

The simplest method for slashing
simply transfers the impacted tokens to the slashing contract.
This gives the contract full freedom
to distribute the tokens immediately
or keep them for future rewards.

The simple method of slashing does not enable
the enforcement of any relevant invariants
in the staking contract itself,
and thus all staked tokens are potentially subject to t-transfer.

==== Simple variant

A variant of the simple method would use two different slashing functions:
`slash` and `slashAndReward`.
`slash` would be a straightforward seizure of collateral
followed by distributing the tokens in an unbiased way,
while `slashAndReward` would nominate a tattletale staker
to receive a specified fraction of the seized tokens
and keep the rest in the functionality contract for unbiased distribution.

The simple variant allows more sophisticated discrimination
between stakes that may be subject to efficient t-transfer
and stakes that are distributed evenly.
Even in this case, it is both necessary
and impossible within the staking contract
to ensure that the contract actually implements the unbiased distribution.

==== Limited-bias slashing

A more sophisticated variant could be constructed
using a separate contract for the desired unbiased distribution scheme.
In this case it would be possible
to determine the characteristics of the reward scheme,
and use unbiased distributions safely
where biased distributions pose t-transfer threats.

The functionality contract would use the functions
`slashAndSeize` and `slashAndDistribute` for the collateral.
With `slashAndSeize` the tokens would be subject to arbitrary distribution,
while `slashAndDistribute` would grant them in an approved unbiased way.
Thus `slashAndDistribute` could be called without limits
on tokens subject to grants,
and the problem would be limited to `slashAndSeize`.

If the creator of the grant approves in advance
the contracts `slashAndDistribute` may be used with,
determining the unbiasedness of any particular reward distribution scheme
is externalized onto an off-chain party
whose incentives obviously maximally align with those of the grant creator.

It may be recommendable to always call `slashAndSeize` with `slashAndDistribute`
to provide a ceiling on the maximum achievable t-transfer efficiency.
If _t_ tokens are slashed,
with _t * B_ going to `slashAndSeize`
and _t * (1 - B)_ going to `slashAndDistribute`,
the distribution may be called a _partially biased distribution_
with a bias ceiling of _B_,
or a _B-biased distribution_ (eg. "50% biased distribution").

If a cap on reward distribution bias is enforced by the grant creator,
so that only _partially biased distributions_ are allowed,
requiring that _0 =< B =< maximum allowed bias < 1_,
a known minimum resistance to t-transfer can be ensured.
The grant amount could be staked with _B * minimum stake_ being vested tokens
and _(1 - B) * minimum stake_ being unvested tokens.

=== False stake

If Mallory has a grant and is expecting the grant to be revoked,
tokens that would be unvested at the time of revocation are not efficient stake;
Mallory has nothing to lose from expending such tokens
as stakes for misbehavior that gives any personal advantage otherwise.

If Mallory is not expecting the grant to be revoked,
the time value of money and future expectations on token value
can still reduce the effective value of the locked-up tokens.

In the case of non-revocable grants,
it would be possible to reduce the effect of future discounting
by requiring more tokens if the tokens vest at a time far in the future.

=== Staking ahead

Withdrawing staked tokens requires waiting the _unstaking period_.
If staker _S_ is choosing between unstaking and continuing at time _T_,
the amount of unlocked tokens they could withdraw at the earliest possible time
is _UnlockedTokensAt(T + T~unstake~)_.
Thus it may be safe to use tokens
that are locked at the present time but would vest within the unstaking period
as collateral.

If minimum stake is 10,000 KEEP or 1/100,000 of the total supply,
and grants last 2 years,
the de facto minimum stake to begin staking immediately
is determined by _minimum stake * (100 weeks / unstaking period)_

.Unstaking period vs. de facto minimum stake at various market caps
|===
|Waiting period |$10M |$100M |$1,000M

|1 week   |$10k   |$100k |$1M 
|2 weeks  |$5k    |$50k  |$500k
|4 weeks  |$2,500 |$25k  |$250k
|10 weeks |$1,000 |$10k  |$100k
|25 weeks |$400   |$4k   |$40k
|===

=== Grant-compatible staking

Instead of staking contract, split the responsibilities:

==== Staking proxy

The staking proxy is not called directly;
instead an entry is created
when one of the staking contracts has a staking event.

staker[staker_id] -> backend::
The contract addresses of the rules each staker operates under

initialize(staker_id)::


remove(staker_id)::
Remove the backend address entry of the specified staker

==== Staking backend

A contract that can provide the required interface to the staking proxy:

weight(staker_id) -> int::
Returns the staker weight of the specified staker.

operator(staker_id) -> address::
Returns the address which has _operator_ authority for the specified staker.

beneficiary(staker_id) -> address::
Returns the address which has _beneficiary_ authority for the specified staker.

overseer(staker_id) -> address::
Returns the address which has _overseer_ authority for the specified staker.

reward(staker_id, amount)::
Rewards the staker with tokens or currency.

slash(staker_id, amount)::
Seizes _amount_ tokens from the staker and gives them to the calling contract.
If the staker state is `Active`
this method is required to transfer the tokens to the calling contract.
Calling `slash` on an `Unstaking` staker is backend-specific.

===== Backend: free stakes


* `amount` of staked tokens
* `state` of the staker (`Active` or `Unstaking`)
* `since` time of last change (staking or unstaking)
* `owner` of the tokens
* `operator` address performing operations
* `beneficiary` address to send rewards to
* `overseer` address to determine authorized contracts

stake(amount, operator, beneficiary, overseer)::
Initiate staking by specifying the addresses of the other roles
and transferring at least _minimum stake_ tokens to the contract
+
The caller is designated as the owner
+
May be called by any address with at least _minimum stake_ tokens

unstake(staker_id)::
Initiate unstaking, start the unstaking period
and stop the staker from joining any new operations
+
May be called by either the owner or the operator of the staker

return_tokens(staker_id)::
Terminate a staker that has finished unstaking
and return the staked tokens to the owner
+
May be called by either the owner or the operator of the staker

reward(staker_id, amount)::
Reward a staker for correct operation
and transfer currency or tokens to its beneficiary address
+
May be called by a functionality contract

slash(staker_id, amount)::
Punish a staker for misbehavior and seize some of its tokens
+
The seized tokens may be used in whathever way is specified by the contract
+
May be called by a functionality contract authorized by the staker's overseer
and not blocked by the panic button


==== Free token staking

==== Limited token staking
