export const ALLOWED_UPGRADE_DELAY = 1209600; // 2 weeks in sec. TODO: add as an option.param
export const CLIENT_TIMESTAMP_INDEX = 1;
export const CLIENT_VERSION_INDEX = 0;
export const DEFAULT_NETWORK = "goerli";
export const MIN_PRE_PARAMS = 500; // min requirement for pre params daily avg
export const PRE_PARAMS_AVG_INTERVAL = "24h"; // hours
export const PRE_PARAMS_RESOLUTION = "24h"; // hours
export const QUERY_STEP = 600; // 10min in sec
export const REQUIRED_UPTIME = 96; // percent
export const UPTIME_REWARDS_COEFFICIENT = "upTimeRewardsCoefficient";
export const IS_BEACON_AUTHORIZED_FACTOR = "isBeaconAuthorized";
export const BEACON_AUTHORIZATION = "beaconAuthorization";
export const IS_TBTC_AUTHORIZED_FACTOR = "isTbtcAuthorized";
export const TBTC_AUTHORIZATION = "tbtcAuthorization";
export const UP_TIME = "upTimePercent";
export const IS_UP_TIME_SATISFIED = "isUpTimeSatisfied";
export const INSTANCE = "instance";
export const VERSION_FACTOR = "version";
export const PRE_PARAMS_FACTOR = "preParams";
export const PRECISION = 1000;
export const UPTIME_QUERY_RESOLUTION = 120 // 2min is a sampling time for the uptime metric
export const HUNDRED = 100