# Trickster Configuration File.
#
# A full configuration file example can be found here:
# https://github.com/trickstercache/trickster/blob/main/examples/conf/example.full.yaml

frontend:
  listen_port: 8480

backends:
  default:
    provider: prometheus
    origin_url: http://prometheus:9090
    is_default: true
    healthcheck:
      path: /prometheus/-/ready
      upstream_path: /prometheus/-/ready
      interval_ms: 5000
      expected_body: "Prometheus Server is Ready.\n"

metrics:
  listen_port: 8481
  listen_address: ""

logging:
  log_level: info
