= Keep Network Private Testnet

We set up a Keep Network Private Testnet that is accessible by the permitted parties.
Here we hold the code helping us to create bundles for the parties.

The network runs against the link:https://goerli.net/[Ethereum Görli Testnet].

The generated bundles contain a preinitialized Ethereum Account details. The account
receives a stake delegation to the Staking Provider Account with authorized `beacon` and
`tbtc` application. This is a production-like experience for the Staking Providers,
where they will receive stakes from their customers.

== Scripts

=== Prerequisites

The scripts require the following tools to be installed:

- `npx` - link:https://nodejs.org/en/download/package-manager/#macos[macOS install]
- `geth` -  link:https://geth.ethereum.org/docs/install-and-build/installing-geth#macos-via-homebrew[macOS install]
- `asciidoctor` - link:https://asciidoctor.org/docs/install-asciidoctor-macos/#homebrew-procedure[macOS install]
- `docker` - link:https://docs.docker.com/desktop/install/mac-install/[macOS install]

=== Create New Bundle

To create a new bundle run:

```bash
./scripts/new-bundle.sh
```

=== Initialize Staking Provider

To simulate a Staker delegation to a Staking Provider and authorize the applications run:

```bash
./scripts/init-provider.sh
```
