resources:
  - storage-class.yaml
  - minter-statefulset.yaml
  - guardian-statefulset.yaml

namespace: default

commonLabels:
  app: tbtc-v2-maintainer
  network: goerli

configMapGenerator:
  - name: tbtc-v2-maintainer-eth-accounts-info
    files:
      - config/tbtc-v2-minter-0-keyfile
      - config/tbtc-v2-guardian-0-keyfile
  - name: electrum-api-testnet
    literals:
      - electrumx-url-wss=wss://electrumx-server.test.tbtc.network:8443

secretGenerator:
  - name: tbtc-v2-maintainer-eth-accounts-password
    files:
      - .secret/tbtc-v2-minter-0-password
      - .secret/tbtc-v2-guardian-0-password

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: generated
