= Details+Rationale

== Message delivery

=== Broadcast channel

Every group member in phase _p_ can safely assume
every non-inactive group member has seen
all messages broadcast within _T~p~_ after the beginning of phase _p_.

All messages broadcast by _P~i~_ are assumed to be signed with _X~i~_.

A message is malformed if it cannot be parsed and validated
as the message required in a particular phase of the protocol.

The implementation details of the broadcast channel
are currently out of scope for this document.

==== Assumptions and implications

The broadcast channel is assumed to give all participants
the same view of the world,
and deliver all messages from non-inactive participants
within a time that is less than the applicable time limit for each phase.

If these assumptions don't hold, certain attacks become possible.
For example, if a message from _P~i~_
reaches honest participant _P~j~_ but not _P~k~_,
their sets of inactive participants _IA~Pj~_ and _IA~Pk~_ will differ.
This will make them vote for different results,
which will prevent quorum from being reached on _full signing_,
while on _escalating votes_ a coordinating adversary
could make its preferred incorrect result win the vote.
To protect against the latter,
_escalating votes_ assumes a null result when any single result is opposed
by _f~max~ + 1_ participants as it means that the honest votes are split.

== Result format

The result of the DKG protocol can be either a success or a failure.

Success means the DKG protocol finished with at most _M~fail~_ participants
misbehaving or dropping offline during the execution of the protocol,
and the group of the remaining honest participants _G_
should be added to the signing groups for the threshold relay.

Failure means that the group creation could not finish, due to either
the number of (inactive + disqualified) participants exceeding _M~fail~_,
or the presented results being disputed
in a way where the correct outcome cannot be ascertained.
