= DKG: notes

== Result format

data Result = NoFaultFailure
            | FailureDQ { disqualified :: Array Bool }
            | PerfectSuccess { pubkey :: BeaconPubkey }
            | SuccessIA { pubkey :: BeaconPubkey
                        , inactive :: Array Bool }
            | SuccessDQ { pubkey :: BeaconPubkey
                        , disqualified :: Array Bool }
            | MixedSuccess { pubkey :: BeaconPubkey
                           , inactive :: Array Bool
                           , disqualified :: Array Bool }
----

For a reasonably compact representation,
we can use the first byte of the result to encode not only success/failure,
but also whether there were inactive or disqualified participants.

The inactive and disqualified participants are listed
in one-indexed bit arrays where the __i__th bit being set means
_P~i~_ is in the corresponding set.

WARNING: One-indexing is a risk factor for off-by-one errors in the code.
Using zero-indexed arrays with the first bit unset
would instead move the risk into the length calculations.

If the __i__th bit is set in both `inactive` and `disqualified`,
the result message can either be deemed invalid
or have disqualification take precedence.

The maximum length of a result message is _1 + |BeaconPubkey| + n/4_ bytes.

(For an unreasonably compact representation we could use ternary in trees
to represent only the indexes of participants who were in _IA_ or _DQ_.
In theory this would save space almost every time,
as the longest message (_MixedSuccess_) may only contain
1/4 of participants in either of them.
A less ridiculous ternary encoding would be squeezing 5 trits into 1 byte
between 0-242, using 8 bytes where binary encoding would use 10.
These trytes could be further compressed by prefixing them with bytes
encoding which trytes of the entire array contain any nonzero values,
saving a small amount of space in most cases.
In practice there is no way it would be worth it,
especially given the reputation of ternary in this industry.)

== Dispute resolution

Given that the protocol is performed off-chain,
participants may submit incorrect results
in an attempt to gain advantage.
By relying on the honest majority assumption,
this can be mitigated by having participants vote on results.

Voting on results means that only votes need to be counted on-chain;
validating everything else can be offloaded onto the honest majority.
This has significant cost advantages as _O(n^2^)_ blockchain operations,
including _O(n)_ transactions and up to _O(n^2^)_ elliptic curve operations,
can be replaced with simply _O(n)_ transactions of mostly constant size,
or a single transaction with _O(n)_ elliptic curve operations.

There are two main ways this voting can be performed:
either by members signing valid results, which are then verified on-chain,
or by designated members being eligible to submit a result
which may be challenged by others if they consider it incorrect.

=== Full signing w/ ECDSA (FE)

The _full signing_ technique of voting is simple.
The designated eligible submitter _P~sub~_ publishes the correct result
which is then checked by the contract to contain at least _M~max~ + 1_
valid signatures from unique members of _P_.

This technique requires fewer transactions and is less complex to implement,
but bears a constant cost as _O(n)_ signatures must be validated on-chain
upon every group creation.
Assuming for the sake of example _N = 201_ and _M~max~ = 100_,
and that `ecrecover = 3000 gas` dominates the transaction fees,
the cost of full signing would be constant on the order of 325,000 gas.

If every participant in the group signs a result,
the unnecessary signatures can be pruned to ensure constant
size and cost of the result submission transaction.

This also sets a hard limit on the group size of _N < gasLimit / 3000_,
but in practice this would only happen with impractically large groups
(currently more than 2,000 participants).

It is easy to see why _full signing_ would be correct:
if _M~max~_ is the largest number of malicious participants,
requiring _M~max~ + 1_ signatures means that any result accepted by the system
must have at least one honest participant supporting it.

.costs
|===
|Operation |Cost

|`EcrecoverGas`
|3,000

|Verification with _H = 101_
|324,000

|Verification with _H = 201_
|624,000

|Verification with _H = 500_
|1,021,000
|===

=== Full signing w/ BLS (FB)

By using a BLS group signature instead of individual ECDSA signatures,
the on-chain size of the result can be significantly reduced.
However, pairing checks are extremely expensive,
even if EIP-1108 gets passed.

Given that the length of the BLS signature would be 256 bits,
`k = 2` and the gas price of one pairing operation is currently `260,000`;
with EIP-1108 the price would fall to `91,000`;
with Vitalik's version `120,000`.

The full cost of validating a BLS group signature
by at least _H_ members of _P_ is approximately
_21000 + 2 * (GPAIRINGBASE + 2 * GPAIRINGPERPOINT) + ECADD * (H - 1)_
from the necessary `Bn256Add` operations.
Without cost reductions, this is `570,000` for _H = 101_

.costs
|===
|Operation |Cost at status quo |Cost with EIP-1108 |Cost with Vitalik's proposal

|`GPAIRINGBASE`
|100,000
|80,000
|40,000

|`GPAIRINGPERPOINT`
|80,000
|5,500
|40,000

|`ECADD`
|500
|50
|500

|Base cost of BLS verification

|520,000
|182,000
|240,000

|Verification with _H = 101_
|591,000
|208,000
|311,000

|Verification with _H = 201_
|641,000
|303,000
|361,000

|Verification with _H = 500_
|790,500
|452,500
|510,500
|===

=== Escalating votes

As an alternative to the above,
_escalating votes (EV)_ is a protocol where a result is submitted,
and accepted if it is not challenged within a specified time limit.
If multiple results are presented,
the participants will proceed to submit votes on the results
iff their preferred result is not in the lead,
or their vote would break a tie.
After a certain time limit has elapsed since the last vote,
a confirmation request transaction may be presented by anybody,
and the result with the highest number of supporting votes is accepted.

The security of this scheme is less obvious,
but follows from the honest majority assumption:
since at least _M~max~ + 1_ honest players are online at the voting stage,
for any amount of adversary votes _0 < v~m~<= M~max~_
there will be _v~m~ + 1_ honest participants
who will outvote the malicious players
(proof by induction).

This scheme is only suitable for situations where _N >= 2 * M~max~ + 1_,
due to the reliance on the honest majority assumption.
If the majority of participants is dishonest,
the plurality result may be incorrect.

In the worst-case scenario escalating votes will cost
_(M~max~ + 2) * 21000_ gas to the honest participants,
or around 2.15 million gas.
However, the practical cost of using escalating votes would be variable
and would be expected to be significantly lower most of the time.

Given that a rational adversary who cannot break the honest majority assumption
will expect to inevitably lose the escalating vote,
and the cost of the voting is symmetrical
(submitting one vote costs approximately 21,000 gas,
so the malicious players will pay _v~m~ * 21000_ gas
while honest players will pay _(v~m~ + 2) * 21000_ gas in total;
this means the honest players will always pay exactly
42,000 gas more than the malicious players regardless of the value of _v~m~_),
one would expect the escalating votes to usually go unchallenged.

In the example scenario, _EV_ is cheaper than _FE_
if the average number of votes supporting the highest-voted incorrect result
is less than 13 out of 200 participants,
or alternatively if the worst-case scenario occurs at most 1/8 the time.

== Incentives

After performing the group creation correctly,
participants will be members of _G_
and eligible for rewards from producing signatures for the random beacon.

The protocol requires some parties to publish transactions on-chain.
Honest parties publishing correct transactions should be compensated for
the gas required for these transactions.

Malicious parties who violate the protocol should be penalized.

=== Required transactions

Group selection will be performed as part of a previous transaction.

If using _FS_ for voting on results,
the protocol will require one particularly expensive transaction.
If _EV_ is used, a larger number of transactions may be required,
up to a limit of one transaction from each honest participant,
but each transaction has a lower cost.


Types of possible misbehavior in the execution include:

* sending malformed messages
** malicious only
* presenting inconsistent shares
** malicious only
* voting for incorrect outcome
** can be done by honest participant
if the broadcast channel assumption fails

Ways a participant may be inactive during execution:

* inactivity in the beginning
* inactivity during the execution
* inactivity at result stage
** not signing correct result if using FV
** with EV it gets super complex and don't want to think about it
