= Terms used in distributed key generation (DKG)

== Time limits

[horizontal]
T~p~::

Time limit for phase _p_ of the key generation; after _T~p~_ has elapsed every
non-inactive participant is assumed to have broadcast its own message for phase
_p_ and received others' messages

T~DKG~::

Time limit for the distributed key generation to finish and _P~1~_ to submit the
result

T~STEP~::

Time limit after which the next participant in queue becomes eligible to submit
the result

T~VOTING~::

Time limit after which any disputes over the correct result are assumed to be
resolved, with the plurality being honest

T~RESPONSE~::

Extension to the time limit after a new vote has been submitted, to ensure
honest members are able to react to last-minute votes.

== Rewards and punishments

[horizontal]
R~DKG_SUBMIT~::
Reward for the member submitting the finally accepted result

D~DKG_MISSED_SUBMISSION~::
Penalty for all members _P~1~ .. P~i-1~_ who failed to submit the result
before _P~i~_, if _i > 1_

D~DKG_DQ~::
Penalty for members on the disqualified list


== Values at the time of group creation

[horizontal]
V~i~::
**_i_**th output of the random beacon

S::
The set of all stakers at the time of _V~i~_

P::
The candidate group of players selected from _S_ with _V~i~_,
who will try to perform the key generation to create signing group _G_

P~j~::
__j__-th node in _P_ based on the group candidate selection algorithm

== Values in the DKG protocol

[horizontal]
IA~p~::
The set of nodes in _P_ that first failed to broadcast a required message within
a specified time limit in phase _p_ and were thus added to the set of inactive
nodes after that phase

IA::
IA~1~ + IA~2~ + ...
+
The set of inactive nodes in _P_ (nodes that failed to broadcast a required
message within a specified time limit during the DKG)

DQ~p~::
The set of nodes in _P_ that were disqualified in phase _p_ for provably and
attributably violating the protocol

DQ::
DQ~1~ + DQ~2~ + ...
+
The set of all disqualified nodes in _P_

G~p~::
G~p-1~ - IA~p-1~ - DQ~p-1~
+
The set of nodes in _P_ that were active and well-behaved at the
beginning of phase _p_ (_G~1~= P_)

G::
P - IA - DQ
+
The successfully created group after removal of inactive
and misbehaving nodes

== Keys

[horizontal]
X~i~::
Long-term ECDSA private key of _P~i~_

Y~i~::
Long-term ECDSA public key of _P~i~_

x~ij~::
Ephemeral ECDH private key of _P~i~_ for the purpose of encrypted communication
with _P~j~_

y~ij~::
Ephemeral ECDH public key of _P~i~_ for the purpose of encrypted communication
with _P~j~_

k~ij~ = k~ji~::
ECDH(x~ij~, y~ij~)
+
Symmetric key generated by _P~i~_ for encrypting and decrypting communications
with _P~j~_

X::
X = Σ z~i~
+
The (virtual) private key corresponding to the group _G'_

Y::
Y = X * P1
+
The public key corresponding to the group _G'_

z~i~::
z~i~ = a~i0~
+
Piece of the group private key _X_ generated by _P~i~_

y~i~::
y~i~ = z~i~ * P1 = A~i0~
+
Piece of _P~i~_ of the group public key _Y_

x~i~::
x~i~ = Σ s~ji~
+
The individual private key of _P~i~_ corresponding to a share of _X_ at _i_

gx~i~::
gx~i~ = x~i~ * P1 = Σ (s~ji~ * P1)
+
The individual public key of _P~i~_ corresponding to a share of _Y_ at _i_
