node1: go run main.go -l 2701 --seed 1 #for some reason using 2700 causes it to be weird???
node2: go run main.go -l 2702 --seed 2
node3: go run main.go -l 2703 --seed 3
node4: go run main.go -l 2704
node5: go run main.go -l 2705
