# Default values for ethereum.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

bootnode:
  replicaCount: 1
  image:
    repository: ethereum/client-go
    tag: alltools-v1.8.2

# Config for geth nodes (tx node or a miner node).
node:
  image:
    repository: ethereum/client-go
    tag: v1.8.2
  netrestrict: 10.0.0.0/8

# List of geth nodes.
nodes:
  - nodeName: good-miner-node
    nodeType: miner
  - nodeName: unfriendly-miner-node
    nodeType: miner
  - nodeName: tx-node
    nodeType: tx

monitor:
  replicaCount: 1
  image:
    repository: ethereumex/eth-stats-dashboard
    tag: latest
