== Intro

Here we provide a mechanism to prepare deployment bundles for external parties
particpating in our private testnet.  New bundles need to be generated after each
contract migration or keep-client build for the `keep-test` environment.  Bundles
are managed via scripts provided in the `/scripts` dir and should require little
context to operate.

== Directory Structure

This touches on directory format and reasons for this format.  It's not exhaustive,
but should cover the bits that must be honored.

=== Top level

On `keep-core/private-testnet` we store files that are generally applicable to
external participants.  This should look like:

```
.
├── KeepToken.json
├── README.adoc
├── TokenStaking.json
├── changelog.adoc
├── eth-account-password.txt
├── keep-client-snapshot.tar
├── keyfiles
├── participants
└── scripts

3 directories, 6 files
```

Files the bundling script expects to be on this level:

* keep-client-snapshot.tar
* eth-account-password.txt
* changelog.adoc

=== Participants

Participant directories should all live in `/private-testnet/partcipants`.
Each particpant must get their own directory.  The bundling script and quickstart
guide both operate under the assumption that each participant directory is
structured in the format highlighted below:


*Top-level in `keep-core/participants`:*
```
.
├── bisontrails
├── figment
└── staked

3 directories, 0 files
```

*Individual participant directory structure:*
```
.
├── config
│   ├── eth-account-keyfile
│   └── keep-client-config.toml
└── persistence

2 directories, 3 files
```

== Scripts

There are 3 scripts that make up preparing deployment bundles:

* `private-testnet/scripts/prepare-participant-bundles.js`
  ** Creates a `.tar.gz` bundle to be distributed to each participant.  The file
     is stored on the top level of the particpant directory.
* `private-testnet/scripts/fetch-contract-data.js`
  ** Grabs the latest contract data for `KeepToken` and `TokenStaking`.  These are
     used in the `stake-accounts.js` script
* `private-testnet/scripts/stake-accounts.js`
  ** Stakes each ETH account that is assigned to a participant.

`prepare-participant-bundles.js` can be run before staking, you just need to make sure that
`fetch-contract-data.js` is run before `stake-accounts.js`.


=== Dependencies

Script excution requires the following NPM packages:

* web3@1.0.0-beta.55
* fs
* @google-cloud/storage

