:toc: macro
:toclevels: 4

= Roles and authorizations

ifndef::yellowpaper[toc::[]]

== Roles

Governance::

Governance is the final arbiter of authority in the Keep Network.
The role of Governance is to enable recovery from key compromise
by rekeying other roles.
Governance has the authority to change the addresses of
the _Registry Keeper_, _Panic Button_,
and the service contracts' _Operator Contract Upgraders_
The rekeying process is currently unspecified.

Registry Keeper::

The Registry Keeper maintains the global _registry_ of approved contracts.
Each operator contract must be approved by the Registry Keeper
before it can be authorized to punish operators
or used by a service contract.
The Registry Keeper can be rekeyed by _Governance_.

Panic Button::

The Panic Button can disable malicious or malfunctioning contracts
that have been previously approved by the Registry Keeper.
When a contract is disabled by the Panic Button,
its status on the _registry_ changes to reflect this,
and it becomes ineligible to penalize operators.
Contracts disabled by the Panic Button can not be reactivated.
The Panic Button can be rekeyed by _Governance_.

Operator Contract Upgrader::

Each service contract has an Operator Contract Upgrader
whose purpose is to manage operator contracts for that service contract.
The Operator Contract Upgrader
can add new operator contracts to the service contract,
and deprecate old ones.
The Operator Contract Upgraders can be rekeyed by _Governance_.

Authorizer::

Each operator has an Authorizer
whose purpose is to determine which operator contracts
may punish the operator for misbehavior.
The operator can only perform work for authorized operator contracts.
The Authorizer cannot be rekeyed except by undelegating and redelegating.

== Authorizations

=== The Registry and Panic Button

The registry tracks all Keep Org -approved contracts.
Operator contracts have a special status on the registry,
reflecting the ability of the Panic Button to disable them.

Each operator contract's status may be `NULL`, `APPROVED` or `DISABLED`.

A status of `NULL` is the default
and means that the operator contract has not been approved
by the _Registry Keeper_.

When the _Registry Keeper_ approves a operator contract,
its status switches to `APPROVED` in the registry.
Approved operator contracts can be authorized to punish operators,
and service contracts may utilize them.

The _Panic Button_ can be used
to set the status of an `APPROVED` contract to `DISABLED`.
Operator Contracts disabled with the _Panic Button_ cannot be re-enabled,
and disabled contracts may not punish operators
nor be selected by service contracts to perform work.

=== Staking contracts: authorized operator contracts

Staking contracts hold staked tokens,
enforce staking rules,
and punish misbehaving operators
on behalf of authorized operator contracts.
For this purpose,
each staking contract tracks which operator contracts
have been authorized by which addresses.

The _authorized operator contracts_ are a mapping
of `(address authorizer, address operator_contract) -> status`.

The status of a contract may be either `NULL` or `AUTHORIZED`.
A status of `NULL` is the default
and means the operator contract is not authorized.
A status of `AUTHORIZED` means that the operator contract
may impose punishments on those operators
who have assigned that `authorizer` as their _Authorizer_.

To authorize an operator contract on a staking contract,
the operator contract must have been `APPROVED` on the _registry_.
Once a operator contract has been authorized,
authorization cannot be withdrawn by the authorizer.
However, a operator contract that has been `DISABLED` by the _Panic Button_
may not punish stakers.

=== Service contracts: used operator contracts

Service contracts use the basic functionality performed by operator contracts,
to provide useful services to the public.
Service contracts can use multiple different versions of operator contracts
to perform the operator contract functions.
To permit system upgrades,
the list of used operator contracts can be updated with proper authorization.

A service contract is deployed with zero operator contracts,
rendering the service contract inactive
until at least one operator contract is activated.

Each service contract has its own _Operator Contract Upgrader_
who can add used operator contracts.
To add a used operator contract,
the operator contract must have been `APPROVED` on the _registry_,
and the interface it claims to implement
must match what the service contract expects.

If an operator contract has been `DISABLED` by the _Panic Button_,
the service contract must not use its functionality.
This must be checked when the service contract selects an operator contract.

== Impact of compromised keys

=== Individual keys

==== Registry Keeper

A compromised Registry Keeper can approve arbitrary operator contracts.
However, using those operator contracts for a service contract
requires the service contract's Operator Contract Upgrader as well.
Thus, a compromised Registry Keeper cannot endanger customers alone.
Similarly, stakers' funds are safe from being slashed by malicious contracts
unless their Authorizers are also compromised.

==== Panic Button

A compromised Panic Button can disable arbitrary operator contracts
and halt all network services.
Recovery is impossible until Governance has rekeyed the Panic Button.

This is inevitable due to the functionality of the Panic Button,
but the impact could be mitigated
by setting a cap on how many times the Panic Button can be invoked
within a particular timeframe.
However, if a compromised Registry Keeper
approves a large number of malicious contracts,
a rate-limited Panic Button would be overwhelmed
and unable to disable them all.
This could be further mitigated by rate-limiting the Registry Keeper similarly.

==== Operator Contract Upgrader

A compromised Operator Contract Upgrader
can activate operator contracts on the affected service contract
within the strict constraints of the upgrade process.
It is unlikely that an uncompromised Registry Keeper
would have approved an operator contract that would satisfy the constraints
yet cause a significant impact on the service contract.

==== Authorizer

If only the Authorizer of some staker is compromised,
the attacker can authorize operator contracts
that have been approved by the Registry Keeper,
and that use the same staking contract as the staker.

This has a very limited negative impact
unless the Registry Keeper has approved
a faulty or malicious operator contract.

=== Key combinations

==== Registry Keeper + Operator Contract Upgrader

If a malicious operator contract can get globally approved,
the impacted service contract can be completely subverted
by switching all work to the malicious operator contract.

While already existing operations should finish normally,
the service contract can be rendered effectively useless for new requests.

==== Registry Keeper + Authorizer

If the Registry Keeper approves a malicious operator contract,
and a staker's Authorizer authorizes it,
the malicious contract can be used to steal staked funds
within the constraints of tattletale rewards:
seizing up to 5% to the attacker and burning the rest.
