:icons: font
:numbered:
toc::[]

== Overview

Here we present a continuous delivery method for a service or services running
in a Kubernetes cluster.  It is expected that one or more of these services
has Ethereum contracts developed alongside the service.  It is expected that
there is a relationship between service and contract to a degree that we must
ensure both service and contract are deployed continuously.  The entirety of the
solution is targeted at development and test environments.  The requirements for
utilizing the outlined approach in production will not be covered here. Our one
and only service at this time is the keep-client.  The RFC will focus on the
keep-client as a result, however the solution is applicable outside the
keep-client.  This RFC requires a basic understanding of Kubernetes objects.

=== Implementation

This implementation will automate `Ethereum Contract Deployment` and `keep-client Configuration`. `keep-client service deployment` is already automated via Keel.

==== Part 1: Contract Migration

TODO: Which of these is used in the current implementation, or is this up to the user? 
Either a new workflow or new jobs to existing workflow will be added to the `keep-core` circle config. Before image publish on master merge Circle will run this workflow/job to trigger a script that will:

- migrate all contracts

- Copy compiled contract JSON to Circle and store in a Workspace for persistence
  in the `InitContainer` image.

- Here we must implement an access point for Circle into the private Kubernetes
  cluster.  We can do this with the `gcp_push_deploy` Terraform module.

==== Part 2: keep-client Preparation

On each keep-client Kubernetes deployment we run an `InitContainer` that does
the following:

- create ETH account
- unlock ETH account
- stake ETH account
- write contract addresses, ETH host/port, bootstrap peer addresses to config
  template
- write configuration file and ETH account keyfile to a persistent volume
- mount configuration file / keyfile persistent volume to keep-client deployment

The `InitContainer` operates exclusively on the ETH account and is assigned to the `keep-client` being deployed.  If there are 100 `keep-client` Kubernetes
deployments, there are 100 `InitContainer` instances unlocking and staking
for each of the assigned ETH accounts.  This is an infinitely scalable (system
resources aside) and reduces `unlock + stake` time to a ceiling of the time it
takes to operate on a single account.

The `InitContainer` has a copy of each Keep contracts compiled JSON.  The
files will be used to fetch contract ABI's for account staking and contract addresses for configuration file setup.  The updated configuration values will be fed into a complete `keep-client` configuration template and stored in a Kubernetes persistent volume.  This volume will be mounted to the `keep-client` deployment where the config can be passed via command line argument on service start.

For now we're going to bake a custom image for the `InitContainer` with the script for doing ETH account creation, unlock and stake, and keep-client configuration. This will be checked into the `keep-core/infrastructure/kube` directory.

==== A Note On Configuration Value Scope
We provide configuration values via environment variables at two points in this process: Circle contexts and Kube deployment configuration files.

We have *environment* and *client* properties. Where some N configuration values
are of context/properties environment and some are of context/properties client.
Environment properties

An example:

Using the *environment*/*client* context to organize configurations we can draw a line at where config values get populated.

`ETH_HOSTNAME` is a property of the environment, where `KEEP_CLIENT_ETH_ACCOUNT`
is a property of a client (because we’ve assigned it so).

Environment context property `ETH_HOSTNAME` gets configured at the Circle context level and baked into the `InitCointainer` and `KEEP_CLIENT_ETH_ACCOUNT`
gets configured on the Kube deployment.

TODO: I removed the background section since it might not be as relevant to the YP?