:toc: macro

= Random Beacon Distributed Key Generation

:toclevels: 4

This proposal for Distributed Key Generation for the threshold relay
is based on a protocol by Gennaro, Jarecki, Krawczyk and Rabin <<GJKR>>.
GJKR is further based on Pedersen-VSS (verifiable secret sharing) <<Ped>>.
For this implementation, GJKR has been modified
to make protocol violations objectively attributable
and remove the need for one-to-one messaging channels.

The protocol uses ephemeral ECDH keys
to encrypt one-to-one communication on the broadcast channel.
This ensures that participants can neither
make baseless complaints nor
cause a minor nuisance with subtle misbehavior.

Additionally, the threshold relay public key submission protocol
is defined.

toc::[]

include::dkg-terms.adoc[]

include::dkg-concepts.adoc[]


== Protocol

Input: _V~i~, S_

Output: one of

* Successfully generated group _P_ including
** public key _Y_ of _P_
** lists of absent and disqualified nodes _IA_ and _DQ_
* Failure to generate a valid group including
** list of disqualified nodes _DQ_

The group generation protocol selects a new candidate group _P_ from _S_
and runs a distributed key generation (DKG) protocol
to create a threshold signature public key _Y_ for the group,
to be used in the random beacon.

After a successful execution of the protocol,
_P_ will be the group of nodes
that may participate in the random beacon signing,
having been neither inactive or misbehaving during the DKG.

Inactive nodes will be removed from _P_
and not be eligible for the rewards
from participating in the random beacon
by contributing to the signature _V~j~_
should _P_ be chosen as the group to produce
the __j__th random number from the beacon.

Disqualified nodes will be removed from _P_
and their stake will be slashed in punishment
for provably and attributably acting in breach of the DKG protocol.

=== Group Selection

_TBD_

Input: _V~i~_, _N_

Output: _[Y~1~, Y~2~, ... Y~N~]_

For the purposes of the DKG algorithm,
group selection can be left undefined for now.
The protocol requires an ordered list of node identifiers,
represented here as public keys of participants _P~1~_ to _P~N~_.
This list is produced from _P_ using _V~i~_ as input.

=== Distributed Key Generation

Phases are seen from the perspective of _P~i~_

After phase _p_, the nodes that failed to broadcast a required message
will be added to _IA~p~_.
Nodes that broadcast a malformed message may be added to _IA~p~_ or _DQ~p~_.

[#phase-1,reftext="Phase 1"]
==== Phase 1. Ephemeral key generation

To ensure integrity in later parts of the DKG protocol,
we will require every _P~i~_ to generate
an ephemeral ECDH keypair _(x~ij~, y~ij~)_ for every other member _P~j~_ in _P_.
These will be broadcast in phase 1.

Registering the ephemeral keys on-chain is not required
if the broadcast channel assumption holds,
and all honest participants agree on the keys
published by each participant in phase 1.

.Phase 1
[source, python]
----
include::dkg.py[tags=phase-1]
----

[#phase-2,reftext="Phase 2"]
==== Phase 2. Ephemeral ECDH

Every node in _P_ has now published a valid list of ephemeral ECDH pubkeys.
_P~i~_ will perform ECDH with every _P~j~_ in _P_ to create _k~ij~_.

.Phase 2
[source, python]
----
include::dkg.py[tags=phase-2]
----

.Utility functions
[source, python]
----
include::dkg_util.py[tags=phase-2]
----

[#phase-3,reftext="Phase 3"]
==== Phase 3. Polynomial generation

Every node in _G~3~_ has, for every other node in _G~3~_, a symmetric key that
can be used for encrypted and attributable communications over the broadcast
channel. The Pedersen-VSS phase of the GJKR DKG algorithm can commence.

Create two polynomials _f~i~(z)_ and _g~i~(z)_ of degree _M_ and calculate
other players' shares as points on these polynomials. Additionally, calculate
Pedersen commitments to the coefficients of _f~i~(z)_ using the coefficients
of _g~i~(z)_.

Shares to _P~j~_ are encrypted with the symmetric key _K~ij~ = K~ji~_
shared by _P~i~_ and _P~j~_.
Commitments and encrypted shares are broadcast to other players.

.Phase 3
[source, python]
----
include::dkg.py[tags=phase-3]
----

.Utility functions
[source, python]
----
include::dkg_util.py[tags=phase-3]
----

[#phase-4,reftext="Phase 4"]
==== Phase 4: Share verification


Receive, decrypt and validate shares from other participants. If any share
proves inconsistent with the sender's published commitments, broadcast a
complaint by publishing the identity of the misbehaving party along with the
corresponding ephemeral private key so others can check the result.

.Phase 4
[source, python]
----
include::dkg.py[tags=phase-4]
----

.Utility functions
[source, python]
----
include::dkg_util.py[tags=phase-4]
----

[#phase-5,reftext="Phase 5"]
==== Phase 5: Share complaint resolution

If anyone has complaints about another player, use the published private keys
to decrypt transmitted messages and determine fault.

As every message in the broadcast channel is signed, decrypting previous
messages makes misbehavior attributable. For every complaint, one party will be
disqualified: either the accused sent invalid shares, or the accuser made a
false complaint.

.Phase 5
[source, python]
----
include::dkg.py[tags=phase-5]
----

.Utility functions
[source, python]
----
include::dkg_util.py[tags=phase-5]
----

[#phase-6,reftext="Phase 6"]
==== Phase 6: Share calculation

Each player sets their share _x~i~_ of the secret _X_ to equal the sum of all
shares _s~ji~_ as per GJKR. _X_ equals the sum of shares _s~j0~_.

.Phase 6
[source, python]
----
include::dkg.py[tags=phase-6]
----

[#phase-7,reftext="Phase 7"]
==== Phase 7: Public key share points

Each player broadcasts their _A~ik~_ values.

.Phase 7
[source, python]
----
include::dkg.py[tags=phase-7]
----

[#phase-8,reftext="Phase 8"]
==== Phase 8: Public key share validation

Each player validates the values received in <<phase-7>>.

.Phase 8
[source, python]
----
include::dkg.py[tags=phase-8]
----

.Utility functions
[source, python]
----
include::dkg_util.py[tags=phase-8]
----

[#phase-9,reftext="Phase 9"]
==== Phase 9: Second complaint resolution

As in <<phase-5>>, but with the validation formula from <<phase-8>>.

It should be noted that the symmetric nature of the encryption
allows the parties to also decrypt _E~jm~_ and not just _E~mj~_.
This is not very significant though,
as even the publication of only the misbehaving participants' shares
would reduce the security margin excessively
if a large fraction of _P_ were to misbehave.
By setting the threshold for group creation failure at _M/2_
the impact of this is reduced to a manageable level.

.Phase 9
[source, python]
----
include::dkg.py[tags=phase-9]
----

.Utility functions
[source, python]
----
include::dkg_util.py[tags=phase-9]
----

[#phase-10,reftext="Phase 10"]
==== Phase 10: Disqualified share opening

All active players in _G~10~_ broadcast the keys they share with
players in _DQ~9~_, so the reconstruction of Pedersen-VSS can be done
offline.

.Phase 10
[source, python]
----
include::dkg.py[tags=phase-10]
----

[#phase-11,reftext="Phase 11"]
==== Phase 11: Disqualified share reconstruction

Decrypt and reconstruct _z~m~_ for every participant _P~m~_ that presented
valid shares in <<phase-3>> but whose public key shares in <<phase-7>> were invalid.
Calculate _y~m~ = z~m~ * P1_ for each reconstructed _z~m~_.

.Phase 11
[source, python]
----
include::dkg.py[tags=phase-11]
----

.Utility functions
[source, python]
----
include::dkg_util.py[tags=phase-11]
----

[#phase-12,reftext="Phase 12"]
==== Phase 12: Public key reconstruction

Let _G~12~ = G~11~_

Combine _y~j~_ for all participants in _G~6~_ to reconstruct the public key for
the group. Additionally, calculate and store each qualified participant's
individual public key for validating signature shares.

.Phase 12
[source, python]
----
include::dkg.py[tags=phase-12]
----

.Utility functions
[source, python]
----
include::dkg_util.py[tags=phase-12]
----

[#phase-13,reftext="Phase 13"]
==== Phase 13: Result publication

Let _IA = IA~1~ + IA~2~ + ... + IA~10~_

Let _DQ = DQ~1~ + DQ~2~ + ... + DQ~10~_

Player _P~1~_ is the participant designated to submit the result on-chain.
However, if _P~1~_ does not submit a transaction
within _T~dkg~_ blocks of starting the key generation protocol,
_P~2~_ becomes eligible to submit the public key.
After _T~dkg~ + T~step~_ blocks, _P~3~_ becomes eligible,
after _T~dkg~ + 2 * T~step~_ blocks _P~4~_, and so on.

When _P~j~_ submits the result, players _P~k~ | k < j_ will face a small
penalty for being late, while _P~j~_ will receive the submission reward.

[source, python]
----
if nPlayers(IA + DQ) > M_nofail:
  correctResult = Result.failure(disqualified = DQ)
else:
  correctResult = Result.success(pubkey = Y, inactive = IA, disqualified = DQ)

resultHash = hash(correctResult)

alreadySubmitted = False
resultPublished = False
finished = False

while not resultPublished:
  T_now = getCurrentBlockHeight()

  # using T_init from phase 1
  T_elapsed = T_now - T_init

  # determine highest index j eligible to submit
  if T_elapsed <= T_dkg:
    j = 1
  else:
    T_over = T_elapsed - T_dkg
    j = 1 + ceiling(T_over / T_step)

  if j >= i:
    broadcast(correctResult)
    resultPublished = True
    alreadySubmitted = True
  else:
    resultPublished = checkChainForResult()
----

[#phase-14,reftext="Phase 14"]
==== Phase 14: Result conflict resolution

Because of the honest majority assumption, we can expect
a result supported by at least _H_ participants to be correct.

If any participant disputes a result submitted on-chain, they can submit a
different one.

If any participant disputes the submitted result that currently has the greatest
number of signatures on-chain, believing a different result submitted on-chain
to be the correct one, they can publish a support message by publishing a
hash of their preferred result
(implicitly authenticated with the signature inherent in publishing on-chain).

Any participant can only vote for one submitted result, by submitting it or
publishing a support message for it.

Because of the available honest majority assumption, we can expect that any
result that is not at the lead after _T~conflict~_ time has elapsed has
acquired its maximum number of signatures it would be able to receive, and
thus the result receiving the plurality of support is the correct one.

An exception to this is if the total number of signatures supporting all other
submitted results is higher than _M~max~_, in which case the result is declared a
failure without disqualifications.

[source, python]
----
while resultPublished and not finished:
  allResults = getSubmissions()
  leadResult = allResults.mostVotes

  T_now = getCurrentBlockHeight()
  T_first = allResults.earliest.submitTime
  T_latestVote = allResults.latest.submitTime

  majorityVoted = leadResult.votes > M
  timeoutReached = T_now > (T_first + T_conflict)
  noRecentVotes = T_now - T_latestVote > T_voteResponse

  if majorityVoted or timeoutReached and noRecentVotes:
    finished = True

  elif correctResult = leadResult or alreadySubmitted:
    wait()

  elif correctResult in allResults:
    submit(sign(resultHash))
    alreadySubmitted = True

  else:
    submit(correctResult)
    alreadySubmitted = True
----

From the perspective of the chain:


[source, python]
----
# memberVotes :: Set PlayerID
memberVotes = Set.empty()

# receivedSubmissions :: Map (HashOf Result) Result
receivedSubmissions = Map.empty()

# submissionVotes :: Map (HashOf Result) Int
submissionVotes = Map.empty()


def eligibleSubmitter(P_i):
    T_now = getCurrentBlockHeight()
    T_elapsed = T_now - T_init

    i = P_i.index

    if i == 1:
        True
    elif T_elapsed >= T_dkg + (i-2) * T_step:
        True
    else:
        False


def addVote(player, resultHash):
    memberVotes.add(player)
    submissionVotes[resultHash] += 1


def alreadyVoted(player):
    memberVotes.contains(player)


def addSubmission(submitter, result):
    resultHash = hash(result)
    receivedSubmissions[resultHash] = result
    memberVotes.add(submitter)
    submissionVotes[resultHash] = 1


def alreadySubmitted(resultHash):
    receivedSubmissions.hasKey(resultHash)

# data Submission = Submission Result PlayerID
# data Vote = Vote (HashOf Result) PlayerID

def receiveSubmission(s):
    P_s = s.submitter
    result = s.result
    resultHash = hash(result)

    if receivedSubmissions == {}:
        if eligibleSubmitter(P_s): # <1>
            addSubmission(P_s, s)
        else:
            reject(s)
    else:
        if alreadyVoted(P_s):
            reject(s)
        elif alreadySubmitted(resultHash): # <2>
            addVote(P_s, resultHash)
        else:
            addSubmission(P_s, result)

def receiveVote(v):
    P_v = v.submitter
    resultHash = hash(v.result)

    if alreadyVoted(P_v) or not alreadySubmitted(resultHash):
        reject(v)
    else:
        addVote(P_v, resultHash)


def getFinalResult():
    (leadingResult, highestVoteN) = submissionVotes.maxByValue()
    totalVotes = sum(submissionVotes.values())

    if totalVotes - highestVoteN >= M: # <3>
        return Result.failure(disqualified = [])
    else:
        return leadingResult
----

<<1>> Eligibility gets tested on the first submission only;
after one valid submission it's a free for all.

<<2>> When the same result gets "initially" submitted,
such as when a different result was previously submitted and two
participants submit theirs in the same block

<<3>> If more than _M_ participants vote for a non-leading result,
our honest majority assumption has failed
and we cannot determine the correct outcome.

[bibliography]
== References

- [[[GJKR]]] Gennaro R., Jarecki S., Krawczyk H., Rabin T. (1999)
Secure Distributed Key Generation for Discrete-Log Based Cryptosystems.
In: Stern J. (eds) Advances in Cryptology — EUROCRYPT ’99. EUROCRYPT 1999.
Lecture Notes in Computer Science, vol 1592. Springer, Berlin, Heidelberg

- [[[Ped]]] Pedersen T.P. (1992)
Non-Interactive and Information-Theoretic Secure Verifiable Secret Sharing.
In: Feigenbaum J. (eds) Advances in Cryptology — CRYPTO ’91. CRYPTO 1991.
Lecture Notes in Computer Science, vol 576. Springer, Berlin, Heidelberg

- [[[EIP-197]]]
EIP 197: Precompiled contracts for optimal ate pairing check on the elliptic
curve alt_bn128
