=== Incorrect signature share

Instead of broadcasting _Sig~m~_, _P~m~_ broadcasts a different, incorrect
value _Sig'~m~_ to other members of the signing group.

==== Attributability

*Full*

==== Viability

*Low*

Signature shares can be validated against the individual public key known from
DKG, and invalid shares ignored.

==== Mitigation

*None* (initially) to *full* (potentially)

Relies on DKG individual public key attributability

Relies on tracking beacon outputs signed by each group

Signing an incorrect value can be proven with the signature that doesn't
correspond to any previous beacon input, the member's public key, and its merkle
path to the DKG merkle root.


=== Selfish signing - greedy

Instead of revealing their signature share the operator waits to receive shares
from others, trying to delay others' signature reconstruction and to gain
the submitter reward.

==== Attributability

*Low*

A signature submission by a node that hasn't broadcast its own signature share
is evidence of selfish signing, but this can be circumvented by having the
submitter node broadcast its share normally while the adversary's other nodes
withhold theirs.

As the signature is reconstructed from shares it is not possible to tell which
nodes provided the shares for a given submission, and if the adversary
participates normally on one node its other nodes are indistinguishable from
offline nodes.

==== Viability

*Moderate* to *high*

The relationship of the derivative of the submitter's reward (grows over time)
vs the group rewards (declines over time) influences the viability of this
attack.

If the attack is successful at _T~submit~_, the adversary benefits by
_R~submitter~(T~submit~) - R~group~(T~submit~)_.
Because selfish signing results in the signature being submitted later than
it otherwise would at _T'~submit~_, the full viability of the greedy variant for
an adversary with _m_ nodes is governed by
__R~submitter~(T~submit~) + (m - 1) * R~group~(T~submit~) - m * R~group~(T'~submit~)_.

If _R~submitter~(T) > R~group~(T')_ for all _T, T'_, successful selfish signing
is always profitable when _m = 1_ and will remain profitable for larger _m_ if
_T_ and _T'_ are close enough.

If the selfish signing is unsuccessful, the operator will lose out on
_m * (R~group~(T'~submit~) - R~group~(T~submit~))_
which is small if _T_ is close to _T'_.

Additionally, delaying the submission deliberately can be profitable when
_dR~submitter~ / dT + (m - 1) * dR~group~ / dT > 0_ (always for _m = 1_).

If the system is modeled as a theoretical broadcast channel and the adversary
as rushing, the attack will always succeed. In a real system the probability of
success increases with _m_; a true linchpin adversary with
_m + n~inactive~ + n~disqualified~ > M_
will always succeed at selfish signing. Variability in message transmission
time reduces success chances as a different member may have their signature
reconstructed by the time _P~m~_ has received _H - m_ shares. Miner censorship
and DoS attacks on the other participants can improve chances of success.

==== Mitigation

*None* (initially) to *high to full* (potentially)

A fair exchange protocol or similar could be used to force operators to share
their signature shares such that any individual node only learns enough shares
to reconstruct the signature if all participants learn enough shares. In the
greedy form of the attack the adversary only cares about maximizing its own
profit, and thus it will prefer to reveal its signature share to others if not
doing so would result in an indefinite stalemate.

The cost of such a fair exchange as opposed to simple broadcast is lower group
rewards for all participants due to slower submission of results, but
participating in a suitable fair exchange protocol would be a dominant strategy.
TODO: Whether fair exchange protocols that are resistant to a rushing adversary
without a trusted third party are possible needs further investigation.


=== Selfish signing - malicious

A linchpin operator who can block others from completing the threshold
signature selfishly submits the signature at such time _T~submit~_ that their
own net reward
_R~submitter~(T~submit~) + (m - 1) * R~group~(T~submit~)_
is positive while everyone else suffers a late submission penalty:
_R~group~(T~submit~) < 0_.

This attack can be used to bootstrap dominance in the network.

==== Attributability

*Low*

A signature submission by a node that hasn't broadcast its own signature share
is evidence of selfish signing, but this can be circumvented by having the
submitter node broadcast its share normally while the adversary's other nodes
withhold theirs.

As the signature is reconstructed from shares it is not possible to tell which
nodes provided the shares for a given submission, and if the linchpin operator
participates normally on one node its other nodes are indistinguishable from
offline nodes.

==== Viability

*High* with sufficient adversary power;
can be augmented by DoS capabilities

The relationship of the derivative of the submitter's reward (grows over time)
vs the group rewards (declines over time) influences the viability of this
attack: an adversary with _m_ nodes can benefit absolutely when
_dR~submitter~ / dT + (m - 1) * dR~group~ / dT > 0_
; an adversary with 1 node will always benefit but is highly unlikely to become
linchpin, while an adversary with a large number of controlled nodes is less
likely to benefit but more likely to have linchpin status.

In relative terms this attack is always profitable, and regardless of _m_ there
always exists a _T~submit~_ such that
_R~group~(T~submit~) < 0_
but
_R~submitter~(T~submit~) + (m - 1) * R~group~(T~submit~) > 0_
and thus a sufficiently powerful and motivated adversary can use this attack to
bleed out honest participants

==== Mitigation

*None* (initially) to *limited* (potentially)

A malicious adversary may be willing to pay the opportunity costs of this attack
and thus mitigations are more difficult to come by than with a greedy adversary.

A fair exchange protocol does not work as well against a true linchpin
adversary, as the adversary could still behave extortionately and deny everybody
the beacon rewards unless it is allowed to become the submitter.

In such a case the honest nodes could attempt to extort in return, but due to
_m < h_ the marginal damage inflicted on the honest participants always exceeds
the damage on the malicious party in the case of an indefinite stalemate.

Additionally, identifying the presence of such an adversary is unlikely to be
possible except via circumstantial evidence.


=== Private key reveal

The opposite of selfish signing; the misbehaving staker reveals their individual
private key for the group's threshold signature with the intent to increase
their reward as a non-submitter by letting other stakers calculate their
signature share locally, and to let the staker be offline.

==== Attributability

*Full*

The corresponding public key is known by all members in the same group.

==== Viability

*Low*, requires extremely specific conditions to be profitable

If the cost of broadcast is high,
the cost of operating a well-functioning node high,
the reduction in group member rewards by increased time _dR~group~ / dT_ steep,
the number of nodes _m_ controlled by _P~m~_ high,
the probability of _P~m~_ otherwise getting submitter position low,
the difference in submitter and group rewards _R~submitter~(T) - R~group~(T)_ low,
the marginal improvement in submission time _T~submit~ - T'~submit~_ high,
and the (probability of being caught) times the (impact on token price) low,
it can be profitable to reveal one's individual signing key to other stakers so
that _Sig~m~_ can be calculated locally without need for _P~m~_'s participation.

==== Mitigation

*None* (initially) to *full* (potentially)

Relies on DKG individual public key attributability

Any member in the group can prove this happened by publishing a tattletale
message signed by the private key, containing the corresponding public key and
its merkle path generated from the DKG results. On-chain would then verify the
signature, and use the merkle path of the public key to verify that it belongs
to the accused group member. If a valid accusation is published, the accuser
would be rewarded and the misbehaving staker penalized.
