= Keep Random Beacon Work-in-progress Yellowpaper

This directory contains a yellowpaper/specification for the Keep random
beacon, which will initially be built out for Ethereum. The yellowpaper
is currently still a work-in-progress, and is being developed alongside
the core beacon code.

The core beacon code will be shared at a later time, while the yellowpaper, and
its progress, are available now. Note that core yellowpaper progress is still
handled in the Keep monorepo; we are syncing the branch history to and from
this repository on an ongoing basis.

The yellowpaper is written in AsciiDoc and built using
https://asciidoctor.org[Asciidoctor]. It renders directly in GitHub, so please
feel free to click through the files in GitHub to see the rendered content,
starting with <<index#,the index document>>.  Notably, GitHub does not process
inter-file includes, so includes are rendered as links to the embedded files.

You can also see a fully-built version of the yellowpaper at
http://docs.keep.network/random-beacon/, or, if you prefer a PDF version, at
http://docs.keep.network/random-beacon/index.pdf.

== Building

To build the yellowpaper yourself, you should
https://asciidoctor.org/#installation[install Asciidoctor]. Then you can enter
the root directory of this repository and run `asciidoctor index.adoc` to
produce an `index.html` file. Asciidoctor also supports several
https://asciidoctor.org/docs/user-manual/#selecting-an-output-format[other
output formats].
