:toc: macro

= RFC 14: Token grants

:icons: font
:numbered:
toc::[]

== Background

A token grant represents a gradual transfer of KEEP tokens
from the grant creator to the _grantee_.
The difference between these _grant tokens_ and ordinary _liquid tokens_ is
that grant tokens cannot be transferred away from the grant
before their ownership is fully transferred to the grantee
according to a _vesting schedule_.

In addition, some grants will be _revocable_
so that the grant manager can _revoke_ the remaining grant
and the remaining unvested tokens
will return to an address specified by the grant manager.

=== Use-cases and expected characteristics

Keep Org uses token grants widely,
to distribute tokens to investors and to reward employees.

Investors' token grants limit the amount of liquid tokens
that could be dumped on exchanges to make a quick profit,
and incentivize holders to stake instead.
A typical investor's grant vests in two years,
but six-month and one-year grants are also used.
Investor grants are non-revocable.

Employees' token grants replace traditional startup equity,
and need to support vesting cliffs and revocability.
Employees' opportunities to stake early are less important
and may even be contractually restricted
to prevent various conflicts of interest.

=== Staking token grants

The grantee should be able to use their grant tokens for staking,
but they should not be able to withdraw them prematurely.
This presents various problems in practice.

==== Tattletale transfer

In the Keep network,
staked tokens are used as collateral to enforce correct behavior.
When staker _Alice's_ misbehavior is proven on-chain,
some of her staked tokens will be _slashed_ as a punishment.
Slashing can mean either _burning_ the tokens,
effectively returning their value to all other token-holders;
or _seizing_ the tokens to the contract imposing the punishment
so they can be redistributed according to the contract's rules.

In some cases, detecting and penalizing Alice's misbehavior
will require collaboration from another staker, _Bob_.
To incentivize Bob to prove Alice's misbehavior,
the network entitles him to a _tattletale reward_,
a fraction of Alice's slashed tokens.

However, if this _tattletale fraction_ is sufficiently high,
a new type of attack emerges:
if Alice and Bob are secretly the same party,
they can reclaim the tattletale reward by tattling on themselves.
In this situation,
a _tattletale transfer_ from Alice to Bob happens.

Tattletale transfers (or _t-transfers_ for short)
can bypass many limits ordinarily in place.
Tokens can be transferred between stakers
without waiting for the normal unstaking time-lock to release,
and deterrent to misbehavior can be significantly reduced.
With token grants, the most relevant consideration is that
tattletale transfers could be used to extract unvested tokens from a grant.
Any scheme for staking grant tokens
must be able to prevent such _premature withdrawals_
from significantly undermining the integrity of the grant.

===== Limiting tattletale transfer: minimum burn fraction

By burning most (e.g. 95%) of slashed tokens,
the efficiency of tattletale transfer can be significantly constrained.
If Alice proves Bob's misbehavior and Bob is penalized by 100 KEEP,
at least 95 KEEP would be destroyed and at most 5 KEEP transferred to Alice.

This serves two goals.
First, Bob cannot efficiently withdraw unvested tokens
through tattletale transfer.
With a 95% minimum burn,
only 1/20 of the slashed tokens can be t-transferred.
On a 24-month grant this represents an amount
that would vest in 1.2 months or roughly 37 days,
at the cost of the entire rest of the grant.
As the remaining vesting time grows shorter,
this "advance withdrawal window" also grows narrower.

Second, limiting tattletale transfer efficiency
makes certain types of misbehavior more costly or less profitable.
Burning tokens benefits all token-holders
equally in proportion to how many tokens they own,
while an adversary who expects to be caught
can always collect the tattletale rewards
from proving their own misbehavior.

With a high tattletale transfer efficiency
(80% for the sake of illustration)
Alice and Bob could collaborate to misbehave and collect the tattletale reward,
reducing the effective deterrent very significantly.
If Alice and Bob together own 30% of the token supply,
they would only suffer 14% of the nominal punishment:
Alice would collect 80 KEEP as her tattletale reward
and their remaining holdings would indirectly accrue
30% of the value of the burned 20 KEEP (6 KEEP).
With a 95% minimum burn Alice and Bob could only recoup 33.5%:
5 KEEP as tattletale reward and 28.5 KEEP indirectly (95 KEEP * 0.30).

Similarly, if Alice has compromised Bob's operator keys
she could use tattletale transfer to steal Bob's stakes.
It is desirable that compromised operators' stakes can be stolen,
but it is also desirable to limit the fraction of the token supply
owned by proven malicious parties.
Some have estimated that 5% of all BTC have been stolen.
If a similar amount of KEEP were to be stolen from compromised operators,
with a 95% minimum burn
the thieves would only represent 0.25% of stakeable tokens.

===== Limiting tattletale transfer: locking tattletale rewards

As a further obstacle to "advance withdrawals" via tattletale transfer,
all tattletale rewards could be locked for a time
equal to the unstaking time (e.g. 3 months).
With a 95% minimum burn and 3 month lock on tattletale rewards,
the amount that can be "advance withdrawn" with tattletale transfer
is less than the amount that would vest by the time the tokens are freed
for grants vesting in less than 60 months.

==== Revocable grants and illusory stake

If Alice is expecting her grant to be revoked in the near future,
the value of her unvested tokens at that time is effectively zero.
This _illusory stake_ significantly weakens the effective deterrent
when staking with revocable grant tokens.

==== Trusted staking contracts and upgrading them

If unvested grant tokens can be staked,
staking contracts are privileged towards grants;
the grant contract trusts the staking contract not to behave in certain ways
without being able to enforce it.
If a grantee could stake their grants on arbitrary contracts,
they could make up their own "staking contracts"
that exploit grant staking to the maximum possible extent.

This presents a problem with upgrades.
The RFC 11 upgrade process consists of Keep Org deploying a new staking contract
and stakers migrating their stakes by unstaking and re-staking.
The token grant scheme must not prevent staking upgrades
while grants are active,
but the addresses of future staking contracts are unknown.

=== Previously considered schemes

==== Unlimited stake-ahead

In the unlimited stake-ahead model,
grantees can instruct the grant contract
to stake all of their grant tokens
by transferring an equal amount of liquid tokens to the staking contract.
The grant contract acts as the _owner_ of the tokens;
grantees nominate the _operator_, _beneficiary_, and _authorizer_,
and can acquire rewards from operating with the stake as collateral.
Upon unstaking the tokens are returned to the grant.

The grant contract can be unprivileged,
affecting only the security of tokens involved in grants,
and no special considerations are required in the staking contract.
However, unlimited stake-ahead provides no protection from t-transfer abuse
or illusory stake.

==== Limited stake-ahead

In the limited stake-ahead model,
grantees can only stake tokens that would vest within the unstaking time.
The grantee can be assigned as the owner,
as the amount of tokens that become liquid upon unstaking 
equals or is less than the amount
they would have otherwise been able to withdraw from the grant.

Limited stake-ahead preserves normal incentives with non-revocable grants
but doesn't protect against illusory stake.
It also places short grants in a significantly more favorable position
as they can stake their tokens earlier.

==== Grant tokens as a separate type of collateral

If the special status of grant tokens is maintained when staking,
any tattletale rewards would simply consist of another grant, vesting over time.
This prevents premature withdrawals with t-transfer,
but doesn't address illusory stake.

Recognizing grants as valid collateral
makes the grant contract a part of the security-critical core;
if someone could arbitrarily manipulate the grant contract
they would be able to create unlimited amounts of forged collateral.
Additionally, calculating correct vesting times is complex
as grants are split by slashing and tattletale transfers.

==== Enforcing invariants with a staking proxy

If a separate staking proxy is established
between the grant contract and staking contracts,
the grant contract could transfer liquid tokens to the proxy
which then enforces the desired _staking invariants_
on arbitrary staking contracts.
This protects the integrity of grants
by making staking contracts unprivileged,
and the effectiveness of t-transfer could be limited by the right invariants.

If the majority of slashed tokens are burned
and only a small fraction can be seized
and possibly used as a tattletale reward,
t-transfer becomes dramatically less abusable.

However, a staking proxy has to
duplicate large parts of staking contract functionality,
and cross-contract calls make staking operations more expensive.
Behavior defined in the proxy is permanently immutable
unless the proxy itself is upgradeable.

== Proposal

Non-revocable token grants are staked with unlimited stake-ahead,
by transferring liquid tokens from the grant contract
to a staking contract authorized by the grant's manager,
appointed by the grant creator upon grant creation.
Revocable grants can't be staked through the grant contract;
instead, vested liquid tokens can be withdrawn and staked normally.

_Authorized staking contracts_ are assumed to enforce the invariants
a particular grant's manager wants enforced.
For the use of Keep Org's grants,
this consists of a _minimum burn fraction_ of 95%:
when a staker is slashed,
at least 95% of the tokens are burned and at most 5% are seized.

Authorized staking contracts are identified
using a two-role authorization from RFC 11:
the grant manager can authorize contracts from a global master list
of staking contracts sanctioned by the governance structure.

Upgrades to staking contracts are accommodated
by providing a way for the grant contract
to pass arbitrary instructions from the grantee to the staking contract.

=== Goal

Unprivileged grant contract::
The security of the Keep network as a whole should be unaffected
even if the grant contract were to execute arbitrary malicious code.

Upgradeable staking contract::
The grant scheme should not prevent future improvements to the staking scheme
as defined in RFC 11.

Fair grant staking::
The recipient of a non-revocable grant
should be able to stake with the full grant.
A grant's vesting schedule should only determine
the amount of liquid tokens the grantee could withdraw at a given time.

Limited tattletale transfer::
Abusing tattletale transfer to violate the rules of a token grant
should provide little benefit at a significant cost.

No illusory stake::
The need for a reliable deterrent to misbehavior is prioritized
over revocable grantees' opportunity to obtain staking rewards.

=== Implementation

A token grant represents a gradual transfer of KEEP tokens
from the creator of the grant to the _grantee_ (grant recipient).

A token grant is characterized by its _basic parameters_
and its _vesting schedule_.

==== Basic parameters

The basic parameters of a token grant
include the _grant manager_,
the _grant recipient_,
the _grant amount_
and the _revocability_ of the grant.

Grant manager::
The address appointed to manage the grant.
If the grant is irrevocable,
the grant manager may determine the _authorized staking contracts_
the grant can be staked on.
If the grant is revocable,
the grant manager may revoke the grant.

Grant recipient::
The address of the party receiving the grant.
The recipient may withdraw vested tokens from the grant,
or stake non-revocable grant tokens.

Grant amount::
The number of tokens involved in the grant.

Revocability::
Whether the grant is revocable (_True_) or non-revocable (_False_).

===== Revocability

Token grants may be _revocable_ or _non-revocable_.
A non-revocable grant represents an irreversible transfer of tokens
that, once initiated, cannot be stopped or altered.
A revocable grant represents a conditional transfer,
subject to continuing consent of the grant manager.
The grant manager can revoke a revocable grant at any time.
If a grant is revoked,
all unvested tokens are returned to an address specified by the grant manager.
Vested tokens remain in the grant
and are available for the grantee to withdraw.

==== Vesting schedule

Tokens in a grant are locked until _vested_
according to a linear schedule defined by
the _starting time_,
_grant duration_
and the _vesting cliff_.

Tokens in the grant start vesting at the starting time,
becoming available for withdrawal gradually over the grant duration.
The vesting cliff denotes the earliest time
tokens can be withdrawn from the grant.

Vested tokens that aren't otherwise in use
can be withdrawn at the grantee's discretion.

Starting time::
The time the grant begins vesting.
The starting time of a grant
may differ from the exact time the grant creation transaction is processed.

Grant duration::
Time after starting until the grant is fully vested
and all tokens may be withdrawn.

Vesting cliff::
The earliest time after starting tokens can be withdrawn from the grant.

==== Creating a token grant

A token grant is created by submitting a transaction
defining the _basic parameters_ and the _vesting schedule_,
and transferring the _grant amount_ of tokens to the grant contract.

===== Example

Alice wants to transfer 1,000 KEEP to Bob and Carol each.
Bob should receive his tokens over 12 months,
and be able to start withdrawing tokens after 1 month.
Carol's grant should be revocable,
lasting 24 months with a 6 month vesting cliff.

----
Grant 1
Manager: Alice
Recipient: Bob
Amount: 1,000 KEEP
Starting time: T_0
Duration: 12 months
Vesting cliff: 1 month
Revocable: False

Grant 2
Manager: Alice
Recipient: Carol
Amount: 1,000 KEEP
Starting time: T_0
Duration: 24 months
Vesting cliff: 6 months
Revocable: True
----

==== Grant status

When a grant is created,
all grant tokens start unvested and unstaked.

Over time, grant tokens will vest
and become available for withdrawal as liquid tokens.
_Vesting status_ is calculated implicitly
from the vesting schedule and the current time.

Grant tokens can be withdrawn once vested.
Non-revocable grant tokens can also be staked,
and staked tokens can be lost as punishment.
The _usage status_ of a grant's tokens tracks these developments.

===== Vesting status

All grant tokens are either _vested_ or _unvested_.
The vested amount at some time
represents the maximum number of tokens that may be withdrawn at that time.
Grant tokens vest linearly over the grant duration;
when half of the grant duration has elapsed
50% of the grant tokens will have vested, and so on.
However, until the vesting cliff is reached,
the number of vested tokens is fixed at zero.

The amount of vested tokens at time `time_now` is calculated as follows:

[source, python]
----
time_elapsed = time_now - time_starting
cliff_reached = time_now >= vesting_cliff

if cliff_reached:
    vested_fraction = time_elapsed / grant_duration
else:
    vested_fraction = 0

vested_tokens = grant_amount * vested_fraction
----

3 months in, Bob's vesting cliff has been reached,
so the amount of vested tokens in Bob's grant equals
`1000 KEEP * (3 months / 12 months) = 250 KEEP`.
Carol's 6-month vesting cliff has not been reached;
if it had, her grant would have
`1000 KEEP * (3 months / 24 months) = 125 KEEP`
available for withdrawal.

===== Usage status

The _usage status_ of a grant's tokens consists of
_available_, _withdrawn_, _staked_, and _slashed_;
all grant tokens fall within one of these categories.

_Withdrawn_ means tokens that have vested
and been withdrawn from the grant as liquid tokens.
The number of withdrawn tokens is tracked in its own entry,
which is updated whenever a successful withdrawal is performed.

_Staked_ grant tokens are actively being used
as collateral for staking.
The number of staked tokens is calculated
by summing the _staked amount_ in each individual _grant stake_ of the grant.

_Slashed_ grant tokens were staked and have been lost in a penalty.
The grant tracks the number of slashed tokens explicitly.
When a grant stake has finished unstaking and its tokens are returned,
the difference between the returned amount and the original stake
is added into the slashed tokens.
With revocable tokens, the _slashed_ status is used for revocation.

Tokens in the grant that aren't _withdrawn_, _staked_, or _slashed_
are _available_ by default.
Available grant tokens can be withdrawn if the vesting schedule permits,
or staked if the grant is non-revocable.
The number of available grant tokens is calculated
by subtracting _withdrawn_, _staked_ and _slashed_ tokens
from the grant amount.

===== Grant stakes

When non-revocable grant tokens are staked,
some relevant information is stored in a _grant stake_ entry.
Each non-revocable grant maintains a list of its grant stakes.

A grant stake entry includes
the _staking contract_ used for the stake,
the _operator address_ of the stake,
and the _staked amount_ originally transferred to the staking contract.
Grant stakes can be uniquely addressed by the pair
`(staking_contract, operator_address)`.

A grant stake entry is erased
when its corresponding stake has finished unstaking
and its tokens are successfully returned to the owner.

==== Grant records

Each token grant is stored in the _grant contract_ as a _grant record_.
The grant record consists of the following:

* Basic parameters:
  * _grant manager_
  * _grant recipient_
  * _grant amount_
  * _revocability_
* Vesting schedule:
  * _creation time_
  * _grant duration_
  * _vesting cliff_
* Grant status records:
  * _withdrawn tokens_
  * _slashed tokens_
  * _grant stakes_

==== Staking token grants

Non-revocable token grants are staked
by instructing the grant contract to stake them
with an _operator_, _beneficiary_ and _authorizer_ appointed by the _grantee_.
The grant contract acts as the _owner_ of the stake.

Both vested and unvested tokens can be staked
and the rewards collected by the grantee.

==== Authorized staking contracts

In the _authorized staking contracts_ model,
grants can be staked in any staking contract
that has been approved by the _grant authorizer_.
The _grant authorizer_ is expected to audit new staking contracts
and verify that they enforce the desired invariants adequately,
before approving them for staking grants.

When a staking contract has been approved,
the grant contract will trust it to enforce the staking invariants
and any grantee can direct the grant contract
to stake some or all of their _available tokens_
(not already staked or withdrawn) in the grant.
The grant contract will then transfer the specified amount of tokens
to the staking contract,
along with all other necessary information.
The stake is recorded in the grant contract,
and the staked amount subtracted from the _available tokens_ in the grant.

The grant contract takes the role of the _owner_ in the staking contract,
while the _operator_, _beneficiary_ and _authorizer_
are defined by the _grantee_.
Any rewards or punishments to the staker are applied in the staking contract,
without involving the grant contract in any way.

When the grantee wishes to unstake,
they direct the grant contract
to unstake and reclaim the remaining tokens.
Unstaking and reclaiming tokens
terminates the staker relationship between the _owner_ and _operator_,
and all remaining stake is returned to the _owner_.
Therefore, if the _returned amount_ is less than the original _staked amount_,
the difference has been slashed in punishment
and is recorded in the grant contract as such.
Redelegating grant stakes is not supported.

===== Option A: registry master as grant authorizer

In option A,
any staking contract listed on the _registry_
as a _sanctioned staking contract_
is automatically authorized for grant staking.

If the role of the _registry master_ is compromised,
arbitrary "staking contracts" can be authorized.
Existing stakes on legitimate staking contracts are unaffected,
but unstaked irrevocable grants can be emptied.

===== Option B: global grant authorizer

In option B,
the grant contract has its own _grant authorizer_ role,
approving staking contracts for all grantees.
All grants share the same authorized staking contracts,
ensuring that the disappearance of the grant manager
does not prevent grantees from staking on new contracts.

A staking contract can be approved by the grant authorizer
only if it has been _sanctioned_ on the registry.
The authorizations in Option B are similar to
how _service contracts/gateways_ are managed in RFC 11.
As in RFC 11, the compromise of neither the _registry master_
nor _grant authorizer_ alone can compromise token grants;
both must be compromised simultaneously.

===== Option C: grant manager as grant authorizer

In option C,
_grant managers_ authorize staking contracts
for all grants they manage.
Grants with the same _grant manager_
share the same authorized staking contracts.

Like in option B,
staking contracts must be _sanctioned_ to be authorized.

==== Operations on grants

===== Withdrawing tokens

_Vested_ tokens that haven't already been _withdrawn_
can be withdrawn at the discretion of the grantee, if tokens are available.
The amount of tokens that can be withdrawn at a point in time
equals `min(available, (vested - withdrawn))`.

To withdraw, the _grantee_ requests a withdrawal
and specifies a _withdrawal amount_.

If the _withdrawal amount_ is equal or less than
the _maximum withdrawal_ at the time,
the grant contract will add _withdrawal amount_ to the _withdrawn_ tokens
and send the grantee _withdrawal amount_ tokens.

If the _withdrawal amount_ exceeds the _maximum withdrawal_,
the withdrawal will fail.

===== Staking tokens

_Available_ tokens can be staked regardless of vesting status.

To stake, the _grantee_ specifies a _staking amount_,
the _staking contract_ to stake in,
and the _operator_, _beneficiary_ and _authorizer_.
The grantee must also provide a signature from the _operator_
to operate for the _grant contract_ as the _owner_.

The _staking amount_ must be
equal or less than the number of _available_ tokens.
The _staking contract_ must be approved by the applicable _grant authorizer_.
If either condition is not satisfied, the staking request will be rejected.
If both conditions are satisfied,
the grant contract will attempt to stake _staking amount_ tokens
at the _staking contract_,
using the supplied _operator_, _beneficiary_ and _authorizer_ addresses.

The _grant stake_,
consisting of the triplet `(staking_contract, operator, staking_amount)`,
is recorded in the grantee's _grant stakes_.
The _staking amount_ is added to _staked_ tokens of the grant,
reducing the _available_ tokens by the same amount.

===== Unstaking a grant stake

At any time, the grantee can request any _grant stake_ to be unstaked.
To unstake, the grantee specifies the _staking contract_ and _operator_
of the _grant stake_ they wish to initiate unstaking on.

If the combination of _staking contract_ and _operator_
matches an active _grant stake_ of the grantee,
the grant contract will request the _staking contract_ to initiate unstaking.
Otherwise, the grant contract will ignore the request.

===== Reclaiming tokens from an unstaked grant stake

At any time, the grantee can request any _grant stake_ to be reclaimed.
The grantee specifies the _staking contract_ and _operator_
of the relevant _grant stake_.

If the grantee has a matching _grant stake_,
the grant contract will request the _staking contract_
to return unstaked tokens.
Otherwise, the grant contract will ignore the request.

If reclaiming the tokens fails,
the grant contract will assume the stake had not finished unstaking
and will not modify the _grant stake_ information.

If reclaiming the tokens succeeds,
the grant contract will note the _returned amount_.
If the _returned amount_ matches the original _staking amount_,
the _returned amount_ is subtracted from _staked_ grant tokens
and added to _available_ grant tokens.
If the _returned amount_ is less than the original _staking amount_,
the _difference_ is added to _slashed_ grant tokens,
the _staking amount_ is subtracted from _staked_ grant tokens,
and the _returned amount_ is added to _available_ grant tokens.
In either case, the _grant stake_ is removed.

===== Revoking the grant

A revocable grant can be revoked at any time by the grant manager.
Revoking a grant slashes its unvested tokens,
transferring them to an address specified by the manager.

Grants are revoked by submitting a transaction
specifying the grant to be revoked
and the recipient address.

The grant contract checks that the grant exists,
is revocable,
and the transaction was sent by the grant manager.

A revocable grant cannot be staked,
so the slashed amount on a revocable grant shows whether it has been revoked.
If the grant already has slashed tokens,
it has been revoked earlier and the repeat revocation is ignored.

If the checks pass,
the amount of unvested tokens in the grant is calculated.
The _unvested amount_ is added to the _slashed_ grant tokens
and transferred to the recipient address.

=== Limitations

Without TATTLETALE_LOCK,
grantees can abuse t-transfers to withdraw more than the vested amount
although at the expense of the remaining grant

Even with TATTLETALE_LOCK, revocable grants can still be overwithdrawn
if any level of stakeahead is permitted

=== Proof of Concept

If you have PoC code, refer to the relevant branch and give a brief summary.

== Future Work (optional)

If applicable, what future evolutions could you see this approach leading to?
Particularly if these possibilities influenced your thinking about the main
proposal, this is important.

== Open Questions (optional)

Should TATTLETALE_LOCK be implemented,
or is the loss of MINIMUM_BURN_FRACTION sufficient
to disincentivize tattletale transfer

How to deal with revocable grants:
unlimited stakeahead as with non-revocables,
limited stakeahead,
or no staking of unvested tokens at all

[bibliography]
== Related Links

- Flowdock Links
- Other links
- If you have publications, you can include them in bibliography style. If you
  start your bullet with an id in _triple_ square brackets (e.g. `+[[[AAKE]]]+`),
  you can reference it in the content body using regular cross-reference syntax
  (e.g. `+<<AAKE>>+`).
