:toc: macro

= RFC 6: Group expiration specification

:icons: font
:numbered:
toc::[]

== Proposal
This document focuses on specifying a group expiration mechanism. The proposed
functionality enables a group to expire after a particular condition is met.
An expired group can not be chosen to perform new actions, but any ongoing group
actions will continue until finished.

=== Goal
The goal is to provide a minimal set of functions necessary for implementing the
group expiration mechanism into the Keep network. The group expires when group
expiration timeout passes.

=== Terminology

work contract:: Referes to any contract performing a system action for which it
  needs to have an active group assigned. 

== Specification

=== Contract

Group selection contract should include the following information:

- active groups list (with group formation agreements),
- active groups counter,
- active groups threshold (which protects the network from expiring all groups),
- expired groups list,

and (per group formation agreement):

- group formation agreement identifier,
- group members identifiers,
- registration time when the group was created,
- timeout, after which the group expires,
- current state indicating if the group is active or expired.

The contract should also have the following discrete pieces of functionality:
<<registration, group registration>>, and <<selection, group selection>>.

=== Functionality

[#registration]
==== Registration
When a group is formed, the group formation agreement is added to the active 
groups list, the active groups counter is incremented, and the 
agreement is filled with:

- unique group formation agreement identifier,
- group members identifiers,
- registration time set to current block time,
- timeout evaluated as the time required to mark a group as expired, counted in
  blocks, (it might be explicit or implicit),
- current agreement state set to _active_.

[#selection]
==== Selection
When a group selection is invoked, the work contract (the one that is
starting the group selection) needs to call the group selection contract. When
called, the group selection contract selects at random potential group from the 
active groups list and performs the <<verification, group status verification>>.
And then the 
<<response, group selection contract responds with group information>>.

[#response]
===== Group information response
The group selection contract presents the selected group to the work contract.

The work contract is obligated to forbid non-members from group work.

[#verification]
===== Group status verification
If the number of active groups is below the _active groups threshold_ all
remaining groups on the _active groups list_ are treated as _active_.

Otherwise, the following is performed.

If the current block time is larger than the group registration time plus the
timeout then set the group agreement status to _expired_. Move the expired group
agreement from the _active groups list_ to the _expired groups list_ and
decrease the _active group counter_ by one. Then the next group is selected and
its status is verified until an active group is found or the number of active
groups falls below the _active groups threshold_.

Expired groups need not be tracked for an unlimited time. They might be removed
when deemed unnecessary for current network operations.

[bibliography]
== Related Links
- https://docs.keep.network/random-beacon/group-expiration/
- https://www.flowdock.com/app/cardforcoin/keep/threads/NL6VK7goghV9QaWUXyFT_YgwV_M
