:toc: macro

= RFC 3: Stake delegation requirements

:icons: font
:numbered:
toc::[]

== Background

Keep tokens are going to be staked by having token owners delegate their staked
balance to an operator account and use it to run the Keep Client. The operator
account cannot access the stake directly, nonetheless, it operates on behalf of
the owner and bad acting will result in slashing the owners' stake. The operator
may be a third party, or it may be a different address controlled by the owner.

Stake delegation will be beneficial for the security of Keep users as it allows
for on-stake operations with a "cold wallet". Thus, putting Keep users wallets
offline protects them from "hacks" and stake delegation enables continuous
rewarding on safe operations on staked assets. 

=== Terminology

owner:: The address of an owner of the staked tokens.

operator:: The address of a party authorized to operate a stake on behalf of a
  given _owner_.

beneficiary:: The address where the rewards for participation are sent, earned by an
  _operator_, on behalf of an _owner_.

delegated stake:: An _owner_'s staked tokens, delegated to the _operator_ by the
  _owner_.

on-stake:: Refers to the type of operations performed by an _operator_ on a
  _delegated stake_.

== Proposal

Stake delegation enables a token _owner_ to delegate their already-staked tokens
to an _operator_ and enables an _operator_ to operate staked tokens on behalf
of the _owner_. The owner also defines a _beneficiary_ address (recipient) where all
rewards generated by the _operator_ for the staked tokens are sent.

=== Goal

The goal of this proposal is to specify a simple and secure stake delegation
mechanism. It should enable Keep users to have their wallets offline and their
stake operated by operators on their behalf. The Keep client software should
be able to run without exposing Keep operator's private key and should not
require any owner's keys at all. The stake delegation should also optimize
the network throughput without compromising the security of owners stake.


=== Design Assumptions

1. _owner_ can only have one operator.
2. _owner_ can only delegate all of his stake.
3. _operator_ cannot have any KEEP tokens at all.
4. _operator_ can only have a _delegated stake_ from only one _owner_.
5. If an _owner_ tries to delegate to more than one operator, the tx must
fail.
6. If an _owner_ tries to delegate a stake to an _operator_ who already has a
stake, the tx must fail.
7. The end of an _on stake operation_ happens only after all rewards are
granted and all penalties are imposed. 
8. Rewarding and penalization happens as the last phase of all operations.


=== Design Factors Analysis

During the design, we have considered several different factors that impact the
performance and the security of the proposed solution. We are going to discuss
them in more detail in this section.

==== Operating

Operating is the first of the analyzed factors. It has the greatest influence on
performance as it is strictly associated with network throughput. We have
analyzed the following operating strategies and their impact
on the proposed solution.

===== Atomic Operating

Atomic operating is an operating strategy that allows an operator to only
perform one staking operation at a time. Such an operation locks the stake, and
no other operation can be done until the end of the current operation.
This ensures that the stake cannot be changed during the on-stake operation.
Hence, we achieve a high level of stake protection.

The downside of this solution is that the network throughput is strongly limited
as the maximal number of possible concurrent operations is TOTAL_SUPPLY /
MINIMUM_STAKE.

===== Multi-Operating

The second analyzed operating strategy is multi-operating, where the number of
on-stake operations is not limited. Using this strategy an operator can perform 
as many on-stake operations as possible and is only limited by the stake that is
delegated to him. In other words, an operator cannot perform a single on-stake
operation with more than his delegates stake but can simultaneously execute an
arbitrary number of operations with the same delegated stake. Therefore, the
multi-operating strategy achieves the highest possible network throughput.

Unfortunately, the multi-operating strategy can lead to severe security and
economic ramifications. For example, with such an unlimited operating, an 
operator can execute such a high number of on-stake operations that the combined
penalties would be larger than the total owner's stake, depleting their entire
stake.

Another issue that is associated with multi-operating, assuming that it is
possible to withdraw a fraction of stake instantly after being selected to the
group, is as follows.
If an operator A operates on more than the MINIMUM_STAKE he can participate in
the same number of operations as an operator B who has multiple MINIMUM_STAKE
and both will get the same rewards.
Such a possibility might have a negative impact on the owners' motivation to
delegate more than the necessary minimum to get more rewards.

===== Atomic Multi-Operating

The third analyzed strategy is a hybrid approach where we combine atomic
operating with multi-operating. This strategy enforces that when an on-stake
operation is performed, a portion of a delegated stake is locked (e.g.
MINIMUM_STAKE if the penalty for misbehaving is lower than the MINIMUM_STAKE or
MAXIMAL_PENALTY otherwise) and cannot be used for other operations until the end
of the current operation. Hence, achieving the stake atomicity. The operator can
use the remaining delegated stake for other concurrent on-stake operations.
Therefore, achieving the multi-operating feature. No more operations are
permitted when the amount of unlocked stake is lower than the required portion
of a stake to be locked.

This strategy protects the stake of the owner from being rapidly depleted,
unlike the pure multi-operating. It also enables higher network throughput than
the pure atomic operating strategy.

The atomic property limits the operating leverage introduced by the
multi-operating strategy. It gives more control over the number of operations
that an operator can perform. Therefore, it promotes owners with a more
delegated stake as more stake is operated, more rewards can be received. The
controlling mechanism of atomicity can be used in a more flexible manner to
increase network throughput. This can be achieved by introducing a stake
operation multiplier, where each operator is allowed to operate on a multiple of
the delegated stake. This mechanism can be used as an additional benefit for
early players and the value of multiplier could gradually decrease over time.

==== MINIMUM_STAKE

The MINIMUM_STAKE plays a crucial role in the process of on-stake operations. It
is the limiting factor of how many concurrent operations an operator take part.
Therefore, we have also analyzed two possible scenarios for setting
MINIMUM_STAKE.

===== Static MINIMUM_STAKE

The static approach towards MINIMUM_STAKE is that its value does not change
during the lifetime of the system. It can only be updated during the hard forks.
This makes the system easier to implement but less flexible for external
economic factors. During the lifetime of the system, the costs of operations
might change significantly and rapidly, limiting the affordability of further
operations. 

===== Dynamic MINIMUM_STAKE

Dynamic MINIMUM_STAKE enables flexible changes of the MINIMUM_STAKE value during
the lifetime of the system without forcing a hard fork. This approach makes the
system more flexible for adjusting the on-stake operating prices and makes the
system more rigid against external economic factors. The downside of this
approach is its implementational and operational complexity.

==== Undelegation

Last analyzed factor is undelegation strategy. The way how the stake delegation
is canceled plays a crucial role in protecting owners stake against misbehaving
operators.

===== Instant Undelegation

The first undelegation strategy is an instant undelegation. It is a 
straightforward approach where an owner or an operator revokes the stake
delegation. When such undelegation is invoked an operator instantly stops all
on-stake operations and the stake is returned to the owner. As a result of
stopping all of the on-stake operations, the resulting penalties are imposed on
the owner's stake. Here we can distinguish between undelegation penalties being
treated as inactivity, misbehavior, or as a separate type of penalty - which
will be discussed in the penalization section. 

===== Delayed Undelegation

The second strategy for the undelegation is a delayed undelegation. When a stake
delegation is revoked using this strategy, the delegated stake is locked for an
UNDELEGATION_TIMEOUT period. Starting from the undelegation initiation and
during the UNDELEGATION_TIMEOUT no new on-stake operations are allowed (any
attempt should be rejected). All of the already started on-stake operations that
will finish before the UNDELEGATION_TIEMOUT are treated as usual and all rewards
and penalties are calculated normally. If an on-stake operation will not end
before UNDELEGATION_TIMEOUT period it needs to be terminated instantly at the
end of the timeout and the owner stake will be penalized accordingly to the
penalization strategy. Therefore, the safest option here is to have
UNDELEGATION_TIMEOUT as long as necessary to safely end all of the ongoing
operations - it should be longer than duration of any operation in the network.
After the UNDELEGATION_TIMEOUT the delegated stake is unlocked and is returned
to the owner.

==== Penalisation

Last key factor impacting the performance of the solution and its security is
the cost of undelegation. The impact of the stake delegation on the mechanics
and economy of the solution is strictly related to the way how the undelegation
happens. In this section, we will discuss several undelegation penalization
strategies.

It is important to emphasize that the penalization happens only when an
undelegation hits an ongoing operation and that operation will not end before an
effective undelegation. Therefore, any operation that will end before the
UNDELEGATION_TIMOUT will not be penalized.

===== Inactive (zero cost)

First penalization strategy is to treat the stake undelegation on an ongoing
operation as an operators inactivity. This strategy does not require excessive
mechanics as the network should verify in every step the eligibility of the
operator to participate in an operation. From the perspective of the owner and
impact on the stake, this would be the most beneficial strategy as the stake
would not be impacted as the result of the undelegation.

The downside of this approach is that it could be used as a fairly cheap way for
an owner to resign from an unfavorable operation due to the low cost (virtually
zero cost) of the inactivity penalty. This could lead to major instability of
the network operations.

===== Misbehaving (normal cost)

Second penalization strategy is to treat an operator as misbehaving as the
result of the undelegation. The undelegation happens on-chain, therefore, we can
perform normal penalization as we have an on-chain proof. This strategy is most
beneficial for the network as it protects other participants from the
undelegation abuse.

The downside of this strategy is its implementation complexity as it requires
tracking the undelegation events and aligning them with the inner workings of a
particular operation (including adding an internal mechanism for proofing and
validating an external undelegation event). 

===== Consequent (opportunistic cost)

A third strategy is a consequent approach, where an undelegated operator is
treated as an inactive until an operation fails. If the operation fails due to
inactivity of the operator, he will be marked as misbehaving and the owner will
be adequately penalized.

=== Design Strategy

Each of the analyzed factors is orthogonal and required to be a part of the
designed architecture. As the goal of the proposal is to provide a solution that
has high network throughput and is secure we need to eliminate less optimal
strategies.

==== Operating

The Atomic Operating is the strategy that has the lowest network throughput,
therefore it should be rejected.

The Multi-Operating strategy is the theoretically slightly less secure, but
practically at the same level of security as Atomic Operating, therefore it
should be considered as an available solution.

The Atomic Multi-Operating strategy is also a viable solution as it provides
higher network throughput (assuming version with stake multiplier) than the
Atomic Operating and theoretically more secure than the Multi-Operating (against
"leveraged staking/penalization") but realistically similar. One of the benefits
over Multi-Operating is the possibility to control the network throughput
through the stake multiplier, which might become an important feature for
mitigating the influence of external (associated) currencies fluctuations on the
economy of the solution.

==== MINIMUM_STAKE

Both dynamic and static MINIMUM_STAKE strategies are valid ones and do not
influence the performance of the network heavily. The dynamic one has an
advantage over static one for being more resilient against external factors but
for the cost of increased complexity. Therefore, a more optimal choice would be
the dynamic MINIMUM_STAKE strategy.

==== Undelegation

The Instant Undelegation is associated with high-security risks and in the case
of a deliberate operators misbehavior can lead to sever owner stake
penalization. Therefore, it should be rejected.

The Delayed Undelegation bares lower security risk and should be perceived as
the best choice.

==== Penalisation

Both Consequent and Misbehaving Penalisation strategies have an adequate
influence on the performance and the security of the solution. The Consequent
Penalisation tends to be more liberal and might lead to minor abuse but its
impact on the network throughput is minimal. The Misbehaving Penalisation is
more strict and might enforce more conservative behavior of the operators.

The Inactive Penalisation should be rejected as it enables zero cost end of the
operation which might impact negatively on the network stability and performance.


=== Architecture

Accordingly to the design strategy and the design requirements the design
architecture should be based on the following combinations of strategies:

(optionally Atomic) Multi-Operating with Dynamic or Static MINIMUM_STAKE and 
Delayed Undelegation with Consequent Penalisation

Other strategies tend to be suboptimal from the perspective of both security and
network throughput requirements, or from implementation.


=== General requirements notes

==== Slashing operator
Adding a slashing bound between an owner and an operator should create positive
feedback and decrease an operators motivation to misbehave. This can be done
either by defining an additional slashing address for the operator or by
enabling the operator to have its own stake. Therefore, the requirement from the
operator to not have any stake might be loosened.

==== Operator and owner on the same address
If an operator would be allowed to have his own stake and to operate on it, then
it might be possible to allow an address to be both the operator and the owner.
This might be contradicted by the security and privacy argument as we want to
separate roles/addresses to protect owner keys from the exposure.

== Open Questions

How is this going to interact with RFC 4 (on secure upgrades)?

Can we have different stake delegation contracts at the same time? - The
mechanics of proposed contracts might not be conflicting with each other and it
might be beneficial to have parallel contract types fulfilling the particular
needs of our users.

=== Penalization
How to penalise misbehaviour?

Should an _operator_ have an accountable address which will be slashed?

=== Timeouts
What timeouts are reasonable?

== Future work
Consider how the stake delegation will interact with ETH bonding (part of Keep,
but not the beacon).

[bibliography]
== Related Links
- https://www.flowdock.com/app/cardforcoin/tech/threads/UQhnqrQAWk3azp2TO9UhOJQRMXp
- https://www.flowdock.com/app/cardforcoin/keep/threads/TA-Jwe9oMaOBAylc3yRJObc5Bq_
- https://www.flowdock.com/app/cardforcoin/keep/threads/k6MV7jS9DEd0DnvOpkAt5SjsS9w
- https://www.flowdock.com/app/cardforcoin/tech/threads/-Lbr4JzmX0gY31CMDTRGnQUbbuw
- https://github.com/keep-network/keep-core/pull/121
- https://github.com/keep-network/keep-core/blob/76e3e68430576c21ac76c0a56eec4a320a39a5e2/docs/random-beacon/delegation-notes.adoc
- https://www.flowdock.com/app/cardforcoin/keep/threads/kLxyy_0DH71UiQkTXHRQnaZyN_C
