:toc: macro

= RFC 5: Stake delegation specification

:icons: font
:numbered:
toc::[]

== Proposal

<<rfc-3-stake-delegation-requirements, RFC 3,>> discusses the architectural
tradeoffs to be considered for the stake delegation design. That document
concludes with the preferred architectural approaches, and the remainder of this
section describes a subset of these. The approaches in RFC 3 that are not
detailed below are omitted in the interests of a simpler initial implementation,
but may be layered on in later RFCs. For now, this document focuses on a system
that uses _multi operation with static minimum stake and delayed undelegation
with consequent penalisation_. 

=== Goal

The goal of this proposal is to specify a simple and secure stake delegation
mechanism. It should enable Keep users to have their wallets offline and their
stake operated by operators on their behalf. The Keep client software should
be able to run without exposing Keep operator's private key and should not
require any owner's keys at all. The stake delegation should also optimize
the network throughput without compromising the security of owners stake.

=== Terminology

owner:: The address of an owner of the staked tokens.

operator:: The address of a party authorized to operate a stake on behalf of a
  given _owner_.

beneficiary:: The address where the rewards for participation are sent, earned by an
  _operator_, on behalf of an _owner_.

delegated stake:: An _owner_'s staked tokens, delegated to the _operator_ by the
  _owner_.

on-stake:: Refers to the type of operations performed by an _operator_ on a
  _delegated stake_.

operation:: A set of interactions with the system with a defined start and
  finish, executed entirely by an _operator_, during which the operator does
  tasks on behalf of all or part of a _delegated stake_.

=== Design Requirements

1. _operator_ can only have a _delegated stake_ from only one _owner_.
2. The end of an _on stake operation_ happens only after all rewards are
granted and all penalties are imposed.
3. Rewarding and penalizing happens as the last phase of all operations.

== Roles

In this proposal, we are specifying three roles: owner, operator, and beneficiary.
They are briefly characterized in this section.

=== Owner

The owner is the ultimate holder of the tokens. Before stake delegation, the
owner has full control over the tokens, and the tokens are returned to the owner
after stake delegation has finished. The owner's participation is not required
in the day-to-day operations on the stake, so cold storage can be accommodated
to the maximum extent.

The owner can <<delegating, delegate its stake>>,
<<undelegating, undelegate its stake>> and
<<restoring, restore the delegated tokens>>.

=== Operator

The operator handles the everyday operations on the delegated stake without
actually owning the staked tokens. While this enables third-party delegation
without, e.g., making it possible for the operator to simply transfer away
tokens, it should be noted that a malicious operator can exploit stake slashing
to destroy tokens and thus the entire staked amount is indeed at stake.

The operator address is used to provide network functionality by
<<operating, participating in various operations>>.

The operator can unilaterally <<undelegating, finish delegation>> 
and <<restoring, restore the tokens to the owner>>.

=== Beneficiary

The beneficiary collects <<rewarding,rewards>> earned from
<<delegating, stake delegation>> and
<<operating, participation in the network>>. The beneficiary doesn't sign or publish
any protocol-relevant transactions, but any currency or tokens earned by the
operator will be transferred to the beneficiary.

== Specification Features

Following is a high-level description of each of the features in that sentence:

Multi Operation::
    A feature that enables a virtually unlimited number of operations on a
    delegated stake. It allows operators to operate on a delegated stake without
    any limits (except the minimum stake requirements).

Static Minimum Stake::
    A feature that determines the value of the minimum stake will be constant
    through the network lifetime. It can only be changed during a hard-fork.

Delayed Undelegation::
    A mechanism for revoking a delegation. Undelegation starts when an
    undelegation request is submitted, and lasts through the undelegation
    period. During this period, the operator has time to end all ongoing
    operations. During the undelegation period, the delegated stake is locked
    and no new operations are allowed. Already-started operations may be
    continued. After the undelegation period timeout, the delegated stake is
    released to the owner, and the bond between operator and owner is removed.

Consequent Penalization::
    Is the way undelegation is penalized. When an undelegation happens during an
    operation and the operation terminates successfully, then there is no
    penalty. If the operation terminates unsuccessfully, then the penalties are
    imposed. This the same way as standard penalization happens for an inactive
    peer.

== Specification

=== Contract

The contract should include the following information:

* _owner_ address,
* _operator_ address,
* _beneficiary_ address,
* _bond_ indicator between an operator and an owner,
* amount of delegated _tokens_,
* _state_ of the agreement between an owner and an operator,
* agreement state _change_ time.

The contract should also have the following discrete pieces of functionality:
 <<delegating, `delegation`>>, <<undelegating, `undelegation`>>,
 <<restoring, `restoration`>>, <<penalizing, `penalization`>>,
 and <<rewarding, `rewarding`>>.

=== Functionality

[#delegating]
==== Delegating a stake

1. The _owner_ chooses the number of tokens to delegate, _operator_, and
_beneficiary_ and creates a _delegation order_ containing this information.

2. The contract receives the _delegation order_ and verifies the following (if
any condition is unfulfilled, processing aborts):
  * _beneficiary_ address is set,
  * _operator_ is not involved in another active delegating contract,
  * amount of delegated tokens is lower or equal to the owner staked tokens.

3. If all conditions are satisfied the contract processes the _delegation order_
and sets the variables accordingly to the _delegation order_, and binds the
owner with the operator. The state of agreement between the owner and the
operator is set to `active`, and the agreement state change time is set to
current time.footnote:[Ability to increase the delegated stake can be
implemented via undelegating and delegating stake again with the new amount.]

4. The _operator_ can now use this delegated stake for operating.

[#undelegating]
==== Undelegating a stake

1. The _owner_ or _operator_ chooses to undelegate the stake, and creates an
_undelegation order_.

2. The contract receives the _undelegation order_ and verifies that the agreement exists.

3. If the conditions are satisfied, the contract processes the
_undelegation order_ and sets the following:
  * contract state is set to `undelegating`,
  * contract state change time is set to current time.

4. The _operator_ cannot enter new operations until the undelegated stake is
restored and the _owner_ cannot delegate the delegated stake to a new
_operator_.

[#restoring]
==== Restoring undelegated stake

1. After undelegating delay timeout since the _undelegation order_ has been
processed, the _owner_ or _operator_ creates a _stake restoration order_.

2. The contract receives the _stake restoration order_ and verifies the
following:
  * the agreement exists,
  * the contract state is set to undelegating,
  * undelegation timeout has passed.

3. The contract processes the _stake restoration order_ and sets the following:
  * returns delegated stake to the owner (minus any undelegation penalties if
    applicable),
  * removes the bond between the operator and the owner.

4. The _operator_ is now free to start operating for a new _owner_.

[#operating]
==== Operating on a stake

1. When the _operator_ tries to join operation (e.g., present a ticket for
beacon group selection) they should create an _operation initialization order_,
signed by the _operator_.

2. The _operation initialization order_ is published along with any other data
required to join the operation, after which the following should be checked:
  * the agreement exists,
  * the state of the agreement is `active`,
  * the request is signed by the operator.

3. If the checks pass, the operator may join the operations.

[#rewarding]
==== Rewarding

If the operator is awarded a _reward_ of currency, the reward should be paid
to beneficiary address. In this document, we are not specifying how rewarding
should be done.

[#penalizing]
==== Penalizing

1. If the operator is to be punished by stake slashing, the
_penalizing contract_ should call the _delegation contract_ with the _penalty_.
The _penalty_ should contain the following:
  * the _penalty amount_,
  * the _operator_ address.

2. The _delegation contract_ should then check the _penalty amount_ is not 
higher than the minimum stake.

3. If the penalty is valid, the _delegation contract_ will subtract the 
_penalty amount_ from the delegated stake. If the _penalty amount_ is higher
than the delegated stake then the delegated stake should be set to zero.

[bibliography]
== Related Links
- <<rfc-3-stake-delegation-requirements, RFC 3>>
- https://www.flowdock.com/app/cardforcoin/keep/threads/XvKc8gLwZesycPdyeBYZL6Iyt3Z
