:toc: macro

= RFC 8: Beacon signature share verification

:icons: font
:numbered:
toc::[]

== Background

Currently, broadcasting invalid shares
when generating a threshold signature
can serve as a DOS attack vector.
Without verification of signature shares,
a small number of colluding members
can greatly delay or prevent the entry from being generated.

=== Terminology

`P1`:: The generator point for the BLS elliptic curve

`X_k`:: The group private key of `Group_k`

`Y_k`:: The group public key: `Y_k = P1 * X_k`

`Entry_e`:: The entry matching the entry identifier `e`

`Input_e`:: The input for generating the new entry:
`Entry_e = Input_e * X`

`x_i`:: The individual private key of `P_i`

`y_i`:: The individual public key of `P_i`: `y_i = P1 * x_i`

`Share_i`:: The signature share by `P_i`: `Share_i = Input_e * x_i`

`N`:: The number of members in a group

`H`:: The number of members required for a honest majority

=== Invalid shares as DoS attack vector

When beacon operators generate the threshold signature
to produce a new entry,
they use their individual private keys to sign the entry input
to create signature shares
which are then broadcast to other members in the group.
These signature shares are combined
to reconstruct the threshold signature,
which is then submitted as the next entry for the beacon.

If one or more participants broadcast invalid signature shares,
they may significantly hinder or altogether prevent
the entry generation within the allotted time.
If an invalid share is included in the `H` signature shares
the threshold signature is reconstructed from,
the reconstruction will fail to produce a valid threshold signature.
If the received shares are not verified,
the only recourse is to try new combinations of signature shares
until a valid signature is produced.
With `m` invalid shares being broadcast,
trying all possible combinations takes _O(N^m)_ time:
first `choose(H+1, 1)` attempts
excluding each share on its own,
then `choose(H+2, 2)` attempts
to see if rejecting two shares leads to a valid signature,
then `choose(H+3, 3)` attempts excluding all combinations of 3 shares,
and so on for a total of `sum(i in [1 .. m], choose(H+i, i))` attempts.

== Proposal

The document specifies an update
to verify threshold signature shares for the random beacon
before reconstructing the threshold signature.

As an optional feature for later,
operators who broadcast invalid shares can be punished
by publishing irrefutable proofs of misbehavior on-chain.

=== Goal

To eliminate an attack
where a beacon operator broadcasts invalid shares
to other members in the same signing group,
hindering or preventing the group
from reconstructing a valid threshold signature.

=== Implementation

When receiving signature shares from other members in the signing group,
the shares are verified using the senders' individual private keys
stored at the conclusion of the DKG.
Invalid signature shares are rejected.

==== Verifying signature shares

When `P_j` creates a signature share `Share_j`
as a member of `Group_k` producing a threshold signature for `Entry_e`,
the share must be broadcast to the other members
in a message containing:

* the signature share `Share_j`
* the member index `j` of the sender `P_j`;

When `P_i` receives a signature share `Share_j` broadcast by `P_j`,
the share can be verified by `blsVerify(Share_j, y_j, Input_e)`.
If `Share_j` is valid,
`P_i` can use it for reconstructing the threshold signature.
If `Share_j` is invalid,
`P_i` must not use it for reconstructing the entry.

=== Limitations

Operators can still broadcast invalid shares with inpunity,
as failing the share verification has no consequences to the sender.

== Future Work

It is possible to validate signature-shares on-chain
and thus punish operators who broadcast invalid shares.
This approach is explored in RFC 10.

[bibliography]
== Related Links
- https://github.com/keep-network/keep-core/pull/628
