---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: electrumx-data-electrumx-2
  namespace: bitcoin
  labels:
    app: electrumx
    chain: bitcoin
    network: mainnet
spec:
  storageClassName: electrumx-v2
  dataSource:
    name: electrumx-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 450Gi
