apiVersion: batch/v1
kind: Job
metadata:
  name: electrumx-compact-history
  namespace: bitcoin
  labels:
    chain: bitcoin
    app: electrumx
    network: mainnet
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        chain: bitcoin
        app: electrumx
        network: mainnet
        job-name: electrumx-compact-history
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        # https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: electrumx
          image: lukechilds/electrumx:v1.16.0 # TODO: switch to our image
          imagePullPolicy: Always
          command:
            - /electrumx/electrumx_compact_history
          env:
            - name: COIN
              value: BitcoinSegwit
            - name: NET
              value: mainnet
            - name: DB_DIRECTORY
              value: /mnt/electrum/data
            - name: DAEMON_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bitcoind
                  key: rpc-password
            - name: DAEMON_HOST
              valueFrom:
                configMapKeyRef:
                  name: electrumx
                  key: daemon-host
            - name: DAEMON_URL
              value: http://$(DAEMON_USER):$(DAEMON_TOKEN)@$(DAEMON_HOST)
            - name: COST_SOFT_LIMIT
              value: "0"
            - name: COST_HARD_LIMIT
              value: "0"
            - name: LOG_LEVEL
              value: debug
          volumeMounts:
            - name: electrumx-data
              mountPath: /mnt/electrum/data
      restartPolicy: Never
      volumes:
        - name: electrumx-data
          persistentVolumeClaim:
            # Update to the desired replica's volume index.
            claimName: electrumx-data-electrumx-2
