:toc: macro

= Technical Status Report: 1 month of tBTC rc.1

toc::[]

On September 15th, 2020, the tBTC rc.1 contracts were deployed on Ethereum
mainnet. The 48 hours after the initial deploy were designed for testing and
setup by the development team, with an imposed supply cap of 2 TBTC. Once
that expired on September 17th, the supply cap went up to its first usage
level of 100 TBTC, and we announced the availability of tBTC in limited
fashion in the Keep Discord.

On September 22nd, the supply cap automatically increased to 250 TBTC, and we
announced tBTC rc.1 broadly via the tBTC site and other channels. This status
report covers the time **from the contract deploy on September 15th to
October 13th ~17:00 UTC**, though most of the activity prior to the 22nd was
still fairly limited (7.02 TBTC total was minted prior to the 22nd) and the
system had not yet been broadly announced.

== Understanding the System

Our community is one of the most central pieces of Keep and tBTC's future: a
decentralized system with a centralized development team is, after all, not
particularly decentralized. As we like to say, a system is only as decentralized
as its most centralized component. The Keep community has done an incredible job
of putting together a host of useful tools to observe both the Keep and tBTC
ecosystems as part of the Playing for Keeps program that awards KEEP tokens to
great work that advances the projects and the community itself.

Several of those tools were used to assemble this report. To that end, if
you're interested in tracking the tBTC system’s current and historical state,
you can look to these sites for information:

* https://allthekeeps.com
* https://keepscan.com
* https://keepstats.org

== Volume and Activity

First, a quick look at the volume and activity in the system during the first
weeks of the release candidate:

* **3,287.91 TBTC has been minted** since deployment.
* **2,774.91 TBTC has been redeemed**, meaning the corresponding BTC has been
  transferred out of addresses controlled by tBTC signers and back to other
  addresses on the Bitcoiin chain.
* **841 deposits** have been created in that time.

tBTC deposits are backed by signer groups that put up ETH collateral to
guarantee their availability. This means system health is not only a function
of how many deposits are opened, but also how much bond is available to back
new deposits. Currently, the system has **~58,680 ETH** available to it, with
**29,830 ETH** bonded to existing deposits. The current supply cap is 750 BTC
and current minted amount is 513 TBTC, so the available ETH is more than
enough to accommodate the available value.

== Governance Actions

The team has only done one thing to change the network's characteristics:
shortly after the supply cap went up to 250 TBTC, we added two additional lot
sizes, 5 BTC and 10 BTC, for deposits. This lot size bump was made to
accommodate the relatively high gas prices that were at play at the time,
since opening a deposit has a fixed cost. Opening up larger lot sizes allows
for more cost-efficient movement of BTC into the system, while increasing the
value risk of single deposits (as each signing group is now responsible for
more BTC and puts up a correspondingly higher bond amount).

372 of the deposits opened since then (not all of which were funded) were at
these higher lot sizes---a total of 55% of the deposits opened since the rc.1
was released.

== Observed Liquidations

We observed 4 liquidations in the first month of the system, almost all in
the first week. Note that for these purposes, a failure is considered an
event that resulted in a liquidation or a seeming loss of BTC. Each of these
is detailed below under its respective cause.

The tBTC system, even in its RC state, is unique in being decentralized while
still ensuring every TBTC corresponds to BTC available for redemption. It is
also unique in being designed to ensure that **a holder of TBTC can get back
an equivalent amount of BTC** in case of most system failures, at the cost of
increased risk for signers.

This design decision has been borne out in the release candidate: though
there have been 4 deposits (0.5% of all deposits representing ~0.5% of the
total minted value in the system) that have faced issues, **in all cases the
depositor was able to retrieve their value in BTC**. Moreover, only a single
signer issue resulted in signer bond loss. While we would obviously have
preferred for there to have been no issues and no bond loss, mainnet is never
the same as testnet, and operating any system comes with some risk.

=== Deposit State Transitions

Two deposits,
https://allthekeeps.com/deposit/dp-0x6b6ec592fede474e108f8fe5333d1c34cbefaf74[one
on October 7th (0.01 BTC)] and
https://allthekeeps.com/deposit/dp-0x6a3f8a78d09fc1645abd19c74d63c99d6e51fd10[one
on September 27th (0.2 BTC)], were liquidated due to a missing state
transition.

With help from the community, the team is helping to push deposits that are
in certain states that can result in liquidation to their "next" states.
While the dApp typically does this, users can occasionally abandon the dApp
mid-flow, and the signer client that handles key material does not currently
advance the deposit through these states automatically. These two deposits
both resulted from a failure to make such a state transition---the first
occurred a matter of hours before the solution to push these through was
enabled, and the second due to a bug in that solution.

There is https://github.com/keep-network/keep-ecdsa/issues/574[work planned]
to make ECDSA clients take care of this in the short term.

=== Missing Signer Backups

On September 25th,
https://allthekeeps.com/deposit/dp-0x77bcd4ec2f0db39c71a229150ef15fdfb73da684[a
10 BTC deposit] was liquidated due to a failure by signers to provide the
signature for a redemption proof in time, used to move BTC back out of the
tBTC system to the BTC chain. One of the operators in question reached out to
us during the redemption signature time to indicate that they were observing
a lack of activity on their client.

After investigating the situation on the network, we determined that one of
the operators in the signing group had experienced an unrecoverable loss of
their key share data due to a combination of insufficient backups and a
server change (unrelated to the client software). We coordinated a
liquidation of the funds that resulted in all signer bonds being returned to
the signers backing the deposit. The original depositor was able to recover
the 10 TBTC through this liquidation, for future redemption of a different
deposit, maintaining the system’s underlying guarantee that TBTC holders are
made whole.

As a result, we also took several additional actions to reduce the likelihood
of this issue recurring:

* We convinced the operator in question to move their operations to one of the
  staking providers to achieve greater reliability.
* We reached out to remaining operators in the system to remind them that they
  should have ongoing backups of key material as a regular part of their
  operational plan.
* We added several more calls to action in our documentation to emphasize that
  backups of key material are a baseline expectation for operators in the
  system.

=== Race Condition in the ECDSA Client

On September 26th,
https://allthekeeps.com/deposit/dp-0x2cd0bb9e8d1eb1210506aa4cb28c115e201fe65d[a
10 BTC deposit] was liquidated due to a race condition in the ECDSA client,
triggered by a combination of events:

* A duplicate `BondedECDSAKeepCreated` event was received by the ECDSA client on
  three operators, all ~30s after the first event. We suspect a short-term
  chain reorg was the cause.
* During the time since the first event was received, all 3 signers had
  completed their Distributed Key Generation procedure, generated private
  keyshares and a public key for the group corresponding to that event.
* During that same time, all three signers had also submitted transactions to
  publish the public key to the `BondedECDSAKeep` contract.
* None of the three transactions had been confirmed on-chain.

Due to how the client managed in-memory representations of bonded ECDSA
keeps, there was a window of time after key generation completed and before
the public key publish transaction confirmed where a duplicate event could
cause a second key generation to trigger normally. As a result, in the above
scenario, all three signers performed a second key generation and submitted a
second key to the chain. The on-chain contract rightly rejected this second
key; however, due to a combination of circumstances on the client, the second
key overwrote the first key on the system’s persistent storage and both key
generation cycles were considered successful.

Once key generation completes, the client spins up an event watcher
monitoring for signature requests from the chainーthis is the mechanism used
to respond to redemption requests. In this case, each of the 3 signers for
the deposit spun up two event watchers, one corresponding to each key. When
the redemption signature request came up, both watchers saw it and attempted
to participate in a signing exchange on the network. Due to the nature of the
protocol, having 6 signers with two different sets of key shares trying to
perform a single signature resulted in repeated failure of the signature
protocol. Thus, the redemption signature could not be provided.

Once the deposit was liquidated, approximately 1/3 of each signer’s bond was
returned to them. The depositor was made whole in TBTC, as with the previous
instance, maintaining the system’s guarantees to depositors. The team
confirmed that the key shares that reached persistent storage were for the
key that did not receive the BTC, thus the underlying BTC was lost. This
makes it impossible for the signers to recover more than the already-returned
bonds.

Several changes were made as a result of this incident:

* The same day as the incident response, a PR fixing the underlying race
  condition was merged and a release tagged and built with these changes. All
  operators were notified of the client upgrade and the underlying potential
  bond loss.
* Within a week, the tooling was completed to investigate the underlying key
  shares. Though the result was not sufficient to recover the BTC, the
  tooling forms the backbone of future key recovery needs. The intent is for
  key recovery to be an unusual but well-supported part of client operations,
  since it is the mechanism through which operators are generally able to
  recover any value lost to liquidations.
* Release 1.4.0 of the client was shipped this week shortly, adding additional
  snapshotting of key material so that even if there is a different
  possibility of overwriting key material, all key shares of all key
  generations will have been captured in a separate directory without the
  possibility of overwriting.

== Other Failure Types

A few other failure types were observed on mainnet, none of which resulted in
liquidation, covered in summary form below:

* **Depositors failing to fund deposits they have opened**. This results in a
  loss to the depositors of the opening fee for the deposit. Signer bonds are
  held for a short duration (3 hours) and can then be released by the
  signers. A number of these have been observed on-chain.
* **Depositors funding deposits incorrectly (by sending less than the required
  amount of BTC to the signer group)**. None of these were observed on-chain
  during the first month; however, in these cases the underlying BTC can be
  recovered with some coordination, provided a cooperative signer group.
  There is ongoing work to automate this coordination in the default case.
* **Depositors failing to prove funding in time**. A BTC funding transaction
  must be proven to have 6 confirmations within 3 hours of the deposit’s
  having a public key, or the deposit can be closed by the signers. A proof
  can fail to be submitted on time if a BTC transaction is mined too slowly
  and the depositor does not increase their fee, or if the transaction has
  its confirmations but the depositor never submits the proof to the chain.
  One of these was observed during the first month; as with incorrect
  funding, the underlying BTC is recoverable via coordination in these cases.
  As with incorrect funding, there is ongoing work to automate this
  coordination in the default case.
* **Relay maintainer running out of gas**. The cross-chain nature of tBTC
  requires an SPV relay, which enables Ethereum contracts to confirm that a
  Bitcoin transaction exists on the Bitcoin chain and has been confirmed a
  certain number of times. Without this component, funding and redemption
  proofs cannot be submitted to tBTC, leading to the system's
  deposit/redemption flow stalling out. Bitcoin can still flow, and any
  unproven funds are still recoverable as with most other states the system
  can enter, but obviously this is not ideal. The underlying causes for this
  particular issue are still under investigation---a balance check
  notification and a page for the insufficient funds issue on the maintainer
  both failed to fire. Fortunately, the team at
  https://strudel.finance[strudel.finance] noticed this issue shortly after
  it occurred, and started feeding the relay updates---first manually, and
  then automatically. The tBTC system (and strudel.finance’s system that also
  relies on the relay) both ran normally during this time. You can also read
  their
  https://medium.com/@strudelfinance/trustless-bridges-collaborating-on-block-relay-9a4b8855623c[blog
  post on the incident].
+
Generally the community acts as the "notifier of last resort" for the team,
and much of the team keeps a close eye on Keep Discord mentions as a
result. Thanks to the fact that strudel.finance started feeding the relay,
no one reached out to the team until the Strudel team did. Unfortunately
they reached out on the https://chat.tbtc.network[tBTC Discord server]
rather than the Keep one, which is new and which the team hasn't been
monitoring as closely. We independently discovered the issue on our end and
fixed it, but we have also begun monitoring the tBTC Discord more closely
as a result.

== Community Participation

As mentioned above, the community plays a large part in operating the tBTC
system successfully and correctlyーthe team largely doesn’t mint TBTC, largely
doesn’t operate nodes on the network, and largely doesn’t bond ETH. As such,
TBTC in circulation and signer nodes in operation are largely out of our
control, and we rely on and encourage community feedback and communication to
help guide both the development of the project and the discovery of
low-likelihood or unusual issues.

We wanted to call out the specific contributions that have come in from various
parts of the community, generally rewarded through the Playing for Keeps
program:

* **Running scripts**: several community members run additional scripts to
  monitor and move system state between deposits where reasonable. Redundancy is
  good in these cases, and protects against single points of failure.
* **Building explorers**: as linked at the start of this report, a handful of
  community members have assembled different views on different aspects of the
  Keep and tBTC systems. The results have been great tools that work fast and
  provide a tremendous amount of useful information about the network. The team
  uses some of these tools ourselves in cases where they provide different views
  than the tools we’ve built.
* **Updating the SPV relay**: The folks at strudel.finance kept the relay
  running in a situation where our own maintainer account was low on balance
  (see <<Other Failure Types>> for more). We’re now working on a collaboration
  with them to incentivize more folks to help keep the relay up-to-date, since
  it is fundamentally a public good and our central maintenance of it was by
  circumstance rather than by design.

== Conclusion and Next Steps

The first month of tBTC’s existence has seen relatively few major issues. The
two user-impacting issues that were observed were seen in the first week of the
system, and have resulted in added resilience to the ECDSA client and better
communication to the community about baseline expectations for operating a
client in the network. We have heard of no crashes in the client software, and
had several teams reach out to remark on the overall stability of the client.

There are several short- and mid-term client improvements in the works that were
already on the roadmap and would have helped in the first month, or that are a
direct result of the observed behavior in the first month. Here are a few
examples:

* **Fund recovery automation** to make coordination of fund recovery in cases of
  funding issues automatic.
* **tBTC-specific behaviors in the ECDSA client** to prevent state-transition
  related issues. This is being handled through out-of-band scripts at the
  moment, but integrating it natively into the ECDSA client will make it a
  direct responsibility of the signers.
* **Support for non-disk-based persistent storage** to allow key shares to be
  stored in e.g. encrypted S3 buckets or other forms of durable, managed
  persistent storage that require less ongoing backup overhead.
* **Considering reduction of lot sizes** to decrease per-deposit risk. Lot size
  decisions balance per-deposit risk against minting efficiency (since deposits
  have a fixed overhead cost for opening new lots) and other incentive
  components (such as the Keep staking rewards mechanism).
* **Decentralizing maintenance of the Bitcoin difficulty relay on Ethereum** by
  incentivizing difficulty relay maintenance, in collaboration with other teams
  using it such as the strudel.finance team.

The tBTC rc.1 graduated supply cap seems to have clearly communicated to signers
and users both that confidence in the system should increase with time,
something that has been borne out in practice. We continue to be satisfied that
no user funds have ever been at risk, and that the mechanisms for user fund
recovery in cases of unexpected failures have worked exactly as designed.

Here’s to many more months and years of decentralized BTC earnings on DeFi 🚀
