---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: electrumx-data-electrumx-1
  namespace: bitcoin-testnet
  labels:
    app: electrumx
    chain: bitcoin
    network: testnet
spec:
  storageClassName: electrumx-v2
  dataSource:
    name: electrumx-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
