resources:
  - ../../../../templates/bitcoin/electrumx

namespace: bitcoin-testnet

commonLabels:
  network: testnet

secretGenerator:
  - name: test-tbtc-network-cloudflare-origin-cert
    type: kubernetes.io/tls
    files:
      - .secret/tls.crt
      - .secret/tls.key

patches:
  - target:
      kind: Service
      name: electrumx
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: electrumx
      spec:
        type: LoadBalancer
        loadBalancerIP: 34.70.22.39
  - target:
      kind: StatefulSet
      name: electrumx
    patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: electrumx
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: electrumx
                env:
                  - name: NET
                    value: testnet
            volumes:
              - name: tbtc-network-cloudflare-origin-cert
                secret:
                  secretName: test-tbtc-network-cloudflare-origin-cert
        volumeClaimTemplates:
          - metadata:
              name: electrumx-data
              labels:
                chain: bitcoin
                app: electrumx
                network: testnet
            spec:
              storageClassName: electrumx-v2
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 40Gi

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: generated
