:toc: macro

= KEEP Development Process

:icons: font
:numbered:
toc::[]

In this document, we describe KEEP development process from an organizational 
perspective. We identify events and artifacts allowing for a transparent, 
adaptable and predictable development process.

== Milestone

Milestone is a box of items identifying releasable product increment with no 
more than one-month horizon of development effort. New Milestone starts 
immediately after the conclusion of the previous Milestone. Milestone scope is 
identified during the Planning Meeting and is a plan of work for the Development 
Team for the next couple of weeks. Individual team members may have a 
specialized area of focus but they all cooperate on the implementation of 
Milestone items and accountability for delivering the Milestone belongs to the 
team as a whole. Each Milestone has an expected delivery date assigned. Expected 
delivery date is evaluated from estimates provided by Development Team members 
during the Planning Meeting. 

== Planning Meeting

The Planning Meeting is a time-boxed event of 45 minutes happening at the 
beginning of each new Milestone. Before the Planning Meeting, Tech Lead sends a 
list of items from the top of the backlog. Items should be presented in a clear 
way allowing the Development Team to understand items to the level needed. Each 
Development Team member should invest some time in preparing to Planning 
Meeting: reviewing items, making sure they are well-understood and preparing 
questions if needed.


Planning Meeting consists of two parts Retrospective and New Milestone Planning.

=== Retrospective

Retrospective part is time-boxed to a maximum of 15 minutes. During this part, 
the Development Team inspects how the previous Milestone went. Every Development 
Team member has a chance to tell what in their opinion went particularly well 
and what could be improved. 

=== New Milestone Planning

On the beginning of the New Milestone Planning part, Tech Lead presents items 
from the top of the backlog and Development Team works on providing estimates to 
those items and splitting work on them. The provided estimate should include 
enough development effort to meet the definition of Done for the given item. 
Development Team members are assigned to individual items during the Planning 
Meeting but the accountability belongs to the entire team. Work on individual 
items is split into smaller tasks during the Planning Meeting, enough to start 
work on them immediately. Tasks may be clarified and re-organized later as more 
is learned.

== Daily Standup

The goal of the Daily Standup is to optimize team performance and collaboration. 
The team uses Daily Standups to track Milestone progress, identify impediments 
and synchronize about required development work. Daily Standup should not be 
considered as a management report duty. 

Everyone should answer three questions for a Daily Standup:

1. What did I do since the last Daily Standup?
2. What will I do today to progress work towards achieving the Milestone goal? 
3. Are there any blockers that prevent me from progressing the work?

Development Team members should be specific and provide enough details so that 
other team members know the current status, and if they work on the same 
codebase, what should they do next and in what order.

=== Example of a good Daily Standup message

*Yesterday*

* Conflict resolution phase. 
** Opened PR with a stub interface for the on-chain part: <link>. 
** Did initial work on off-chain voting event handling code, just local chain 
stub implementation.

*Today*

* Continuing work on the conflict resolution phase
** I received a review on my stub on-chain interface, want to address all 
comments. Should be ready today for another review round.
** I want to finish ethereum off-chain voting event handling code and open 
PR today. Should be ready for review at the end of the day

*Blockers*

* I do not understand how conflict resolution phase votes are summarized, need 
to talk with someone about it.


== Definition of Done

When Milestone item is described as “Done” everyone must share the same 
understanding of what “Done” means. For a milestone item to be considered as 
“Done”, the following requirements must be met: 

* Code merged to `master` branch
* The feature described by the item working as expected
* The implemented code is of high quality, no technical debt other than agreed 
in the item’s description 
* The implemented code has been reviewed and approved by at least one other 
Development Team member
* Tests implemented and passing
* Item does not break other existing functionalities
