:toc: macro

= Keep Client Quickstart

:icons: font
:numbered:
toc::[]

Here we provide a short description of material and steps required to run the keep-client.

The deployment bundle referenced in this document will be sent separately.

== The Parts

The deployment bundle contains five items:

1. keep-client Docker image
2. keep-client configuration file
3. Ethereum account keyfile
4. Text file with Ethereum account password
5. This document

== Starting The Client

*Depending on how you orchestrate containers, these steps will vary.  Here we illustrate
from the perspective of the Docker client.*

*The keep-client configuration file is already prepared, should you want to change the file paths
feel free.  This guide will assume you use the default paths.*


=== Unzip the bundle

`tar -xvf keep-client-deployment-bundle.tar.gz`

Resulting directory should look like:

```
.
├── keep-client-deployment-bundle
│   ├── config
│   │   ├── eth-account-keyfile
│   │   └── keep-client-config.toml
│   ├── eth-account-password.txt
│   ├── keep-client-quickstart.adoc
│   └── keep-client-snapshot.tar
└── keep-client-deployment-bundle.tar.gz
```

=== Load the Docker image

```
cd keep-client-deployment-bundle
docker load -i keep-client-snapshot.tar
```

Resulting image should be listed in `docker image ls` as:

`gcr.io/keep-test-f3e0/keep-client:latest`

=== Run the container

Run this from the `keep-client-deployment-bundle` directory:

```
export KEEP_CLIENT_ETHEREUM_PASSWORD=$(cat eth-account-password.txt)
export KEEP_CLIENT_CONFIG_DIR=$(pwd)/config

docker run -dit \
--volume $KEEP_CLIENT_CONFIG_DIR:/mnt/keep-client/config \
--env KEEP_ETHEREUM_PASSWORD=$KEEP_CLIENT_ETHEREUM_PASSWORD \
gcr.io/keep-test-f3e0/keep-client --config /mnt/keep-client/config/keep-client-config.toml start
```

=== Check logs for startup

`docker ps | grep keep-client | awk '{print $1}' | xargs docker logs -f`

Startup log should look like:
```
Established connection with bootstrap peer [xxxxxx]
---------------------------------------------------------------------------------------------
| Node: node                                                                                |
| Port: 0                                                                                   |
| IPs : /ip4/127.0.0.1/tcp/3919/ipfs/xxxxxx                                                 |
|       /ip4/172.17.0.2/tcp/3919/ipfs/xxxxx                                                 |
---------------------------------------------------------------------------------------------
```

== Commands

=== Submit Relay Request

```
docker ps | \
grep keep-client awk '{print $1}' | \
xargs -I {} docker exec -t {} keep-client --config /mnt/keep-client/config/keep-client-config.toml relay request
```

== Network Details

=== Ethereum Network

- *Dashboard:* http://eth-dashboard.test.keep.network
- *Transactions:*
  ** _RPC:_ http://eth-tx.test.keep.network:8545
  ** _WebSocket:_ link:[ws://eth-tx.test.keep.network:8546]

=== Keep Network

- link:[bootstrap.test.keep.network:3919]


