:toc: macro

= Keep Client Quickstart

:icons: font
:numbered:
toc::[]

Here we provide a short description of material and steps required to run the keep-client.

The deployment bundle referenced in this document will be sent separately.

== The Parts

The deployment bundle contains five items:

1. keep-client Docker image
2. keep-client configuration file
3. Ethereum account keyfile
4. Text file with Ethereum account password
5. This document

== Networking

The application needs ingress/egress access on port `3919`.

The ingress port is configurable and can be set in the included `keep-client-config.toml` file.

`Port` is in section `[libp2p]`.

=== `LibP2P.AnnouncedAddresses`

Depending on your deployment conditions it's possible the node address announced to the Keep
Network is not publicly accessible.  When this happens other peers on the network will not be able
to communicate directly with your node.

If you have a list of publicly accessible IP addresses and/or DNS hostnames that can route traffic to
your node you can configure them under `AnnouncedAddresses` in section `[libp2p]`.  When your
node starts up it will announce the provided list instead of the default.  If you want to use the
default address then leave `AnnouncedAddresses` set to `[]` or remove the entry all together.

`AnnouncedAddresses` should consist of multiaddrs and must be formatted accordingly. See link:[https://github.com/multiformats/multiaddr] for more information on formatting.

==== Example

`AnnouncedAddresses = ["/dns4/example.com/tcp/3919", "/ip4/80.70.60.50/tcp/3919"]`

== Starting The Client

*Depending on how you orchestrate containers, these steps will vary.  Here we illustrate
from the perspective of the Docker client.*

*The keep-client configuration file is already prepared, should you want to change the file paths
feel free.  This guide will assume you use the default paths.*

=== Unzip the bundle

Note: Your bundle will be prefixed with a timestamp, below is just an example.

```
mkdir keep-client-deployment-bundle
tar -xvf keep-client-deployment-bundle.tar.gz -C keep-client-deployment-bundle
```

Resulting directory should look like:

```
.
├── keep-client-deployment-bundle
├── .secrets
│   └── eth-account-password.txt
├── keep-client-deployment-bundle.tar.gz
├── config
│   ├── eth-account-keyfile
│   └── keep-client-config.toml
└── persistence
```

=== Load the Docker image

```
cd keep-client-deployment-bundle
docker load -i keep-client-snapshot.tar
```

Resulting image should be listed in `docker image ls` as:

`gcr.io/keep-test-f3e0/keep-client:latest`

=== Make configuration changes

If you want to alter default configurations it needs to be done before the service is started. For
now the only configuration that is configurable beyond what's already set is `AnnouncedAddresses` in
section `LibP2P`.  See section <<AnnouncedAddresses>> for configuration examples.

=== Run the container

Run this from the `keep-client-deployment-bundle` directory:

```
export KEEP_CLIENT_ETHEREUM_PASSWORD=$(cat .secrets/eth-account-password.txt)
export KEEP_CLIENT_CONFIG_DIR=$(pwd)/config
export KEEP_CLIENT_PERSISTENCE_DIR=$(pwd)/persistence

docker run -dit \
--volume $KEEP_CLIENT_PERSISTENCE_DIR:/mnt/keep-client/persistence \
--volume $KEEP_CLIENT_CONFIG_DIR:/mnt/keep-client/config \
--env KEEP_ETHEREUM_PASSWORD=$KEEP_CLIENT_ETHEREUM_PASSWORD \
--env LOG_LEVEL=debug \
-p 3919:3919 \
gcr.io/keep-test-f3e0/keep-client --config /mnt/keep-client/config/keep-client-config.toml start
```

=== Check logs for startup

`docker ps | grep keep-client | awk '{print $1}' | xargs docker logs -f`

Startup log should look like:
```
▓▓▌ ▓▓ ▐▓▓ ▓▓▓▓▓▓▓▓▓▓▌▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄
▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▌▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
  ▓▓▓▓▓▓    ▓▓▓▓▓▓▓▀    ▐▓▓▓▓▓▓    ▐▓▓▓▓▓   ▓▓▓▓▓▓     ▓▓▓▓▓   ▐▓▓▓▓▓▌   ▐▓▓▓▓▓▓
  ▓▓▓▓▓▓▄▄▓▓▓▓▓▓▓▀      ▐▓▓▓▓▓▓▄▄▄▄         ▓▓▓▓▓▓▄▄▄▄         ▐▓▓▓▓▓▌   ▐▓▓▓▓▓▓
  ▓▓▓▓▓▓▓▓▓▓▓▓▓▀        ▐▓▓▓▓▓▓▓▓▓▓         ▓▓▓▓▓▓▓▓▓▓▌        ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
  ▓▓▓▓▓▓▀▀▓▓▓▓▓▓▄       ▐▓▓▓▓▓▓▀▀▀▀         ▓▓▓▓▓▓▀▀▀▀         ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▀
  ▓▓▓▓▓▓   ▀▓▓▓▓▓▓▄     ▐▓▓▓▓▓▓     ▓▓▓▓▓   ▓▓▓▓▓▓     ▓▓▓▓▓   ▐▓▓▓▓▓▌
▓▓▓▓▓▓▓▓▓▓ █▓▓▓▓▓▓▓▓▓ ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  ▓▓▓▓▓▓▓▓▓▓
▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓ ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  ▓▓▓▓▓▓▓▓▓▓

Trust math, not hardware.

-----------------------------------------------------------------------------------------------
| Keep Random Beacon Node                                                                     |
|                                                                                             |
| Port: 3919                                                                                  |
| IPs : /ip4/127.0.0.1/tcp/3919/ipfs/xxxx                                                     |
|       /ip4/<ip-address>/tcp/3919/ipfs/xxx                                                   |
-----------------------------------------------------------------------------------------------
```

== Commands

=== Submit Relay Request

```
docker ps | \
grep keep-client | awk '{print $1}' | \
xargs -I {} docker exec -t {} keep-client --config /mnt/keep-client/config/keep-client-config.toml relay request
```

== Token Dashboard

You can view and manage your stake with our token-dasboard.  It can be found at http://dashboard.test.keep.network/



