resources:
  - grafana-deployment.yaml
  - grafana-pvc.yaml
  - grafana-service.yaml

namespace: monitoring

commonLabels:
  app: grafana
  type: monitoring

configMapGenerator:
  - name: grafana-config
    files:
      - config/grafana.ini
      - config/dashboards.yaml
      - config/datasources.yaml
  - name: grafana-dashboards-keep
    files:
      - dashboards/keep/keep-network-nodes-public.json
      - dashboards/keep/keep-network-nodes.json
  - name: grafana-dashboards-infrastructure
    files:
      - dashboards/infrastructure/kubernetes-deployments.json

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: generated
