= General group selection

Functionality contracts in the Keep network require groups of stakers
to perform operations.

== Basic description

The _group selection contract_ provides a mechanism
for selecting a group of stakers in a representative way.
Each staker has a chance of being selected
that is proportional to their _staker weight_.

When a _functionality contract_ needs a new group,
it calls the `initiateGroupSelection` method on the _group selection contract_.
The _functionality contract_ is required to provide
a _selection seed_, and the _group size_ of the desired group (_n_).

When the `initiateGroupSelection` method is called,
_stakers_ may begin submitting _tickets_
to show their eligibility for the new group.

Each ticket contains the _staker ID_ of its _creator_,
the _selection seed_ of the group it is for,
and a _ticket index_ used to distinguish the _creator's_ different tickets.
With these, a pseudorandom _ticket value_
and a unique _ticket identifier_ can be calculated.

Tickets with the lowest _ticket values_ are the most favorable.
Each staker can create a number of tickets equal to its _staker weight_.
Stakers with promising tickets of a low _ticket value_
can submit them on-chain until _ticket submission timeout_ is reached. 

Once _ticket submission timeout_ is reached,
the new group can be created by calling `finishGroupSelection`
which returns the best _n_ tickets.

In the future, alternative group selection contracts can be created
to provide different features,
such as staker indistinguishability.

== Details

=== Tickets

A ticket consists of the triplet `(selection_seed, staker_ID, ticket_index)`.

Ticket values are calculated as
`sha3(selection_seed, staker_ID, ticket_index)`.
The _ticket index_ is a value between 1
and the _staker weight_ of the ticket's creator, inclusive.
Each staker can submit a number of tickets equal to their staker weight.

Because `sha3` is pseudorandom,
each ticket has an independent chance of being in the _n_ best tickets.
This means a given staker may be included multiple times in the same group.
This independence of tickets is considered desirable
to simplify the group selection protocol
while also ensuring that it cannot be manipulated
by distributing stakes in any particular way.
The _staker weight_ of staker _Alice_
is equal to the number of separate stakers Alice could form with their stake.
Thus Alice cannot gain more tickets by distributing their stake
over more than one staker identity.

=== Threshold

The _threshold_ is the value of the _n_-th best ticket;
after the _ticket submission deadline_,
there are _n_ tickets with values at or below the _threshold_.

=== Ticket submission

The contract is agnostic to how tickets are submitted
as long as the transactions are processed before the ticket submission deadline.
To avoid unnecessary transactions,
it is recommended that clients submit their best tickets first as follows:

When instructed to submit more than one ticket at once
the staker should submit the most favorable one,
wait a block, submit the next most favorable one,
and so on.

Calculate the values of each ticket the staker is eligible to submit.
Order the tickets by favorability;
with tickets of the lowest value first.

==== Natural threshold and initial submission

Calculate the _natural threshold_.
The _natural threshold_ is the value the _threshold_ would take
if all tokens in existence were staked with maximum efficiency
and the ticket values were evenly distributed in the domain of `sha3`.
----
max_stakers = token_supply / minimum_stake
natural_threshold = (group_size / max_stakers) * (2^256 - 1)
----

If the staker has any tickets below the _natural threshold_,
those tickets should be submitted immediately.

Most of the time there are less than _n_ tickets below the natural threshold,
because the tokens are not staked in the most efficient possible way
and some stakers may be inactive or unable to submit their tickets.

==== Continued submission

If less than _n_ tickets are submitted immediately,
the remaining tickets should be scheduled:

For each ticket, calculate the scheduled submission delay
by calculating how many multiples of the natural threshold the ticket value is,
and multiplying the _submission delay increment_ by that number.
----
submission_delay(t) = ((t.value / natural_threshold) - 1) * delay_increment
----
Add the submission delays to the _group selection initiation time_
to get the time each ticket is scheduled to be submitted.
----
submission_time(t) = initiation_time + submission_delay(t)
----

Submit each remaining ticket at the indicated time,
until at least _n_ tickets with lower values than the next ticket
have been submitted.

[NOTE]
.Submission delay
====
The protocol isn't particularly sensitive
to the exact value of the _submission delay increment_.
If the increment is too small,
it may lead to the premature submission of ultimately ineligible tickets.
If the increment is too large,
it may lead to others submitting ultimately ineligible tickets.

Major problems would occur only where the submission delay increment
is set to such a high value that an ultimately eligible ticket
fails to get processed before the deadline.
This can be avoided by calculating and using
a worst-case delay increment:
----
natural_threshold_fraction = group_size / max_stakers
delay_increment_count = (1 / natural_threshold_fraction) - 1
delay_increment = submission_period / delay_increment_count
----

With the worst-case delay increment
every possible ticket value gets scheduled within the submission window.

To illustrate:
----
group_size = 50
max_stakers = 10,000
natural_threshold = 0.005 * (2^256 - 1)

natural_threshold_fraction = 1/200
delay_increment_count = 199
delay_increment = submission_period / 199
----
Because the natural threshold is 1/200-th of the domain,
on average 1 in 200 tickets would fall below it.
The remaining 199 out of 200 tickets are scheduled
so that the worst possible ticket `2^256 - 1`
would get submitted just at the end of the submission window.

For practical applications,
this worst-case delay increment is extremely pessimistic
and would cause unnecessary transaction fees to its user.
====

=== Processing tickets

Tickets are submitted by calling the method
`submitTicket(selection_seed, staker_ID, ticket_index)`.

The _selection seed_ is used
to identify which group selection each ticket belongs to,
as there may be multiple group selections running in parallel.
Submitting a ticket whose selection seed is invalid,
or where the corresponding group selection not accepting new tickets,
should lead to the ticket being *discarded*.

The _staker ID_ is used to identify the staker that created the ticket.
The staker must exist,
its status must be _Active_ (it may not be in the process of unstaking),
and it must have _authorized_ the contract corresponding to the selection seed.
Tickets failing these criteria should be *discarded*.

The _ticket index_ is used to distinguish different tickets
when a staker whose weight is more than 1
is eligible to submit multiple tickets,
and to act as a nonce for the pseudorandom function
to ensure different tickets get independent values.
The ticket index should be between 1 and the _staker weight_
of the staker corresponding to the _staker ID_, inclusive.
Tickets with a ticket index outside these bounds should be *discarded*.

Ticket values of valid tickets are calculated as
`sha3(selection_seed, staker_ID, ticket_index)`.

=== Finishing

Once the _ticket submission deadline_ has been reached,
the method `finishGroupSelection(selection_seed)` can be called.
It returns the best _n_ tickets in ascending order of ticket value.
These tickets are assigned the numbers from _1_ to _n_ inclusive,
and these numbers are used as _member indices_ for the resulting group.
