:toc: macro

= RFC 16: Pricing

:icons: font
:numbered:
toc::[]

== Background

Why do we want to do the thing this RFC describes?

== Proposal

Beacon entries are priced
based on a _cost estimate_ which covers entry verification and DKG,
and a _profit margin_ that scales linearly in group size.
An interface is provided
for customer applications to query the current _entry fee estimate_.
The customer should provide a _callback address_ to receive the entry,
and ensure they provide a sufficient _callback allowance_
to cover the gas fees of the callback.
Any surplus is returned to the customer in a _surplus recipient_ address.

When a valid entry is submitted,
the submitter receives a _submitter reward_
and every other member in the signing group receives a _group reward_.
To incentivize submitting an entry,
the _submitter reward_ increases as a request goes unserved
while the _group reward_ diminishes.
Rewards not paid out to the operators
are paid out to requesters to subsidize new requests.

=== Goal

Simple pricing method

=== Implementation

==== Making requests

When a customer wishes to receive an entry,
they should query the beacon for a current _entry fee estimate_.
The customer should also know
the _callback address_ they wish to receive the entry in,
and the _surplus recipient_ address for refunding excess fees.
The customer should prepare a sufficient _callback allowance_
to cover the gas costs of the callback.

When making a request for an entry,
the customer should submit the request
with the _callback_ and _surplus recipient_ addresses
while transferring _request fee = entry fee estimate + callback allowance_
currency to the beacon.
However, no new requests should be made
while the beacon is already processing another request.
Requests made while the beacon is busy
will be rejected and refunded to the _surplus recipient_ address.

==== Receiving a request

If the beacon is already serving an earlier request,
it rejects any new requests
and refunds the _request fee_
to the surplus recipient of the rejected request.

When the beacon is non-busy and receives a request,
it first checks that the _request fee_ exceeds
the _entry fee estimate + minimum callback allowance_.
Insufficiently funded entries forfeit the request fee.

Once the request has been verified to be sufficiently funded,
it is queued among the _pending requests_
and the request fee is divided into various budgets.

The _entry fee estimate_ is subtracted from the _request fee_
to gain the _callback allowance_ of the request.
The callback allowance is recorded in the pending request.

The _entry fee estimate_ is divided into
a _DKG cost fraction_,
an _entry verification cost_,
and a _profit margin_.

The _DKG cost fraction_ is added to the _DKG fee pool_.
When a DKG trigger event occurs,
the state of the DKG fee pool is checked.
Group creation and DKG are initiated
if the DKG fee pool exceeds the DKG cost estimate at the time.

A signing group is selected and tasked with generating the new entry.

==== Serving a request

When the signing group has produced a valid entry,
one of its members should submit it to the beacon.
The first member to submit a valid entry is the _submitter_.

Submissions that fail verification are ignored.
Repeat submissions for a request that has already been served
should be dropped immediately,
minimizing the gas expenditure.

When a valid entry submission is received on-chain,
it is provided to the corresponding request's _callback address_,
using the _callback allowance_ as the gas budget.
Once the callback returns,
the gas cost of the callback is multiplied
with the exact gas price used for the transaction
to obtain the actual _callback gas expenditure_.
The callback gas expenditure is subtracted from the callback allowance
to obtain the _callback gas surplus_.

The _callback gas surplus_ is refunded
to the requester's _surplus recipient_ address,
along with 1% of the _request subsidy pool_ of the beacon.

The submitter and other group members are rewarded
based on the _submission delay_;
time from when the request was originally received
to the submission of the valid entry.
If no valid entry has been received by the _submission deadline_,
the failing group is terminated,
its members slashed,
and a new signing group is selected
and the submission delay calculation reset.

==== Rewards

The _base reward_ for submitting an entry
equals the _profit margin_ divided by _group size_.
The exact rewards paid out to operators are based on the base reward
but vary according to _submission delay_ and submitter position.

If the amount paid out to the signing group in _group rewards_
and the submitter's _extra reward_ is less than the _profit margin_,
the difference is added to the beacon's _request subsidy pool_
to incentivize customers to request entries.

===== Group reward

The group reward is paid to every member of the signing group,
including the submitter,
upon submission of a valid entry.

The group reward equals the _base reward_
multiplied by a _delay factor_
equaling the fraction of time left by the submission deadline, squared.
If the maximum time to submit is 20 blocks
and an entry is received 4 blocks from the request,
the delay factor is _0.8^2^ = 0.64_.
Thus the _group reward = base reward * 0.64_,
with the difference being the _delay penalty = base reward * (1 - 0.64)_.

If the submission deadline is reached and the delay factor reaches 0,
the entry submission fails and all group members are penalized.

===== Submitter reward

In addition to the _group reward_,
the submitter is reimbursed for gas fees
and receives an extra reward.

The _submitter reward_ consists of
the _callback gas expenditure_ to cover the exact cost of the callback;
the _entry verification fee_ to cover the cost of verifying the submission;
and 5% of the _delay penalties_ of the entire group.

Unlike the _callback allowance_,
the entire _entry verification fee_ is paid to the submitter
regardless of their gas expenditure.
The submitter is free to spend less or more,
keeping the surplus or paying the difference.
This is to incentivize optimizing gas fees.

To incentivize a race for the submitter position,
the submitter receives _group size * delay penalty * 0.05_ as an extra reward.
With realistic group sizes this is significant,
but not high enough to render certain attacks profitable.
If the group size is 100 and the delay factor is 0.64,
the submitter receives an extra reward of
_base reward * 0.36 * 100 * 0.05 = base reward * 1.8_.
In this scenario the full submitter reward would be
_base reward * (1.8 + 0.64) + callback expenditure + entry verification fee_.

==== Cost estimates

===== Gas price feed

A short-term gas price feed is required
to estimate the gas cost components.

The critical feature of the gas price feed is
that the feed price multiplied by a safety margin for fluctuations (e.g. 1.5)
should be sufficient for getting beacon entries processed
within the deadline under all circumstances.
The gas price estimate for an entry is set when the request is processed,
but the entry submission transaction will be sent later.

If actual gas prices rise to a level
where the feed price and margin are insufficient
for getting a transaction to be mined,
and stays there for the duration of the entry submission window,
the basic profit margin for the operators cannot be guaranteed.

However, this does not imply that high gas prices
would render the beacon inoperable.
The submitter's extra reward incentivizes submitting
even when the entry verification fee cannot cover the gas costs.
In the extreme,
avoiding the severe penalty for failure to produce an entry
should incentivize group members to pay the gas prices
up to the (theoretical) limit
where gas for the entry submission transaction
costs as much as the KEEP tokens at stake.

The exact implementation of this gas price feed
is out for scope for this RFC.

===== DKG cost estimate

The gas required for DKG should be calculated.
Multiply DKG gas by gas estimate to get DKG cost estimate.
Use a DKG frequency divider _d_ to set the group creation rate;
once every _d_ entries on average.
Divide DKG cost estimate by _d_ to get DKG contribution for each entry.

Long-term gas price feed not required
when performing DKG whenever sufficient money has accumulated.
If gas price goes up,
DKG frequency goes down temporarily;
If gas price goes down,
DKG performed more often.

===== Entry verification fee

Calculate gas required for verifying entry
and associated support operations.
Multiply by gas price plus a fluctuation margin (e.g. 1.5)
to get entry verification fee.

=== Limitations

Entry price reacts slightly to entry quality
(faster entries -> lower surplus -> lower request subsidies)
but not to other factors.
Processing entries one-by-one doesn't scale.
If submitter is miner,
can set arbitrary gas fees to attack the requester
by making the callback run out of gas;
no recourse is provided in the design,
and mitigations seem difficult at first look.

=== Proof of Concept

If you have PoC code, refer to the relevant branch and give a brief summary.

== Future Work (optional)

If applicable, what future evolutions could you see this approach leading to?
Particularly if these possibilities influenced your thinking about the main
proposal, this is important.

== Open Questions (optional)

If any open questions are left that you haven't yet investigated, what are they?

[bibliography]
== Related Links

- Flowdock Links
- Other links
- If you have publications, you can include them in bibliography style. If you
  start your bullet with an id in _triple_ square brackets (e.g. `+[[[AAKE]]]+`),
  you can reference it in the content body using regular cross-reference syntax
  (e.g. `+<<AAKE>>+`).
