:toc: macro

= RFC 3: Stake delegation requirements

:icons: font
:numbered:
toc::[]

== Background

Keep enables token owners to delegate their tokens to the third party operators
who will be operating on their behalf on their stake.

=== Terminology

owner:: The address of an owner of the staked tokens.

operator:: The address of a party authorized to operate a stake in the name of a
  given  _owner_.

magpie:: The address where the incentives are sent, earned by an _operator_ in
  the name of an _owner_.

delegated stake:: A number of tokens delegated to an _operator_ by an _owner_.

== Proposal

Stake delegation enables a token _owner_ to stake his tokens to an _operator_
and enables an _operator_ to operate staked tokens in the name of the _owner_.
The owner defines also a _magpie_ address (recipient) where all incentives
generated by the _operator_ on the staked tokens are uploaded.

=== Goal

The goal of this proposal is to specify a simple and secure stake delegation
mechanism.

=== General requirements for staking (safe assumptions):
_owner_:: can only have one operator, can only delegate all of his stake
(relaxing?).
_operator_:: cannot have any stake of his own, can only have a stake from one
owner.

=== Functionality

==== Delegating a stake:
1. The _owner_, signs a contract where he declares a _stake_ (the number of
tokens he wants to delegate), an _operator_ address (who will be operating on
the _stake_) and a _magpie_ address (where the rewards will be sent).
2. The _operator_, agrees to the contract, hence making it effective and starts
operating on the _stake_.
3. If there will be no acceptance from the _operator_ until a timeout, then the
_stake_ needs to be return to the _owner_. In that case the _owner_ needs to
be informed.

==== Undelegating a stake by the owner:
1. The _owner_ initiates undelegation of the _stake_.
2. The _stake_ is locked forbidding any further operations on it by either an
_operator_ or a _owner_.
3. The _operator_ finishes all previously started on _stake_ operations and
confirms undelegation.
4. After reception of the confirmation from the _operator_ or after a timeout,
the _stake_ is unlocked and returned to the _owner_.

==== Undelegating a stake by the operator:
1. The _operator_ initiates undelegation of the _stake_.
2. The _stake_ is locked for a period necessary to finish all operations already
initiated by the _operator_ (or the _operator_ can only initiate an undelegation
after finishing all operations). A notification is sent to the _owner_.
3. After a timeout _stake_ is unlocked and transferred to the _owner_.

==== Operating on a stake:
Every operation made on a stake needs to be atomic, in the meaning that when an
_operator_ is staking a _owners_ _stake_, he needs to provide a reference to
the appropriate contract that there is a consensus between _stake_, _operator_,
_owner_ and _magpie_. Therefore, the parties performing an operation always
need to validate the staking credentials and verify:

- if the contract is valid,
- if the _operator_ is correct,
- if the _stake_ is correct,
- if the _owner_ is correct,
- if the _magpie_ is correct.

The incentives need always to be sent to the correct _magpie_ address.

The penalties/slashing need always to be done on the correct _owner_ address.

== Open Questions

=== Incentivisations:
Do we want to promote being an _operator_?

How to make profitable being an _operator_?

Should an _operator_ get a portion of the rewards he own? If so, we need to add
 an _operators-magpie_ address where the portion of rewards will be sent.


=== Penalisation:
How to penalise misbehaviour?

Should an _operator_ have an accountable address which will be slashed?

=== Timeouts:
What timeouts are reasonable?

[bibliography]
== Related Links
- https://www.flowdock.com/app/cardforcoin/tech/threads/UQhnqrQAWk3azp2TO9UhOJQRMXp
- https://www.flowdock.com/app/cardforcoin/keep/threads/TA-Jwe9oMaOBAylc3yRJObc5Bq_
- https://www.flowdock.com/app/cardforcoin/keep/threads/k6MV7jS9DEd0DnvOpkAt5SjsS9w
- https://www.flowdock.com/app/cardforcoin/tech/threads/-Lbr4JzmX0gY31CMDTRGnQUbbuw
- https://github.com/keep-network/keep-core/pull/121