:toc: macro

= RFC 6: Group expiration specification

:icons: font
:numbered:
toc::[]

== Proposal
This document focuses on specifying a group expiration mechanism. The proposed
functionality enables a group to expire after particular condition is met.
Members of an expired group are forbidden from taking any new actions within the
group, but all of the already ongoing in-group operations can still continue. 

=== Goal
The goal is to provide a minimal set of functions necessary for implementing the
group expiration mechanism into the KEEP network. The group expires when group
expiration timeout passes.

== Specification

=== Contract

Group selection contract should include the following information (per group
formation agreement):

- group formation agreement identifier,
- group members identifiers,
- the initiation time when the group was created,
- timeout, after which the group expires,
- current state indicating if the group is active or expired.

The contract should also have the following discrete pieces of functionality:
<<initiation, initiation>>, and <<operation, operation>>.

=== Functionality

[#initiation]
==== Initiation
When a group is formed, the group formation agreement is created and filled
with:

- unique group formation agreement identifier,
- group members identifiers,
- initiation time set to current block time,
- timeout set to an arbitrary time to group expiration counted in blocks,
- current agreement state set to _active_.

[#operation]
==== Operation
When a group operation is invoked, the operating contract (one that is invoking
the operation) needs to call the group selection contract with the group
formation agreement identifier. During the call, the group selection contract
performs <<verification, group agreement status verification>>. When the group
formation agreement is active, then the
<<active, group selection contract responds with active group information>>
otherwise, the 
<<expired, group selection contract responds with expired group information>>.

[#active]
===== Active group response
The group selection contract sends _group members identifiers_ to the operating
contract.

The operating contract is obligated to forbid non-members from group operations.

[#expired]
===== Expired group response
The group selection contract sends _expired_ group status to the operating
contract. The operating contract should not commence any new operation. It
should inform its invoker or group of invokers about the fact that the group
expired.

[#verification]
===== Group agreement status verification
If the current block time is larger than the group initiation time plus the
threshold then set the group agreement status to _expired_.

[bibliography]
== Related Links
- https://docs.keep.network/random-beacon/group-expiration/
- https://www.flowdock.com/app/cardforcoin/keep/threads/NL6VK7goghV9QaWUXyFT_YgwV_M
