:toc: macro

= RFC 12: Keep Network application interface

:icons: font
:numbered:
toc::[]


== Proposal

This document specifies how applications interact with Keep Network.

=== Terminology

Application:: Application is an external smart contract or a set of smart  
              contracts utilizing functionalities offered by Keep Network.

a keep:: A keep is a smart contract used by an application to perform some work. 
         It is a privacy primitive enabling secure storage and usage of secrets.

sMPC cluster:: A keep can have off-chain clients executing work for a keep. 
               Off-chain clients serving a keep together form an sMPC cluster. 
               sMPC cluster observes state of a keep and reacts appropriately. 

Keep Network:: The Keep network consists of all stakers, all keeps and 
               associated sMPC clusters, and the random beacon.

KEEP:: KEEP is an ERC-20 work token used to stake in the Keep network. 
       A minimum staked value is required for operator to join the network and 
       fulfill requests.

Keep Core:: Keep Core consist of a set of on-chain contracts and off-chain  
            client providing the functionality of random beacon
            and KEEP token along with all stake management interfaces.

tECDSA:: Threshold Elliptic Curve Digital Signature Algorithm. 

Bond:: Bond is a security instrument preventing network operators to collude 
       and act against agreed rules, for example to censor withdrawals or 
       abscond with funds. Bond may get slashed or seized in case of malicious
       behaviour of the operator.


=== Goal
The goal of this proposal is to specify the interface between an application and 
the keeps atop which the application is built. This proposal specifies 
mechanism of creating and registering keeps. This proposal introduces two types
of keeps: tECDSA keep and Bonded tECDSA keep. Those keeps are just the first
two types of keeps which are going to be offered by Keep Network.

==== sMPC cluster requirements

Each off-chain client of sMPC cluster should be a separate process. Keep Core 
client should be a separate client than Keep tECDSA client:
```
./keep-core
./keep-tecdsa 
```

(The above snippet is just an example for the first keep type)

Each operator is required to run Keep Core client. Running Keep tECDSA client is 
optional. Eventually, we hope other developers will build their own clients.

==== Bonding requirement

Some applications requires a bond to be provided by signers. Stakers who want to 
participate in signing need to opt-in and provide the required bond. A bond can 
be provided in ETH or ERC-20 token specific to the application.

=== Implementation

==== ECDSA keep factory

ECDSA keep factory is an on-chain factory of ECDSA keeps. The factory creates 
and destroys keeps and is responsible for maintaining the list of all active 
keeps. sMPC cluster clients working with ECDSA keeps observe ECDSA keep registry 
for all new ECDSA keeps created. Registry is responsible for group selection 
using the random beacon.

===== Pseudocode

```
contract ECDSAKeepFactory {
    address[] internal _keeps;

    function openNewKeep(
        uint256 threshold, 
        uint256 groupSize, 
        address owner
    ) returns (address) {
        address keep = new ECDSAKeep(
            selectGroup(threshold, groupSize), 
            owner
        );

        _keeps.push(keep);
        return keep;
    }

    // (...)
}

contract ECDSAKeep {
    // (...)

    function sign() { 
        require(msg.sender == _owner, "Only keep owner can ask to sign");
        // (...)
    }
}
```

==== Bonded ECDSA keep factory

Bonded ECDSA keep factory is an on-chain factory of Bonded ECDSA keeps. The 
factory creates and destroys keeps and is responsible for maintaining the list 
of all active keeps. Bonded ECDSA keep has extra bonding logic over a vanilla 
ECDSA keep. Registry is responsible for group selection using the random beacon.

===== Pseudocode

```
contract BondedTECDSAKeepFactory is ECDSAKeepFactory {
    function openNewKeep(
        uint256 threshold, 
        uint256 groupSize,
        Bond bond, 
        address owner
    ) returns (address) {
        address keep = new ECDSAKeep(
            selectGroup(threshold, groupSize, bond), 
            owner
        );

        _keeps.push(keep);
        return keep;
    }

    // (...)
}

contract BondedECDSAKeep is ECDSAKeep {
    // (...)
}
```


==== Keep registry

Keep registry is an interface for application to interact with Keep Network. Keep 
registry specifies what are the sanctioned types of keep factories and is an 
upgrade mechanism for the entire system. Application interacts with Keep registry to 
open a keep. The registry returns a brand new instance of the requested type of 
a keep. All sanctioned keep factories need to be registered in Keep registry.

===== Pseudocode

```
contract Application {
    address internal _keepRegistry;

    function openDeposit() {
        address keep = KeepRegistry(_keepRegistry).openBondedECDSAKeep(
            threshold, 
            groupSize, 
            bond
        );

        // (...)
    }
}
```

```
contract KeepRegistry {
    address internal _bondedTECDSAKeepFactory;    

    function openBondedECDSAKeep(
        uint256 threshold, 
        uint256 groupSize, 
        Bond bond
    ) returns (address) {
        keep = BondedTECDSAKeepFactory(_bondedTECDSAKeepFactory).openNewKeep(
            threshold,
            groupSize,
            bond
            msg.sender,
        );

        return address(keep);
    }

    // (...)
}
```
