:toc: macro

= RFC 3: Stake delegation requirements

:icons: font
:numbered:
toc::[]

== Background

Keep tokens are going to be staked by having token owners delegate their staked
balance to an operator account and use it to run the Keep Client. The operator
account cannot access the stake directly, nonetheless, it operates on behalf of
the owner and bad acting will result in slashing the owners' stake. The operator
may be a third party, or it may be a different address controlled by the owner,
or it may be the same address that owns the tokens.

The stake delegation will be beneficial for the security of Keep users as it
allows on-stake operations with a "cold wallet". Thus, putting Keep users
wallets offline protects them from "hacks" and stake delegation enables
continuous rewarding on safe operations on staked assets.

=== Terminology

owner:: The address of an owner of the staked tokens.

operator:: The address of a party authorized to operate a stake in the name of a
  given  _owner_.

magpie:: The address where the incentives are sent, earned by an _operator_ in
  the name of an _owner_.

delegated stake:: A number of tokens delegated to an _operator_ by an _owner_.

== Proposal

Stake delegation enables a token _owner_ to delegate their already-staked tokens
to an _operator_ and enables an _operator_ to operate staked tokens in the name
of the _owner_. The owner defines also a _magpie_ address (recipient) where all
incentives generated by the _operator_ on the staked tokens are uploaded.

=== Goal

The goal of this proposal is to specify a simple and secure stake delegation
mechanism.

=== General requirements for staking:
1. _owner_ can only have one operator.
2. _owner_ can only delegate all of his stake.
3. _operator_ cannot have any stake of his own.
4. _operator_ can only have a _delegated stake_ from one _owner_.
5. If an _owner_ tries to delegate to more than one operator, the tx must
fail.
6. If an _owner_ tries to delegate a stake to an _operator_ who already has a
stake, the tx must fail.
7. If an _operator_ tries to operate on a stake that he already operates on, the
tx must fail.

=== Functionality

==== Delegating a stake:
1. The _owner_, signs a contract where he declares a __delegated stake_ (the 
number of tokens he wants to delegate), an _operator_ address (who will be
operating on the __delegated stake_) and a _magpie_ address (where the rewards
will be sent).
2. The _operator_, agrees to the contract, hence making it effective and starts
operating on the __delegated stake_.
3. If there will be no acceptance from the _operator_ until a timeout, then the
__delegated stake_ needs to be return to the _owner_. In that case the _owner_
needs to be informed.

==== Undelegating a stake by the owner:
1. The _owner_ initiates undelegation of the __delegated stake_.
2. The __delegated stake_ is locked forbidding any further operations on it by
either an _operator_ or a _owner_.
3. The _operator_ finishes all previously started on __delegated stake_ 
operations and confirms undelegation.
4. After reception of the confirmation from the _operator_ or after a timeout,
the _delegated stake_ is unlocked and returned to the _owner_.

==== Undelegating a stake by the operator:
1. The _operator_ initiates undelegation of the _delegated stake_.
2. The _delegated stake_ is locked for a period necessary to finish all 
operations already initiated by the _operator_ (or the _operator_ can only 
initiate an undelegation after finishing all operations). A notification is sent
to the _owner_.
3. After a timeout _delegated stake_ is unlocked and transferred to the _owner_.

==== Operating on a stake:
Every operation made on a stake needs to be atomic, in the meaning that when an
_operator_ is staking a _owners_ _delegated stake_, he needs to provide a 
reference to the appropriate contract that there is a consensus between 
_delegated stake_,  _operator_, _owner_ and _magpie_. Therefore, the parties
performing an operation always need to validate the staking credentials and 
verify:

- if the contract is valid,
- if the _operator_ is correct,
- if the _delegated stake_ is correct,
- if the _owner_ is correct,
- if the _magpie_ is correct.

The incentives need always to be sent to the correct _magpie_ address.

The penalties/slashing need always to be done on the correct _owner_ address.

== Open Questions

How is this going to interact with RFC 4 (on secure upgrades)?

=== Penalisation:
How to penalise misbehaviour?

Should an _operator_ have an accountable address which will be slashed?

=== Timeouts:
What timeouts are reasonable?

== Future work
Consider how the stake delegation will interact with ETH bonding (part of Keep,
but not the beacon).

[bibliography]
== Related Links
- https://www.flowdock.com/app/cardforcoin/tech/threads/UQhnqrQAWk3azp2TO9UhOJQRMXp
- https://www.flowdock.com/app/cardforcoin/keep/threads/TA-Jwe9oMaOBAylc3yRJObc5Bq_
- https://www.flowdock.com/app/cardforcoin/keep/threads/k6MV7jS9DEd0DnvOpkAt5SjsS9w
- https://www.flowdock.com/app/cardforcoin/tech/threads/-Lbr4JzmX0gY31CMDTRGnQUbbuw
- https://github.com/keep-network/keep-core/pull/121