:toc: macro

= RFC 15: Slashing

:icons: font
:numbered:
toc::[]

== Background

To incentivize correct behavior in the Keep network,
misbehaving participants need to be punished.
In some situations,
proving misbehavior requires cooperation from another participant,
a _tattletale_.
This coordination is incentivized by rewarding the _tattletale_
by granting them a fraction of the tokens
taken from the misbehaving participant.

== Proposal

=== Goal

Slashing should be simple to implement and reason about.
The slashing method should implement the tattletale transfer mitigations
defined in the link:rfc-14-token-grants.adoc[token grant RFC],
always burning at least 95% of the penalty amount.

To protect staker funds,
only authorized operator contracts should be able to punish an operator.

=== Implementation

Tokens are staked by transferring them to the staking contract.
The staking contract tracks the stake allocated to each _staker_.
Stakes can be _slashed_ to punish misbehavior.
Tokens backing slashed stakes are burned;
if a tattletale proves another operator's misbehavior
they will receive 5% of the slashed tokens,
the remainder being burned.

When an operator is punished for misbehavior,
they should generally be removed
from the group/keep the misbehavior occurred in.

==== Authorization

_Operator contracts_ are authorized to impose penalties
by stakers' _authorizers_.
All stakers using the same _authorizer_
share the set of authorized operator contracts.
Once given, this authorization cannot be revoked by the authorizer.

When a staker wishes to join a group
the contract responsible for creating the group
must be authorized by the staker's authorizer.
The operator contract must check its authorization status
when determining a staker's eligibility.

In the random beacon a staker's eligibility is checked
when tickets are submitted;
this means that authorization must be checked
when validating a ticket.
If an operator submits a ticket to an unauthorized operator contract,
the ticket must be rejected as invalid.

==== Penalties

When an operator misbehaves on-chain,
the operator contract calls the staking contract to punish the operator.
The staking contract checks
that the operator contract is authorized to punish the staker,
and if true, applies the penalty.

A penalty can be applied to one or more stakers simultaneously.
Each affected staker is penalized by the same amount.

===== Pure slashing

When misbehavior is detected without third-party input,
a _pure slashing_ penalty is applied.
Pure slashing means that the staking contract
subtracts the applicable penalty from the operator's stake
and burns tokens equal to the penalty amount.

===== Seizing

When a tattletale proves another operator's misbehavior,
a fraction of the penalty amount is _seized_ and transferred to the tattletale,
while the rest is burned.
The tattletale reward can be set to any value
between 0 and the maximum of 5% of the penalty.

To apply a seizing penalty,
the operator contract includes the tattletale operator's address in the call.
The staking contract subtracts the applicable penalty from the operator's stake
and transfers the reward to the tattletale's _beneficiary_ address.
The remainder is burned.

===== Penalty amounts

Penalties for misbehavior could be adjusted
to match the severity of the misbehavior.
However, initially a simple rule should be sufficient:
when `op_contract` imposes a punishment,
the amount slashed should equal
the minimum stake required to participate in operations on `op_contract`.
If contract _Foo_ requires 10,000 KEEP to participate with one virtual staker,
_Foo_ should slash a misbehaving virtual staker by 10,000 KEEP.

==== Interface requirements

===== Staking contract: slashing

`slash(tokens sum, address[] misbehavers)`::

Check that `msg.sender` is authorized
to slash each `misbehaver` in `misbehavers`:
`isAuthorized(msg.sender, misbehaver.authorizer) == true`.
+
Subtract `sum` tokens from the stake of each `misbehaver`
and burn `sum * length(misbehavers)` tokens.

`seize(tokens sum, float pay, address tattletale, address[] misbehavers)`::

Check that `msg.sender` is authorized
to slash each `misbehaver` in `misbehavers`:
`isAuthorized(msg.sender, misbehaver.authorizer) == true`.

Check that `0 < pay <= 1`.

Subtract `sum` tokens from the stake of each `misbehaver`;
set `total = sum * length(misbehavers)` and `reward = total * 0.05 * pay`;
burn `total - reward`; transfer `reward` to beneficiary of staker `tattletale`.

===== Staking contract: authorizations

`authorize(address op_contract)`::

Authorize `op_contract`.
Operators using `msg.sender` as their authorizer
may now join operations on `op_contract`
and `op_contract` may slash their stakes.

`isAuthorized(address op_contract, address by) -> bool`::

Check if the authorizer `by` has authorized `op_contract`.

===== Token contract

`burn(amount sum)`::

Any address that holds tokens can call `burn(amount sum)`
to burn `sum` tokens, limited by tokens held by the address.

=== Misbehavior and penalties in the Random Beacon

==== DKG

===== Invalid ticket

An operator might submit an invalid ticket in the DKG.

Invalid tickets are detected automatically
without the need for a tattletale.

Proof of invalid tickets is _objective_,
as all information required to verify tickets is available on-chain.

Because the cost of ticket submission is paid by the submitter,
the ticket can be simply rejected and the transaction reverted.

===== Failure to produce a DKG result

The created group might fail to produce a valid result.

Failure to finish DKG is verifiable without additional proof,
but requires a trigger transaction for this verification
after the deadline for completing DKG has passed.
If no other trigger transaction is made,
the trigger transaction for another DKG shall check
if the previous attempt at DKG has failed to produce a result.

Failure to finish DKG is _objective_.

Failure to produce a result means
that a honest and available majority
was not present in the DKG for some reason or other.
The precise reasons can be unpredictable.
Failing to finish DKG is inherently punished
by the opportunity cost of not getting into a signing group
despite having paid the ticket submission fees.
Because of this,
failure to produce a valid DKG result should not be separately penalized
without further examination of the possible causes of failure
and the effects of collective punishment.

===== Submitting an invalid DKG result

An operator might submit an invalid result for the DKG.

Invalid DKG results are detected automatically.

Proof of invalid DKG results is _objective_.

Because the cost of verifying a DKG result is paid by the submitter,
and the submitter is reimbursed only for valid results,
submitting invalid results inherently punishes itself
and no further penalty is needed beyond reverting the transaction.

===== Inactivity in DKG

An operator might fail to send a required message during DKG.
This lowers the effective safety margin of the group
against lynchpinning and inability to produce a signature.

Inactivity in DKG is determined by
the list of inactive members in the DKG result submission.

Unless DKG is performed on-chain,
proof of inactivity in DKG is _subjective_
and subject to the honest majority assumption;
a dishonest majority could always forge a false proof of inactivity.
It is not possible to make off-chain DKG inactivity objectively provable.

Inactive members shall be removed from the group,
but not otherwise punished;
the opportunity cost of not being included in the group
already provides an incentive to be active.

===== Disqualification in DKG

An operator might misbehave in a variety of ways during DKG.
Active misbehavior can lower the effective safety margin of the group
against frontrunning, lynchpinning, or signature failure.

Disqualification in DKG is determined like inactivity,
by the list of disqualified members being included in the result submission.

On-chain proof of disqualification is _subjective_
and a dishonest majority could forge a false proof.

Punishing disqualified members based on subjective proof
creates opportunities for dishonest majorities
to attack other stakers
in a way which extends beyond the damage caused by frontrunning the beacon.
Because of this,
punishing disqualified members without objective proof
requires further examination of the associated risks and incentives.

For the first version,
disqualification shall be treated like inactivity
and only punished with removal from the group.

==== Signing

===== Invalid signature share

An operator may broadcast an invalid signature share to other operators
when reconstructing the threshold signature.

Invalid signature shares can only be detected on-chain
if a tattletale submits a proof
that includes the signature share and the information required to verify it.

In the first version,
the infrastructure for verifying these proofs is not yet in place.
Invalid signature shares shall be simply rejected by the other members.

===== Failing to broadcast a signature share

When a signing group is tasked with producing an entry,
its members are expected to broadcast signature shares.
An operator might fail to broadcast its signature share,
either due to actual inactivity
or as an attempt to gain a lynchpin position and guaranteed submitter reward.

Failure of an individual member to broadcast a signature share
can not be reliably detected on-chain,
even in the event the group as a whole fails to produce a signature.
Thus, individual failures to broadcast shares shall not be punished.

===== Submitting an invalid signature

An operator may submit an invalid threshold signature on-chain
when generating a beacon entry.

Invalid signatures are automatically detected.

Proof of an invalid threshold signature is _objective_.

As verifying a threshold signature is relatively expensive,
no separate punishment is needed beyond reverting the transaction.

===== Unauthorized use of individual private key

An operator's individual private key may be leaked
and used inappropriately.

Unauthorized use of a member's individual private key
can be proven on-chain by the submission of a suitable proof.

The first version is not yet able to verify these proofs,
so unauthorized use of individual private keys is not separately penalized.

===== Creating an unauthorized signature

An entire signing group's private key could be abused
to create an unauthorized signature.

Unauthorized threshold signing can be proven by publishing
a value the group hasn't been previously requested to sign,
and a valid signature for the value.

Proof of unauthorized signing is _objective_.

Unauthorized signing shall be punished
by _seizing_ tokens from all members,
with the submitter of the proof as the _tattletale_.

===== Failure to produce a signature

A signing group may fail to produce a new entry within the deadline.

Failure to generate an entry can be verified on-chain without a separate proof,
but requires a transaction to trigger this check.

The proof of failure is _objective_.

When a group fails to produce an entry,
all of its members shall be subject to _seizing_
and the group itself shall be terminated.
The submitter of the trigger transaction shall be treated as the _tattletale_,
but the tattletale reward shall be limited to
`min(1, 20 / group_size)` of the maximum,
or effectively the minimum stake of a single member.
This is to prevent actors in a lynchpin position
from profitably stealing other stakers' funds.

=== Limitations

Slashing is not limited to the amount originally staked
for participating in the relevant operations;
a malfunctioning operator contract could cause a staker to lose all stake.

Chain reorganizations may lead to honest behavior in one branch
being punishable misbehavior in another.
Mitigations for this have not been included in this RFC.

== Future Work

With a different staking paradigm
that tracks individual keep and group memberships,
it is possible to limit the risk
from malfunctioning operator contracts or trusted applications
to the stake actually corresponding to the operations.

=== Authorization

This RFC doesn't cover authorizing individual keeps,
or situations where a trusted application
has the authority to impose a penalty.

Because authorizations cannot be revoked,
operator contracts can safely cache positive authorization
after the first lookup to the staking contract.
Lack of authorization cannot be cached,
as the operator contract could later become authorized.

=== Punishments

==== DKG

===== Failure to produce a DKG result

Punishing the failure to produce a DKG result
has interesting implications that could be explored further.

===== Disqualification in DKG

Punishing disqualified DKG members on subjective proof
creates opportunities to attack honest stakers
but can also provide a way for compromised groups
to profitably reveal and remove themselves
if seizing on subjective proof is permitted.
The implications and tradeoffs of
concentrated vs. distributed risk are interesting.

However, disqualification is defined by there being _objective_ off-chain proof,
so the operator contract could be made to verify DKG transcripts
to render DKG disqualification _objective_ on-chain as well.

Disqualified members must be removed from the group.
If disqualification is objectively proven,
the operator must be punished with _seizing_ their stake.
The submitter of the transaction containing the DKG transcript
shall be the _tattletale_.

==== Signing

===== Invalid signature share

Invalid signature shares can only be detected on-chain
if a tattletale submits a proof
that includes the signature share and the information required to verify it.
If the DKG result includes a merkle root
of each member's individual public key,
this proof can be relatively compact and inexpensive to verify.

Proof of an invalid signature share is _objective_.

If the broadcast of an invalid signature share is proven
the responsible operator shall be punished by _seizing_,
with the submitter of the proof receiving the tattletale reward.

===== Unauthorized use of individual private key

Unauthorized use of a member's individual private key
can be proven on-chain by the submission of a suitable proof.
The proof must contain the DKG merkle root,
a merkle path to the individual public key,
some value that isn't a requested entry,
and a valid signature of that value with the individual public key.

Such proof is _objective_.

Unauthorized use of an individual private key
shall be punished by _seizing_,
with the submitter of the proof as the _tattletale_.

=== Chain reorganizations

When chain reorganizations happen,
a honest entry generation in one branch
can be indistinguishable from frontrunning in the other.
It is easy to punish the generation of unauthorized threshold signatures
on values that aren't a part of the entry chain,
and this can serve as a way to incentivize actors
that have compromised the group private key of some group
to destroy the group for immediate profit
instead of covertly frontrunning the beacon.
However, actual frontrunning is more difficult to deal with.

[bibliography]
== Related Links

- link:rfc-14-token-grants.adoc[RFC 14: Token grants]
