:toc: macro

= RFC 08: Continuous Delivery

:icons: font
:numbered:
toc::[]

[abstract]
.Abstract

Here we present a continuous delivery method for a service or services running
in a Kubernetes cluster.  It is expected that one or more of these services
has Ethereum contracts developed along side the service.  It is expected that
there is a relationship between service and contract to a degree that we must
ensure both service and contract are deployed continuously.  The entirety of the
solution is targeted at development and test environments.  The requirements for
utilizing the outlined approach in production will not be covered here. Our one
and only service at this time is the keep-client.  The RFC will focus on the
keep-client as a result, however the solution is applicable outside the
keep-client.  Though this RFC will focus on cloud based continuous delivery there
are elements that we can and should apply to local environments.  I will call
those elements out.  This RFC requires a basic understanding of Kubernetes objects.


== Background

There are *three* parts to deployments with keep-clients:

*Service Code and Service Configuration:*

Deploying manually is a pain in the ass. At a minimum there are 5 clients that
need to be orchestrated with proper images and configurations.  It's possible to
manage this manually at such a low number of clients though you run a non-trivial
risk of human error and deployment step repetition as as result.  This has an
adverse effect on both the engineering experience and time efficiency.

When scaling the solution beyond 5 clients manual configuration becomes untenable
regardless of due-diligence.

*Contract Code:*

The keep-client service leans on a collection of Ethereum contracts that are in
development alongside the service.  When contracts are changed they have to be
deployed to the Ethereum network that the keep-clients are connecting to.

This arrangement creates a dependency between the service service configuration and
contract code on a couple levels:

1. keep-client configuration files require contract addresses.  These addresses
change when contracts are updated.  This means we need to be aware of contract
changes on the keep-client configuration side and make sure keep-client
configuration files get updated contract addresses.

2. We can assume keep-client code will be updated to utilize the latest contract
functionality.  We can assume that this may or may not break keep-client
behavior if the service is deployed against old contracts. This can potentially
happen the other way around as well, where an updated contract is deployed and
removes/changes functionality an old keep-client can't deal with.  Therefore
we must ensure both keep-clients and Keep contracts get deployed together,
contracts before clients due to client startup behavior.

=== Sample keep-client Service Configuration File

*Standard Peer*
```
# This is a TOML configuration file for DKG, P2P networking and connection to Ethereum

# Provider Initialization Example

[ethereum]
  URL                = "ws://eth-host:ws-port"
  URLRPC             = "http://eth-host:rpc-port"

[ethereum.account]
  Address            = "eth-address-keep-client-uses"
  KeyFile            = "path/to/in-use/keyfile"

[ethereum.ContractAddresses]
  # Hex-encoded address of KeepRandomBeacon contract
  KeepRandomBeacon = "address"
  # Hex-encoded address of KeepGroup contract
  KeepGroup = "address"
  # StakingProxy
  Staking = "address"

[LibP2P]
  Peers = ["comma separated list of bootstrap peers"]
  Port = keep-client-port

```

*Bootstrap Peer*
```
# This is a TOML configuration file for DKG, P2P networking and connection to Ethereum

# Provider Initialization Example

[ethereum]
  URL                = "ws://eth-host:ws-port"
  URLRPC             = "http://eth-host:rpc-port"

[ethereum.account]
  Address            = "eth-address-keep-client-uses"
  KeyFile            = "path/to/in-use/keyfile"

[ethereum.ContractAddresses]
  # Hex-encoded address of KeepRandomBeacon contract
  KeepRandomBeacon = "address"
  # Hex-encoded address of KeepGroup contract
  KeepGroup = "address"
  # StakingProxy
  Staking = "address"

# Bootstrap node creating a new network.
  [LibP2P]
  Seed = seed-number-for-id-generation
  Port = keep-client-port

```

=== Current Functionality

We currently have a single cloud environment (`keep-dev`) that is in a mixed state of
continuous delivery and manual configuration.  Current functionality will be
outlined as the "three parts" described in Background.

*keep-client Service Deployment:*

keep-client service deployment is done automatically whenever code is merged to
master.  This is facilitated by a lightweight tool called https://keel.sh/[Keel] that runs
in the Kubernetes cluster.  This is a pull based deployment mechanism where Keel
is subscribed to our container registry and listens for publish events.  On image
publish Keel checks Kubernetes deployments for annotations and matches labels set
there for what should be deployed. On match Keel pulls the image and does a
deployment.

Keel Infrastructure: https://github.com/thesis/infrastructure/tree/master/terraform/modules/gcp_pull_deploy[Keel Terraform Module]
`keep-dev` Keel Implementation: https://github.com/keep-network/keep-core/blob/master/infrastructure/terraform/keep-dev/main.tf#L186-L201[keep-dev Terraform main.tf]


*keep-client Configuration:*

Our first goal was to separate service configuration from the service image.
This exists in the form of each deployed keep-client having its own Kubernetes
ConfigMap.  This allows for the use of a "standard" keep-client service image
across all deployed keep-clients.  There are two pieces of data that make up a
keep-client ConfigMap:

1. keep-client-config.toml
2. Ethereum keyfile

Configuration of the data that populates the ConfigMaps and ConfigMaps themselves
are updated *manually*.

Maintenance log and Kubernetes CRUD commands: https://github.com/keep-network/keep-core/blob/master/infrastructure/kube/keep-dev/kube-setup.org[kube-setup]
keep-client config files: https://github.com/keep-network/keep-core/tree/master/infrastructure/kube/keep-dev/keep-client/config[keep-client.toml]


*Ethereum Contract Deployment:*

Ethereum contracts and subsequent steps are managed against `keep-dev` *manually*.
This is done from a local machine on the `keep-dev` VPN using Truffle.

It's worth noting that when contracts are deployed we need to do the following:

1. Ensure Ethereum accounts are unlocked.
2. Stake Ethereum accounts with KEEP tokens.
3. Update the keep-client configuration files and ConfigMaps with new contract
   address. (see previous section)
4. re-deploy keep-clients.

Sample Commands:

```
truffle migrate --reset --network keep_dev (migrate contracts)
truffle exec ./get-and-unlock-eth-accounts.js http://eth-tx-node.default.svc.cluster.local:8545 eth-account-passphrase --network keep_dev (unlock ETH accounts)
truffle exec ./demo.js --network keep_dev (stake ETH accounts)
```


== Proposal

To bring parts `Ethereum Contract Deployment` and `keep-client Configuration`
into automated configuration such that they can be continuously deployed with
the already automated `keep-client service` deployment.

=== Goal

To automatically provision the `keep-dev` environment on master merge with all
appropriate configurations and app code without human intervention.

=== Implementation

To reiterate:  The implementation will aim to automate
`Ethereum Contract Deployment` and `keep-client Configuration`.
`keep-client service deployment` is already automated via Keel.

Either a new workflow or new jobs to existing workflow will be added to the
`keep-core` circle config.  Before image publish on master merge Circle
will run this workflow/job to trigger a script that will:

- migrate all contracts if any are changed
- unlock in-use ETH accounts
- stake in-use ETH accounts
- update in-use keep-client ConfigMaps with new contract addresses

_The described scripts can be targeted a local environment to do migration_

=== Limitations

- It requires Kubernetes
- It requires Keel
- It require CircleCI
- It requires Truffle
- All contracts are migrated, can't be selective
- No rollback mechanism if things go sideways
- No order to which type of keep-client gets deployed first (bootstrap vs standard)

=== Proof of Concept

`keep-dev` is running Keel.  Code is already referenced.


== Future Work

Open

== Open Questions

Open

[bibliography]
== Related Links

- https://www.flowdock.com/app/cardforcoin/keep/threads/zzxutnh8USazp5U8cC6lNIDu7gI[Contract Migration Automation]
- Various Github Issues discussing one or more of the 3 deployment parts outlined here:
  - https://github.com/keep-network/keep-core/issues/721[CircleCI Config Work]
  - https://github.com/keep-network/keep-core/issues/618[keep-client Configs to ConfigMap]
  - https://github.com/keep-network/keep-core/issues/667[Keel implementation via Terraform]
  -
