:toc: macro

= RFC 3: Stake delegation requirements

:icons: font
:numbered:
toc::[]

== Background

Keep tokens are going to be staked by having token owners delegate their staked
balance to an operator account and use it to run the Keep Client. The operator
account cannot access the stake directly, nonetheless, it operates on behalf of
the owner and bad acting will result in slashing the owners' stake. The operator
may be a third party, or it may be a different address controlled by the owner,
or it may be the same address that owns the tokens.

The stake delegation will be beneficial for the security of Keep users as it
allows on-stake operations with a "cold wallet". Thus, putting Keep users
wallets offline protects them from "hacks" and stake delegation enables
continuous rewarding on safe operations on staked assets. Also exposure of
Keep users private keys will be limited. 

=== Terminology

owner:: The address of an owner of the staked tokens.

operator:: The address of a party authorized to operate a stake in the name of a
  given _owner_.

magpie:: The address where the incentives are sent, earned by an _operator_ in
  the name of an _owner_.

delegated stake:: All of _owner_ tokens delegated to the _operator_ .

== Proposal

Stake delegation enables a token _owner_ to delegate their already-staked tokens
to an _operator_ and enables an _operator_ to operate staked tokens in the name
of the _owner_. The owner defines also a _magpie_ address (recipient) where all
incentives generated by the _operator_ on the staked tokens are uploaded.

=== Goal

The goal of this proposal is to specify a simple and secure stake delegation
mechanism. It should enable Keep users to have their wallets offline and their
stake operated by operators on their behalf. The Keep client software should
be able to run without exposing Keep users private keys. 

=== General requirements for staking:
1. _owner_ can only have one operator.
2. _owner_ can only delegate all of his stake.
3. _operator_ cannot have any stake of his own.
4. _operator_ cannot have any tokens at all.
5. _operator_ can only have a _delegated stake_ from only one _owner_.
6. If an _owner_ tries to delegate to more than one operator, the tx must
fail.
7. If an _owner_ tries to delegate a stake to an _operator_ who already has a
stake, the tx must fail.
8. If an _operator_ tries to operate on a stake that he already operates on, the
tx must fail.
9. _delegated stake_ is locked until a particular operation initiated by the
_operator_ ended.
10. The end of an _on stake operation_ happens only after all rewards are
granted and all penalties are imposed. 
11. Rewarding and penalisation happens as the last phase of all operations.

=== Stake changes atomicity
By implementing this proposal we are going to enforce the stake changes 
atomicity. It means that the stake cannot be changed during an on stake
operation. When an operator starts to perform an operation (enters a game) on
the delegated stake, then the stake is locked and no other operations are
possible to be done on it (requirement 8.). Releasing delegated stake and
enabling its usage for next operations is possible only after the game ends
(requirement 9.). The end of the game happens only after all slashing and
rewarding are done (requirement 10.) and it is the last phase of all of the
games (requirement 11.). The operator can only have one delegated stake
(requirement 5.), the owner can delegate only to one operator (requirement 1.),
and there cannot be more than one on-stake operation at the same time
(requirement 8.), then there is always a one-to-one relation between the owner,
stake, operator, and a game. Therefore, during a game, the stake can only be
changed as a result of slashing which only occurs at the end of the game.

=== Functionality

==== Delegating a stake:
1. The _owner_, signs a contract where he delegates all of his stake to an
_operator_ address (who will be operating on the __delegated stake_) and a
_magpie_ address (where the rewards will be sent).
2. The _operator_, agrees to the contract, hence making it effective and starts
operating on the __delegated stake_.
3. If there will be no acceptance from the _operator_ until a timeout, then the
__delegated stake_ needs to be return to the _owner_. In that case the _owner_
needs to be informed.

==== Undelegating a stake:
1. The _owner_/_operator_ initiates undelegation of the _delegated stake_.
2. The _delegated stake_ is locked for a period necessary to finish all 
operations already initiated by the _operator_. No new actions are possible on a
locked stake until the timeout.
3. After a timeout _delegated stake_ is unlocked and transferred to the _owner_.

==== Operating on a stake:
Any operation on a stake needs to start from presenting a valid stake delegation
certificate. All of the parties (_operators_) participating in a particular
 operation are required to validate each other's certificates.

To validate the certificate, it is necessary to verify:

- if the contract is valid, (properly signed)
- if the _operator_ is correct, (is signed by the same party which is presenting
the contract)
- if the _owner_ is correct,
- if the _magpie_ is correct.

The _delegated stake_ is taken from the on-chain data of the _owner_. This value
should not be explicitly written in the contract.

The incentives need always to be sent to the correct _magpie_ address.

The penalties/slashing need always to be done on the correct _owner_ address.

== Open Questions

How is this going to interact with RFC 4 (on secure upgrades)?

=== Penalisation:
How to penalise misbehaviour?

Should an _operator_ have an accountable address which will be slashed?

=== Timeouts:
What timeouts are reasonable?

== Future work
Consider how the stake delegation will interact with ETH bonding (part of Keep,
but not the beacon).

[bibliography]
== Related Links
- https://www.flowdock.com/app/cardforcoin/tech/threads/UQhnqrQAWk3azp2TO9UhOJQRMXp
- https://www.flowdock.com/app/cardforcoin/keep/threads/TA-Jwe9oMaOBAylc3yRJObc5Bq_
- https://www.flowdock.com/app/cardforcoin/keep/threads/k6MV7jS9DEd0DnvOpkAt5SjsS9w
- https://www.flowdock.com/app/cardforcoin/tech/threads/-Lbr4JzmX0gY31CMDTRGnQUbbuw
- https://github.com/keep-network/keep-core/pull/121