:toc: macro

= RFC 15: Slashing

:icons: font
:numbered:
toc::[]

== Background

To incentivize correct behavior in the Keep network,
misbehaving participants need to be punished.
In some situations,
another participant's cooperation is required to prove misbehavior.
This coordination is incentivized by rewarding the _tattletale_.

== Proposal

=== Goal

Slashing should be simple to implement and reason about.
The slashing method should implement the tattletale transfer mitigations
defined in the link:rfc-14-token-grants.adoc[token grant RFC],
always burning at least 95% of the penalty amount.

To protect staker funds,
only authorized operator contracts should be able to punish an operator.

=== Implementation

Tokens are staked by transferring them to the staking contract.
The staking contract tracks the stake allocated to each _staker_.
Stakes can be _slashed_ to punish misbehavior.
Tokens backing slashed stakes are burned;
if a tattletale proves another operator's misbehavior
they will receive 5% of the slashed tokens,
the remainder being burned.

When an operator is punished for misbehavior,
they should be removed from the group/keep the misbehavior occurred in.

==== Authorization and slashing

_Operator contracts_ are authorized to impose penalties
by stakers' _authorizers_.
All stakers using the same _authorizer_
share the set of authorized operator contracts.
Once given, this authorization cannot be revoked.

When a staker wishes to join a group
the contract responsible for creating the group
must be authorized by the staker's authorizer.
The operator contract checks its authorization status
when determining a staker's eligibility.

===== Directly authorized operator contracts

When an operator misbehaves on-chain,
the operator contract calls the staking contract to punish the operator.
The staking contract checks
that the operator contract is authorized to punish the staker,
and if true,
applies the penalty
by subtracting the applicable penalty from the operator's stake
and burns tokens equal to the penalty amount.

When a tattletale proves another operator's misbehavior,
the operator contract includes the tattletale operator's address in the call.
The staking contract subtracts the applicable penalty from the operator's stake
and burns 95% of it.
The remaining 5% is transferred to the tattletale's _beneficiary_ address.

==== Penalty amounts

Penalties for misbehavior could be adjusted
to match the severity of the misbehavior.
However, initially a simple rule should be sufficient:
when `op_contract` imposes a punishment,
the amount slashed should equal
the minimum stake required to participate in operations on `op_contract`.
If contract _Foo_ requires 10,000 KEEP to participate with one virtual staker,
_Foo_ should slash a misbehaving virtual staker by 10,000 KEEP.

==== Interface requirements

===== Staking contract: slashing

`slash(address perp, tokens sum)`::

Check that `msg.sender` is authorized to slash `perp`:
`isAuthorized(msg.sender, perp.authorizer) == true`.
+
Take `sum` tokens from stake of `perp` and burn them.

`seize(address perp, tokens sum, address mole)`::

Check that `msg.sender` is authorized to slash `perp`:
`isAuthorized(msg.sender, perp.authorizer) == true`.
+
Take `sum` tokens from stake of `perp`;
burn `sum * 0.95`; transfer `sum * 0.05` to beneficiary of staker `mole`.

===== Staking contract: authorizations

`authorize(address op_contract)`::

Authorize `op_contract`.
Operators using `msg.sender` as their authorizer
may now join operations on `op_contract`
and `op_contract` may slash their stakes.

`isAuthorized(address op_contract, address by) -> bool`::

Check if the authorizer `by` has authorized `op_contract`.

===== Token contract

`burn(amount sum)`::

Any address that holds tokens can call `burn(amount sum)`
to burn `sum` tokens, limited by tokens held by the address.

=== Limitations

Slashing is not limited to the amount originally staked
for participating in the relevant operations;
a malfunctioning operator contract could cause a staker to lose all stake.

== Future Work

With a different staking paradigm
that tracks individual keep and group memberships,
it is possible to limit the risk
from malfunctioning operator contracts or trusted applications
to the stake actually corresponding to the operations.

This RFC doesn't cover authorizing individual keeps,
or situations where a trusted application
has the authority to impose a penalty.

[bibliography]
== Related Links

- link:rfc-14-token-grants.adoc[RFC 14: Token grants]
