name: Solidity v1

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - "solidity-v1/**"
      - "!solidity-v1/dashboard/**"
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for workflow execution'
        required: false
        default: 'dev'
      upstream_builds:
        description: 'Upstream builds'
        required: false
      upstream_ref:
        description: 'Git reference to checkout (e.g. branch name)'
        required: false
        default: 'main'

jobs:
  contracts-detect-changes:
    runs-on: ubuntu-latest
    outputs:
      path-filter: ${{ steps.filter.outputs.path-filter }}
    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'pull_request'

      - uses: dorny/paths-filter@v2
        if: github.event_name == 'pull_request'
        id: filter
        with:
          filters: |
            path-filter:
              - './solidity-v1/!(dashboard)/**'

  contracts-lint:
    needs: contracts-detect-changes
    if: |
      github.event_name == 'push'
        || needs.contracts-detect-changes.outputs.path-filter == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./solidity-v1
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"
          cache-dependency-path: solidity/random-beacon/yarn.lock

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint
  
  contracts-slither:
    needs: contracts-detect-changes
    if: |
      github.event_name == 'push'
        || needs.contracts-detect-changes.outputs.path-filter == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./solidity-v1
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"
          cache-dependency-path: solidity/random-beacon/yarn.lock

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.5

      - name: Install Solidity
        env:
          SOLC_VERSION: 0.8.6 # according to solidity.version in hardhat.config.js
        run: |
          pip3 install solc-select
          solc-select install $SOLC_VERSION
          solc-select use $SOLC_VERSION

      - name: Install Slither
        env:
          SLITHER_VERSION: 0.8.0
        run: pip3 install slither-analyzer==$SLITHER_VERSION

      - name: Install dependencies
        run: yarn install

      - name: Run Slither
        run: slither .
  
  contracts-build-and-test:
    needs: contracts-detect-changes
    if: |
      github.event_name != 'pull_request'
        || needs.contracts-detect-changes.outputs.path-filter == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./solidity-v1
    outputs:
      version: ${{ steps.npm-version-bump.outputs.version }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"
          cache-dependency-path: solidity/random-beacon/yarn.lock
            
      - name: Install dependencies
        run: yarn install

      - name: Build solidity contracts
        run: yarn build

      - name: Bump up package version
        id: npm-version-bump
        uses: keep-network/npm-version-bump@v2
        with:
          work-dir: ./solidity-v1
          environment: ${{ github.event.inputs.environment }}
          branch: ${{ github.ref }}
          commit: ${{ github.sha }}

  contracts-deployment-dry-run:
    if: |
      github.event_name != 'pull_request'
        || needs.contracts-detect-changes.outputs.path-filter == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./solidity/random-beacon
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          working-directory: ./solidity-v1
          tenderly-token: ${{ secrets.TENDERLY_TOKEN }}
          tenderly-project: thesis/keep-test
          eth-network-id: ${{ env.NETWORK_ID }}
          github-project-name: keep-core
          version-tag: ${{ steps.npm-version-bump.outputs.version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Upload keep-core contracts for initcontainer build
        uses: actions/upload-artifact@v2
        with:
          name: Contracts
          path: ./solidity-v1/build/contracts/*

  contracts-deployment-testnet:
    needs: [contracts-detect-changes, contracts-build-and-test]
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./solidity/random-beacon
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"
          cache-dependency-path: solidity/random-beacon/yarn.lock
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # TODO: Configure tenderly

      - name: Deploy contracts
        env:
          CHAIN_API_URL: ${{ secrets.KEEP_TEST_ETH_HOSTNAME_HTTP }}
          CONTRACT_OWNER_ACCOUNT_PRIVATE_KEY: ${{ secrets.KEEP_TEST_ETH_CONTRACT_OWNER_PRIVATE_KEY }}
        run: yarn deploy --network ${{ github.event.inputs.environment }}

      - name: Bump up package version
        id: npm-version-bump
        uses: keep-network/npm-version-bump@v2
        with:
          work-dir: solidity/random-beacon
          environment: ${{ github.event.inputs.environment }}
          branch: ${{ github.ref }}
          commit: ${{ github.sha }}

      - name: Publish to npm
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        with:
          module: "github.com/keep-network/keep-core/solidity-v1"
          url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          environment: ${{ github.event.inputs.environment }}
          upstream_builds: ${{ github.event.inputs.upstream_builds }}
          upstream_ref: ${{ github.event.inputs.upstream_ref }}
          version: ${{ needs.contracts-migrate-and-publish.outputs.version }}

      # TODO: Notify CI about completion of the workflow
