---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoind
spec:
  replicas: 1
  serviceName: bitcoind
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        # https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: bitcoind
          image: keepnetwork/bitcoind:24.1
          imagePullPolicy: Always
          command:
            - bitcoind
            - -chain=$(CHAIN)
            - -datadir=/mnt/bitcoind/data
            - -rpcport=8332
            - -port=8333
            - -rpcbind=0.0.0.0
            - -rpcallowip=0.0.0.0/0
            - -rpcuser=$(RPC_USER)
            - -rpcpassword=$(RPC_PASSWORD)
            - -disablewallet=1
            - -txindex=1
          env:
            - name: RPC_USER
              valueFrom:
                secretKeyRef:
                  name: bitcoind
                  key: rpc-user
            - name: RPC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bitcoind
                  key: rpc-password
            - name: CHAIN
              valueFrom:
                configMapKeyRef:
                  name: bitcoind
                  key: chain
          ports:
            - name: rpc
              containerPort: 8332
              protocol: TCP
            - name: network
              containerPort: 8333
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: rpc
            initialDelaySeconds: 20
            periodSeconds: 10
          # TODO: Define readiness probe based on: https://bitcoin.stackexchange.com/a/103370
          # readinessProbe:
          #   exec:
          #     command:
          #       - bitcoin-cli
          #       - getblockcount
          #   initialDelaySeconds: 20
          #   periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 2Gi
          volumeMounts:
            - mountPath: /mnt/bitcoind/data
              name: bitcoind-data
      volumes:
        - name: bitcoind-data
          persistentVolumeClaim:
            claimName: bitcoind-data
  volumeClaimTemplates:
    - metadata:
        name: bitcoind-data
      spec:
        storageClassName: bitcoind
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            # Estimated required storage based on the network:
            # - for mainnet: 650 Gi (default)
            # - for testnet: 40 Gi
            storage: 650Gi
