apiVersion: v1
kind: Service
metadata:
  name: bitcoind
spec:
  type: ClusterIP
  ports:
    - name: rpc
      port: 8332
      targetPort: rpc
    - name: network
      port: 8333
      targetPort: network
