resources:
  - bitcoind-service.yaml
  - bitcoind-statefulset.yaml
  - bitcoind-storageclass.yaml
  - bitcoind-volumesnapshotclass.yaml

commonLabels:
  chain: bitcoin
  app: bitcoind

configMapGenerator:
  - name: bitcoind
    literals:
      - chain=main

secretGenerator:
  - name: bitcoind
    envs:
      - .env.sample

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: generated
