resources:
  - prometheus-deployment.yaml
  - prometheus-pvc.yaml
  - prometheus-service.yaml

namespace: monitoring

commonLabels:
  app: prometheus
  type: monitoring

configMapGenerator:
  - name: prometheus-config
    files:
      - config/config.yaml

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: generated
