---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  storageClassName: monitoring-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
